### ISSUE TITLE
inconsistent 0-rawreads/daligner-runs segfault with first submitted job

### ISSUE THREAD

**Issue by jasmynp** [PacificBiosciences/pbbioconda#101]
We are seeing strange behavior where we get failure running fc_run.sh due to one daligner job under 0-rawreads/daligner-runs/j_00*/ segfault'ing at the start.  

However, when we rerun, it works fine but at times it just fails.  This happens very often and we're not sure what would cause the flakiness.  I noticed that the timestamps are strange.  It seems to always happen with the first daligner job of the batch that gets submitted concurrently because it has the earliest timestamp.  It also is usually a few minutes from the timestamp of all the daligner-chunks jobs.

We are running things on slurm with sbatch --wait.  It is very hard to reproduce but makes things very unstable for us.

from 0-rawreads/daligner-runs/j_0040/*stderr:
```
daligner -v -k18 -w8 -H3000 -e0.7 -s1000 -M100 -P. -mtan -mdust -mrep0 raw_reads
.17 raw_reads.1 raw_reads.2 raw_reads.3
+ daligner -v -k18 -w8 -H3000 -e0.7 -s1000 -M100 -P. -mtan -mdust -mrep0 raw_rea
ds.17 raw_reads.1 raw_reads.2 raw_reads.3
run_daligner.sh: line 1: 13180 Segmentation fault      daligner -v -k18 -w8 -H30
00 -e0.7 -s1000 -M100 -P. -mtan -mdust -mrep0 raw_reads.17 raw_reads.1 raw_reads
.2 raw_reads.3
[WARNING]Call 'bash -vex run_daligner.sh' returned 35584.
Traceback (most recent call last):

```
Rerunning the same command after it fails has no issue.  Could there be some kind of race condition going on?

**Comment by pb-cdunn** [comment]
If it works when re-run, the error is probably due to filesystem latency. 

We could add a settable delay to every task. Would you really want that? And what if it's something else, like a temporary problem with that specific host. You're probably best off just resuming after the crash.

We could add an automatic retry mechanism someday, but it's not currently available.

What filesystem are you on? And what is your pypeflow configuration (assuming you are using that)?

**Comment by jasmynp** [comment]
Thanks.  I see an issue on our end is contributing to the filesystem latency that could possibly be resolved.  

I didn't know there was a way to configure pypeflow.  I am using the default pypeflow setup with the conda package:

falcon-kit 1.2.3
pypeflow 2.1.0

How do you go about setting up pypeflow config?

**Comment by pb-cdunn** [comment]
[This](https://github.com/PacificBiosciences/pypeFLOW/wiki/configuration) might help.
