### ISSUE TITLE
[Unzip]polish_include_zmw_all_subreads

### ISSUE THREAD

**Issue by foala** [PacificBiosciences/pbbioconda#102]
Hi,
Using the new release, can I know how I can set this option to be true, as per the release notes:

Only if [Unzip]polish_include_zmw_all_subreads is "true".

Thank you very much

**Comment by pb-cdunn** [comment]
```ini
[Unzip]
polish_include_zmw_all_subreads = true
```
It's actually a standard Python `ConfigParser`, so `1`, `yes`, and `on` [work too](https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser.getboolean).

**Comment by foala** [comment]
Thanks very much
