### ISSUE TITLE
unsupported chemistries found: (P4-C2)

### ISSUE THREAD

**Issue by mawad89** [PacificBiosciences/pbbioconda#107]
I trying to polish a genome using quiver but I get this error
`Failure: The Quiver algorithm is not trained for Sequel data. Please use the Arrow algorithm instead` 
then I am trying arrow but I get this error
`Arrow:unsupported chemistries found: (P4-C2)`
I am using  conda 4.5.11 and variantCaller version 2.3.2
**I used the following command for quiver and arrow** 

> quiver pbalign.bam -r genome.fa -o name.gff -o name.fasta -o name.fastq
arrow pbalign.bam -r genome.fa -o name.gff -o name.fasta -o name.fastq

I want to solve the problem with quiver or arrow

**Comment by pb-dseifert** [comment]
Could you post the first, say, 20 lines from the BAM file?

**Comment by mawad89** [comment]
Thanks for your replay
the first 20 lines is very very long 
but this a representative part from the first 5 lines demonstrate the component of each line
`m54124_170724_161202/14418689/0_7764    0   tig00000001 1   254 1297S20=1D10=1D17=1I3=1X3=1D2=1I3=1X3=1S    *   0   0   TAAACCAAAAACCATAAAACCCTAAAAACAAACCTGAACG    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    cx:i:0  ip:B:C,12,8,38,58,88,2,20,72,10,7,11,23    np:i:1  pw:B:C,5,13,2,4,15,19,5,8,16,16,12   qe:i:7764   qs:i:0  rq:f:0.8    sn:B:f,5.73134,10.7392,6.60592,10.0153  zm:i:14418689   RG:Z:e3bc0aa7   AS:i:-24769 NM:i:830`

`m54124_170724_161202/52101586/0_19020   0   tig00000001 1   254 555S6=2I1=4I6=2I1=4I2=2I1=2I1=1I9=1I1=4I1=1I1=3I1=1I2=1I1=1I1=1I2=1I1=X11= *   0   0   CAATAAAACACAAACCCTAAAACTAAGACA    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!    cx:i:2  ip:B:C,15,2,70,4,68,44,48,106   np:i:1  pw:B:C,2,10,2,2,7,5,10,4,7,3,1126,5,11,5,7,15,5,4,10    qe:i:19020  qs:i:0  rq:f:0.8    sn:B:f,5.71517,10.8823,6.31898,9.64915  zm:i:52101586   RG:Z:e3bc0aa7   AS:i:-73307 NM:i:2153`

`m54124_170725_043014/40109052/0_16913  0   tig00000001 1   254 135S34=1D1=1X2=1I1=1I10=1X3=1X3=1I9=1D7=1D2X4=1I1=1S    *   0   0   ACCCTAAACCCCAAAACTCCCAAAACCAAACCCAAACCCTAACACTAAACCCTAAACCCTAAACCCTATTGA   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   cx:i:0  ip:B:C,66,34,116,28,3,39,19,76,1,100,27,43,255 np:i:1  pw:B:C,4,16,2,15,5,4,4,4,4,8,3,17,1,7,3,9,7,3,2,8,5,6,6,20,4,2,6,11,8,22,20,65,4,1  qe:i:16913  qs:i:0  rq:f:0.8    sn:B:f,6.20477,11.6038,7.00251,10.5942  zm:i:40109052   RG:Z:f4d8058f   AS:i:-62916 NM:i:2330`

`m54124_170725_043014/70910809/0_6831    0   tig00000001 1   254 733S19=1D1X19=1X14=1X7=1D18=1I8=1D4=1D1X17=1X9=2S *   0   0   ACCCTAACCCTAAACCCGAAACCCCAAAACCCACCCAAACCATAAACACGAAACCCTAAAAAA !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! cx:i:2  ip:B:C,14,30,27,12,6,19,17,25,8,4,15,7,3,34,10,3,17,32,18,66,10,11,21 np:i:1  pw:B:C,4,4,7,10,3,94,18,30  qe:i:6831   qs:i:0  rq:f:0.8    sn:B:f,5.79354,11.0318,6.05654,9.35197  zm:i:70910809   RG:Z:f4d8058f   AS:i:-23625 NM:i:786`

`m54124_170722_124905/17826032/0_15851   16  tig00000001 1   254 1680S26=9I2=10I2=5I5=2I1=1X4I2=3I1=4I1=2I1=2I2=1X10= *   0   0   GGGTGGGTGGTGAGGGGGGGGTGGGGAGGGGGAGGGGC !!!!!!!!!!!!!!!!!!!!!!!! cx:i:0  ip:B:C,19,12,3,34,10,8,14,68,2,3,88,3,25,1,255,25 np:i:1  pw:B:C,6,4,5,4,4,38,13,6,24,10,12    qe:i:15851  qs:i:0  rq:f:0.8    sn:B:f,5.56864,10.1927,6.32023,9.47242  zm:i:17
826032   RG:Z:85439fbc   AS:i:-55275 NM:i:1808`

**Comment by armintoepfer** [comment]
Please include the header

**Comment by mawad89** [comment]
`@HD VN:1.5  SO:coordinate   pb:3.0.1`
`@SQ SN:tig00000108  LN:46272    M5:c2dc4caed240821fdd3aa7fdbb7fd7dc`
`@SQ SN:tig00000110  LN:2210903  M5:ee732884ec10ca998e3eff680ec2af6e`
`@SQ SN:tig00000116  LN:15770    M5:ab5b1328909f02fea4ca6d392744089d`
`@SQ SN:tig00000117  LN:1940094  M5:e7d0d62ba568efb8e29097a369f5fb87`
`@SQ SN:tig00000121  LN:206614   M5:9277c43b487c5a6ac58ce30adc72d87c`
`@SQ SN:tig00000127  LN:860289   M5:b2b9295a8d8e751ef44a1fbf9d500e3a`

`@RG ID:185bfc2d PL:PACBIO   DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=100-619-300;SEQUENCINGKIT=100-902-100;BASECALLERVERSION=4.0.0.189308;FRAMERATEHZ=80.000000  PU:m54124_170724_222101 PM:SEQUEL`
`@RG ID:5f57b1ec PL:PACBIO   DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=100-619-300;SEQUENCINGKIT=100-902-100;BASECALLERVERSION=4.0.0.189308;FRAMERATEHZ=80.000000  PU:m54124_170724_101258 PM:SEQUEL`
`@RG ID:85439fbc PL:PACBIO   DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=100-619-300;SEQUENCINGKIT=100-902-100;BASECALLERVERSION=4.0.0.189308;FRAMERATEHZ=80.000000  PU:m54124_170722_124905 PM:SEQUEL`
`@RG ID:ceb9cbaa PL:PACBIO   DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=100-619-300;SEQUENCINGKIT=100-902-100;BASECALLERVERSION=4.0.0.189308;FRAMERATEHZ=80.000000  PU:m54124_170722_184809 PM:SEQUEL`
`@RG ID:da5c965e PL:PACBIO   DS:READTYPE=SUBREAD;DeletionQV=dq;DeletionTag=dt;InsertionQV=iq;MergeQV=mq;SubstitutionQV=sq;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=100236500;SEQUENCINGKIT=001558034;BASECALLERVERSION=2.1.0.0.127824;FRAMERATEHZ=75.000000   PU:m141101_113331_42207_c100661932550000001823125811271466_s1_X0    PM:RS`
`@RG ID:e3bc0aa7 PL:PACBIO   DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=100-619-300;SEQUENCINGKIT=100-902-100;BASECALLERVERSION=4.0.0.189308;FRAMERATEHZ=80.000000  PU:m54124_170724_161202 PM:SEQUEL`
`@RG ID:f31aee96 PL:PACBIO   DS:READTYPE=SUBREAD;DeletionQV=dq;DeletionTag=dt;InsertionQV=iq;MergeQV=mq;SubstitutionQV=sq;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=100236500;SEQUENCINGKIT=001558034;BASECALLERVERSION=2.1.0.0.127824;FRAMERATEHZ=75.000000   PU:m141018_142348_42207_c100661972550000001823125811271427_s1_X0    PM:RS`
`@RG ID:f4d8058f PL:PACBIO   DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=100-619-300;SEQUENCINGKIT=100-902-100;BASECALLERVERSION=4.0.0.189308;FRAMERATEHZ=80.000000  PU:m54124_170725_043014 PM:SEQUEL`
`@PG ID:21   PN:BLASR    VN:5.3.2    CL:blasr /home/bam.fofn /home/genome.fa --out /home/tmpEl8IzR/32ynOo.bam --bam --bestn 10 --minMatch 12 --maxMatch 30 --nproc 20 --minSubreadLength 50 --minAlnLength 50 --minPctSimilarity 70 --minPctAccuracy 70 --hitPolicy randombest --randomSeed 1 `
`@PG ID:bax2bam-0.0.8    PN:bax2bam  VN:0.0.8    DS:bax2bam converts the legacy PacBio basecall format (bax.h5) into the BAM basecall format.
    CL:bax2bam /home/Analysis_Results/m141101_113331_42207_c100661932550000001823125811271466_s1_X0.bas.h5` 
`@PG ID:baz2bam  PN:baz2bam  VN:4.0.0.189308 CL:/opt/pacbio/ppa-4.0.0/bin/baz2bam /data/pb/m54124_170725_043014.baz -o /data/pb/m54124_170725_043014 --metadata /data/pb/.m54124_170725_043014.metadata.xml -j 12 -b 12 --progress --silent --minSubLength 50 --minSnr 4.000000 --adapters /data/pb/m54124_170725_043014.adapters.fasta --controls /etc/pacbio/600bp_Control_c2.fasta `
`@PG ID:bazFormat    PN:bazformat    VN:1.3.0`
`@PG ID:bazwriter    PN:bazwriter    VN:4.0.0.189308`

**Comment by pb-dseifert** [comment]
As I thought, your alignment contains RS **and** Sequel data. Given the architecture of GenomicConsensus, this is an unsupported configuration, as Arrow can only polish P6-C4 RS data, and Quiver can only polish RS data. Your best best would be to split the data, and try Arrow polishing on the Sequel data and Quiver polishing on the RS data.
