### ISSUE TITLE
bax2bam: symbol lookup error: ../lib/libblasr.so.5.3.1: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxEy

### ISSUE THREAD

**Issue by fbemm** [PacificBiosciences/pbbioconda#11]
**Operating system**
4.4.0-119-generic #143-Ubuntu with anaconda 1.6.14

**Package name**
bax2bam

**Describe the bug**
bax2bam throws a lookup error.

**Error message**
bax2bam: symbol lookup error: ../lib/libblasr.so.5.3.1: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxEy

**To Reproduce**
conda install -c bioconda
bam2bax -f fofn

**Expected behavior**
bax2bam should convert my bax to bam ;)

**Comment by pb-dseifert** [comment]
You probably have HDF5 from anaconda and not conda-forge. Please set up your channel priorities according to https://bioconda.github.io/#set-up-channels

**Comment by Christos3** [comment]
I have the same issue even after setting up my channel priorities, I receive the following message:
bax2bam: symbol lookup error: /conda/bin/../lib/libblasr.so.5.3.1: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxEy

conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 2.7.15.final.0
            platform : linux-64

**Comment by fbemm** [comment]
Solved it with conda install -c conda-forge hdf5.

**Comment by Christos3** [comment]
Tried it but unfortunately not solved..

conda install -c conda-forge hdf5
Solving environment: done
# All requested packages already installed.

bax2bam: symbol lookup error: /conda/bin/../lib/libblasr.so.5.3.1: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxEy

**Comment by pb-dseifert** [comment]
Unless you get hdf5 from conda-forge, your installation will be broken

```
$ conda create -n smrttools bax2bam
Solving environment: done

## Package Plan ##

  environment location: /home/soap/miniconda2/envs/smrttools

  added / updated specs:
    - bax2bam


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
[...]
    hdf5-1.10.2                |       hc401514_2         4.8 MB  conda-forge
[...]
$
```

Have you set up your channel priorities correctly? bioconda changed the global channel precedence list like 2 months ago:
https://bioconda.github.io/#set-up-channels

**Comment by pb-dseifert** [comment]
have you tried `codna update --all` on your "normal" installation?

**Comment by Christos3** [comment]
conda update --all 

made it work without the need of activating smrttools
Thank you

**Comment by esolares** [comment]
Hi,

I have tried all of the above and even a clean install of miniconda2. I keep getting the error libblasr.so.5.3.1: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxEy

Please help....

**Comment by esolares** [comment]
I have just tried this on a different linux system and I get the same issue.... There appears to be some sort of bug. When the conda install was going through, I saw that hdf5 was indeed using condaforge hdf5.

**Comment by MehmetGoktay** [comment]
Same here: 
../lib/libblasr.so.5.3.1: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxEy

conda update -all does not solve problem

**Comment by ealdraed** [comment]
Hello, I get the same error: 
```
bax2bam: symbol lookup error: <env_path>/bin/../lib/libblasr.so.5.3.1: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxEy
```
Here are the packages and channels:

```
# Name                    Version                   Build  Channel
bax2bam                   0.0.9                h82bacf8_5    bioconda
blasr                     5.3.2                h82bacf8_5    bioconda
blasr_libcpp              5.3.1                h82bacf8_4    bioconda
h5py                      2.8.0           py27hfb8609e_1004    conda-forge
hdf5                      1.10.3            hba1933b_1001    conda-forge
```

Downgrading HDF5 to version 1.10.2 will let me use bax2bam: `conda install hdf5=1.10.2`

```
The following packages will be DOWNGRADED:

  bax2bam                                  0.0.9-h82bacf8_5 --> 0.0.9-hac9d22c_4
  blasr                                    5.3.2-h82bacf8_5 --> 5.3.2-hac9d22c_4
  blasr_libcpp                             5.3.1-h82bacf8_4 --> 5.3.1-hac9d22c_3
  h5py                              2.8.0-py27hfb8609e_1004 --> 2.8.0-py27h3010b51_1003
  hdf5                                 1.10.3-hba1933b_1001 --> 1.10.2-hc401514_3
```
