### ISSUE TITLE
[Falcon-Unzip] 3-unzip/reads running for two days

### ISSUE THREAD

**Issue by baozg** [PacificBiosciences/pbbioconda#110]
**Operating system**
CentOS 7.4

**Package name**

**Conda environment**
falcon-unzip 1.1.7
falcon-kit 1.2.6
pypeflow 2.1.1

**Describe the bug**
Use the latest pb-assembly to assembly a plant genome （54x UM coverage）
- `p_ctg.fa` have 2104 contigs , N50 334kb, total length 319M
- `a_ctg.fa` have 1444 contigs, N50 30kb，total length 39M

When I use the `Falcon-Unzip` to get the phased genome , it run for `3-unzip/reads` for two days. When I try to use same config to assembly 2.5G genome, 3-unzip + 4-polish use two days. 
The last line of  `stderr`,  when I ssh the compute nodes, seem all the falcon process are sleeping in the raw reads, so how can I fix this issue?
![image](https://user-images.githubusercontent.com/20680150/54325372-c8103c00-463c-11e9-8cac-3ea4a9fa36c7.png)

```shell
[22390]finished run_tr_stage1('../../0-rawreads/build/raw_reads.db', u'/public/seed_40/0-rawreads/las-merge-gathered/../las-merge-runs/m_00042/uow-00/raw_reads.43.las', 2500, 40, dict(111974 elem))
[22506]maxrss: 25467364
[22506]finished run_tr_stage1('../../0-rawreads/build/raw_reads.db', u'/public/seed_40/0-rawreads/las-merge-gathered/../las-merge-runs/m_00041/uow-00/raw_reads.42.las', 2500, 40, dict(111974 elem))
[22403]maxrss: 25531180
[22403]finished run_tr_stage1('../../0-rawreads/build/raw_reads.db', u'/public/seed_40/0-rawreads/las-merge-gathered/../las-merge-runs/m_00043/uow-00/raw_reads.44.las', 2500, 40, dict(111974 elem))
```

Here is my `fc_unzip.cfg`, which was successfully run on the 2.5G genome, but cannot run in the 320M plant genome.

```shell
[General]
max_n_open_files = 1000
NPROC = 8
jobs=50

[Unzip]
input_fofn = input.fofn
input_bam_fofn = input_bam.fofn

[job.defaults]
submit = qsub -S /bin/bash -sync y -V  \
  -q ${JOB_QUEUE}     \
  -N ${JOB_NAME}        \
  -o "${JOB_STDOUT}" \
  -e "${JOB_STDERR}" \
  -pe smp ${NPROC}    \
  "${JOB_SCRIPT}"

job_type=sge
JOB_QUEUE = all
pwatcher_type = blocking
MB = 30000
NPROC = 8
jobs=50

[job.step.unzip.track_reads]
njobs=1
NPROC=24
MB=38000
# this is using minimap2 now, not blasr
[job.step.unzip.blasr_aln]
njobs=80
NPROC=4
MB=20000
[job.step.unzip.phasing]
njobs=80
NPROC=4
MB=20000
[job.step.unzip.hasm]
njobs=1
NPROC=24
MB=80000
# this uses arrow, not quiver
[job.step.unzip.quiver]
njobs=50
NPROC=8
MB=10000
```

**Comment by pb-cdunn** [comment]
You can `cd` into `3-unzip/reads`, and look at `user_script.sh`. You can run bits of that yourself and try to debug. You might be able to figure out the problem that way.

**Comment by baozg** [comment]
I find the problem is the rawread_to_contigs stage. After comment the `rawdata to contigs` stage, `preads_to_contigs` can successfully run without error. But when I mannually run the `rawdata to cotigs` serveral times, it just sleeping in some las randomly.

**Comment by pb-cdunn** [comment]
That can happen from a crash in `LA4Falcon`. Try to find a failing `LA4Falcon` call from the logs and run that yourself. If that sub-process fails when called directly, you might be able to debug. Typical culprit: out-of-memory. If that's the problem, you might need smaller "blocks", or maybe a smaller number of concurrent sub-procs (nproc) could be enough.

**Comment by baozg** [comment]
Thanks for the reply. I set the NPROC=16, now it could run into the `pread` stage. Thanks.
