### ISSUE TITLE
sam is NOT sorted

### ISSUE THREAD

**Issue by ke-shi** [PacificBiosciences/pbbioconda#117]
In the SMRT Link ver6.0 (release_6.0.0.47841) /Iso-Seq3 with mapping, we got an error message saying:

> SAM file alignments.sam is NOT sorted. ABORT!

, and the pipeline was broken. How can the sam be sorted?

Thanks!

**Comment by armintoepfer** [comment]
For SMRT Link support, please contact PacBio Tech Support. This bug tracker is purely for software distributed via bioconda. Thank you.
