### ISSUE TITLE
ImportError: cannot import name _distributor_init

### ISSUE THREAD

**Issue by xiaoyezao** [PacificBiosciences/pbbioconda#118]
The fc_unzip stops at **4-polish/quiver-run**, and the error is: `ImportError: cannot import name _distributor_init`. 

This is the complete stderr file: 
[run-P5424dcd7f27e67.bash.stderr.txt](https://github.com/PacificBiosciences/pbbioconda/files/3011287/run-P5424dcd7f27e67.bash.stderr.txt)

How can I fix this ?

**Comment by pb-cdunn** [comment]
```py
+ variantCaller --algorithm=arrow -x 5 -X 120 -q 20 -j 8 -r ../../../quiver-split/refs/000000F/ref.fa aln-000000F.bam -o cns.fasta.gz -o cns.fastq.gz --minConfidence 0 -o cns.vcf
Traceback (most recent call last):
  File "/PARA/app/anaconda2/2018.12-pb-assembly/bin/variantCaller", line 3, in <module>
    from GenomicConsensus.main import main
  File "/PARA/app/anaconda2/2018.12-pb-assembly/lib/python2.7/site-packages/GenomicConsensus/main.py", line 14, in <module>
    from pbcore.io import AlignmentSet, ContigSet
  File "/PARA/app/anaconda2/2018.12-pb-assembly/lib/python2.7/site-packages/pbcore/io/__init__.py", line 3, in <module>
    from .BasH5IO import *
  File "/PARA/app/anaconda2/2018.12-pb-assembly/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 15, in <module>
    import numpy as np
  File "/PARA/app/anaconda2/2018.12-pb-assembly/lib/python2.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import _distributor_init
ImportError: cannot import name _distributor_init
```
Interesting ...

**Comment by pb-cdunn** [comment]
Searching the web, I see examples of this problem, but no definitive solution:

* https://stackoverflow.com/questions/48423782/importerror-cannot-import-name-distributor-init
* https://stackoverflow.com/questions/54894671/networkx-importerror-cannot-import-name-distributor-init
* https://stackoverflow.com/questions/55048364/numpy-importerror-cannot-import-name-distributor-init

That last links seems most helpful. Try `python` in your shell, then in the python-shell, `import numpy`. You might get a more useful traceback.

If that doesn't help, could you post `conda list`? Maybe you have a version inconsistency somewhere? `conda update --all` might help. But I'm totally guessing.

**Comment by xiaoyezao** [comment]
Thanks. The last link solves my problem. There is an older version of numpy in the conda environment.

**Comment by pb-cdunn** [comment]
`conda update --all` may solve your problems. Minimally, we would need to see `conda list`.

**Comment by pb-cdunn** [comment]
Closing this ticket, since you've already posted your last comment as a new Issue, #120.

**Comment by xiaoyezao** [comment]
> `conda update --all` may solve your problems. Minimally, we would need to see `conda list`.

Thanks, I posted the conda list in https://github.com/PacificBiosciences/pbbioconda/issues/120
