### ISSUE TITLE
fc_unzip stops at 4-polish/track-reads with ERROR: readlink: command not found

### ISSUE THREAD

**Issue by xiaoyezao** [PacificBiosciences/pbbioconda#119]
I am running fc_unzip on a cluster. fc_unzip works well with` job_type=local`, but it failes with slurm `job_type=slurm`, and report **user_script.sh: line 17: readlink: command not found**.

The readlink is actually available:  `which readlink` `/bin/readlink`

this is the stderr file:
[run-Pa8ce5428e6e7e2.bash.stderr.txt](https://github.com/PacificBiosciences/pbbioconda/files/3017726/run-Pa8ce5428e6e7e2.bash.stderr.txt)

I am struggling to understand what's going wrong here. Your help will be appreciated very much!

**Comment by xiaoyezao** [comment]
I finally figured out what's going wrong here. The login node where I run fun_unzip locally has access to readlink, but the remote nodes to where the job was submitted has no access to readlink.

**Comment by pb-cdunn** [comment]
`readlink -f` is not available on Mac either. Do we need to stop using that? What was your work-around?
