### ISSUE TITLE
how to distribute arrow polish job in multiple nodes

### ISSUE THREAD

**Issue by xiaoyezao** [PacificBiosciences/pbbioconda#122]
Hi,
I am doing arrow polish on a 1.4G genome (100x PacBio rawreads) in our cluster (24core-65G per node). Currently, arrow is running on a single node with 16 cpus (-j 16). It seems that it's very slow, and only generate 16M consensus.fasta data after 5 hours running. Based on the size of the assembly (1.4G), it will take about 20 days to finish.

My question is: does arrow support parallel computing using multiple nodes? Or any solutions to speed it up?

Your help will be appreciated very much!

**Comment by harish0201** [comment]
The easiest way would to be to slice the bam files contig/scaffold wise and run those many jobs in parallel.

**Comment by xiaoyezao** [comment]
Hi harish0201, thanks for your helpful advice. Can you please give more details about how to slice the bam file?

**Comment by harish0201** [comment]
Sure, make a list of your bam files as an fofn. Similarly put out a list of your input sequence-headers as another list.

Use bamtools merge with -list option being the bam fofn, and -region being the sequence-header list.

Index the generated bams using pbindex. You can then use variantCaller/Arrow using your scheduling system to distribute the work-load.

**Comment by xiaoyezao** [comment]
few more questions:

> make a list of your bam files as an fofn

I have a single bam alignment file generated by pbmm2. Can I just use this as input?

> put out a list of your input sequence-headers as another list

what is the sequence-header? 

> Use bamtools merge with -list option being the bam fofn, and -region being the sequence-header list.

There seems no `-list` and '-region' option available in bamtools. I am using v2.4.0. Is this version too old?

Thanks for your patience. I am new to bioinformatics, and please bear with me.

**Comment by xiaoyezao** [comment]
Hi harish0201,

I managed to slice the bam file and indexed it, but arrow seems fails at this:

```
File "/PARA/app/anaconda2/2018.12-pb-assembly/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 73, in _loadReferenceInfo
    refMD5s    = [r["M5"] for r in refRecords]
KeyError: 'M5'
```

I used the complete reference fasta file, is it the cause? should I also slice the reference file ?

Thanks

**Comment by armintoepfer** [comment]
Please don't duplicate your issue many times. #144 #137
