### ISSUE TITLE
Run fc_unzip on canu assembly ?

### ISSUE THREAD

**Issue by xiaoyezao** [PacificBiosciences/pbbioconda#123]
Hi, is it possible to run falcon unzip and polish on a genome assembly derived from canu assembler?

**Comment by pb-cdunn** [comment]
Not at the moment. Sorry.

**Comment by xiaoyezao** [comment]
Thanks for your quick reply.

I am currently running arrow to do the polish. arrow crashed because of external reasons. Is it possible to resume the process from where it stops?

**Comment by pb-cdunn** [comment]
The workflow, yes. But that point in a specific arrow run, now.
