### ISSUE TITLE
Question about barcode demultiplexing (lima report file)

### ISSUE THREAD

**Issue by lyraealpha** [PacificBiosciences/pbbioconda#124]
Dear developers:
         I used lima  to split my Isoseq data , and got some results just like data showing below(Lima) ,as you can see, half of my ZMWs was filtered by the score lead threshold,I found FAQs on your website(https://github.com/PacificBiosciences/barcoding),you suggest to try to decrease --score-lead threshold  with the potential risk of introducing false positives,but I did not find anything that can help me to fully understand the value of  ScoreLead, I summarized the distribution of   ScoreLead  values from my lima results，and the results are showing below( ScoreLead),most of my ScoreLead result is -1,what does -1 mean, highly unreliable or something else?
        Furthermore,there are some extra questions that I want to ask:
1. what do columns(IdxLowestNamed,IdxLowestNamed,IdxLowest,IdxHighest) actually mean in lima report file.
2. how does lima generete results of IdxLowestNamed and IdxLowestNamed (mainly about the ifelse condition).

Lima:
ZMWs input                (A) : 479070
ZMWs above all thresholds (B) : 218231 (46%)
ZMWs below any threshold  (C) : 260839 (54%)
ZMW marginals for (C):
Below min length              : 166 (0%)
Below min score               : 1 (0%)
Below min end score           : 1 (0%)
Below min passes              : 0 (0%)
Below min score lead          : 220958 (85%)
Below min ref span            : 798 (0%)
Without adapter               : 39751 (15%)
ZMWs for (B):
With same barcode             : 218231 (100%)
Coefficient of correlation    : 17.55%
ZMWs for (A):
Allow diff barcode pair       : 416644 (87%)
Allow same barcode pair       : 439319 (92%)
Reads for (B):
Above length                  : 10285833 (100%)
Below length                  : 19130 (0%)

 ScoreLead：
1 ScoreLead
     76 0
     72 1
 259411 -1
    110 10
     94 11
     98 12
    112 13
    106 14
    109 15
    109 16
    115 17
    116 18
     99 19
     89 2
    118 20
    137 21
    140 22
    137 23
    151 24
    168 25
    155 26
    164 27
    192 28
    188 29
    160 3
    205 30
    231 31
    231 32
    211 33
    237 34
    288 35
    299 36
    362 37
    321 38
    349 39
    143 4
    421 40
    402 41
    423 42
    466 43
    497 44
    514 45
    516 46
    596 47
    658 48
    625 49
    156 5
    738 50
    789 51
    771 52
    894 53
    870 54
    941 55
   1062 56
   1123 57
   1227 58
   1254 59
    157 6
   1456 60
   1539 61
   1717 62
   1774 63
   2092 64
   2289 65
   2526 66
   2794 67
   3092 68
   3537 69
    132 7
   3917 70
   4532 71
   5257 72
   6113 73
   6895 74
   8161 75
   9348 76
  11002 77
  12429 78
  13814 79
    107 8
  15278 80
  16432 81
  16390 82
  15102 83
  12074 84
   7728 85
   4082 86
   2570 87
   1297 88
    816 89
     96 9
    671 90
    402 91
    284 92
    363 93
    126 94
     91 95
     63 96
    230 97
     39 98
     10 99

**Comment by armintoepfer** [comment]
Hi! 
Could you please paste the exact command that you ran and the content of your fasta file that you've used for demuxing?

Armin

**Comment by lyraealpha** [comment]
Command:
smrtlink6/smrtlink/smrtcmds/bin/lima        --num-threads 6      --split-bam-named     my_input_sequel_subreads.bam   my_barcode.fasta    my_output_subreads.bam

barcode:
>bc1001
CACATATCAGAGTGCG
>bc1014
CTCACTACGCGCGCGT

results extracted form lima report:
ZMW	ScoreLead	IdxLowest	IdxHighest
m54206_190310_023946/4194371	-1	0	0
m54206_190310_023946/4194374	-1	0	0
m54206_190310_023946/4194375	61	1	1
m54206_190310_023946/4194377	83	1	1

one subread form input bam file:
m54206_190310_023946/4194371/14624_15163	4	*	0	255	*	*	0	0	CCATTTATTCCTCAACTTTGGCATTTTTTTTAAAGACATTTCTTAGACCTGGTGATATTTTAAGACAGAGATGCAGACATAATATATGATTGGGGGTTAAGTTTGGTCGATAGCAAGGATTCCATATTATCCCCTTCCATAGCCTCTGAACTACTTCCCAGTACTGGATGGTAAATATGTGATTGCATTATGTGATATTACACCCAAACGGATAATGCGGGTGTCAAATTGTCAACCAAACACAAGAAAATGTTGGTTCCCGGGAGTTACAAGGTGTCTTATGTCCATGGTAAAAAGTGATGTACTTTGATCCACGTGTTAAGACAAATATTATTGGATTCCTGTGGGGGAATTGAGGTAACAAATTTTTTGCTTTGGACGCCTTGTATCAGCCATTTCAGTGATGGCATTGTTACACTGTCTTATGGAATAGTTTGTGAGATTATTAAACTTTTATCATGCTCTCCAACAAAAAAAAAAAAAAAAAAAAAAAAAGTACTCTGGCGTTGATACCACTGCTTCGCACTCGGTGATATGTG	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!	cx:i:2	ip:B:C,28,50,0,15,74,1,20,17,33,0,6,0,2,3,17,75,4,4,0,29,69,2,18,55,47,33,13,28,0,14,0,18,5,10,3,12,33,11,0,64,4,9,1,41,21,23,63,8,21,9,111,4,1,14,8,11,20,13,5,28,19,6,35,66,2,4,13,5,6,38,1,24,13,22,8,7,6,8,5,14,5,52,21,6,23,10,35,20,18,9,47,18,3,0,1,11,4,61,0,12,8,36,1,28,17,33,18,11,6,38,55,75,0,3,12,6,16,20,3,20,27,8,25,8,29,5,11,17,16,39,25,70,42,2,69,9,14,49,6,17,3,41,34,24,5,0,24,5,5,50,46,7,16,2,11,29,4,8,1,3,2,39,35,2,18,1,0,15,10,8,16,7,20,16,2,6,42,56,2,0,17,1,15,72,6,5,28,23,8,72,57,13,21,0,6,10,14,8,5,8,1,2,37,16,13,0,3,14,35,48,11,5,38,17,10,5,12,6,9,1,39,7,28,56,11,2,9,5,6,29,9,1,22,0,13,73,8,5,3,7,0,2,6,2,1,3,6,31,7,26,20,10,30,17,17,22,0,17,36,10,10,54,28,16,10,7,26,38,15,7,4,40,24,0,0,1,3,19,37,18,56,73,29,25,2,1,50,4,0,7,4,11,23,32,55,85,12,5,1,5,11,1,1,2,46,10,29,40,13,0,16,7,4,2,23,0,22,3,18,3,10,57,17,9,16,5,13,20,15,12,12,2,6,18,123,7,28,11,89,3,16,5,1,6,22,28,11,5,4,19,5,32,10,24,22,4,6,36,8,10,83,11,75,16,15,11,4,14,2,10,26,4,14,40,24,11,3,26,1,59,1,9,19,7,36,7,2,23,31,3,75,46,50,10,12,24,87,18,3,2,67,22,1,5,18,11,0,0,7,5,16,3,23,2,7,10,0,67,32,13,18,9,16,15,1,20,12,10,31,1,17,22,20,13,50,38,10,19,19,1,7,10,0,60,0,4,6,18,5,0,25,7,5,6,28,12,5,5,0,1,16,34,12,0,2,81,31,8,52,0,0,14,37,4,4,29,8,50,1,5,17,0,16,6,11,8,33,10,19,4,10,8,2,17,56,4,8,29,25,14,75,65,36,7,4,29,44,40,41,24,4,10,11,3,143,13,12,39,4,15,99,7,21,17,0,15,10,15,12,0,9,18,34,35,11,14,6,9,59	np:i:1	pw:B:C,22,16,4,7,11,5,19,22,20,16,4,10,53,10,27,30,8,13,28,65,3,7,10,7,12,3,4,60,2,42,56,5,22,14,36,27,31,3,3,24,11,39,7,10,16,21,3,30,12,5,33,26,10,18,20,7,18,27,16,12,13,47,3,11,62,23,6,17,17,18,9,9,23,30,7,38,21,10,3,5,5,17,6,12,2,7,5,11,36,4,28,16,5,4,4,25,7,49,11,4,14,5,17,7,54,12,13,59,55,10,2,35,7,31,5,7,12,4,9,18,12,6,25,3,3,4,6,12,13,11,5,33,8,4,5,5,43,22,5,7,11,3,38,19,6,13,57,64,4,25,7,3,32,20,8,22,20,24,38,3,3,3,16,8,12,12,6,17,13,38,14,8,3,12,8,9,3,4,16,16,17,5,6,11,24,14,22,10,16,23,10,28,4,8,32,20,19,3,8,48,26,9,19,20,7,13,12,5,24,28,53,17,14,54,13,2,3,20,15,14,12,23,11,16,19,21,4,18,3,10,26,21,23,10,10,64,8,8,8,8,4,7,6,11,52,5,6,14,4,10,20,23,17,11,6,11,37,22,65,16,6,4,23,4,10,7,11,18,24,28,4,19,27,11,3,9,4,37,3,8,13,13,5,7,6,13,9,13,4,16,23,22,28,3,26,16,7,12,15,18,12,6,19,13,20,12,12,5,5,8,5,46,18,6,13,10,7,30,5,11,10,3,10,82,16,12,8,7,7,9,4,8,6,23,10,16,20,14,27,11,17,47,8,16,8,11,51,11,15,11,55,26,10,15,15,14,15,10,12,11,18,4,5,4,20,8,2,6,9,39,9,81,56,3,7,4,4,14,20,18,2,14,15,9,16,12,26,13,20,2,8,3,10,13,9,6,12,10,15,10,3,11,9,16,7,11,13,44,10,37,18,36,23,10,9,10,6,17,16,4,30,15,3,21,9,10,17,6,25,4,3,4,2,5,11,5,14,14,3,15,4,36,2,9,5,70,9,25,5,24,13,3,27,9,6,13,6,21,11,18,9,50,12,2,23,4,35,9,64,17,38,17,10,16,13,6,52,3,5,32,24,25,7,28,14,21,6,17,17,16,6,33,7,14,18,4,10,2,7,9,15,5,35,5,46,15,22,11,32,6,5,11,8,2,3,24,15,7,3,8,13,4,37,25,7,18,4,136,119,49,28,44,15,5,9,19,18,3,5	qe:i:15163	qs:i:14624	rq:f:0.8	sn:B:f,7.00698,13.218,8.16834,14.1587	zm:i:4194371	RG:Z:70a01535

**Comment by armintoepfer** [comment]
May I ask why you are not using SMRT Link? You are obviously not following any of our isoseq documentation, neither those distributed by PacBio directly or on GitHub. This is the wrong the lima command with incorrect barcodes. This is not a problem of the software distributed via bioconda. Please contact your local PacBio representative or read the available documentation distributed by PacBio or alternatively https://github.com/PacificBiosciences/IsoSeq_SA3nUP/wiki

**Comment by lyraealpha** [comment]
Sorry ,your answers just made me more confused.

First of all:
I used lima command by the instruction on your website: https://github.com/pacificbiosciences/barcoding

your example command :
lima 
movie.subreads.bam
barcodes.fasta 
prefix.bam

my command:
lima 
--num-threads 6 
--split-bam-named 
my_input.bam 
my_barcodes.fasta 
my_output_subreads.bam
despite the optional args(--num-threads 6 --split-bam-named ),I can not see any difference:

secondly :
your example barcodes file:
>bc1000
CTCTACTTACTTACTG
>bc1001
GTCGTATCATCATGTA
>bc1002
AATATACCTATCATTA

my barcodes file:
>bc1001
CACATATCAGAGTGCG
>bc1014
CTCACTACGCGCGCGT

Could you please tell me what's wrong with my command exactly, I'd be very thankful for your help.

**Comment by armintoepfer** [comment]
There is a whole isoseq section. Please scroll down.
