### ISSUE TITLE
preassembled coverage

### ISSUE THREAD

**Issue by hermeseduardo** [PacificBiosciences/pbbioconda#127]
Hi there, the preassembled_coverage is 10 but the seed_coverage was 48, does this sounds right? please find bellow the stats and the info. from the cfg. The gene content of the assembly after arrow is a bit low so I try lowering the seed coverage and length cutoff to get a larger genome size.
```js
pre_assembly_stats.json
{
    "genome_length": 550000000,
    "length_cutoff": 500,
    "preassembled_bases": 5556292487,
    "preassembled_coverage": 10.102,
    "preassembled_esize": 11866.489,
    "preassembled_mean": 8840.589,
    "preassembled_n50": 11023,
    "preassembled_p95": 18259,
    "preassembled_reads": 628498,
    "preassembled_seed_fragmentation": 1.237,
    "preassembled_seed_truncation": 1298.262,
    "preassembled_yield": 0.207,
    "raw_bases": 26882689393,
    "raw_coverage": 48.878,
    "raw_esize": 13935.667,
    "raw_mean": 9147.263,
    "raw_n50": 12685,
    "raw_p95": 21486,
    "raw_reads": 2938878,
    "seed_bases": 26882689393,
    "seed_coverage": 48.878,
    "seed_esize": 13935.667,
    "seed_mean": 9147.263,
    "seed_n50": 12685,
    "seed_p95": 21486,
    "seed_reads": 2938878
}
```
fc_run_pb_assembly

#### Input
```cfg
[General]
input_fofn=input.fofn
input_type=raw
pa_DBdust_option=
pa_fasta_filter_option=pass
target=assembly
skip_checks=False
LA4Falcon_preload=false

#### Data Partitioning
pa_DBsplit_option=-x500 -s200
ovlp_DBsplit_option=-x500 -s200

#### Repeat Masking
pa_HPCTANmask_option=
pa_REPmask_code=0,300;0,300;0,300

####Pre-assembly
genome_size=550000000
seed_coverage=3
length_cutoff=500
pa_HPCdaligner_option=-v -B128 -M24
pa_daligner_option=-e.8 -l1000 -k18 -h480  -w8 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 1 --max-n-read 1800
falcon_sense_greedy=False

####Pread overlapping
ovlp_daligner_option=-e.9 -l1000 -k24 -h1024 -w6 -s100
ovlp_HPCdaligner_option=-v -B128 -M24

####Final Assembly
overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 1
#fc_ovlp_to_graph_option=100
fc_ovlp_to_graph_option=
length_cutoff_pr=1000

[job.defaults]
job_type=SLURM
pwatcher_type=blocking
job_queue=defq
MB=32768
NPROC=48
njobs=32
NNODES=1
#submit = srun --partition=${job_queue} --wait=500 --output=${JOB_STDOUT} --error=${JOB_STDERR} --ntasks-per-node=${NNODES} --cpus-per-task=${NPROC} --mem=${MB}M ${JOB_SCRIPT}
submit = srun --wait=5 --output=${JOB_STDOUT} --error=${JOB_STDERR} --ntasks-per-node=${NNODES} --cpus-per-task=${NPROC} --mem=${MB}M ${JOB_SCRIPT}

#DELETED from submit  --q ${job_queue}  -N ${JOB_NAME} -S /bin/bash -sync y -V  -N=${NNODES} 

[job.step.da]
NPROC=4
MB=32768
njobs=240
[job.step.la]
NPROC=4
MB=32768
njobs=240
[job.step.cns]
NPROC=8
MB=65536
njobs=240
[job.step.pda]
NPROC=4
MB=32768
njobs=240
[job.step.pla]
NPROC=4
MB=32768
njobs=240
[job.step.asm]
#job_queue=m512gb
NPROC=20
#MB=196608
MB=126976
njobs=1
```

**Comment by sunnycqcn** [comment]
> Hi there, the preassembled_coverage is 10 but the seed_coverage was 48, does this sounds right? please find bellow the stats and the info. from the cfg. The gene content of the assembly after arrow is a bit low so I try lowering the seed coverage and length cutoff to get a larger genome size.
> 
> ```js
> pre_assembly_stats.json
> {
>     "genome_length": 550000000,
>     "length_cutoff": 500,
>     "preassembled_bases": 5556292487,
>     "preassembled_coverage": 10.102,
>     "preassembled_esize": 11866.489,
>     "preassembled_mean": 8840.589,
>     "preassembled_n50": 11023,
>     "preassembled_p95": 18259,
>     "preassembled_reads": 628498,
>     "preassembled_seed_fragmentation": 1.237,
>     "preassembled_seed_truncation": 1298.262,
>     "preassembled_yield": 0.207,
>     "raw_bases": 26882689393,
>     "raw_coverage": 48.878,
>     "raw_esize": 13935.667,
>     "raw_mean": 9147.263,
>     "raw_n50": 12685,
>     "raw_p95": 21486,
>     "raw_reads": 2938878,
>     "seed_bases": 26882689393,
>     "seed_coverage": 48.878,
>     "seed_esize": 13935.667,
>     "seed_mean": 9147.263,
>     "seed_n50": 12685,
>     "seed_p95": 21486,
>     "seed_reads": 2938878
> }
> ```
> 
> fc_run_pb_assembly
> 
> #### Input
> ```haproxy-config
> [General]
> input_fofn=input.fofn
> input_type=raw
> pa_DBdust_option=
> pa_fasta_filter_option=pass
> target=assembly
> skip_checks=False
> LA4Falcon_preload=false
> 
> #### Data Partitioning
> pa_DBsplit_option=-x500 -s200
> ovlp_DBsplit_option=-x500 -s200
> 
> #### Repeat Masking
> pa_HPCTANmask_option=
> pa_REPmask_code=0,300;0,300;0,300
> 
> ####Pre-assembly
> genome_size=550000000
> seed_coverage=3
> length_cutoff=500
> pa_HPCdaligner_option=-v -B128 -M24
> pa_daligner_option=-e.8 -l1000 -k18 -h480  -w8 -s100
> falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 1 --max-n-read 1800
> falcon_sense_greedy=False
> 
> ####Pread overlapping
> ovlp_daligner_option=-e.9 -l1000 -k24 -h1024 -w6 -s100
> ovlp_HPCdaligner_option=-v -B128 -M24
> 
> ####Final Assembly
> overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 1
> #fc_ovlp_to_graph_option=100
> fc_ovlp_to_graph_option=
> length_cutoff_pr=1000
> 
> [job.defaults]
> job_type=SLURM
> pwatcher_type=blocking
> job_queue=defq
> MB=32768
> NPROC=48
> njobs=32
> NNODES=1
> #submit = srun --partition=${job_queue} --wait=500 --output=${JOB_STDOUT} --error=${JOB_STDERR} --ntasks-per-node=${NNODES} --cpus-per-task=${NPROC} --mem=${MB}M ${JOB_SCRIPT}
> submit = srun --wait=5 --output=${JOB_STDOUT} --error=${JOB_STDERR} --ntasks-per-node=${NNODES} --cpus-per-task=${NPROC} --mem=${MB}M ${JOB_SCRIPT}
> 
> #DELETED from submit  --q ${job_queue}  -N ${JOB_NAME} -S /bin/bash -sync y -V  -N=${NNODES} 
> 
> [job.step.da]
> NPROC=4
> MB=32768
> njobs=240
> [job.step.la]
> NPROC=4
> MB=32768
> njobs=240
> [job.step.cns]
> NPROC=8
> MB=65536
> njobs=240
> [job.step.pda]
> NPROC=4
> MB=32768
> njobs=240
> [job.step.pla]
> NPROC=4
> MB=32768
> njobs=240
> [job.step.asm]
> #job_queue=m512gb
> NPROC=20
> #MB=196608
> MB=126976
> njobs=1
> ```

Did you solve your problem? I met the same problem. The "preassembled_yield": 0.306.
Thanks,
Fuyou
