### ISSUE TITLE
pbmm2 primary alignments

### ISSUE THREAD

**Issue by Adamtaranto** [PacificBiosciences/pbbioconda#128]
When using pbmm2 will setting "--best-n 1" return only the best alignment for a read or just the first alignment that passes the alignment threshold criteria?

I've got reads in my dataset that map to many transposon instances. I'm concerned about this introducing errors during polishing. Should secondary alignments be filtered before running ARROW?

**Comment by armintoepfer** [comment]
In general, you should not limit the number of alignments. pbmm2 will give you supplementary but never secondary alignments. The same query base is never aligned twice.
