### ISSUE TITLE
Arrow polish failed with exitcode=-9

### ISSUE THREAD

**Issue by xiaoyezao** [PacificBiosciences/pbbioconda#130]
Hi,
my arrow polish exited with `exitcode=-9` in almost its half way after 6 days running. I have no idea what's going wrong, maybe out of memory?

the slurm out message is : 

**Child process exited with exitcode=-9.  Aborting.
[ERROR] Child process exited with exitcode=-9.  Aborting.
Aborting
[ERROR] Aborting
srun: error: cn13119: task 0: Exited with exit code 255**

Any suggestions would be appreciated much.

**Comment by esrice** [comment]
@xiaoyezao did you fix this issue? I'm getting the same error currently. Thanks!
