### ISSUE TITLE
Continual adapters flank CCS reads

### ISSUE THREAD

**Issue by niehu2018** [PacificBiosciences/pbbioconda#133]
Hello, 
    I am not going to report a bug. I have not found a bug in your codes for now.
    I found a bug in my data, and want to share with you.
    I aligned my iso-seq Raw CCS reads (produced by ccs program) to the reference genome(mm10) using minimap2, and view it in IGV.

I picked one CCS here:
AAGCAGTGGTATCAACGCAGAGTACGATCTCTACTATATGCTTTTTTTTTTTTTTAAGGGATTTTGTATTTATTGCATTGGGAGCTTCTGGGAGCCTGGGGCCCTTAGCACAGATGGGTGCCTGGTGGGCCCTTGGTGCTCTGTGTCAGGGCCAGGGGATGGGGGGGAGATGCGTGCAGGGGGCAGCAATGGTGTGTGGAGTGTGTGAGACTGCTGCTCCGGGCACATCCTGAGTCACGAGCGGGTGTGATTGGTAGAGAGGCACGTGGATCCCTGGGACACGGCCTCTTCCACATGTGTGGGATTCCCCATGCCCTGAGATTCCCTGGAAGGACCTGGACAAGGGACACAGTGAGACTTTGAAGAAAGGAGCTGTGTTGGACATGGTGTACCTGCCCGCTGTCCCTACTACAGTAGAGGCTGAGGCAGGCAGGCTAGTTCCAGGCCAGCCTGGGCTATAGCAGTGAGTTCCAGACCAGCCTGAGCGATCTAGGGAGTCCTGGTCTCAAAAAAAAAAAAAAAAAAAAAAAAATCTGAAAAGACACCAGGGTGAGATATGCAAACCTGGGCTCAGTCCCCAGAATATAAAAAAAAACAAACAAACAACAACAAACAAAACCTCAACATGTGTGGTTCCTTCAAGTTCCCCTCCCGCCCCACATACCCGGGTCAGCTGGGGGCAGCCTCGGTCTTCACTCTTTTGGGGGGCCTGTGGAGTATAGGGCTGTTGGGCTTGGACTTATACGAAACATGCACTGCACCATTGAGATGCACGGGGGGCTCAGCCTTGAGTGCTACTGGGCGAGGCAGAGGTGGCAGGGCTTTGTCTAGCACGCAGGGTCCATCCCAGGCTGGAATCTCCAGCCCCAGATGCTTCATGAGTCTGCACATCACCTCATCCACGTAGCCGTGGATGCGCAGGTCAGCCTGGCGGTCATGTTTTGTGGGTTGCAGGTTGACAATGACCAGACGGCCTCCTCGGCGCTTAGTGGCAAGGGGCAGGTTCCCACTGGGGCGGATCTGCAGCGAGGTACCCAGGGTGACAGACAGGTCTGCGGTCCTGCTGGCCTCATCAGCGAGCATCAGGTCCCGGTCAGGCAACGAGTCCTCCCAGTCCAGAATGGTGTCTCTCAGCTCCCCTCTACAGGCCCGAAGTCCCCTGGTCTTGGCCACGGTGCAGAGCCGGCCTGTGGCCTTGAGGCCCATGGTGCCCACAACCGTGTCTCTGACGTACTGCGTCTTACACTTGGGACATTCCTCTACAAACATGTTTCCGTGCAGCTCTGCCAGCTTGTCCCTGGGGAAGCCCGAGCGCACGTGCAGCCCGTCTACGTTCTGGCTGACCAGGAAGCTGAGGAAGCCCATGCGTTCTAGCTGAACCAGGGCCATGTGGGTCTTCGAGGGCCGAGCATTCTCGAAGGTGGTGTCAACTTGGGGGCCAGGCCGCGTTCCTCCATGGTCCACACGCCATGGGGGCCTCTGAAGTCGGGGATGCCAGAGGCGGTGCTGATGCCGGCGCCCGTGTGGAAAACCACGCTGGAGGACTGCCAATTAGCCGGGCCAGCTCCCACACCTTGCGTTCCAGCTCCTCTGGTGGGTCGAAGATCTCGGGCAGCCCGCACTTGCCCTTATCCGCGTAAGGCGACAACCCTGCTGCATAATTCACCGACATCGTCGCCGGCGCTGCCGCACGGGAACAATAAAGTTTCCCTTGTTGAGGCCGCTTCCGCCGGAAGT(**CCCCATGTACTCTGCGTTGATACCACTGCTT**)(**CCCATGTACTCTGCGTTGATACCACTGCTT**)(**CCCATGTACTCTGCGTTGATACCACTGCTT)(CCCATGTACTCTGCGTTGATACCACTGCTT**)

As you can see, there are four SMRT adapters in the 5' end of the RNA.
Have you ever encountered this situation? and what may lead to this?

Best !
Hu

**Comment by armintoepfer** [comment]
This looks strange. If this is also in the subreads, then something went wrong during library prep. If it's _not_ in the subreads, it's a software bug. We can help here if it's a software problem. Otherwise, maybe worthwhile to ask your local PacBio representative or tech support.

**Comment by niehu2018** [comment]
Yes, it is also in the subreads indeed. So, it's not a software problem, thanks for your timely reply.
I will ask the local PacBio representative for help. Thanks!
