### ISSUE TITLE
Functional Differences between pbmm2 bam and Pbbamify bams

### ISSUE THREAD

**Issue by harish0201** [PacificBiosciences/pbbioconda#134]
Hi, 

I curious about the flags that are being set in Pbbamify bams for the reads, are there any flags that get added that are not being reported by pbmm2?

Because currently (and superficially), the addition that pbbamify makes is the M5 header in the aligned bams, while resetting the sort order. I'm sure that I'm missing the flag that states don't mess with the SO though :(

Please see the few lines below to get what I mean:

Pbmm2 aligned bams:
`@HD     VN:1.5  SO:coordinate   pb:3.0.5`
`@SQ     SN:ctg1363      LN:18924`
`@SQ     SN:ctg1364      LN:23673`
`@RG     ID:67667dcf     PL:PACBIO       DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-500-400;SEQUENCINGKIT=101-427-500;BASECALLERVERSION=5.0.0;FRAMERATEHZ=100.000000        PU:m54143_190304_073244 SM:UnnamedSample       PM:SEQUEL`
`@PG     ID:baz2bam      PN:baz2bam      VN:6.0.0.47712  CL:/opt/pacbio/ppa-6.0.0/bin/baz2bam /data/pb/m54143_190304_073244.baz -o /data/pb/m54143_190304_073244 --metadata /data/pb/.m54143_190304_073244.metadata.xml -j 12 -b 12 --progress --silent --minSubLength 50 --minSnr 3.750000 --adapters /data/pb/m54143_190304_073244.adapters.fasta --controlAdapters /data/pb/m54143_190304_073244.controls.adapters.fasta --controls /data/pb/m54143_190304_073244.controls.fasta --maxInputQueueZMW 10000 --zmwBatchSize 1000 --zmwHeaderBatchSize 1000`
`@PG     ID:bazFormat    PN:bazformat    VN:1.5.0`
`@PG     ID:bazwriter    PN:bazwriter    VN:6.0.0.47712`
`@PG     ID:pbmm2        PN:pbmm2        VN:1.0.0 (commit 1.0.0) CL:pbmm2 align cns.mmi m54143_190304_073244.subreads.bam align/m54143_190304_073244.aligned.bam --sort -j 6 -J 10`

Pbbamify bams:
`@HD     VN:1.5  SO:unknown      pb:3.0.5`
`@SQ     SN:ctg1363      LN:18924`
`@SQ     SN:ctg1364      LN:23673        M5:5ef8167c05a36d7470d552007b360ec3`
`@RG     ID:b40e3956     PL:PACBIO       DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-500-400;SEQUENCINGKIT=101-427-500;BASECALLERVERSION=5.0.0;FRAMERATEHZ=100.000000        PU:m54143_190226_222527 PM:SEQUEL`
`@PG     ID:baz2bam      PN:baz2bam      VN:6.0.0.47712  CL:/opt/pacbio/ppa-6.0.0/bin/baz2bam /data/pb/m54143_190226_222527.baz -o /data/pb/m54143_190226_222527 --metadata /data/pb/.m54143_190226_222527.metadata.xml -j 12 -b 12 --progress --silent --minSubLength 50 --minSnr 3.750000 --adapters /data/pb/m54143_190226_222527.adapters.fasta --controlAdapters /data/pb/m54143_190226_222527.controls.adapters.fasta --controls /data/pb/m54143_190226_222527.controls.fasta --maxInputQueueZMW 10000 --zmwBatchSize 1000 --zmwHeaderBatchSize 1000`
`@PG     ID:bazFormat    PN:bazformat    VN:1.5.0`
`@PG     ID:bazwriter    PN:bazwriter    VN:6.0.0.47712`
`@PG     ID:pbmm2        PN:pbmm2        VN:1.0.0 (commit 1.0.0) CL:pbmm2 align cns.mmi m54143_190226_222527.subreads.bam align/m54143_190226_222527.aligned.bam --sort -j 6 -J 10`

Asking this because if this is the case that no additional flags are being set in the bams, I can just paste up the differences in the bam headers instead of running pbbamify completely.

**Comment by harish0201** [comment]
Just curious, I tend to use the mmi index would that be causing the absence of the m5 tag?

**Comment by armintoepfer** [comment]
We can't compute M5, exactly because of mmi. But we also don't need M5 for anything. pbbamify was a workaround before I finished pbmm2.

**Comment by harish0201** [comment]
Awesome! I just uses the contig file directly to generate the alignments and successfully was able to parse it using arrow on my test case.

Maybe you might want to put a PSA on the pbmm2 readme?
