### ISSUE TITLE
pbmm2 illegal instruction

### ISSUE THREAD

**Issue by mchaisso** [PacificBiosciences/pbbioconda#136]
**Operating system**
Which operating system and version are you using?
CentOS
**Package name**
pbmm2 1.0.0 (commit 1.0.0)

Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**
Running the executable with no options (or any options) results in "Illegal instruction"

**Error message**
illegal instruction

**To Reproduce**
pbmm2 
(just running) 
This architecture crashes:
cpu family      : 16
model           : 9
model name      : AMD Opteron(tm) Processor 6176
stepping        : 1
microcode       : 0x10000d9
cpu MHz         : 800.000
cache size      : 512 KB
physical id     : 0
siblings        : 12
core id         : 0
cpu cores       : 12
apicid          : 16
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 5
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc art rep_good nopl nonstop_tsc extd_apicid amd_dcm pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate retpoline_amd ibp_disable vmmcall npt lbrv svm_lock nrip_save pausefilter
bogomips        : 4600.03
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual

The following architecture works fine:
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 26
model name      : Intel(R) Xeon(R) CPU           E5540  @ 2.53GHz
stepping        : 5
microcode       : 0x1d
cpu MHz         : 1600.000
cache size      : 8192 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm dca sse4_1 sse4_2 popcnt lahf_lm ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida spec_ctrl intel_stibp flush_l1d
bogomips        : 5053.99
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:

The difference between flags is:
< 3dnow
< 3dnowext
< 3dnowprefetch
< abm
< amd_dcm
---
> 
> acpi
> aperfmperf
7c5,6
< art
---
> arch_perfmon
> bts
10d8
< cmp_legacy
12d9
< cr8_legacy
14a12
> dca
16,17c14,22
< extapic
< extd_apicid
---
> ds_cpl
> dtes64
> dtherm
> dts
> eagerfpu
> ept
> est
> flexpriority
> flush_l1d
20d24
< fxsr_opt
22,24c26,29
< hw_pstate
< ibp_disable
< ibs
---
> ibpb
> ibrs
> ida
> intel_stibp
26d30
< lbrv
30d33
< misalignsse
32d34
< mmxext
36d37
< nodeid_msr
39,40d39
< npt
< nrip_save
42d40
< osvw
45,46c43,45
< pausefilter
< pdpe1gb
---
> pbe
> pdcm
> pebs
54d52
< retpoline_amd
56c54,56
< skinit
---
> spec_ctrl
> ss
> ssbd
59,61c59,62
< sse4a
< svm
< svm_lock
---
> sse4_1
> sse4_2
> ssse3
> stibp
62a64,66
> tm
> tm2
> tpr_shadow
65,66c69,73
< vmmcall
< wdt
---
> vmx
> vnmi
> vpid
> xtopology
> xtpr

Finally, minimap2 runs fine on both cpus

**Comment by armintoepfer** [comment]
You are right. I forgot to add that to the FAQ. We explicitly compile with `sse4_1` to have the speed boost. We currently don't support CPUs without that instruction set. Have you compared the speed differences between those two servers for minimap2? I'm curious.

**Comment by mchaisso** [comment]
No, but I can. I can also just exclude these nodes from cluster
submission.. they make up ~30% of our cores and 70% is more than what I'm
allowed to use. I thought it would be a bigger issue but jobs were landing
on the opteron nodes with priority.

**Comment by armintoepfer** [comment]
Please use those nodes that support sse4_1 and I'll try to add a proper runtime error.
