### ISSUE TITLE
resume arrow polishing

### ISSUE THREAD

**Issue by xiaoyezao** [PacificBiosciences/pbbioconda#137]
I am running arrow to polish a 1.4G assembly with 100x pacbio subreads data. The job has run for 6 days and stopped because of external reason. I checked the log file finding that arrow seems to operate the contigs one by one. I am wondering is it ok to extract the remaining contigs and let arrow to run on these contigs and combine the results when finishing. Or are there any other solutions to finish the job? It would be painful to restart from the very beginning.

Your help will be much appreciated!

**Comment by armintoepfer** [comment]
You duped here #144
