### ISSUE TITLE
pbmm2 feature request: --tmpdir

### ISSUE THREAD

**Issue by charmichaeld** [PacificBiosciences/pbbioconda#138]
Hi,
A nice feature for pbmm2 would be to have a --tmpdir option which allows user to specify a temporary directory to use during the samtools sort step. This would be useful when running `pbmm2 align --sort` on HPC clusters that have a local drive on the compute node.

Thanks,
Michael

**Comment by armintoepfer** [comment]
Thank you, I'll consider it for the next version.

**Comment by pb-dseifert** [comment]
The POSIX way would be to use `TMPDIR` and not `--tmpdir`

**Comment by charmichaeld** [comment]
we use the $TMPDIR environment variable on our compute nodes

**Comment by pb-dseifert** [comment]
What are you trying to say? That you're using it for other purposes or you think it's good?

**Comment by charmichaeld** [comment]
we use the $TMPDIR environment variable on our compute nodes for the local drive on the compute node so it will work at least for our clusters. Either having pbmm2 look for a value in $TMPDIR or having an option similar to --tmpdir will be good for me.

**Comment by armintoepfer** [comment]
Just implemented it in the latest development version. It will take a bit of time until I cut a new release and push it publicly.
