### ISSUE TITLE
[pb-assembly] Script for generating haplotig placement files

### ISSUE THREAD

**Issue by gbdias** [PacificBiosciences/pbbioconda#139]
Hi,

- pb-assembly now outputs a very useful PAF file with the placement of haplotigs relative to the primary contigs after Unzipping.

> New! Placement Files -haplotig placement (PAF format) generated in 3-unzip stage
- I assume this file is obtained with minimap2, but some processing is done to the output.
- Could you point me to the script that generates this file?

Thanks,
Guilherme

**Comment by gbdias** [comment]
- The haplotig placement is not valid after Arrow polishing because the lengths of primary and haplotigs change a little bit.
- It would be super useful to have the haplotig placement file be generated again in the 4-polishing stage.
- I am trying to do this now and having a hard time with it.

**Comment by gbdias** [comment]
- I needed to obtain haplotig placement info to submit a phased assembly to genbank (haploid+alts).
- Repeats and structural variants will create a ton of weird alignments between haplotigs and primary contigs.
- However, by retaining the single longest alignment segment for each haplotig one can usually find the correct placement.
- I achieved this using minimap2 with the preset `-x asm5`.
- The alignment will sometimes not span the entirety of the haplotig, but the GenBank alternate locus placement format (https://www.ncbi.nlm.nih.gov/assembly/docs/submission/#ex4) allows one to specify the length of the alignment tails.
- It would be nice to have more precise boundaries for haplotig placement but this might be enough in some cases.

<img width="924" alt="Screen Shot 2019-05-14 at 6 32 07 PM" src="https://user-images.githubusercontent.com/7614153/57736607-99cbce80-7676-11e9-9866-9657b55e0fcc.png">

**Comment by zeeev** [comment]
Hi @gbdias,

I thought I would mention that FALCON-Phase, in it's first stage, produces haplotype placements using mummer. Perhaps they might work better in this case?

**Comment by gbdias** [comment]
Hi @zeeev , thank you for the tip.

Apparently GenBank is no longer taking haplotig placement info into account when you submit phased assemblies, so I no longer need this placement info for that particular purpose. But FALCON-Phase placement could be useful in many scenarios.

Thanks
