### ISSUE TITLE
tandem repeat mask error

### ISSUE THREAD

**Issue by kray02** [PacificBiosciences/pbbioconda#140]
Hello,

I have tried two different mask.bed files (repeatmasker, TRF) for the --tandem-repeats input for pbsv discover, but when I use pbsv call I get this error:

>|> 20190430 21:20:54.936 -|- WARN       -|- Summarize at ../src/tools/mike/InsertionCaller.cpp:203 -|- 0x7ff73d322740|| -|- Trying to cluster insertions of different tandem repeats!

this is for mmul8, four subreads.bam files of two samples. Any suggestions?

Thanks,
Karina

**Comment by armintoepfer** [comment]
It's a warning, not an error. You can safely ignore it. No worries. I'll decrease this message to debug in the next release.
