### ISSUE TITLE
pbmm2 truncated output.bam

### ISSUE THREAD

**Issue by mycecilia** [PacificBiosciences/pbbioconda#143]
**Operating system**
Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-46-generic x86_64)

**Package name**
*pbmm2*
**Conda environment**
```
# packages in environment at /home/shyche/.conda/envs/my_pb_env:
pb-assembly               0.0.5                    py27_2    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.7            py27hc0aa232_1    bioconda
pbalign                   0.3.2                    py27_0    bioconda
pbbam                     0.23.0               h88345a9_0    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  0.4.2                h3f2a3d2_1    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pbgcpp                    0.0.1                         0    bioconda
pbmm2                     1.0.0                ha888412_0    bioconda
```
**Describe the bug**
I ran `nohup pbmm2 align --sort -j 8 -J 4 $Reference $InputFile $OutputFile &> out.pbmm2 &`. Without any error message or logging message, the program generated 1654 tmp.nnnn.bam files, and a truncated output.bam file. I checked that there were enough disk space and at least 8 cpus available. I ran twice and got the same result.

**Comment by armintoepfer** [comment]
I never heard of this problem and we run thousands of pbmm2 jobs every week.
Maybe try to run it in a screen instead of nohup?
Also use `--log-level DEBUG` and then you'll get progress and see where it potentially stops.

**Comment by mycecilia** [comment]
I saw the error message `Bus error (core dumped) nohup pbmm2 align --sort -j 8 -J 4 $Reference $InputFile $OutputFile &> out.pbmm2` on the screen where the program was run.

**Comment by armintoepfer** [comment]
It's likely that your file system has instability. 1654 tmp files means your data is >3tb. Please try to align smaller chunks, like one movie at a time and then `samtools merge` them.
