### ISSUE TITLE
slice reference fasta to do arrow polish ?

### ISSUE THREAD

**Issue by xiaoyezao** [PacificBiosciences/pbbioconda#144]
Hi, can anyone help with arrow polish?

I am struggling to run arrow on a 1.4g assembly. It is estimated to take 10 days in our cluster, but has crashed several times in its halfway because of node problems.  I am thinking to do this:

`1. slice the assembly into 10 small datasets`
`2. use pbmm2 to align subreads to the 10 same datasets`
`3. use arrow to do the polish on the 10 datasets`
`4. merge the results after finishing`

Is this a proper way to do the polish?

**Comment by armintoepfer** [comment]
Align your data against all contigs. Split your alignment by contig using samtools. Polish each contig individually. Merge all polished contigs into one fasta.

**Comment by xiaoyezao** [comment]
When polishing each contig individually, should I use the complete assembly as the reference or use each contig as the reference?

**Comment by armintoepfer** [comment]
Closing as there hasn't been any follow up.
