### ISSUE TITLE
Does lima remove all duplicate sequences?

### ISSUE THREAD

**Issue by niehu2018** [PacificBiosciences/pbbioconda#145]
From page: https://github.com/PacificBiosciences/barcoding 

Even if you only want to remove IsoSeq primers, lima is the tool of choice.
**Remove all duplicate sequences**.
Annotate sequence names with a 5p or 3p suffix. Example:
    >primer_5p
    AAGCAGTGGTATCAACGCAGAGTACATGGGG
    >sample_brain_3p
    AAGCAGTGGTATCAACGCAGAGTACCACATATCAGAGTGCG
    >sample_liver_3p
    AAGCAGTGGTATCAACGCAGAGTACACACACAGACTGTGAG

Lima will remove all duplicate CCS reads?
Or, it will remove the duplicated sequence in the barcode file?

Look forward to any reply!
thanks!

**Comment by armintoepfer** [comment]
You are supposed to remove duplicate sequences from the input fasta file. You misunderstood that ;) I'll rephrase it next release.

**Comment by niehu2018** [comment]
Thanks,  if the user can set whether or not to remove duplicates, it will be better!

**Comment by armintoepfer** [comment]
In the fasta barcode file or reads? The ladder would be a completely different tool ;)

**Comment by niehu2018** [comment]
In the ccs read fasta file, I want to keep all the reads, as they all provide information to my study,
So I have to write my own demultiplex program.
