### ISSUE TITLE
How to interpret IsoSeq3.1 output?

### ISSUE THREAD

**Issue by alissawilliams** [PacificBiosciences/pbbioconda#146]
Hello-

We're having trouble interpreting the final output of the IsoSeq3.1 pipeline. Could you possibly point us to the most up-to-date resources for:
1. Interpreting final output (polished.hq.fasta) -- what does full_length_coverage mean? What does num_subreads mean in this context?
2. A list of parameters for each command. For instance, what are the options for running ccs?
3. A description of how clustering/merging/polishing works.

Thanks in advance for any help you can give us!

**Comment by armintoepfer** [comment]
Hi!

1: `full_length_coverage` is how many FLNC reads support this transcripts. `num_subreads` is equivalent to tag `iz` https://github.com/PacificBiosciences/IsoSeq3#bam-tags-explained.
2/3: Please read https://github.com/PacificBiosciences/IsoSeq3/blob/master/README_v3.1.md. I can't give you more info about the algorithm aside what it's described there.

Armin

**Comment by armintoepfer** [comment]
Closing as there hasn't been any follow up.

**Comment by alissawilliams** [comment]
Sorry for the late reply! Thank you!!
