### ISSUE TITLE
compilation of gcpp

### ISSUE THREAD

**Issue by Hikoyu** [PacificBiosciences/pbbioconda#151]
I want to use pbgcpp for pb-assembly-0.0.6 on macOS.
I have used pb-assembly-0.0.4 on both macOS and Ubuntu without bioconda. (recipes were referred)
I compiled gcpp in unanimity-3.4.1 package, but it doesn't work well. (only output header of fasta, fastq, and vcf)
Are there newer source code?

**Comment by armintoepfer** [comment]
gcpp is currently not available as source. There is a plan to ship all binaries also for macOS, but that won't happen in near future. You have to stick to linux environment for now.
