### ISSUE TITLE
disabling dust , HPCTANmask and REPmask; automatic length_cutoff for preads

### ISSUE THREAD

**Issue by bernardo1963** [PacificBiosciences/pbbioconda#152]
Hi,
There are two features that I think will be useful, and I could not find in the cfg files  (please advise if they are already available):
1. Disabling the filtering of raw reads  (disabling dust , HPCTANmask and REPmask), so people can try different approaches
2. Implement automatic length_cutoff for preads. Something like:

```ini
# The length cutoff used for preads
genome_size = 280000000
pread_coverage = 25
length_cutoff_pr = -1
```

**Comment by pb-cdunn** [comment]
1. For now, you have to set dust and tanmask settings such that the corresponding mask-tracks are empty. Someday, we might make that simpler, but it's low priority.
2. Yes, this could be useful, but it's such a fast step that I haven't bothered.

**Comment by bernardo1963** [comment]
Thanks.  I figured out some time ago  how to disable dust by setting super-restrictive parameters. However, I could not find the documentation to  tanmask.   May you suggest some value that would do the trick?  
There is also repmask, although in my data the daligner track always come empty.
