### ISSUE TITLE
No output from julietflow

### ISSUE THREAD

**Issue by lindongdo** [PacificBiosciences/pbbioconda#155]
Hi,
I am running julietflow for detecting minor variant by the code:
julietflow -i xx.ccs.bam -r xx.reference.fa -j 8

The code is running under miniconda2 where julietflow is installed. I got no error and also no output (I expect any html or json file). Does anyone can help to explain why this happened?

Thanks

Dong

**Comment by armintoepfer** [comment]
I don't know. Hard to tell without an example to reproduce.
