### ISSUE TITLE
"Answer 2" installation for blasr (configuring HDF5 library path)

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/pbbioconda#161]
Hi,

I am trying to install blasr from the source code (I was having issues with the bioconda installation).  I didn't see an "issues" tab with [that repository](https://github.com/PacificBiosciences/blasr/wiki/Blasr-Installation-Qs-&-As), so I thought posting here was the next best thing (although I apologize for the possible confusion).

I think my installation is almost successful, but I think the issue is with properly pointing to the HDF5 library in Ubuntu.

I installed the libraries using `sudo apt-get install libhdf5-serial-dev`.

I then believe that I found the appropriate installation folder in **/usr/lib/x86_64-linux-gnu/hdf5/serial** (with _lib_ and _share_ subfolders).

However, I am getting an error message, which I believe is because ninja (`sudo ninja -C build`) is still not looking in the right location:

```
In file included from ../subprojects/blasr_libcpp/hdf/HDFWriterBase.hpp:11:0,
                 from ../subprojects/blasr_libcpp/hdf/HDFWriterBase.cpp:3:
../subprojects/blasr_libcpp/hdf/BufferedHDF2DArray.hpp:8:10: fatal error: H5Cpp.h: No such file or directory
 #include <H5Cpp.h>
```

I have tried running :

```
export PATH_TO_HDF5_ROOT=/usr/lib/x86_64-linux-gnu/hdf5/serial
export LDFLAGS="-L${PATH_TO_HDF5_ROOT}/lib -lhdf5_cpp -lhdf5"
export CPPFLAGS="-isystem ${PATH_TO_HDF5_ROOT}/include"
```

I have also tried:

`export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/hdf5/serial.lib`

followed by 

```
meson -Dtests=false build . --reconfigure
ninja -C build
```

However, this also gives a similar error message.

Can you please help me configure the libraries properly?

Thank you very much.

Sincerely,
Charles

**Comment by armintoepfer** [comment]
As you might have read, we don't support installations from source, because the bioconda binaries usually work for everybody without messing with strange environments. Maybe you can tell us why the bioconda binary doesn't work for you?

Regarding your problem, did you see the trailing `\` in the meson call, right?

**Comment by cwarden45** [comment]
Thank you very much for your response.

**1)** I was running each command separately, instead of with the `\` (to combine the 3 lines).  Strictly speaking, I ran `cd blasr` before setting the environment variables and running meson (otherwise, I don't think the meson command would have worked, which I just verified).  However, I am also running `export` commands (not described in those directions), which I updated in my question.

**2)** I believe I have gotten blasr to work on my Mac (using bioconda), but I was trying to install on my Ubuntu VM (with more memory and processors).  While I thought I was close to getting the ninja command to work, I'll describe the bioconda issue on the Linux VM:

`/home/largeub/anaconda3/condabin/conda install -c bioconda blasr`

with the following error message:

```
NotWritableError: The current user does not have write permissions to a required path.
  path: /home/largeub/anaconda3/pkgs/blat-35-1/info/repodata_record.json
  uid: 1000
  gid: 1000

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 1000:1000 /home/largeub/anaconda3/pkgs/blat-35-1/info/repodata_record.json

In general, it's not advisable to use 'sudo conda'.
```

followed by 

`sudo chown 1000:1000 /home/largeub/anaconda3/pkgs/blat-35-1/info/repodata_record.json`


For most situations, I could run the `chown` command and fix the problem.  However, I think I've run into an issue with a file that is created during the installation.  I tried using `chmod +wrx` (and this is already in my home directory), but that isn't fixing the issue.

Do you have any recommendations for the Ubuntu VM blasr installation (with either strategy)?

**Comment by pb-dseifert** [comment]
In general we don't have the resources to support users building our software. Even more so with BLASR, which is legacy software and EOL now. Given its dependency on HDF5, building BLASR can be challenging, have a look at the Bioconda `build.sh` for the required flags.

You seem to be having issues with using Bioconda/conda. Once of the advantages of `conda` is that you don't need any special permissions to install Bioconda recipes. From the looks of it, it seems like you have a shared and/or provided by your sysadmin conda installation. This will ultimately not work.

**Comment by cwarden45** [comment]
OK - this is a VM installation of Anaconda.  However, since I have a working version on my Mac, I can work on installing Anaconda/Bioconda within my home directory on other servers where I am not the system admin.

Thank You.
