### ISSUE TITLE
errors in polishing after clustering when i used demo data from isoseq3.

### ISSUE THREAD

**Issue by xinkaitong** [PacificBiosciences/pbbioconda#164]
**Operating system**
Which operating system and version are you using?
linux.
**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?
[isoseq3](https://github.com/PacificBiosciences/IsoSeq3/blob/master/README_v3.1.md)
**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**
it went wrong when i did polishing after clustering demo data from isoseq3. the commands were fully same as the example in [isoseq3](https://github.com/PacificBiosciences/IsoSeq3/blob/master/README_v3.1.md), i was so confused!
**Error message**
Paste the error message / stack.
>|> 20190717 03:13:56.976 -|- ERROR      -|- operator() -|- 0x2b62ffb02700|| -|- Could not find ZMWs for cluster transcript/37
>|> 20190717 03:13:56.994 -|- ERROR      -|- operator() -|- 0x2b6300f0c700|| -|- Could not find ZMWs for cluster transcript/46
>|> 20190717 03:13:56.997 -|- ERROR      -|- operator() -|- 0x2b62fc8e9700|| -|- Could not find ZMWs for cluster transcript/15
>|> 20190717 03:13:57.000 -|- ERROR      -|- operator() -|- 0x2b6302f1c700|| -|- Could not find ZMWs for cluster transcript/60
>|> 20190717 03:13:57.001 -|- ERROR      -|- operator() -|- 0x2b62ff700700|| -|- Could not find ZMWs for cluster transcript/43
>|> 20190717 03:13:57.001 -|- ERROR      -|- operator() -|- 0x2b62fb8e1700|| -|- Could not find ZMWs for cluster transcript/1
>|> 20190717 03:13:57.002 -|- ERROR      -|- operator() -|- 0x2b62ff901700|| -|- Could not find ZMWs for cluster transcript/33
>|> 20190717 03:13:57.002 -|- ERROR      -|- operator() -|- 0x2b630331e700|| -|- Could not find ZMWs for cluster transcript/63
>|> 20190717 03:13:57.003 -|- ERROR      -|- operator() -|- 0x2b62fd4ef700|| -|- Could not find ZMWs for cluster transcript/19
>|> 20190717 03:13:57.003 -|- ERROR      -|- operator() -|- 0x2b62ff0fd700|| -|- Could not find ZMWs for cluster transcript/27
>|> 20190717 03:13:57.004 -|- ERROR      -|- operator() -|- 0x2b62fbce3700|| -|- Could not find ZMWs for cluster transcript/3
>|> 20190717 03:13:57.004 -|- ERROR      -|- operator() -|- 0x2b62fcaea700|| -|- Could not find ZMWs for cluster transcript/8
>|> 20190717 03:13:57.005 -|- ERROR      -|- operator() -|- 0x2b6302316700|| -|- Could not find ZMWs for cluster transcript/53
>|> 20190717 03:13:57.005 -|- ERROR      -|- operator() -|- 0x2b6302b1a700|| -|- Could not find ZMWs for cluster transcript/58
>|> 20190717 03:13:57.006 -|- ERROR      -|- operator() -|- 0x2b630110d700|| -|- Could not find ZMWs for cluster transcript/47
>|> 20190717 03:13:57.007 -|- ERROR      -|- operator() -|- 0x2b62fc6e8700|| -|- Could not find ZMWs for cluster transcript/11
>|> 20190717 03:13:57.007 -|- ERROR      -|- operator() -|- 0x2b62fe4f7700|| -|- Could not find ZMWs for cluster transcript/31
>|> 20190717 03:13:57.008 -|- ERROR      -|- operator() -|- 0x2b6301911700|| -|- Could not find ZMWs for cluster transcript/49
**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!
data url:
https://downloads.pacbcloud.com/public/dataset/RC0_1cell_2017/m54086_170204_081430.subreads.bam
https://downloads.pacbcloud.com/public/dataset/RC0_1cell_2017/m54086_170204_081430.subreads.bam.pbi
https://downloads.pacbcloud.com/public/dataset/RC0_1cell_2017/m54086_170204_081430.subreadset.xml

commands:
ccs m54086_170204_081430.subreads.bam m54086_170204_081430.ccs.bam --noPolish --minPasses 1 --maxPoaCoverage 10
lima m54086_170204_081430.ccs.bam primers.fasta m54086_170204_081430.fl.bam --isoseq --no-pbi --peek-guess
isoseq3 refine m54086_170204_081430.fl.primer_5p--primer_3p.bam primers.fasta m54086_170204_081430.flnc.bam --require-polya
isoseq3 cluster m54086_170204_081430.flnc.bam unpolished.bam --verbose
isoseq3 polish unpolished.bam m54086_170204_081430.subreadset.xml polished.bam --verbose

it went wrong when step five.
**Expected behavior**
finishing the polishing successfully.

**Comment by albodrug** [comment]
I have no issue with the example data, but the same ERROR "Could not find ZMWs for cluster transcript/" when using my data.

Here are the commands I used for the example data (basically a copy paste of the tutorial)
```
>ccs m54086_170204_081430.subreads.bam m54086_170204_081430.ccs.bam --noPolish --minPasses 1 --maxPoaCoverage 10
>lima m54086_170204_081430.ccs.bam primers.fasta m54086_170204_081430.fl.bam --isoseq --no-pbi --peek-guess
>isoseq3 refine m54086_170204_081430.fl.primer_5p--primer_3p.bam primers.fasta m54086_170204_081430.flnc.bam
>isoseq3 cluster m54086_170204_081430.flnc.bam unpolished.bam --verbose -j 28
>isoseq3 polish unpolished.bam m54086_170204_081430.subreadset.xml polished.bam --verbose
```

For my data the only different thing is the dataset create steps which threw no errors:
`>/software/anaconda/anaconda3-5_2_0/./envs/anaCogent5.2/bin/dataset create --type SubreadSet `merged.subreadset.xml *subreadset.xml
`>/software/anaconda/anaconda3-5_2_0/./envs/anaCogent5.2/bin/dataset create --type TranscriptSet `merged.flnc.xml *flnc.bam
The clustering went fine:
`>isoseq3 cluster merged.flnc.xml unpolished.bam --verbose -j 28`
Then the polishing threw the missing ZMWs error:
```
>isoseq3 polish unpolished.bam merged.subreadset.xml polished.bam
>|> 20190719 13:03:14.276 -|- ERROR      -|- operator() -|- 0x7f17f8926700|| -|- Could not find ZMWs for cluster transcript/5
>|> 20190719 13:03:14.284 -|- ERROR      -|- operator() -|- 0x7f17fb12a700|| -|- Could not find ZMWs for cluster transcript/1
>|> 20190719 13:03:14.293 -|- ERROR      -|- operator() -|- 0x7f17f0719700|| -|- Could not find ZMWs for cluster transcript/25
>|> 20190719 13:03:14.293 -|- ERROR      -|- operator() -|- 0x7f17ed514700|| -|- Could not find ZMWs for cluster transcript/9
etc
```

Would appreciate some help as well!

**Comment by albodrug** [comment]
I solved my own issue, this could maybe be helpful to you.

The reason I got the 

> ERROR Could not find ZMWs for cluster transcript/

 seems to be due to the xml file. Maybe double check that you downloaded it correctly? In my case, if the given xml for 

> merged.subreadset

 is generated from 

> *subreadset.xml

 files, isoseq3 polish throws the error however, if I generate the xml for 

> merged.subreadset 

from 

> subreadset.bam 

files, there is no error.

Hope this is somehow helpful!
Cheers

**Comment by pb-cdunn** [comment]
Yes, that could be helpful to other users. Thanks.

**Comment by tiramisutes** [comment]
Hi,
 I generate the xml for merged.subreadset from *subreadset.bam files.But, there is still error with `>|> 20190719 13:03:14.276 -|- ERROR      -|- operator() -|- 0x7f17f8926700|| -|- Could not find ZMWs for cluster transcript/5`.
The following is merged.subreadset.xml file that input into `isoseq3 polish`.
```
<?xml version="1.0" encoding="UTF-8"?>
<pbds:SubreadSet CreatedAt="2022-03-30T22:26:02" MetaType="PacBio.DataSet.SubreadSet" Name="pacbio_dataset_subreadset-220330_135959018" Tags="" TimeStampedName="pacbio_dataset_subreadset-220330_135959018" UniqueId="5b248bf3-b37d-87a1-8107-49f343e81ca4" Version="3.0.1" xmlns:pbbase="http://pacificbiosciences.com/PacBioBaseDataModel.xsd" xmlns:pbds="http://pacificbiosciences.com/PacBioDatasets.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pacificbiosciences.com/PacBioDataModel.xsd">
	<pbbase:ExternalResources>
		<pbbase:ExternalResource MetaType="PacBio.SubreadFile.SubreadBamFile" ResourceId="/data/DATA/RNA/PacBio/m64189e_210920_174554.subreads.0--0.bam" TimeStampedName="pacbio_subreadfile_subreadbamfile-220330_135959017" UniqueId="268c6d52-5dbb-4275-9a81-f7a16255bcc4">
			<pbbase:FileIndices>
				<pbbase:FileIndex MetaType="PacBio.Index.PacBioIndex" ResourceId="/data/DATA/RNA/PacBio/m64189e_210920_174554.subreads.0--0.bam.pbi" TimeStampedName="pacbio_index_pacbioindex-220330_135959016" UniqueId="ea1d334d-2d98-4642-ab48-b7c7085f5354"/>
				<pbbase:FileIndex MetaType="PacBio.Index.BamIndex" ResourceId="/data/DATA/RNA/PacBio/m64189e_210920_174554.subreads.0--0.bam.bai" TimeStampedName="pacbio_index_bamindex-220330_141502148" UniqueId="892ec822-1e97-4d04-84de-57254d24ede7"/>
			</pbbase:FileIndices>
		</pbbase:ExternalResource>
	</pbbase:ExternalResources>
	<pbds:DataSetMetadata>
		<pbds:TotalLength>52397266568</pbds:TotalLength>
		<pbds:NumRecords>30592588</pbds:NumRecords>
	</pbds:DataSetMetadata>
</pbds:SubreadSet>
```
