### ISSUE TITLE
Why do I get Missing. pbi file error in during polish?

### ISSUE THREAD

**Issue by smallfade** [PacificBiosciences/pbbioconda#167]
**Operating system**
Ubuntu 18.04

**Package name**
Isoseq 3.1.2
lima 1.9.0

**Conda environment**
specify each step with conda envs in snakefile

**Describe the bug**
After merge and clustering, the polishing step is asking .pbi file of the cells. Because the --no-pbi option is used, the output from lima contains no pbi file. And I don't do the refine step, it's asking for different 5p and 3p primers when I have the same  primer for both.

**Error message**
>|> 20190726 05:02:54.235 -|- FATAL      -|- Runner -|- 0x7f80cea64b80|| -|- Missing .pbi file for /mnt/disk1/XXXX/isoseq/output/lima/3_C01_1.demux.bam

**To Reproduce**
isoseq3 polish --verbose output/asc_unpolished.bam output/asc_merged.subreadset.xml output/asc_polished.bam &> logs/asc_polish.log

**Expected behavior**
I suppose it should ask for the unpolished.bam.pbi file which is existed.

**Comment by armintoepfer** [comment]
1) I don't fully understand your problem. Polish needs the pbi files for the original subreads.bam files. You can `conda install pbbam` and use `pbindex` on your subreads.bam files.
2) Why exactly don't you perform refine?

**Comment by smallfade** [comment]
>     1. I don't fully understand your problem. Polish needs the pbi files for the original subreads.bam files. You can `conda install pbbam` and use `pbindex` on your subreads.bam files.
> 
>     2. Why exactly don't you perform refine?
1. thanks for your input. I may try with the pbiindex.
2. Because refine is asking for the primer.fa to have multiple primers and requires no duplicates. But in my case, I have the same primer on both end without barcode.

**Comment by armintoepfer** [comment]
>Because refine is asking for the primer.fa to have multiple primers and requires no duplicates. But in my case, I have the same primer on both end without barcode.
How can you even run lima? It can't determine the transcript orientation. Given that you don't follow our library protocol, you are on your own.
