### ISSUE TITLE
[pb-assembly] raw reads stats

### ISSUE THREAD

**Issue by changhan1110** [PacificBiosciences/pbbioconda#169]
It is not error but I just wonder why raw_reads.db has different size of reads from the real one.

Below is my case,

my raw data size is about 87 Gb but when I build a raw_reads.db and check the stats, it shows the size of 79 Gb.

![image](https://user-images.githubusercontent.com/44763914/62266538-9d941380-b463-11e9-90a3-ca39cfae8b3b.png) 

Can you, please, help me to understand why?

Thanks,
Changhan

**Comment by pb-cdunn** [comment]
Sure. Look into your `0-rawreads/build/` directory. You can see the steps used to generate the Dazzler DB. Some subreads will be excluded, either via a flag or an earlier fasta filter. It is _possible_ to include all subreads, but the very short ones have zero value to assembly. (We generally use even the short ones for polishing much later.)

For more details on DazzDB, so this blog: https://dazzlerblog.wordpress.com/about/
