### ISSUE TITLE
bax2bam: libpbbam.so.0.18.0 is missing

### ISSUE THREAD

**Issue by GuyAllard** [PacificBiosciences/pbbioconda#17]
Running bax2bam fails with the following error:
bax2bam: error while loading shared libraries: libpbbam.so.0.18.0: cannot open shared object file: No such file or directory.

# To reproduce:
OS: Debian

Environment.yaml
```
channels:
  - bioconda
dependencies:
  - python=2.7
  - bax2bam=0.0.9
```

## Create environment:
`conda env create -n test -f environment.yaml`

## Activate environment
`source activate test`

## Run bax2bam
`bax2bam --version`
`>> bax2bam: error while loading shared libraries: libpbbam.so.0.18.0: cannot open shared object file: No such file or directory`

# Further info:
Looking in the environment/lib directory, the following are present:
`libpbbam.so` which is a symlink to `libpbbam.so.0.19.0`

So it appears that the supplied bax2bam binary was compiled against an older version of libpbbam than the version installed.

# Even further info:
Downgrading the pbbam package to 0.18.0 after installation of bax2bam allows bax2bam to be used
```
conda install -c bioconda pbbam=0.18.0
bax2bam --version
>>0.0.8
```
(note that bax2bam now reports being version 0.0.8 after downgrading pbbam)

**Comment by armintoepfer** [comment]
We are going to rebuild with the an explicit dependency on the latest pbbam version. 
David linked the PR, as you can see.
Once it's merged and uploaded to the conda cloud, please update your conda installation.
