### ISSUE TITLE
pbalign requires python 2.7 while pb-assembly uses 3.6

### ISSUE THREAD

**Issue by cguyomar** [PacificBiosciences/pbbioconda#170]
While running falcon unzip, I encountered this issue : 
`Exception: Call 'which pbalign' returned 256.`

It appears than pbalign does not work with Python 3.6, which is mandatory since pb-assembly 0.0.6 :
```
$ conda install -c bioconda pbalign
Fetching package metadata ...............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pbalign -> pbcommand >=1.1.1 -> python >=2.7,<2.8.0a0
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

A workaround is to stick with pb-assembly 0.0.5, but I'd like to use the last version.

**Comment by pb-cdunn** [comment]
Officially, **pbalign** is "deprecated". And `pb-assembly-0.0.5` is no longer supported.

Unofficially, you can get this working by using 2 separate Conda envs.

**Comment by pb-cdunn** [comment]
Oh, I might have misunderstood. I thought you were developing your own custom workflow. If you need **pbalign** from **falcon**, simply `conda update --all`. That ensures full consistency. We no longer run **pbalign** from **falcon**, so there is no problem for us.

**Comment by cguyomar** [comment]
My bad, I did not realize that falcon was not up to date in my environment.
Hopefully it should work now.
