### ISSUE TITLE
[pb-assembly] Sleeping jobs

### ISSUE THREAD

**Issue by changhan1110** [PacificBiosciences/pbbioconda#171]
Hi,

I'm running falcon to assemble human genome with about 90X depth of raw data. I set the dbblock size as 800 with -x500 -s800 parameter.

I wonder what's going on with many daligner sleeping jobs which is waiting for I/O operation I guess. Is it normal that many threads are used for just I/O?

TOP screen shot; I set the thread number to 16 but I haven't seen any running jobs with more than 1 thread.
![image](https://user-images.githubusercontent.com/44763914/62518743-2eecf680-b865-11e9-99b9-bc52c8807dc7.png)

HTOP screen shot; it shows many threads are used for I/O operation. If it is abnormal, how can I reduce this?
![image](https://user-images.githubusercontent.com/44763914/62518810-50e67900-b865-11e9-89f3-a9594fb237ae.png)

Thanks,
Changhan

**Comment by pb-cdunn** [comment]
I don't see the sleeping jobs. I see many daligner jobs using multiple threads. (16 would be ideal, but as work is finished that will drop.) I see 1 with 100% (probably a single-threaded section of code), using 74GB, so it's probably reading the DB.

I/O contention can certainly be a problem. Your procs don't seem to be I/O limited here, but it's something to watch for. If your machine is actually swapping -- which I would usually detect by noticing CPU usage near 0% for some jobs, but maybe there are other ways it could manifest -- you will need to reduce the number of concurrent procs. See "njobs" in pypeflow. (The pypeflow wiki might explain that better.)

On a machine with this many processors, you could benefit from a hidden flag to store the DB in `/dev/shm`. However, increasing `-T` is simpler.
