### ISSUE TITLE
How to manage memory with blasr ?

### ISSUE THREAD

**Issue by scauet** [PacificBiosciences/pbbioconda#173]
Hi,
I'm trying to align subreads (5 .bam files from PacBio Sequel) to a draft genome assembly (400Mo) in order to polish my assembly with arrow. I use blasr from pbbioconda.
`blasr --bam --hitPolicy randombest --nproc 4 --maxAnchorsPerPosition 1000 --minMatch 12 --bestn 10 --minPctAccuracy 75 --minPctSimilarity 75 --minSubreadLength 500 --out raw_vs_draft.bam subreads.fofn my_draft_genome.fasta`

I always obtain an out of memory error, even with 128Go of RAM.

Is there a way to limit the memory use by blasr or to manage the memory differently ?

Thank you in advance for your help.
Stephane

**Comment by armintoepfer** [comment]
Here is the trick, you use `pbmm2`. Blasr is end of life and had been fully replaced in all workflows.

**Comment by scauet** [comment]
OK, I will try it, thanks for the quick answer.
