### ISSUE TITLE
Wrong read mode for gzipped files in Unzip

### ISSUE THREAD

**Issue by cguyomar** [PacificBiosciences/pbbioconda#176]
related to  #175 

I observed that the problem did not occurred  while reading the contigs file (in .fa format), but did for the first readset (in fa.gz).

Based on : https://docs.python.org/3/library/gzip.html , gzip.open requires different modes for non binary files.
Replacing mode="r" by "rt" for .gz files in 'open_fasta_reader' apparently fixed the issue.
```
    if filename.endswith(".gz"):
        mode='rt'
        ofs = gzip.open(filename, mode)
```

This probably should be fixed.

**Comment by pb-cdunn** [comment]
I believe you, but I don't understand the Python docs on this.

* https://docs.python.org/3/library/gzip.html
* https://docs.python.org/2/library/gzip.html

> If not given, the ‘b’ flag will be added to the mode to ensure the file is opened in binary mode for cross-platform portability.

That's for py2 gzip, but not for py3 gzip. "binary-mode" in py2 produces `str` from `read()`, while `r` mode in py3 produces `bytes`. So you're right, but I don't understand how. The py3 gzip docs allow `r`, `rt`, and `rb`. `rt` used `io.TextIOWrapper`, but what does `r` use? Not clear to me. In py3, standard [`open()`](https://docs.python.org/3/library/functions.html#open) says

> The default mode is 'r' (open for reading text, synonym of 'rt').

I can see from a simple test that you're correct, but *why* are you correct? Why is `gzip.open(mode='r')` not equivalent to `rt`?
