### ISSUE TITLE
Error in Description of fc_run.cfg - configuration section of pb-assembly page

### ISSUE THREAD

**Issue by pwmcclurg** [PacificBiosciences/pbbioconda#178]
After successfully running the pipeline with arrow about eight months ago I am happy to see all the excellent engineering changes - with all these changes I mistakenly included a suggested line

pa_DBdust_option=true

and am hoping you might change this to 

pa_DBdust_option=

so that other users don't include it.  Overall outstanding work!

**Operating system**
Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Package name**
pb-assembly configuration section:

https://github.com/PacificBiosciences/pb-assembly

**Conda environment**

(partial list)
pb-assembly               0.0.5                    py27_2    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 0.2.7            py27hc0aa232_1    bioconda
pbalign                   0.3.2                    py27_0    bioconda
pbbam                     0.23.0               h88345a9_0    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  0.4.2                h3f2a3d2_1    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pbgcpp                    0.0.1                         0    bioconda
pbmm2                     1.0.0                ha888412_0    bioconda

**Describe the bug**
In the reccomended lines for fc_run.cfg there is

pa_DBdust_option=true

**Error message**

Including this line will set the opitions of DBdust to "true" and the run will fail at that point

**To Reproduce**
Any run will fail with this line included

**Expected behavior**
run failure

**Comment by pwmcclurg** [comment]
I think if you use any legal option for this it is fine - but "true" is not one of them - this is more for the greedy snippet snatcher like me who didn't catch this - I actually debugged this down to the tmp directory where the corresponding job threw an error because of this.  By the way - this pipeline is such an amazing improvement over the state of affairs in 2013 when I first started using it.  Thank you for all the detailed improvements.

**Comment by skingan** [comment]
I updated our cfg files to the suggested parameter setting: "pa_DBdust_option=". It also does not appear with the "true" option in the README: https://github.com/PacificBiosciences/pb-assembly/blob/master/README.md. Is there somewhere else that you're seeing this suggestion @pwmcclurg ?
