### ISSUE TITLE
Error to assembly CCS reads with pb falcon

### ISSUE THREAD

**Issue by scauet** [PacificBiosciences/pbbioconda#181]
Hi,
I try to assemble PacBio CCS corrected reads with falcon (I use fc_run from pbbioconda directly at pread step), but I get this error message :
`File R124_CCS_subreads_demux.lbc66--lbc66.fasta.fasta, Line 1: Pacbio header line format error`
My headers look like this : 
`>m54032_190308_123430/4194521/ccs`
Do I have to change all the headers of my fasta file or is there a way to directly use these files in falcon?
Thanks for your help,
Stéphane

**Comment by pb-cdunn** [comment]
We'll have a newish CCS-based workflow available "soonish". Until then, we don't recommend using CCS reads at all. But if you want to try it, you'll need to modify the `/ccs` characters of the read-names yourself somehow.
