### ISSUE TITLE
raw_reads cutoff and preads stats

### ISSUE THREAD

**Issue by changhan1110** [PacificBiosciences/pbbioconda#182]
I set the cutoff as 10,000 bp for error correction steps, but the preads stats shows that there are still many reads whose length is less than 10,000 bp.

<preads.stats after 10K raw read length cutoff>
![image](https://user-images.githubusercontent.com/44763914/64091459-2a93fa80-cd8b-11e9-8d93-6468fa2ecf18.png)

Is this possible and natural?

**Comment by pb-cdunn** [comment]
That's fine. You won't have anything `< 10000` in `preads4falcon.fasta`. (See run-script in `2-asm-falcon/` directory.) Also, all the A-reads in the A/B overlaps in `1-preads_ovl/` will be longer than that. And you should see `10000` in the file `1-preads_ovl/length_cutoff`.
