### ISSUE TITLE
Racon fails with an Illegal instruction error

### ISSUE THREAD

**Issue by EdHarry** [PacificBiosciences/pbbioconda#186]
Not an error with Falcon directly, but the current bundled version of Racon (v1.4.3) fails with an Illegal instruction error, exclusevly on AMD cpus it seems (from my experience)
https://github.com/lbcb-sci/racon/issues/3

**Comment by isovic** [comment]
Hi Ed,
I think this is likely because the Racon Bioconda recipe was compiled with `march=native`, which can cause this issue on heterogeneous clusters.
We'll try to address this soon.
Thank you for reporting this!
Ivan
