### ISSUE TITLE
pbccs4.0.0 Error when input bax2bam results.

### ISSUE THREAD

**Issue by sssxie** [PacificBiosciences/pbbioconda#193]
ccs --version
ccs 4.0.0 (commit v4.0.0)

ccs bax2bam.subreads.bam ccs.bam
>|> 20190917 01:56:17.433 -|- FATAL -|- ValidateChemistries -|- 0xfc5940|| -|- unsupported sequencing chemistry combination:
    binding kit:        100356300
    sequencing kit:     100356200
    basecaller version: 2.3.0.0.140640

But I tried ccs 3.4.1 (commit c1a7cc8) without this error.

**Comment by armintoepfer** [comment]
This is known and on purpose.

https://github.com/PacificBiosciences/ccs/blob/develop/README.md#help-i-am-getting-unsupported-

>Old chemistries: With ccs 4.0.0, we have removed support for the last RSII chemistry P6-C4. The only option is to downgrade ccs with conda install pbccs==3.4.
