### ISSUE TITLE
Can GenomicConsensus (Arrow/Quiver) be used with CCS reads (instead of subreads)

### ISSUE THREAD

**Issue by maxgmarin** [PacificBiosciences/pbbioconda#195]
I have a PacBIo bioinformatics question.

We are analyzing our PacBio data generated from a bacterial genome.
I specifically have a question regarding the use of GenomicConsensus for variant calling using CCS reads.

Previously, I have been aligning the subreads ("subreads.bam") to our assembly/reference genome (W/ pbmm2) and running GenomicConsensus for variant calling. This is using the GenomicConsensus package (https://github.com/PacificBiosciences/GenomicConsensus)

I have now run CCS (https://github.com/PacificBiosciences/ccs) to generate CCS reads ("ccs.bam") and want to know if GenomicConsensus will work accurately using CCS reads instead of subreads.

I can't find indication on the GenomicConsensus GitHub page that it will work with CCS reads instead of subreads.

Also, I noticed the existence of gcpp: https://github.com/PacificBiosciences/gcpp.

Should I be using gcpp instead? What if some of the data I am working with is from P6-C4 chemistry? 

Thank you!
- Max

**Comment by maxgmarin** [comment]
Also, in the README description of gcpp it says the "Command-line parameters are the same as for GenomicConsensus, with the exception of not supporting Quiver/RSII anymore." What exactly is meant by not supporting RSII anymore? Does this mean the Sequel II System?

Thank you,
Max

**Comment by dbrowneup** [comment]
Hi Max, this issue tracker is intended for our software developers, but you can email support@pacb.com with your query and we will get back to you with the right answers!

**Comment by pb-dseifert** [comment]
Arrow is not idempotent, it is used to produce CCS reads, but cannot then be used to polish genomes using CCS reads. You can try the POA/Plurality modes of GCpp to polish genomes using CCS reads, but this is not officially supported. For polishing genomes using CCS reads, have you tried something like [Racon](https://github.com/isovic/racon)? GCpp will only polishes genomes using aligned subreads, and that will not change.

P6-C4 is an RSII chemistry, and as such is not supported by `GCpp` anymore. `GenomicConsensus` is EOL. It should still work, but will not receive any more updates or fixes.

Even using the old `GenomicConsensus` package, mixed polishing (that is, combining subreads from RSII and Sequel) was never supported and will not work. Mixing Sequel and Sequel II datasets should work but is not officially supported either.
