### ISSUE TITLE
disable repeat masking Falcon assembly 

### ISSUE THREAD

**Issue by HenrivdGeest** [PacificBiosciences/pbbioconda#197]
From the falcon cfg files it is possible to set the parameters for repeat masking:
```
#### Repeat Masking
pa_HPCTANmask_option=
#no-op repmask param set
pa_REPmask_code=0,300;0,300;0,300

```
Form the documentation its not clear to me how to disable this procedure as a whole, or to make it such insensitive that it practically doesn't do anything.

**Comment by pb-cdunn** [comment]
What you have should make REPmask a no-op. It will still distribute a few jobs, but only very quick no-op jobs and nothing in parallel.

For TANmask, see https://dazzlerblog.wordpress.com/command-guides/damasker-commands/
