### ISSUE TITLE
how *.report convert to *.bc1--bc1.bam in Lima1.9.0

### ISSUE THREAD

**Issue by orangeSi** [PacificBiosciences/pbbioconda#201]
**Operating system**
Which operating system and version are you using?

```
CentOS release 6.9 (Final)
```

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?
```
 Lima1.9.0 
```
**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**

When I run  this:
```
lima --ccs ccs.bam barcode.fa out.bam --split-bam-named
```
will  get 
```
out.lima.report
out1.bc1--bc1.bam
out1.bc2--bc2.bam
...
```
I want to know whether ```out1.bc1--bc1.bam``` is generated by ```out.lima.report```. And if it is, ```out.lima.report``` how to generate  ```out1.bc1--bc1.bam```.
**Error message**
Paste the error message / stack.

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!
Thanks~
**Expected behavior**
Thanks~

**Comment by armintoepfer** [comment]
I don't understand, please elaborate. Those files are produced by `lima`. If you want to know more about the `.report` file: https://github.com/pacificbiosciences/barcoding#report

**Comment by orangeSi** [comment]
sorry, when I run ```lima --ccs ccs.bam barcode.fa out.bam --split-bam-named``` I will got ```out1.bc1--bc1.bam```, so ``` out1.bc1--bc1.bam``` is the whole ccs only for barcode ```bc1```, I am right? 
but if I run ```lima --ccs ccs.bam barcode.fa out.bam ``` without ``` --split-bam-named```, I will got 
```
out.bam 
out.lima.report
out.lima.summary
 ````
so if without ```--split-bam-named ```, <b>I don't know  every ccs is belong to which barcode, this is my major question</b>. So I tried to understand the *.report to figure out this question, but I don't understand the every columns of ```*report```.

thanks~

**Comment by armintoepfer** [comment]
Have a look at: https://github.com/pacificbiosciences/barcoding#features
> Clip barcode sequences and annotate bq and bc tags

You have to use samtools and look at the bc SAM tag. But as you said, if you use splitting, this step is done for you.

**Comment by orangeSi** [comment]
ok， I find ```bc:B:S,57,57```  in my ```prefix.bc58--bc58.bam```, so the two 57 mean what? 57 is the index number of bc58? why have two 57?

**Comment by orangeSi** [comment]
> Have a look at: https://github.com/pacificbiosciences/barcoding#features
> 
> > Clip barcode sequences and annotate bq and bc tags
> 
> You have to use samtools and look at the bc SAM tag. But as you said, if you use splitting, this step is done for you.

ok, I find that, thanks~
