### ISSUE TITLE
output of lima did not remove Forward and Reverse barcode  both

### ISSUE THREAD

**Issue by orangeSi** [PacificBiosciences/pbbioconda#203]
**Operating system**
Which operating system and version are you using?
```CentOS release 6.9 (Final)```
**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?
```lima 1.9.0 (commit 6207954) from smrtlink7.0```
**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**
```
when input of lima is ccs.bam, 
output of lima did not remove Forward and Reverse barcode  both
```
**Error message**
Paste the error message / stack.

``` output of lima only remove the Forward bacode, but Reverse barcode not```
**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

``` I upload a demo data, it contain one zmw ccs bam```
[one_zmw_data.zip](https://github.com/PacificBiosciences/pbbioconda/files/3660689/one_zmw_data.zip)
the commad is ``` lima --ccs bc4.zmw.21168990.bam 96.barcode.fa out.bam -j 3```

**Expected behavior**

the output of lima ``` out.bam```  have no Foward barcode, but still have Reverse barcode

**Comment by armintoepfer** [comment]
If you have problems with software from SMRT Link, please contact the official PacBio support. Please refrain from reporting issues that you cannot reproduce with bioconda, because this is a issue tracker for software distributed via bioconda.

That said, latest `lima` version in bioconda works out of the box, with barcode score 100:
```
IN : TGTGTATCAGTACATGAGAGTTTGAT...GTAACAAGGTAGCCTGTGTATCAGTACATGATCTCTCTCTTTTTTTT
OUT:                 AGAGTTTGAT...GTAACAAGGTAGCC
```

**Comment by orangeSi** [comment]
ok， thanks ~
