### ISSUE TITLE
Can Falcon-Phase use multiple Hi-C libraries?

### ISSUE THREAD

**Issue by changhan1110** [PacificBiosciences/pbbioconda#205]
I have two kind of Hi-C data, one of which is made by MboI, the other is made by two enzymes (DpnII and HinfI).

Can falcon-phase use both kind of data at the same time? If not, is there any possible way to use both kinds of data?

Thanks,
Changhan

**Comment by zeeev** [comment]
Hi @changhan1110,

As of now, the code is not setup for multiple library normalization. You can merge all the data and specify multiple enzymes, but we have not studied how that affects the results. 

Best,

Zev
