### ISSUE TITLE
How to change default for "pypeflow_mb": 4000?

### ISSUE THREAD

**Issue by tomoakin** [PacificBiosciences/pbbioconda#206]
On restrictive clusters where use of memory more than requested results in the process to fail. The default value of 4000 seems to be used at many places where not so memory hungry process, without clear way to change the default. This value seems to be too small and the configuration to change this value was not found. 

for example
0-rawreads/build/task.json
0-rawreads/tan-split/task.json
0-rawreads/tan-chunks/tan_000/task.json
do contain the parameter "pypeflow_mb": 4000
specification. Currently tan-chunks jobs dies presumably using more memory than requested. I saw build process fail with multiple fasta inputs, which somehow went away by combining the fasta file to one file before assembly.

**Comment by lparsons** [comment]
I'm running into this problem as well, on the very first `0-rawreads/build` step.

**Comment by pb-cdunn** [comment]
Try
```ini
[General]
MB = 8000
```
And you would need to use `$MB` in your job-distribution `submit` string.

* https://github.com/PacificBiosciences/pypeFLOW/wiki/configuration
