### ISSUE TITLE
Problem with pbmm2 align crashing during 3-unzip/0-phasing step during instances proto/preads.fasta file is empty where 

### ISSUE THREAD

**Issue by chad388** [PacificBiosciences/pbbioconda#208]
**Operating system**
Which operating system and version are you using?
Debian GNU/Linux 9 (stretch)

**Package name**
Which package / tool is causing the problem? 

Which version are you using, use `tool --version`?
pbmm2-1.0.0-ha888412_0

 Have you updated to the latest version `conda update package`?
Yes

 Have you updated the complete env by running `conda update --all`? 
Yes

Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?

**Conda environment**
What is the result of `conda list`? 
``` Name Version Build Channel
 _libgcc_mutex 0.1 main 
 asn1crypto 0.24.0 py37_0 
 bzip2 1.0.8 h7b6447c_0 
 ca-certificates 2019.5.15 0 
 certifi 2019.6.16 py37_0 
 cffi 1.12.3 py37h2e261b9_0 
 chardet 3.0.4 py37_1 
 conda 4.7.10 py37_0 
 conda-package-handling 1.3.11 py37_0 
 cryptography 2.7 py37h1ba5d50_0 
 idna 2.8 py37_0 
 libarchive 3.3.3 h5d8350f_5 
 libedit 3.1.20181209 hc058e9b_0 
 libffi 3.2.1 hd88cf55_4 
 libgcc-ng 9.1.0 hdf63c60_0 
 libstdcxx-ng 9.1.0 hdf63c60_0 
 libxml2 2.9.9 hea5a465_1 
 lz4-c 1.8.1.2 h14c3975_0 
 lzo 2.10 h49e0be7_2 
 ncurses 6.1 he6710b0_1 
 openssl 1.1.1c h7b6447c_1 
 pip 19.1.1 py37_0 
 pycosat 0.6.3 py37h14c3975_0 
 pycparser 2.19 py37_0 
 pyopenssl 19.0.0 py37_0 
 pysocks 1.7.0 py37_0 
 python 3.7.3 h0371630_0 
 python-libarchive-c 2.8 py37_11 
 readline 7.0 h7b6447c_5 
 requests 2.22.0 py37_0 
 ruamel_yaml 0.15.46 py37h14c3975_0 
 setuptools 41.0.1 py37_0 
 six 1.12.0 py37_0 
 sqlite 3.29.0 h7b6447c_0 
 tk 8.6.8 hbc83047_0 
 tqdm 4.32.1 py_0 
 urllib3 1.24.2 py37_0 
 wheel 0.33.4 py37_0 
 xz 5.2.4 h14c3975_4 
 yaml 0.1.7 had09818_2 
 zlib 1.2.11 h7b6447c_3 
 zstd 1.3.7 h0b5b093_0
```

**Describe the bug**
This is during the 3-unzip/0-phasing step when running on a CCS based Falcon assembly using "fc_unzip.py --target=ccs"

In instances where this grep step below results in no CCS reads being found for a particular primary contig, I then encounter an error during the "time pbmm2 align" step. I indicated that specific error below, but it appears to be due to the preads.fasta file being empty. Based upon this code below, where the grep step returns true even if reads are not found matching a primary contig, it seems like you are able to have instances where the preads.fasta will be empty. 

 #grabs the names of all the CCS reads that associate with this primary contig.
        (
        set -vx +e
        grep -w 001459F ../../../mapping/rid_to_cgt.txt >| rid_to_ctg.txt
        true
        )
+ set -vx +e
+ grep -w 001459F ../../../mapping/rid_to_cgt.txt
+ true

**Error message**
time pbmm2 align --preset CCS --sort -j 1 proto/ref.fasta proto/preads.fasta | samtools view  > proto/preads.sam
+ pbmm2 align --preset CCS --sort -j 1 proto/ref.fasta proto/preads.fasta
+ samtools view
>|> 20190926 23:02:53.668 -|- FATAL      -|- DetermineInputTypeFastx -|- 0x7efc40fefb80|| -|- Unkown file type for file proto/preads.fasta starting with character  

**To Reproduce**

**Expected behavior**
If it is acceptable for there to be instances where no CCS reads are associated with a given primary contig and if it is then acceptable for there to be instances of preads.fasta files that are empty, how do we avoid this below? Can we skip running pbmm2 align when the preads.fasta file is empty and just put a run.sh.done file in the /3-unzip/0-phasing/******/uow-fake directory or will this cause further issues downstream?

  time pbmm2 align --preset CCS --sort -j 1 proto/ref.fasta proto/preads.fasta | samtools view  > proto/preads.sam
+ pbmm2 align --preset CCS --sort -j 1 proto/ref.fasta proto/preads.fasta
+ samtools view
>|> 20190926 22:38:24.195 -|- FATAL      -|- DetermineInputTypeFastx -|- 0x7f628d7dcb80|| -|- Unkown file type for file proto/preads.fasta starting with character

**Comment by zeeev** [comment]
Hi @chad388,

Thank you for posting this valid bug report. Pbmm2 _now_ accepts empty input without throwing this error. The update was fairly recent and it might not be in BioConda yet. I'll check-in with my group in the morning and get back to your soon.

Best,

Zev

**Comment by armintoepfer** [comment]
Please update your pbmm2 in bioconda. Latest version is 1.1.0. Why isn't there any PacBio software in your conda list?
