### ISSUE TITLE
get_asm_stats.py errors

### ISSUE THREAD

**Issue by michaeljmetzger** [PacificBiosciences/pbbioconda#209]
The site suggests using pb-assembly/scripts/get_asm_stats.py for getting stats on multiple steps. I have installed via conda and FALCON and FALCON-unzip are working well, but this command does not run (no such file or directory). Since this doesn't seem to direct to anything installed as a part of the conda package, I generated the script based on the git link. However, when I run it I get multiple errors. 

First error:

  File "scripts/get_asm_stats.py", line 83
    print "Please specify a fasta or a 2-asm-falcon dir!"
                                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Please specify a fasta or a 2-asm-falcon dir!")?

This can be fixed by adding parentheses, but then I get the next error:

  File "scripts/get_asm_stats.py", line 100
    print json.dumps(fasta_stats, indent=1, sort_keys=True)
             ^
SyntaxError: invalid syntax

I don't know what to do here.
Is there a new version of this script or do you have any advice for fixing these errors?

Thanks,
Michael

**Comment by natechols** [comment]
You need to use Python 2.7.

**Comment by michaeljmetzger** [comment]
Ah, thanks. Now running with python 2.7 I now get a different error:

Traceback (most recent call last):
  File "scripts/get_asm_stats.py", line 11, in <module>
    from pbcore.io import FastaReader
ImportError: No module named pbcore.io

**Comment by natechols** [comment]
Sorry, are you running with the system python, or one that came with bioconda?  pbcore is included in pbbioconda so this should work as long as you use the correct python interpreter.

**Comment by michaeljmetzger** [comment]
Ok, this might be making a bit more sense. 

I am running the command in an active bioconda environment. "Python" calls the version which came with bioconda, which is python3.7. I can use "Python2" but it looks like this calls the system bioconda. So I either have the wrong version in bioconda or the right version not in bioconda. Is there a 2.7 within bioconda that I can call? Do you know its name?

**Comment by michaeljmetzger** [comment]
It looks like our miniconda was installed with python3.7 instead of 2.7. I may have to uninstall the whole thing and reinstall miniconda with python 2, then reinstall pb-assembly. Thank you for your help in figuring this out.

Also, I have installed pb-assembly, but I don't think anything else was installed, so I do not think I have pbcore unless it gets installed along with pb-assembly. So that may be another issue.

**Comment by michaeljmetzger** [comment]
Installing a new conda env with python2.7 works! Thanks for your help.

Oddly, it looks like FALCON assembly completed with python3.7. Do you happen to know if FALCON assembly is compatible with python3.7 or would you recommend I rerun this? It can be done--it just takes a few weeks, so if there is any chance of an error in assembly due to python version I should probably redo it.

**Comment by michaeljmetzger** [comment]
Just to make this a bit more confusing, I see documentation saying that Python2.7 is required and pb-assembly is incompatible with 3.7 (https://github.com/PacificBiosciences/pbbioconda#availability) and other documentation saying exactly the opposite (https://github.com/PacificBiosciences/pbbioconda/wiki/Release-notes#pb-assembly-006). 

My best guess is that most of pb-assembly-0.0.6 has been upgraded to python3.7 (including FALCON assembly and FALCON-Unzip), but that they lost track of a few scripts (like get_asm_stats.py) which can't be run through the pb-assembly-0.0.6, but have to be run through a different env with python2.7. 

Can anyone tell me if that sounds right? If so, maybe someone could fix the documentation to clarify the split python2.7-3.7 requirements for different components. Regardless, the statement on the pbbioconda page "Python packages require version 2.7; Python 3 is currently not supported!" is wrong and could be fixed. 

Unless there are some bug fixes in pb-assembly-0.0.6 then it might be easiest for people to stick with pb-assembly-0.0.5 until it really is fully python3-compatible.

**Comment by pb-dseifert** [comment]
I agree, the situation is rather unfortunate at the moment. PacBio assembly is Py3-only nowadays, whereas most other PacBio python packages are Py2-only (`pbcoretools` etc). We are in the process of moving towards Py3 for all tools, but will not give ETAs for when this will be ready.

**Comment by pb-cdunn** [comment]
In the meantime, for similar information in a py3 environment, you can try

    falconc stats-assembly -h
