### ISSUE TITLE
bax2bam: small test dataset

### ISSUE THREAD

**Issue by stephanflemming** [PacificBiosciences/pbbioconda#215]
This is not a bug report.

Following a user request I am working on a galaxy wrapper for bax2bam. Therefore I need a small test data set consisting of three bax.h5 files with a size of a few MB. Any idea where I can get  that? Thank you

**Comment by ylipacbio** [comment]
https://github.com/PacificBiosciences/PacBioTestData/tree/master/data/HdfSubreadSet/Analysis_Results/

**Comment by stephanflemming** [comment]
Is there a working data set for output read type --ccs available too? The one mentioned above fails with 

`ERROR, Could not initialize ccs file m140912_020930_00114_c100702482550000001823141103261590_s1_p0.1.bax.h5`

**Comment by natechols** [comment]
You can still find a ccs.h5 in the pbcore library (for now):
https://github.com/PacificBiosciences/pbcore/blob/master/pbcore/data/m130727_114215_42211_c100569412550000001823090301191423_s1_p0.1.ccs.h5

**Comment by natechols** [comment]
`--ccs` just tells the program "the input .h5 contains CCS reads and you should write out a CCS BAM".  It doesn't do any additional processing, so it's only appropriate when using a ccs.h5 file, not bax.h5.
