### ISSUE TITLE
lima run with only One barcode

### ISSUE THREAD

**Issue by bitcometz** [PacificBiosciences/pbbioconda#216]
hello,
I try to run lima with only one barcode:
>bc1000
CTCTACTTACTTACTG

and then I add another two barcodes:
>bc1000
CTCTACTTACTTACTG
>bc1001
GTCGTATCATCATGTA
>bc1002
AATATACCTATCATTA

I found the two results for 'bc1000' is different, the first one is about 6.7G, and the second one is 6.8G. How can I reduce the difference？

Thanks

**Comment by armintoepfer** [comment]
Increase the minimum score required to call a barcode. It's set to 0 by default.
