### ISSUE TITLE
pbmm2 option to get M in CIGAR string

### ISSUE THREAD

**Issue by laurenfitch** [PacificBiosciences/pbbioconda#217]
pbmm2 uses the minimap2 option `--eqx` by default to change M in the CIGAR string to =/X. Is there an option to shut off this behavior and get Ms in the CIGAR string?

**Comment by armintoepfer** [comment]
No. `sed` the SAM. But why doesn't your tool support proper cigar parsing?

**Comment by WellJoea** [comment]
> No. `sed` the SAM. But why doesn't your tool support proper cigar parsing?
I agree with you
