### ISSUE TITLE
segfault from malloc in ccs 4

### ISSUE THREAD

**Issue by conchoecia** [PacificBiosciences/pbbioconda#218]
- Ubuntu 16.04
- ccs 4.0 installed from https://www.pacb.com/support/software-downloads/  smrtlink v8.0.0.80529
- no conda install - just a problem with malloc used in ccs

The bug: I ran ccs v4.0 with a 500Gb Iso-Seq dataset on 96 threads on a 96-thread, 1TB RAM machine. Over 400GB of RAM were free while the program was running.

**Error message**
```
ccs: malloc.c:2927: __libc_malloc: Assertion `!victim || chunk_is_mmapped (mem2chunk (victim)) || ar_ptr == arena_for_chunk (mem2chunk (victim))' failed.
ccs_DS259.sh: line 20: 86371 Segmentation fault      (core dumped) ${CCS_PATH} -j ${THREADS} --report-file final_fastq/${PREFIX}_${COUNTER}_ccs_report.txt --log-file final_fastq/
```

**To Reproduce**
The command was pretty simple:

```
${CCS_PATH} -j ${THREADS} --report-file final_fastq/${PREFIX}_${COUNTER}_ccs_report.txt \
    --log-file final_fastq/ccs.log \
    --log-level INFO \
    path/to/subreads.bam final_fastq/${PREFIX}_ccs_file${counter}.fastq
```

**Comment by conchoecia** [comment]
Update - I ran it again and renamed the output files as `.fastq.gz`, since it appears that this is the allowed file type output. Now, the `ccs` program has completed and I have a directory of fastq.bam files, but the program and its child processes are still running, but at 0.0% CPU. 

I discovered that the `ccs` program is actually just a shell script. The way that it is implemented now, I think that the program might not correctly find the paths to the other programs necessary to finish the script. For example, I used `echo` to look at these variables:

```
# Force the path to only what we need, saving off the original path
PATH_ORIG=$PATH;
PATH=/usr/bin:/bin
g_prog=$(basename "$0");
g_progdir=$(dirname "$0");
g_progdir_abs=$(dirname "$(readlink -f "$0")");
echo ${g_prog}
echo ${g_progdir}
echo ${g_progdir_abs}
```

... and I found that one of the variables was now pointing to a path that didn't exist:

```
/usr/local/bin/smrtcmds
/usr/local/bin/smrtlink/install/smrtlink-release_8.0.0.80529/bundles/smrttools/install/smrttools-release_8.0.0.80502/smrtcmds/bin
/usr/local/bin/smrtcmds/ccs_test: line 49: /usr/local/bin/smrtlink/install/smrtlink-release_8.0.0.80529/bundles/smrttools/install/smrttools-release_8.0.0.80502/smrtcmds/bin/../../../../private/runtime-common/lib/globalenv.ish: No such file or directory
```

This error was from the line `g_exe="${g_progdir_abs}/../../../../private/pacbio/unanimity/bin/ccs";`. I looked up this path and it actually did not exist. I traced what the correct path should be starting from `g_progdir_abs` and found that there should only be two `../`s in the path to get to the correct files, like so:

```
g_exe="${g_progdir_abs}/../../private/pacbio/unanimity/bin/ccs";

g_ldlibpath=""
g_ldlibpath="$g_ldlibpath:${g_progdir_abs}/../../private/pacbio/unanimity/lib";
g_ldlibpath="$g_ldlibpath:${g_progdir_abs}/../../private/thirdparty/gcc/gcc_8.3.0-2.12.1/lib";
g_ldlibpath="$g_ldlibpath:${g_progdir_abs}/../../private/pacbio/pbcopper/lib";
g_ldlibpath="$g_ldlibpath:${g_progdir_abs}/../../private/thirdparty/zlib/zlib_1.2.11/lib";
g_ldlibpath="$g_ldlibpath:${g_progdir_abs}/../../private/thirdparty/htslib/htslib_1.9/lib";
g_ldlibpath="$g_ldlibpath:${g_progdir_abs}/../../private/pacbio/pbbam/lib";
g_ldlibpath="$g_ldlibpath:${g_progdir_abs}/../../private/pacbio/dagger/lib";
g_ldlibpath="$g_ldlibpath:${g_progdir_abs}/../../private/pacbio/pbmm2/lib";
g_ldlibpath="$g_ldlibpath:${g_progdir_abs}/../../private/thirdparty/minimap2/minimap2_2.15-pacbio1/lib";
g_ldlibpath=${g_ldlibpath#:}
echo ${g_ldlibpath}
```

I could be totally wrong though, given that the program produced `bam` files as output!

**Comment by armintoepfer** [comment]
As you are running smrt tools, please contact PacBio's tech support. They will be able to assist you!
