### ISSUE TITLE
No space left on device,how to continue to run

### ISSUE THREAD

**Issue by wuxiaopei0509** [PacificBiosciences/pbbioconda#220]
when I run the unzip statge using the pb-assembly software set ,it stopped during the quiver process,what should I do the continue the pipeline?
Thank you !

**Comment by pb-cdunn** [comment]
Title is same as #219. In neither did you answer the questions we require, though in #219 for no apparent reason you reposted the questions themselves, without answers.

Your title indicates that you ran out of disk-space. That's not something we could help you with anyway.
