### ISSUE TITLE
ccs FATAL: kernel too old Aborted (core dumped)

### ISSUE THREAD

**Issue by MOgene403** [PacificBiosciences/pbbioconda#221]
CCS from bioconda downloaded 10/21/2019 fails with CentOS 6.7 (final).
Apparently a similar issue was also found with SMRT Link 8 (library dependency) and fixed

**Comment by armintoepfer** [comment]
Please read our docs before posting an issue https://github.com/PacificBiosciences/ccs/blob/develop/README.md#the-binary-does-not-work-on-my-linux-system
