### ISSUE TITLE
terminally sleeping gcpp process

### ISSUE THREAD

**Issue by michaeljmetzger** [PacificBiosciences/pbbioconda#225]
I am using FALCON-unzip on a unix server using the latest conda environment with python3. I have hit a stall in the 4-polish step. The server went through three weeks of gcpp process in the quiver stage, then all finished except one which was asleep for some reason. There was one python3 process open that seemed to just be checking occasionally on the sleeping process:

python3 -m falcon_kit.mains.generic_run_units_of_work --nproc=4 --units-of-work-fn=../../quiver-chunks/000172F_009/some-units-of-work.json --bash-template-fn=../../quiver-split/bash-template.sh --results-fn+results.json

The sleeping (S) process was:
gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000172F_009/ref.fa aln-000172F_009.bam -o cns.fasta,cns.fastq,cns.vcf

When I looked at the log file I just see a ton of repeats of this:

2019-10-31 16:43:44,022 - pypeflow.simple_pwatcher_bridge:325 - DEBUG - N in queue: 1 (max_jobs=10)
2019-10-31 16:43:44,022 - pwatcher.blocking:462 - DEBUG - query(which='list', jobids=<1>)

I am showing the last repeat here, but I have done a tail command looking at the last 20,000 lines and it is all repeats of this about 6 times per second.

When I look in the stderr of quiver-run/refs/000172F, I see 

set +e

    set +e
    gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j $nproc -r ../../../quiver-split/refs/000172F_009/ref.fa aln-000172F_009.bam -o ${fasta_fn},${fastq_fn},cns.vcf
    gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000172F_009/ref.fa aln-000172F_009.bam -o cns.fasta,cns.fastq,cns.vcf

    |> 20191015 03:38:54.834 -|- INFO -|- Version -|- 0x7eff8cda0780|| -|- GCpp 0.0.1-e12a6d6*
    |> 20191015 03:38:54.834 -|- INFO -|- ParseFilterWindows -|- 0x7eff8cda0780|| -|- Running on all contigs
    |> 20191015 03:38:54.834 -|- INFO -|- Run -|- 0x7eff8cda0780|| -|- Found consensus models for: (P6-C4, S/P1-C1.1, S/P1-C1.2, S/P1-C1.3, S/P1-C1/beta, S/P2-C2, S/P2-C2/5.0, S/P3-C1/5.0-8M, S/P3-C3/5.0)
    |> 20191015 03:38:54.835 -|- INFO -|- Run -|- 0x7eff8cda0780|| -|- Using consensus models for: (S/P3-C3/5.0)

The sleeping gcpp process had started about two weeks earlier and was sleeping since then. I was able to manually type in this command, and it completed in a few minutes, but when I tried to kill the sleeping process to move on it crashed the whole run. I am currently rerunning the whole thing again hoping it doesn't happen again. Any ideas on what could be causing this?

**Comment by armintoepfer** [comment]
This sounds like a problem with your system, as a manual run completes with no problems.

Please reopen, if it crashes again.

**Comment by michaeljmetzger** [comment]
When you say a problem with the system, do you have any idea what kind of problem you are talking about? 
After retrying using many more threads it ran faster, but still hung up. This time there were 4 different gcpp processes left sleeping, instead of 1. I can keep retrying but without any idea why this is happening I am just doing the same thing hoping for a different outcome.

**Comment by michaeljmetzger** [comment]
I retried this a third time and got nearly a dozen Sleeping processes after all the other gcpp processed had finished. They appear to be stuck on a mutex.
Also, I don't know if responding here really reopens the thread, so I will probably restart a new one.
