### ISSUE TITLE
How can I get output xml file from bax2bam?

### ISSUE THREAD

**Issue by ilnamkang** [PacificBiosciences/pbbioconda#227]
Hi,

I'd like to get output xml file from bax2bam to test if I can import the xml file into SMRT Link.

But, I cannot find how to get output xml file.

I'm running bax2bam (version 0.0.8) installed by conda on Ubuntu 18.04

Below is my command.

bax2bam -o Test --output-xml=Test movie.1.bax.h5 movie.2.bax.h5 movie.3.bax.h5

By using the above command, I can get bam file and pbi file, but not any xml file.

Thanks.

**Comment by ilnamkang** [comment]
I found the solution from the following webpage.

https://github.com/NBISweden/workshop-genome_assembly/wiki/SMRT-Tools

**Comment by natechols** [comment]
Please bear in mind that the latest version of SMRT Link (8.0) no longer supports RSII data.  You can import the subreadset.xml that bax2bam generates, but most tools will complain when you use it as input for analysis applications.

**Comment by ilnamkang** [comment]
Thank you for saving my time.

Then, are there no ways to apply 'Microbial Assembly' application introduced in SMRT Link ver 8.0 for RS II data?

**Comment by isovic** [comment]
Unfortunately RSII data won't be supported in the Microbial Assembly application, because the polishing stage no longer supports the pre-Sequel data.
That applies to HGAP4 as well, because it also uses the same polishing method.

**Comment by ilnamkang** [comment]
Thanks for your answer.
