### ISSUE TITLE
pb-falcon package does not depend on pypeflow package

### ISSUE THREAD

**Issue by peterjc** [PacificBiosciences/pbbioconda#23]
Currently https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pb-falcon/meta.yaml bundles https://github.com/PacificBiosciences/pypeFLOW/archive/2.1.0.tar.gz as part of the source code.

I think it should instead declare a dependency on https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pypeflow/meta.yaml (which I note would first need updating to v2.1.0)

**Comment by pb-cdunn** [comment]
Possibly. But for now, we are not using that `pypeflow` recipe at all, and some of our sdist tarballs are actually stored inside **pypeFLOW** GitHub releases.

**Comment by isovic** [comment]
Thank you for the comment/suggestion @peterjc !
Closing this since @pb-cdunn's reply answers the question. If there is a need for a followup discussion, please reopen this thread.
