### ISSUE TITLE
Recommendation for tools to detect tandem repeats?

### ISSUE THREAD

**Issue by bl24** [PacificBiosciences/pbbioconda#233]
I'm currently trying out pbsv on some mouse data that are aligned to multiple reference genomes that don't have tandem repeat annotations and I was wondering if y'all have recommendations for tools to generate a tandem repeat bed file?

**Comment by ylipacbio** [comment]
You may use Gary Benson's Tandem Repeat Finder, TRFD public database or download TRF tool and run on mouse reference genome.

Or alternatively if you have already installed SMRTLink, you may use 
```
python \
 -m pbsvtools.tasks.split_ref_to_chrs \
 mouse.fasta \
 chr_size.csv

python \
      -m pbsvtools.tasks.tandem_repeat_finder \
      mouse.fasta \
      chr_size.csv \
      mouse.tandemrepeats.bed
```
File `mouse.tandemrepeats.bed` will contain tandem repeats and you may use it as input for `pbsv discover` option `--tandem-repeats`
