### ISSUE TITLE
pbmm2 multi fastq align error

### ISSUE THREAD

**Issue by jiadong324** [PacificBiosciences/pbbioconda#236]
**Operating system**
A HPC of Centos OS.
**Package name**
pbmm2 v1.1.0

**Conda environment**
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2019.10.16                    0  
certifi                   2019.9.11                py27_0  
curl                      7.65.3               hbc83047_0  
htslib                    1.9                  h4da6232_3    bioconda
krb5                      1.16.1               h173b8e3_7  
libcurl                   7.65.3               h20c2e04_0  
libdeflate                1.2                  h516909a_1    bioconda
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libssh2                   1.8.2                h1ba5d50_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
manta                     1.6.0                    py27_0    bioconda
ncurses                   6.1                  he6710b0_1  
openssl                   1.1.1d               h7b6447c_3  
pbbam                     1.0.6                hc16d5b3_1    bioconda
pbcopper                  1.3.0                h3e4de3e_0    bioconda
pbmm2                     1.1.0                hfb76ee0_0    bioconda
pip                       19.2.3                   py27_0  
python                    2.7.16               h9bab390_7  
readline                  7.0                  h7b6447c_5  
setuptools                41.4.0                   py27_0  
sqlite                    3.30.0               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
wheel                     0.33.6                   py27_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3

```
**Describe the bug**
Running commands:
```
ls *.ccs.fastq.gz > myfiles.fofn
pbmm2 align /path/to/ref.fa /path/to/myfiles.fofn /path/to/myfiles.srt/bam --preset CCS --rg '@RG\tID:myid\tSM:mysample' --sort -j 8 -J 8
```
I use absolute path of these files.

**Error message**
```
-|- FATAL -|- operator() -|- 0x2b1bf9f1ef80|| -|- caught SIGABRT
```

**Comment by jiadong324** [comment]
Follow ups:

I can do the alignment of single fastq.gz file. And it should be fine for pbsv.

My question is if it is feasible to merge with samtools and run Sniffles or other long read callers.

Looking forward to the comments, thanks!

**Comment by ylipacbio** [comment]
Thanks for reporting this bug!
I was able to reproduce it. We will take a look.

**Comment by jiadong324** [comment]
@ylipacbio 

Thanks. I would process each fastq and merge.

**Comment by armintoepfer** [comment]
Hi. It's not a bug, as it's simply not supported. Please refer to https://github.com/PacificBiosciences/pbmm2/blob/develop/README.md#multiple-input-files what fofn accepts.

Armin

**Comment by armintoepfer** [comment]
Mhmm the example states gz, I'll check.

**Comment by jiadong324** [comment]
@armintoepfer 

I follow the examples provided, and echo each fastq.gz file to myfiles.fofn.

Thanks.

**Comment by jiadong324** [comment]
@ylipacbio 

Hi, I am using Sniffles on the pbmm2 aligned BAM files. Sniffles requires MD string in the BAM file, which is not provided. Dose pbmm2 has option to enable such operation?

Thanks!

**Comment by armintoepfer** [comment]
Please read https://github.com/PacificBiosciences/sv-benchmark

**Comment by Alicja-RNA** [comment]
I am having the same error code:

>|> 20200227 03:13:52.406 -|- FATAL -|- operator() -|- 0x2aec64340040|| -|- caught SIGABRT

while mapping PacBio subreads.bam with pbm2 align (version smrttools/8.0.0.80529)

It is working for other 5 samples, this one is the biggest, 418G - could that be an issue? I definitely have enough memory, as I have asked for much more (still trying to optimize my pipeline...):
Memory Efficiency: 12.62% of 128.00 GB

I will very much appreciate your help

**Comment by armintoepfer** [comment]
As you are using smrttools, please contact PacBio tech support for further help.

You can give the latest pbmm2 version on bioconda a try.
