### ISSUE TITLE
Detect complex SVs with pbsv

### ISSUE THREAD

**Issue by jiadong324** [PacificBiosciences/pbbioconda#237]
Hi,

I want to discover some complex SVs with pbsv, is there any recommended settings or hints for this? Sniffles has the potential to detect INVDUP and DELINV, I am wondering if pbsv is able to deal with these complex cases?

Thanks!

**Comment by armintoepfer** [comment]
`pbsv` will give you the individual calls, but won't phase them. Phasing is an extra step. Separation of concerns.
