### ISSUE TITLE
IsoSeq v3.2 real world example failed

### ISSUE THREAD

**Issue by altayg** [PacificBiosciences/pbbioconda#239]
**Operating system**
Ubunt 18.04

**Package name**
IsoSeq v3.2

**Describe the bug**
 IsoSeq v3.2 tutorial with the link below that failed at the second step.

https://github.com/PacificBiosciences/IsoSeq/blob/master/README_v3.2.md#real-world-example

When I run this line it looks for primers.fasta file and I do not have it as wget runs above in the tutorial does not download such file.

$ lima m54086_170204_081430.ccs.bam primers.fasta m54086_170204_081430.fl.bam \ --isoseq --peek-guess
 ERROR: Input barcode file does not exist: primers.fasta

**Error message**
 ERROR: Input barcode file does not exist: primers.fasta

**To Reproduce**
The real-world-example in this link:
https://github.com/PacificBiosciences/IsoSeq/blob/master/README_v3.2.md#real-world-example

**Comment by armintoepfer** [comment]
The tutorial shows you the exact content of the file. You need to create said file on your own.
