### ISSUE TITLE
pbmerge or some other way of creating a consolidated ccs report

### ISSUE THREAD

**Issue by adeslatt** [PacificBiosciences/pbbioconda#241]
**Operating system**
Which operating system and version are you using?

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**

**Error message**
Paste the error message / stack.

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**

**Comment by armintoepfer** [comment]
Can you at least provide what you are looking for?

**Comment by adeslatt** [comment]
Hi there -- so sorry -- I think I put this out before I finished my thought.   I do the multi-threaded and I get everything in a single ccs_report -- if you chunk it you get as many chunks in the report -- now (and congratulations!) maybe it doesn't matter so much... you simply keep making it faster and faster.   But it is just the idea to have the ability to put everything back together after separating things out to permit in parallel consensus finding..... Does this make sense now?

**Comment by armintoepfer** [comment]
Oh it does, question is, do we need official support for that or can you write a 20 line python/bash script do merge them on your own. The thing is, would we provide a new tool for that? Should it be part of ccs? Or would it be a simple script that we would put on the ccs github page? What is your opinion as an user?

**Comment by armintoepfer** [comment]
Upcoming CCS version allows to store the ccs_reports as an additional json file. From there, it will be very easy to merge with any programming language supporting json.
