### ISSUE TITLE
Need the unitig sequences.

### ISSUE THREAD

**Issue by Zoexfq** [PacificBiosciences/pbbioconda#247]
Hi, I'm sorry to bother, but I acctually need the unitig sequences for my next step. Can you tell me how can I have access to the unitig sequnces?

**Comment by isovic** [comment]
Hi @Zoexfq,
Falcon doesn't actually construct the individual unitig sequences, nor is there currently an out-of-the box tool to construct them.
I can point you to a deprecated, old, legacy script which hasn't been in active use in years, it might give you a head start if you plan to implement your own unitig constructor for Falcon: https://github.com/PacificBiosciences/FALCON/blob/master/falcon_kit/mains/graph_to_utgs.py
However, this comes with **no guarantee**, and there are no plans to continue development or maintenance of this script.

Best regards,
Ivan.
