### ISSUE TITLE
Lima remove additional bases beyond the barcode primer

### ISSUE THREAD

**Issue by yuqiu77** [PacificBiosciences/pbbioconda#249]
**Operating system**
Linux

**Package name**
Lima 1.10.0

**Describe the bug**
lima remove additional sequences beyond the barcode/primer. 

I tried to use lima to process some targeted isoseq data.  I first run lima and isoseq3 to generate a flnc.bam file.  A sample line is like:

m54278_191216_195902/4391743/ccs        4       *       0       255     *       *       0       0       GATAAACACTGCGGCCAACTTACTTCTGACAACGATCGGAGGACCGAAGGAGCTAACCGCTTTTTGCACAACATGGGG

then I run lima to remove PCR primers:
lima --ccs -d -m 75 --split-bam-named flnc.bam primers,fa lima.bam

primers.fa contains the primer sequences:

>primerF
GATAACACTGCGGCCAACTT
>primerR
TCATGGTTATGGCAGCACTG

The resulted lima.bam file clipped additional sequences:
m54278_191216_195902/4391743/ccs        4       *       0       255     *       *       0       0       GGACCGAAGGAGCTAACCGCTTTTTGCACAACATGGGGGATCATGTAACTCGCCTTGATCGTTG

The dumped_clips file suggested that primer was found at 19-40bp.

>m54278_191216_195902/4391743/19_40 bq:95 bc:0
GATAAACACTGCGGCCAACTT
>m54278_191216_195902/4391743/10822_10842 bq:100 bc:1
CAGTGCTGCCATAACCATGA

**To Reproduce**
lima --ccs -d -m 75 --split-bam-named flnc.bam primers,fa lima.bam

**Expected behavior**
Clipped data should be started from ~20bp. 

** Input flnc.bam file is attached. **

[flnc.zip](https://github.com/PacificBiosciences/pbbioconda/files/4046339/flnc.zip)

**Comment by armintoepfer** [comment]
There are problem with double demux in the bioconda lima version. I'll release a new version soon to fix double demux.

**Comment by armintoepfer** [comment]
It's fixed
