### ISSUE TITLE
Many jobs running on slurm cluster, but not computing anything

### ISSUE THREAD

**Issue by mchaisso** [PacificBiosciences/pbbioconda#250]
**Operating system**
CentOS
**Package name**
falcon-kit 1.8.1 (pip thinks "falcon-kit 1.8.1")
pypeflow 2.3.0

**Conda environment**
Too long (can paste later if helps)

**Describe the bug**
I am running 44 concurrent assemblies (1 for each chromatid). The config file is given below, but the key parts are pwatcher_type=blocking, and the submit command uses srun. I'm trying to burn through as many assemblies as possible, so it's important to maximally utilize the resources on my cluster.  When I ssh to many of the nodes to peek on what is going on, there are no commands that I have running (nothing in htop, and as far as I can tell, when I run ps -efl | grep mchaisso, nothing running other than the shell of my ssh job. So somehow the jobs do not seem to be returning. I've also submitted a ticket to our HPC department to see if there are any issues on the backend configuration.

There are a handful of jobs that are running some daligner or consensus jobs (~3-5), but most are stalled.

           5866999       cmb   falcon mchaisso  R       8:32      1 hpc3962
           5866998       cmb   falcon mchaisso  R      11:03      1 hpc3961
           5866997       cmb   falcon mchaisso  R      12:05      1 hpc3963
           5866906       cmb   falcon mchaisso  R      22:54      1 hpc0950
           5866767       cmb   falcon mchaisso  R    1:12:07      1 hpc2741
           5866768       cmb   falcon mchaisso  R    1:12:07      1 hpc2742
           5866763       cmb   falcon mchaisso  R    1:22:45      1 hpc2740
           5866749       cmb   falcon mchaisso  R    1:23:24      1 hpc0949
           5866750       cmb   falcon mchaisso  R    1:23:24      1 hpc0950
           5866751       cmb   falcon mchaisso  R    1:23:24      1 hpc0951
           5866752       cmb   falcon mchaisso  R    1:23:24      1 hpc0952
           5866753       cmb   falcon mchaisso  R    1:23:24      1 hpc2730
           5866754       cmb   falcon mchaisso  R    1:23:24      1 hpc2731
           5866756       cmb   falcon mchaisso  R    1:23:24      1 hpc2733
           5866758       cmb   falcon mchaisso  R    1:23:24      1 hpc2735
           5866759       cmb   falcon mchaisso  R    1:23:24      1 hpc2736
           5866760       cmb   falcon mchaisso  R    1:23:24      1 hpc2737
           5866761       cmb   falcon mchaisso  R    1:23:24      1 hpc2738
           5866762       cmb   falcon mchaisso  R    1:23:24      1 hpc2739
           5866427       cmb   falcon mchaisso  R    3:15:35      1 hpc0940
           5866425       cmb   falcon mchaisso  R    3:15:37      1 hpc0941
           5866426       cmb   falcon mchaisso  R    3:15:37      1 hpc0941
           5866424       cmb   falcon mchaisso  R    3:15:42      1 hpc0940
           5866422       cmb   falcon mchaisso  R    3:15:47      1 hpc0940
           5866417       cmb   falcon mchaisso  R    3:16:06      1 hpc3596
           5866380       cmb   falcon mchaisso  R    3:26:39      1 hpc0947
           5866263       cmb   falcon mchaisso  R    4:01:12      1 hpc0943
           5866264       cmb   falcon mchaisso  R    4:01:12      1 hpc0945
           5866195       cmb   falcon mchaisso  R    4:25:43      1 hpc0941
           5866196       cmb   falcon mchaisso  R    4:25:43      1 hpc0941
           5866078       cmb   falcon mchaisso  R    5:25:43      1 hpc3954
           5866042       cmb   falcon mchaisso  R    5:32:42      1 hpc3952
           5865975       cmb   falcon mchaisso  R    5:39:40      1 hpc3958
           5865971       cmb   falcon mchaisso  R    5:41:48      1 hpc3595
           5865972       cmb   falcon mchaisso  R    5:41:48      1 hpc3752
           5865968       cmb   falcon mchaisso  R    5:42:19      1 hpc0940
           5865966       cmb   falcon mchaisso  R    5:42:30      1 hpc3836
           5865962       cmb   falcon mchaisso  R    5:42:33      1 hpc3597
           5865963       cmb   falcon mchaisso  R    5:42:33      1 hpc3760
           5865952       cmb   falcon mchaisso  R    5:42:38      1 hpc3956
           5865953       cmb   falcon mchaisso  R    5:42:38      1 hpc3951
           5865954       cmb   falcon mchaisso  R    5:42:38      1 hpc3964
           5865959       cmb   falcon mchaisso  R    5:42:38      1 hpc3761
           5865960       cmb   falcon mchaisso  R    5:42:38      1 hpc3763
           5865863       cmb   falcon mchaisso  R    5:46:46      1 hpc0943
           5865833       cmb   falcon mchaisso  R    5:50:08      1 hpc0943
           5865805       cmb   falcon mchaisso  R    5:53:13      1 hpc0943
           5865746       cmb   falcon mchaisso  R    6:02:01      1 hpc3476
           5865747       cmb   falcon mchaisso  R    6:02:01      1 hpc3477
           5865748       cmb   falcon mchaisso  R    6:02:01      1 hpc3478

**Error message**
Paste the error message / stack.

[job.defaults]
njobs = 100
#submit = /bin/bash -c "${JOB_SCRIPT}"

JOB_QUEUE = cmb
MB = 48000
NPROC = 8
pwatcher_type=blocking

submit = srun \
  -p cmb     \
  -J falcon        \
  --time=8:00:00 \
  --mem=${MB}M \
  -c ${NPROC}    \
  "${JOB_SCRIPT}"

[General]
input_type = raw
pwatcher_type=blocking

#input_type = preads

input_fofn = input.fofn

#pwatcher_type=fs_based

# The length cutoff used for seed reads used for initial mapping

genome_size = 159345973
seed_coverage = 30
length_cutoff = -1

# The length cutoff used for preads
length_cutoff_pr = 8000

falcon_greedy = False
falcon_sense_greedy=False

# overlapping options for Daligner
pa_daligner_option = -e0.8 -l1000 -k18 -h70 -w8 -s100 -T12
ovlp_daligner_option = -k24 -h1024 -e.95 -l1000 -s100 -T12
pa_HPCdaligner_option = -v -B128 -M24 -T12
ovlp_HPCdaligner_option = -v -B128 -M24 -T12

pa_HPCTANmask_option = -k18 -h480 -w8 -e.8 -s100
pa_HPCREPmask_option = -k18 -h480 -w8 -e.8 -s100
#pa_REPmask_code=1,20;10,15;50,10

pa_DBsplit_option = -x500 -s400
ovlp_DBsplit_option = -s400

# error correction consensus option
falcon_sense_option = --output-multi --min-idt 0.70 --min-cov 3 --max-n-read 100 --n-core 8

# overlap filtering options
overlap_filtering_setting = --max-diff 100 --max-cov 200 --min-cov 2 --n-core 8

[job.step.da]
NPROC=12
MB=32000
njobs=200
[job.step.la]
NPROC=4
MB=32000
njobs=200
[job.step.cns]
NPROC=8
MB=16000
njobs=200
[job.step.pda]
NPROC=8
MB=64000
njobs=200
[job.step.pla]
NPROC=8
MB=32000
njobs=200
[job.step.asm]
NPROC=12
MB=92000
njobs=10

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**

**Comment by isovic** [comment]
Hi Mark,
Has there been any development about this topic on your end?
This definitely doesn't sound like an assembly issue, but something related to the cluster setup.
Tagging @pb-cdunn here, he might have better insight into the queue options.

Quick question: is it just the formatting when you copy/pasted, or are you missing backslashes in the `submit` command?

Best regards,
Ivan.

**Comment by mchaisso** [comment]
It was an srun issue -- I changed to sbatch --wait and things are working
well now.

Thanks for looping back,
-Mark

**Comment by isovic** [comment]
Great to hear that! Thanks!
Best regards,
Ivan.
