### ISSUE TITLE
Re-run 2-asm-falcon using different settings

### ISSUE THREAD

**Issue by nsgarcia27** [PacificBiosciences/pbbioconda#253]
Hello. I know this is not a bug, but I can't find a solution anywhere else. 

I would like to re-run "2-asm-falcon" stage using a different "overlap_filtering_setting". If I am not mistaken, I should use the "preads4falcon.fasta" as input for this. In the FAQ, it says I can change the input from "raw" to "preads". But I am not sure if this is the right thing to do because I am not doing the "1-pread_ovl" step anymore. What should the config file look like for this re-run? How do I use "preads4falcon.fasta" to re-run the final contig assembly step? 

Many thanks

Nelson

**Comment by zeeev** [comment]
Hi @nsgarcia27,

There's more than one way to do what you want. I'll tell you my approach. 

go into 2-asm, edit the user script to use the settings you want user_script.sh), then run `bash -vx user_script.sh`

you might want to create a backup of 2-asm, as the method I described will simply overwrite the outputs.

Best,

Zev

**Comment by nsgarcia27** [comment]
Hi Zev,

Thank you so much! Is there another approach that I can run it in a
different directory? I am currently running falcon-unzip and I am afraid
the run might be disturbed if I do this. Can I copy the relevant files in a
different directory and then run it from there?

Nelson

**Comment by zeeev** [comment]
Hi Nelson,

I would opt to backup the working folder. If I remember correctly, a copied folder doesn't work without fiddling with paths.

Zev
