### ISSUE TITLE
Question on Max Genome Size

### ISSUE THREAD

**Issue by cement-head** [PacificBiosciences/pbbioconda#256]
What's the maximum size for FALCON and FALCON-Unzip? I know that HGAP is suitable for 3.0 Gbp, but not larger.  My vertebrate genome is diplod and is approximately 6.0 Gbp.  TIA.

**Comment by pb-dseifert** [comment]
In general, you're limited by contig size, and won't be able to go above `2^31-1` due to limitations in the BAM format.
