### ISSUE TITLE
configure --n-core 4-polish/track-reads

### ISSUE THREAD

**Issue by weihongqi** [PacificBiosciences/pbbioconda#259]
**Operating system**
Linux 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u2~bpo8+1 (2017-06-27) x86_64 GNU/Linux

**Package name**
falcon-unzip 1.3.7 (pip thinks "falcon-unzip 1.3.7")
falcon-kit 1.8.0 (pip thinks "falcon-kit 1.8.0")
pypeflow 2.3.0

**Conda environment**
# packages in environment at /usr/local/ngseq/miniconda3/envs/pb-assembly-newest:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
bedtools                  2.29.0               hc088bd4_3    bioconda
blasr                     5.3.3                h018d624_1    bioconda
blasr_libcpp              5.3.3                h018d624_1    bioconda
bwa                       0.7.17               hed695b0_6    bioconda
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
falcon-kit                1.8.0                    pypi_0    pypi
falcon-phase              1.2.0                    pypi_0    pypi
falcon-unzip              1.3.7                    pypi_0    pypi
future                    0.18.2                   py37_0    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
htslib                    1.9                  h244ad75_9    bioconda
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
falcon-kit                1.8.0                    pypi_0    pypi
falcon-phase              1.2.0                    pypi_0    pypi
falcon-unzip              1.3.7                    pypi_0    pypi
future                    0.18.2                   py37_0    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
htslib                    1.9                  h244ad75_9    bioconda
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdeflate                1.3                  h516909a_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libopenblas               0.3.7                h6e990d7_3    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
minimap2                  2.17                 h8b12597_1    bioconda
mummer4                   4.0.0beta2      pl526hf484d3e_4    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nim-falcon                1.0.1                h2f8a211_0    bioconda
numpy                     1.17.3           py37h95a1406_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
pb-assembly               0.0.8                         0    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 2.2.3            py37hed50d52_0    bioconda
pb-falcon-phase           0.1.0                h3889886_0    bioconda
pbbam                     1.0.6                hc16d5b3_1    bioconda
pbcopper                  1.3.0                h3e4de3e_0    bioconda
pbgcpp                    0.0.1                         0    <unknown>
pbmm2                     1.1.0                hfb76ee0_0    bioconda
pcre                      8.43                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pysam                     0.15.3           py37hbcae180_3    bioconda
python                    3.7.3                h33d41f4_1    conda-forge
python-edlib              1.3.6            py37hc9558a2_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.6.1            py37hc9558a2_1    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
racon                     1.4.10               he513fc3_0    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
setuptools                42.0.1                   py37_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

**Describe the bug**
4-polish/track-reads is too slow.  All 128 processors were used because the default --n-core = n_cpu/2,  the IO becomes extremely slow. 64 fc_rr_hctg_track.py and 64 LA4Falcon jobs are running at the same time, each only uses 1% of CPU, while IO is the limiting factor. 

**Error message**
NO error message. I would like to speed up this step by customising the setting of --n-core

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**
For 3_unzip track reads, when two cpus were used for LA4Falcon, only minutes were needed to track reads. Now it takes days and still running.

**Comment by pb-cdunn** [comment]
You're right, but this is too big a change for us to support right now. I suggest modifying the python code directly (if this is still an issue for you). Not much we can do.

A better solution (if possible) is to switch to hifi reads and try our new IPA assembler, which is very fast.
