### ISSUE TITLE
filter pbsv calls

### ISSUE THREAD

**Issue by jiadong324** [PacificBiosciences/pbbioconda#267]
Hi,

I was using the default settings of pbsv for SV detection. In the VCF file, can I use the number in "AD" to filter the calls? If it is possible, which number in "AD" (there are two numbers) support the ALT allele?

Thanks!

**Comment by armintoepfer** [comment]
We follow VCF standard: https://gatkforums.broadinstitute.org/gatk/discussion/1268/what-is-a-vcf-and-how-should-i-interpret-it
