### ISSUE TITLE
error on dataset create --type ConsensusReadSet combined_demux.consensusreadset.xml

### ISSUE THREAD

**Issue by altayg** [PacificBiosciences/pbbioconda#269]
**Operating system**
Ubuntu 18.04

**Package name**
isoseq3 3.3.0 (commit v3.3.0)
lima 1.11.0 (commit v1.11.0)
ccs 4.2.0 (commit v4.2.0)

**Conda environment**
$ conda list
# packages in environment at /home/ga/anaconda3/envs/anaCogent5.2:
#
# Name                    Version                   Build  Channel
_anaconda_depends         5.1.0                    py27_2  
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py27_1  
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-project          0.8.3                      py_0    conda-forge
argh                      0.26.2                py27_1001    conda-forge
asn1crypto                1.3.0                    py27_0    conda-forge
astroid                   1.6.5                    py27_0    conda-forge
astropy                   2.0.9                    py27_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
autopep8                  1.5                        py_0    conda-forge
avro-python2              1.9.0                      py_0    bioconda
babel                     2.8.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.os              0.1.1                 py27_1001    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5                        py_1    conda-forge
bamtools                  2.5.1                he860b03_5    bioconda
beautifulsoup4            4.8.2                    py27_0    conda-forge
biopython                 1.76             py27h516909a_0    conda-forge
bitarray                  1.2.1            py27h516909a_0    conda-forge
bkcharts                  0.2                      py27_0    conda-forge
blaze                     0.11.3                   py27_0    conda-forge
bleach                    3.1.1                      py_0    conda-forge
blosc                     1.17.1               he1b5a44_0    conda-forge
bokeh                     1.4.0                    py27_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.2            py27hc1659b7_0    conda-forge
bx-python                 0.8.8            py27h9449cc1_0    bioconda
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hfb77d84_1002    conda-forge
cdecimal                  2.3             py27h516909a_1001    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
cffi                      1.14.0           py27hd463f26_0    conda-forge
chardet                   3.0.4                 py27_1005    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    conda-forge
configparser              3.7.3                    py27_1    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
cryptography              2.8              py27h72c5cf5_1    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.15          py27haf22ab1_1    conda-forge
cytoolz                   0.10.1           py27h516909a_0    conda-forge
dask                      1.2.2                      py_3    conda-forge
dask-core                 1.2.2                      py_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
diff-match-patch          20181111                   py_0    conda-forge
distributed               1.28.1                   py27_0    conda-forge
docutils                  0.16             py27h8c360ce_1    conda-forge
entrypoints               0.3             py27h8c360ce_1001    conda-forge
enum34                    1.1.10           py27h8c360ce_1    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastcache                 1.1.0            py27h516909a_0    conda-forge
filelock                  3.0.10                     py_0    conda-forge
flake8                    3.7.9                    py27_0    conda-forge
flask                     1.1.1                      py_1    conda-forge
flask-cors                3.0.8                      py_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
funcsigs                  1.0.2                      py_3    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
future                    0.18.2                   py27_0    conda-forge
futures                   3.3.0                    py27_0    conda-forge
get_terminal_size         1.0.0                haa9412d_0  
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gevent                    1.4.0            py27h516909a_0    conda-forge
glib                      2.58.3          py27h6f030ca_1002    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
gmpy2                     2.1.0b1          py27h04dde30_0    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
greenlet                  0.4.15           py27h516909a_0    conda-forge
grin                      1.2.1                   py_1001    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
h5py                      2.10.0          nompi_py27h513d04c_102    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
imageio                   2.6.1                    py27_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.5.0            py27h8c360ce_1    conda-forge
importlib_metadata        1.5.0                         1    conda-forge
intel-openmp              2019.4                      243  
intervaltree              3.0.2                      py_0    conda-forge
ipaddress                 1.0.23                     py_0    conda-forge
ipykernel                 4.10.0                   py27_1    conda-forge
ipython                   5.8.0                    py27_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
isort                     4.3.21                   py27_0    conda-forge
isoseq3                   3.3.0                         0    bioconda
itsdangerous              1.1.0                      py_0    conda-forge
jbig                      2.1               h14c3975_2001    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.14.1                   py27_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.2.0                    py27_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.4                    py27_1    conda-forge
jupyter_console           5.2.0                    py27_1    conda-forge
jupyter_core              4.6.3                    py27_0    conda-forge
jupyterlab                0.33.12                  py27_0    conda-forge
jupyterlab_launcher       0.11.2                     py_0    conda-forge
kiwisolver                1.1.0            py27h9e3301b_1    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
lazy-object-proxy         1.4.3            py27h516909a_1    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               15_openblas    conda-forge
libcblas                  3.8.0               15_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libdeflate                1.5                  h516909a_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               15_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libopenblas               0.3.8                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
lima                      1.11.0                        0    bioconda
linecache2                1.0.0                      py_1    conda-forge
llvm-openmp               9.0.1                hc9558a2_2    conda-forge
llvmlite                  0.31.0           py27h8b12597_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.5.0            py27h7ec2d77_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py27hdf8410d_1    conda-forge
matplotlib                2.2.5                         1    conda-forge
matplotlib-base           2.2.5            py27h250f245_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py27h516909a_1000    conda-forge
mkl                       2019.5                      281    conda-forge
mkl-service               2.3.0            py27h516909a_0    conda-forge
mock                      3.0.5                    py27_0    conda-forge
more-itertools            5.0.0                      py_0    conda-forge
mpc                       1.1.0             h04dde30_1006    conda-forge
mpfr                      4.0.2                he80fd80_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.2            py27hc9558a2_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
nbconvert                 5.6.1                    py27_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
nltk                      3.4.4                      py_0    conda-forge
nose                      1.3.7           py27h8c360ce_1004    conda-forge
notebook                  5.7.8                    py27_1    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.47.0           py27hb3f55d8_0    conda-forge
numexpr                   2.7.1            py27hb3f55d8_0    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
numpydoc                  0.9.2                      py_0    conda-forge
odo                       0.5.1                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openpyxl                  2.6.4                      py_0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    0.24.2           py27hb3f55d8_0    conda-forge
pandoc                    2.9.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               ha030887_1    conda-forge
parso                     0.6.2                      py_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
patchelf                  0.10                 he1b5a44_0    conda-forge
path.py                   11.5.2                     py_0    conda-forge
pathlib2                  2.3.5                    py27_0    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pbccs                     4.2.0                         0    bioconda
pbcommand                 1.1.1                      py_3    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pbcoretools               0.2.4                    py27_4    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0                    py27_0    conda-forge
pickleshare               0.7.5                 py27_1000    conda-forge
pillow                    6.2.1            py27hd70f55b_1    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
psutil                    5.7.0            py27h516909a_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
pycairo                   1.18.2           py27h438ddbb_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycosat                   0.6.3           py27hdf8410d_1003    conda-forge
pycparser                 2.20                       py_0    conda-forge
pycrypto                  2.6.1           py27h516909a_1003    conda-forge
pycurl                    7.43.0.5         py27h16ce93b_0    conda-forge
pydocstyle                3.0.0                    py27_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pylint                    1.9.2                    py27_0    conda-forge
pympler                   0.8                        py_0    conda-forge
pyodbc                    4.0.30           py27he1b5a44_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyqt                      5.12.3           py27hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.15.7           py27h516909a_0    conda-forge
pysam                     0.15.4           py27hbcae180_0    bioconda
pysocks                   1.7.1                    py27_0    conda-forge
pytables                  3.5.2            py27h9f153d1_2    conda-forge
pytest                    4.6.4                    py27_0    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.3.4                      py_0    conda-forge
python-language-server    0.31.7                   py27_0    conda-forge
python-lzo                1.12            py27h3753786_1000    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.0.3            py27hd352d35_1    conda-forge
pyxdg                     0.26                       py_0    conda-forge
pyyaml                    5.3              py27h516909a_0    conda-forge
pyzmq                     19.0.0           py27h1768529_0    conda-forge
qdarkstyle                2.8                        py_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtawesome                 0.7.0                      py_0    conda-forge
qtconsole                 4.7.1                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0                   py27_0    conda-forge
rope                      0.16.0                     py_0    conda-forge
rtree                     0.9.4            py27h7b0cdae_0    conda-forge
ruamel_yaml               0.15.80         py27h516909a_1000    conda-forge
scandir                   1.10.0           py27h516909a_0    conda-forge
scikit-image              0.14.3           py27hb3f55d8_0    conda-forge
scikit-learn              0.20.3           py27ha8026db_1    conda-forge
scipy                     1.2.1            py27h921218d_2    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
selectors2                2.0.1                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py27_1000    conda-forge
sip                       4.19.20          py27he1b5a44_0    conda-forge
six                       1.14.0                     py_1    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcollections         1.1.2                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.4                    py27_0    conda-forge
sphinx                    1.8.5                    py27_0    conda-forge
sphinxcontrib             1.0                      py27_1  
sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
spyder                    4.0.0                    py27_0    conda-forge
spyder-kernels            1.8.1                    py27_1    conda-forge
sqlalchemy                1.3.15           py27hdf8410d_1    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
ssl_match_hostname        3.7.0.1                 py_1000    conda-forge
statsmodels               0.10.2           py27hc1659b7_0    conda-forge
subprocess32              3.5.4            py27h516909a_0    conda-forge
sympy                     1.5.1                    py27_1    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3                    py27_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   5.1.1           py27h14c3975_1000    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
traitlets                 4.3.3            py27h8c360ce_1    conda-forge
typing                    3.7.4.1          py27h8c360ce_1    conda-forge
ujson                     2.0.1            py27he1b5a44_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
unixodbc                  2.3.7             h227dcee_1000    conda-forge
urllib3                   1.25.7                   py27_0    conda-forge
watchdog                  0.10.2                   py27_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.0                      py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py27_0    conda-forge
wrapt                     1.12.1           py27hdf8410d_1    conda-forge
wurlitzer                 2.0.0                    py27_0    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.2.8                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
yapf                      0.29.0                     py_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_1    conda-forge

**Describe the bug**

I am following this pipeline with my own data:
https://github.com/PacificBiosciences/IsoSeq_SA3nUP/wiki/Tutorial:-Installing-and-Running-Iso-Seq-3-using-Conda

I have 6 samples and want to get reference transcriptome from them.

Ath this step "1. Classify full-length reads:", it is suggested that "If you want to analyze all the demultiplexed FL reads together to increase transcript recovery (Example: Same species, different tissues), you must make a combined data set:"

Therefore I run the below command by modifying for my x.fl.bam files to get a single dataset.
"
dataset create --type ConsensusReadSet combined_demux.consensusreadset.xml \
    prefix.5p--barcode1_3p.bam \
    prefix.5p--barcode2_3p.bam \
    prefix.5p--barcode3_3p.bam ...
"

However it did not work and gave the following error?
Any solution for this error?
as a possible workaround, if I run the 6 .bam files seperately, how can I get the transcriptome out of those 6?

**Error message**
$ dataset create --type ConsensusReadSet combined_demux.consensusreadset.xml     demux.NEB_5p--bc1001_3p.bam     demux.NEB_5p--bc1002_3p.bam     demux.NEB_5p--bc1003_3p.bam     demux.NEB_5p--bc1004_3p.bam     demux.NEB_5p--bc1005_3p.bam     demux.NEB_5p--bc1006_3p.bam 
invalid literal for int() with base 16: 'e53a6e34/0--1'
Traceback (most recent call last):
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcoretools/dataset.py", line 59, in run
    return args.func(args)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcoretools/DataSetEntryPoints.py", line 62, in createXml
    generateIndices=args.generateIndices)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2018, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 485, in __init__
    self.updateCounts()
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2598, in updateCounts
    self.assertIndexed()
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2428, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1975, in _assertIndexed
    self._openFiles()
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2099, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 374, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 183, in __init__
    self._loadReadGroupInfo()
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 81, in _loadReadGroupInfo
    rgID = rgAsInt(rg["ID"])
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/align/_BamSupport.py", line 58, in rgAsInt
    return np.int32(int(rgIdString, 16))
ValueError: invalid literal for int() with base 16: 'e53a6e34/0--1'
[ERROR] 2020-03-12 23:06:49,633Z [pbcoretools.dataset _pacbio_main_runner 143] invalid literal for int() with base 16: 'e53a6e34/0--1'
Traceback (most recent call last):
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcoretools/dataset.py", line 59, in run
    return args.func(args)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcoretools/DataSetEntryPoints.py", line 62, in createXml
    generateIndices=args.generateIndices)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2018, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 485, in __init__
    self.updateCounts()
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2598, in updateCounts
    self.assertIndexed()
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2428, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 1975, in _assertIndexed
    self._openFiles()
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/dataset/DataSetIO.py", line 2099, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 374, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 183, in __init__
    self._loadReadGroupInfo()
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 81, in _loadReadGroupInfo
    rgID = rgAsInt(rg["ID"])
  File "/home/ga/anaconda3/envs/anaCogent5.2/lib/python2.7/site-packages/pbcore/io/align/_BamSupport.py", line 58, in rgAsInt
    return np.int32(int(rgIdString, 16))
ValueError: invalid literal for int() with base 16: 'e53a6e34/0--1'

**Expected behavior**
I expected to get this combined datset
combined_demux.consensusreadset.xml
so that I can run the next command
isoseq3 refine --require-polya combined_demux.consensusreadset.xml primers.fasta flnc.bam

**Comment by natechols** [comment]
Handling the new read group ID format requires a newer version of pbcore - I'm not sure what is currently available through pbbioconda, but 2.0 definitely works (although it now requires Python 3).

**Comment by altayg** [comment]
Thanks but the installation in the begining of the pipeline asks for Python 2.7?
