### ISSUE TITLE
failed to run falcon_kit.mains.ovlp_filter

### ISSUE THREAD

**Issue by xiaoluo91** [PacificBiosciences/pbbioconda#272]
Hi, I am trying to run falcon/unzip on HiFi reads, but failed.
I installed the pb-assembly using these commands:
conda install pb-assembly
and update with:
conda update pb-assembly

python --version
Python 2.7.17 :: Anaconda, Inc.

Then, use this command to run: fc_run.py  falcon.hifi.cfg (refer to https://github.com/PacificBiosciences/pbbioconda/wiki/Assembling-HiFi-data:-FALCON-Unzip3)

but it returned errors in this step: 

python -m falcon_kit.mains.ovlp_filter --db 1-preads_ovl/build/preads.db --las-fofn 1-preads_ovl/las-merge-combine/las_fofn.json --max-diff 400 --max-cov 400 --min-cov 2 --n-core 24 --min-idt 98 --ignore-indels --min-len 10000 --out-fn preads.ovl
falcon-kit 1.3.0
pypeflow 2.2.0
usage: ovlp_filter.py [-h] [--out-fn OUT_FN] [--n-core N_CORE]
                      [--las-fofn LAS_FOFN] [--db DB_FN] [--max-diff MAX_DIFF]
                      [--max-cov MAX_COV] [--min-cov MIN_COV]
                      [--min-len MIN_LEN] [--bestn BESTN] [--stream] [--debug]
                      [--silent]
ovlp_filter.py: error: unrecognized arguments: --min-idt 98 --ignore-indels

It seems the version of ovlp_filter.py  is incompatible, but how should I solve this problem? 
Any help would be appreciated!

**Comment by armintoepfer** [comment]
Please try bioconda package `pbipa`, our new HiFi assembler.
