### ISSUE TITLE
Restrict alignments of subreads to ccs reads by ZMW using pbmm2?

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/pbbioconda#274]
Hi, 

I want to align a genomes worth of subreads to the corresponding ccs reads and I am wondering if there is a good way to go about this. 

Specifically I want to only allow alignments of subreads to a CCS read if the CCS read and subread are from the same ZMW. Is there anyway to do this using pbmm2? 

I can do this for a few specific ZMWs without issues using bamsieve but aligning to millions of CCS reads by subsetting for one ZMW at a time is not very feasible. 

Thanks!
Mitchell

**Comment by natechols** [comment]
Can't you also extract the subsets of CCS reads?  Still millions of iterations, but at least each iteration will be extremely fast if you're aligning to a single CCS read at a time.

**Comment by mrvollger** [comment]
Yes I can do that and that is what I have been doing so far. 

But the limiting factor is extracting the subreads which takes ~two minutes per ZMW. Doing this ~4 million times would take ~100,000 CPU hours and results in 4 million bams on my filesystem that I would have to merge (if my back on the envelope calculations are right). 

The above is possible but would take a really long time.

**Comment by armintoepfer** [comment]
pbmm2 has a C++ API and is together with its dependencies open source. Our BAM files, accompanied by a PBI file, are random accessible. So you could write your own tool and process the data without splitting a single file or even patch pbmm2. That said, it's possible, but you have to write it on your own, as it's not a common use case. But happy to accept pull requests.

**Comment by mrvollger** [comment]
Fair enough, I may do this.  

Do you have a minimal example of using the pbmm2 API? Something like https://github.com/lh3/minimap2/blob/master/example.c for minimap2.
