### ISSUE TITLE
pbccs: draft vs. final consensus sequence

### ISSUE THREAD

**Issue by zc312** [PacificBiosciences/pbbioconda#277]
**Package name**
pbccs 4.2.0

Hi. I have a question about --by-strand pbccs. If all the forward reads are collapsed into a draft forward strand consensus sequence, how is the draft forward consensus sequence polished to create the final forward consensus sequence? Does polishing only require the base information from the single draft forward consensus sequence? 

Thank you!

**Comment by armintoepfer** [comment]
After collapsing reads by strand to a draft, identical reads are used per strand to further improve the draft in the polish step.
