### ISSUE TITLE
pbmm2 API description/example

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/pbbioconda#278]
Is there a minimal example of pbmm2's API or a description?

Something like https://github.com/lh3/minimap2/blob/master/example.c for minimap2 would be very helpful.

Thanks!
Mitchell

**Comment by zeeev** [comment]
Hi @mrvollger,

These unit tests should get you started. 

https://github.com/PacificBiosciences/pbmm2/blob/develop/tests/unit/MM2Test.cpp

**Comment by mrvollger** [comment]
Thanks Zev!
