### ISSUE TITLE
CCS read numbers

### ISSUE THREAD

**Issue by christine-liu** [PacificBiosciences/pbbioconda#279]
Hi,
I'm using pbccs version 4.1.0, and I'm a little confused by the number of reads that are being output when I run ccs on the same dataset with different parameters.
I'm playing around with --minPasses and --min-rq to see what improves our read yield but also has a high enough predicted accuracy to look for what we're interested in. 
I have a single bam file of subreads that I've been using to generate fastq files from using the following cutoffs:

--minPasses 5 --min-rq 0.99
--minPasses 2 --min-rq 0.99
--minPasses 2 --min-rq 0.95
--minPasses 1 --min-rq 0.95
--minPasses 1 --min-rq 0.90

If I compare all the runs with --min-rq 0.99 and varying --minPasses, I expect that --minPasses 5 would have fewer reads than --minPasses 2 because --minPasses 2 should include all the reads that would pass in --minPasses 5. However, this doesn't seem to be the case. The number of reads decreases from 1,013,107 to 983,530 when I reduce the pass cutoff. The same thing is true when I compare --minPasses 1 and --minPasses 2 with --min-rq 0.95

There also seems to be something off about the number of input ZMWs. In the CCS report (A) isn't the same across all the ccs runs 1,214,379 for --minPasses 5; 1,214,362 for both runs with --minPasses 2; and 1,214,357 for both runs with --minPasses 1. Shouldn't this be the same for all runs b/c I'm using the same bam file?

Is this a bug or am I misunderstanding how the CCS cutoffs are applied?

Thank you so much!

**Comment by armintoepfer** [comment]
Please update to the latest version 4.2.0. Also, I'd appreciate if you study the docs by at least reading the changelog, because your bug has been fixed: https://github.com/PacificBiosciences/ccs#why-do-i-get-more-yield-if-i-increase---min-passes
