### ISSUE TITLE
Speed up ipdSummary?

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/pbbioconda#280]
Hi,

I am trying to call m6A methylation on subreads aligned back to their respective CCS/HiFi reads and I am finding ipdSummary to be pretty slow (~1 CPU minute per CCS read with ~1 million to process). 

Are there any parameters that could give me a speed up. For example is it known how it scales with coverage? Could I expect to speed things up significantly with "--maxCoverage" argument, and if so do you have any suggestions on the minimum coverage to call m6A (documentation seems to indicate 10x coverage per strand)? 

Thanks!
Mitchell

**Comment by pb-dseifert** [comment]
how are you running `ipdSummary`? via Bioconda? We currently don't support running base modifications analysis via Bioconda.

**Comment by mrvollger** [comment]
I am using it out of our install of SMRT Link v8.0.

**Comment by armintoepfer** [comment]
In that case, have you tried reaching out to PacBio's tech support? Give it a try!
