### ISSUE TITLE
Falcon njobs parameter not respected with SLURM sbatch

### ISSUE THREAD

**Issue by andreaminio** [PacificBiosciences/pbbioconda#281]
**Operating system**
SLUR based cluster

**Package name**
Falcon3

**Issue**
I'm trying to upgrade all my pipelines from the old pwatcher-based version to the new hosted on bioconda, mostly forced by the necessity to use it in combination with HiFi reads. However  i'm not able to set-up correctly the tool to work on our SLURM based cluster.
I was used to submit the main process/controller as a separate process by `sbatch` and let it control the submission of the subprocesses, run themselves with `sbatch` too, limiting the number of concurrent jobs. This allows me to have more flexibility in running (more) processes in a shared environment. 
I tried to setup my configuration in similar fashion for Falcon3, however:

- If in the  `submit` section I use `srun`, the maximum number of allowed processes is correctly used (`njobs`), but this limits the subprocesses to be "encapsulated" in the main sbatch process, limited accordingly in usable resources and not flexible as I'd need
- If in the  `submit` section I use `sbatch`, the main process submits to the queue the subprocesses that are allowed to run independently and keeps track of them as expected, however `njobs` seems to have no effect. Even if 2 concurrent jobs maximum are required, the main process keeps submitting new ones without limit apparently.

Here is my configuration file, what should I do to gain control over `sbatch` submitted subprocesses?
```
[General]
input_fofn = HiFi_preads.fofn
input_type = preads
length_cutoff = 10000
falcon_sense_skip_contained = TRUE
falcon_sense_option = --output_multi --min_idt 0.70 --min_cov 4 --max_n_read 400
length_cutoff_pr = 4500
pa_DBsplit_option = -x500
pa_daligner_option = -v -B128 -t30 -e0.7 -M60 -l1000 -k16 -h64 -w7 -s1000 -T16
ovlp_DBsplit_option = -x500
#ovlp_daligner_option = -mtan -mrep2 -t60 -k20 -h256 -e.9 -l1000 -s100 -T16 
ovlp_daligner_option = -t60 -k20 -h256 -e.9 -l1000 -s100 -T16
ovlp_HPCdaligner_option = -v -B128 -M60
# HiFi highly heterozygous
overlap_filtering_setting = --max_diff 100 --max_cov 400 --min_cov 3 --ignore-indels -e.95 --min-idt 95

[job.defaults]
job_type=slurm
pwatcher_type=blocking
JOB_QUEUE = bmm
mem = 1
NPROC = 1
njobs = 2
submit = sbatch -N 1 -p bmm -J ${JOB_NAME} -o ${JOB_STDOUT} -e ${JOB_STDERR} --mem ${mem}G -t 120:00:00 -c ${NPROC} ${JOB_SCRIPT}

[job.step.da]
NPROC=16
mem=41
[job.step.la]
NPROC=16
mem=51 
[job.step.cns]
NPROC=16
mem=61
[job.step.pda]
NPROC=16
mem=41
[job.step.pla]
NPROC=16
mem=51
[job.step.asm]
njobs = 1
NPROC = 32
mem   = 201
```

**Comment by andreaminio** [comment]
My bad, the issue is even worse. 
This happens when I run the script from within an interactive bash. So:

- if I open an interactive bash on a machine, and launch manually fc_run.py:
  - processes submitted to the cluster with srun are under control in number, but must be within the interactive bash resources constrain
  - processes submitted with sbatch are not limited by interactive bash resources but neither by njobs
- If I run the fc_run.py command within a script submitted with sbatch
  - Subprocesses submitted with srun fail. 
    - The environmental variable containing the executable script (${PYPEFLOW_JOB_START_SCRIPT}) is not passed to the child process even if the "run-P*.bash" executable is present. 
    - As the variable it is empty the file is not recognised, the child process starts the "wait-for-executable" procedure to see if the executable turns in.
    - As the script name is missing, the procedure will never be able to find it.
    - The script dies after timeout

If I run the fc_run.py command from the bash, the behaviour is what expected, child processes are submitted in the correct number and as separate processes with no restriction but under control. However I need to wrap the process into a script submittable to the queue system, I cannot run it freely on one of the control nodes.

Any idea?

**Comment by armintoepfer** [comment]
If you have HiFi data, please use our new HiFi assembler from bioconda `pbipa`
