### ISSUE TITLE
Report SV support read

### ISSUE THREAD

**Issue by jiadong324** [PacificBiosciences/pbbioconda#282]
Hi,

Is that possible for pbsv to report the SV support reads? I want to subsample BAM files.

Thanks!

**Comment by armintoepfer** [comment]
We'll consider this as a feature request.

**Comment by jiadong324** [comment]
@armintoepfer Thanks! That would be helpful to investigate certain SVs.

**Comment by liuyongming0612** [comment]
Is this request resolved?   it is a lot of convenience if we can get the sv support reads. I want to use pacbio CCS data to do SNP/indel calling and phasing, then use  sv support reads to phase SV genotype, it is possible if I get the sv support reads.

thanks a lot

**Comment by armintoepfer** [comment]
No it's not and it won't be in the next release.

**Comment by zeeev** [comment]
Hello,

I'm closing this issue because we cannot commit to providing this feature in a reasonable timeframe. If you'd like to continue this discussion please contact support@pacbio.com.
