### ISSUE TITLE
pbccs: how to determine strand orientation

### ISSUE THREAD

**Issue by zc312** [PacificBiosciences/pbbioconda#283]
**Package name**
pbccs 4.2.0

Hello. How does pbccs --by-strand sort reads into the forward and reverse buckets? Are strands sorted by comparing DNA insert sequences or does pbccs --by-strand simply split odd vs. even subreads?

Thank you!

**Comment by armintoepfer** [comment]
By picking one as forward reference and then perform alignment of all other subreads against it to determine if it matches or not.
