### ISSUE TITLE
pbmm2 -N

### ISSUE THREAD

**Issue by zc312** [PacificBiosciences/pbbioconda#286]
**pbmm2 1.2.0**

Hi,

1) If I set "-N 1," will this output just the 1 primary alignment and  
2) If I set "-N 2" will this output 1 primary alignment and 1 supplementary alignment? 
3) In the case of a chimeric alignment, how does pbmm2 decide which alignment is primary vs. supplementary? 

Thank you.

**Comment by armintoepfer** [comment]
By alignment score. This is rather an implementation detail of the underlying minimap2

**Comment by zc312** [comment]
Thank you! And, just to confirm, does pbmm2 only ever output one primary alignment? Will there ever be a case with >1 primary alignment?

**Comment by armintoepfer** [comment]
One primary.
