### ISSUE TITLE
pbmm2 sequence identity filters

### ISSUE THREAD

**Issue by zc312** [PacificBiosciences/pbbioconda#287]
**pbmm2 1.2.0**

Hi,
I saw on the Github that the default 70% --min-concordance-perc filter is "only appropriate if applied to resequencing data of haploid organisms." Do you have recommendations for which of the two remaining sequence identity filters (--min-id-perc and/or --min-gap-comp-id-perc) would be best for aligning human ccs reads (with short 1.5-3 kb dna inserts)? 

Thank you!

**Comment by armintoepfer** [comment]
Those are experimental and we can't give you any guidance yet. Once we switch over, you'll find more info on the GitHub documentation.
