### ISSUE TITLE
Depth inconsistency between pbsv VCF file and IGV.

### ISSUE THREAD

**Issue by kostasgalexiou** [PacificBiosciences/pbbioconda#292]
Hi,

I have used pbsv-2.3.0.0 in order to obtain SVs from CCS reads of 16 samples. Below are the commands that I have used:

`pbsv discover -r chr05:24500000-275000000 pbsv_out/$name/$name'_vsMelonv4.bam' 
 pbsv_out/$name/$name'.svsig.gz'; done`

`svsigs=(pbsv_out/*/*svsig.gz)`
`pbsv call --ccs ~/PacBio/Melon_v4.0_PacBio.fasta ${svsigs[@]} pbsv_out/SVs_pbsv.vcf`

When I check the SVs in IGV I see that I get an inflation of read depth in the viewer compared to the DP field in the FORMAT info of the VCF file. For example, for the insertion below:

`chr05	25307107	pbsv.INS.442	C	CTAGCATTGCTTTAAATTGGAAGGATTTTC	.	PASS	SVTYPE=INS;END=25307107;SVLEN=29	GT:AD:DP	1/1:1,38:39	0/0:13,0:13`

pbsv gives me depths of 39 and 13, respectively. But when I look for the insertion in IGV for these 2 samples it can be seen clearly that read depth is much higher (370 and 367, respectively).

![IGVsnapshot](https://user-images.githubusercontent.com/54025256/82029409-429c7780-9697-11ea-9c3d-22f6b6733dbe.png)

Any help will be appreciated.

Thanks,
Kostas

**Comment by armintoepfer** [comment]
Hi!

This makes total sense, because `pbsv discover` subsamples to avoid coverage explosion like you are observing. You can adjust those, have a look at `pbsv discover --help` in particular

```
Downsample Options:
  -w,--downsample-window-length   STR   Window in which to limit coverage, in basepairs. [10K]
  -a,--downsample-max-alignments  INT   Consider up to N alignments in a window; 0 means disabled. [20]
```

Armin

**Comment by kostasgalexiou** [comment]
Thanks for your rapid reply @armintoepfer! 

As long as this doesn't compromise the genotype assignment, I am OK with that.

Kostas
