### ISSUE TITLE
CCS on old RSII P5C3 data

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/pbbioconda#296]
Dear,

(repost after mailing to support, thanks Bas for pointing me to here)

I tries CCS old RSI reads (**at command line**) but the chemistry was not supported by the current pbccs.
I tried installing 3.4.1, 3.4.0 and even 3.3.0 and they all three return the same error

```
# 3.3.0 /// ccs run2_A01_1.subreads.bam run2_A01_1.ccs.bam
>|> 20200525 12:42:21.554 -|- FATAL      -|- Runner -|- 0x7f0d31d83740|| -|- unsupported sequencing chemistry combination:
    binding kit:        100256000
    sequencing kit:     100254800
    basecaller version: 2.1.0.0.127824
```

I think I need to add some jason definitions to have more chance with any version

I read the guidance info on the [dedicated page](https://github.com/PacificBiosciences/ccs/blob/develop/README.md) but still lack the necessary jason (+....?) to try more.

Could you please point me to the file lack now and maybe to some more detailed tutorial on how to proceed.

Thanks

**Comment by armintoepfer** [comment]
P5C3 is so old that it was not even supported by CCS when we started development 5 years ago. You have to use the original SMRT Analysis that came with the instrument. Nothing I can do here.
