### ISSUE TITLE
isoseq3 polish (v3.3.0) failing with segmentation fault

### ISSUE THREAD

**Issue by mollydawson** [PacificBiosciences/pbbioconda#297]
Hello, 

I am running isoseq3 (commit v3.3.0) polish w/ completely updated Conda environment but keep getting segmentation errors after about 35 seconds. I was able to successfully generate polished transcripts with a smaller dataset with the same isoseq3 version (3.3.0) but now I am having trouble. I have already gone through the earlier steps of the pipeline with no problems. 

Please let me know if you can help, thanks!

**Comment by armintoepfer** [comment]
Per our discussions via mail, you were lacking the auxiliary movie.bam.pbi files.
