### ISSUE TITLE
pbmm2 --cs tag request

### ISSUE THREAD

**Issue by zc312** [PacificBiosciences/pbbioconda#299]
Hi,

Would it be possible to add an equivalent of minimap2's [--cs tag](https://github.com/lh3/minimap2#cs) (which encodes bases at mismatches and INDELs) to pbmm2?

**Comment by armintoepfer** [comment]
Yes, it's possible. As pbmm2 is fully open source, feel free to issue a pull request and I'll merge this feature.

**Comment by zc312** [comment]
Thank you very much! I'm not sure how do this code change -- would it be possible for the cs tag to be included in the next update?

**Comment by pb-dseifert** [comment]
Unfortunately no, we do not have the resources for that at the moment.
