### ISSUE TITLE
pbccs --by-strand chunking

### ISSUE THREAD

**Issue by zc312** [PacificBiosciences/pbbioconda#300]
I am running pbccs --by-strand (v 4.2.0) and wish to chunk. Will consensus reads belonging to a particular ZMW always be grouped in the same chunk or is it possible that, for example, the forward consensus sequence of ZMW A is in chunk 1 and the reverse consensus sequence of ZMW A is in chunk 2?

**Comment by armintoepfer** [comment]
The atomic unit of chunking is a ZMW.
