### ISSUE TITLE
help required to create correct fc_run.cfg

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/pbbioconda#302]
Dear,

I am trying to assemble my genome using conda and old RSII reads not supported in the current SMRTLink  (and I cannot install older versions of SL) but I read the pages about using https://github.com/PacificBiosciences/pb-assembly and tried to create my own config file with as result that I crashed my server by memory overflow.

Could someone please help me fix my mistake and produce a standard file for a genome of 1G in local mode with 88 threads and 512GB RAM.

I started from the human file and very likely this was designed for a much larger cluster (and queuing system) than my 88 threads 512GB RAM machine. I adapted the conf as I could to work in local but did not find info on how to adapt the blocks at the bottom of the original file which I think are the killers.

Thanks in advance for your help.

[fc_run.cfg.txt](https://github.com/PacificBiosciences/pbbioconda/files/4716025/fc_run.cfg.txt)

**Comment by pb-dseifert** [comment]
Sorry, all RS support also isn't supported in PB-provided bioconda utilities. We recommend contacting Tech Support for figuring out a solution for installing older versions of SL.

**Comment by splaisan** [comment]
Thanks David, this is sad as I cannot install an old SL on that server.
Afraid I have to stop working ion that data using PB tools.

**Comment by armintoepfer** [comment]
Bioconda utilities are for Sequel I and II. If you have very old data, you have to either use the corresponding tools that shipped with it or use any of the publicly available assemblers.
