### ISSUE TITLE
issue with conda env for pbipa

### ISSUE THREAD

**Issue by aclum** [PacificBiosciences/pbbioconda#305]
When I run  conda install pbipa it is giving me trouble with appdirs
failed
ERROR conda.core.link:_execute(481): An error occurred while installing package 'conda-forge::appdirs-1.4.3-py_1'.
OSError(2, 'No such file or directory')
Attempting to roll back.

Rolling back transaction: done

OSError(2, 'No such file or directory')

**Comment by armintoepfer** [comment]
Did you start from a clean conda environment?

**Comment by aclum** [comment]
Yes. This is a brand new env. I'm not sure what the issue is. When I tried to install this as a bundle, either with pbipa or appdirs I had errors but when I download the appdirs dependencies individually and then retry the install it completes without a problem. So I've got it installed now.

**Comment by pb-cdunn** [comment]
> but when I download the appdirs dependencies individually and then retry the install it completes without a problem. So I've got it installed now.

Good. My guess is that this relates to python version problems. When Bioconda gets up-to-date **pysam** and up-to-date **htslib** in both py3.7 and py3.8, we should be able to resolve those. For now, we have a lot of version-pinning that might be causing this.
