### ISSUE TITLE
Unable to initialize environment because of error: cannot register event client

### ISSUE THREAD

**Issue by bbrunet** [PacificBiosciences/pbbioconda#306]
Wondering if someone can help me figure out how to resolve this issue. I successfully ran falcon-unzip only 3 months ago using the same script, but for some reason it is now giving me the following error:

>>>>
Unable to initialize environment because of error: cannot register event client. Only 950 event clients are allowed in the system
Exiting.
<<<<

I'm running falcon-unzip with the sync option in SGE mode.

Thanks,
Bryan

**Comment by bbrunet** [comment]
FYI - here is the config file, the run script and logs from a recent run that produced this error. Note I am still not able to get this assembly run to complete without the error occuring.

[all.log](https://github.com/PacificBiosciences/pbbioconda/files/4898540/all.log)
[fc_run_aco.cfg.txt](https://github.com/PacificBiosciences/pbbioconda/files/4898541/fc_run_aco.cfg.txt)
[pb_aco_sge.sh.txt](https://github.com/PacificBiosciences/pbbioconda/files/4898542/pb_aco_sge.sh.txt)
[run0.log](https://github.com/PacificBiosciences/pbbioconda/files/4898543/run0.log)

**Comment by pb-cdunn** [comment]
This relates to your SGE setup. I don't think we will be able to help you. Falcon definitely can be configured to use a fairly small number of simultaneous remote jobs (job "concurrency" in falcon config), if you're hitting a resource limit.

https://smrt-analysis.readthedocs.io/en/latest/When-using-the-sync-option-in-SGE,-you-may-see-errors/
