### ISSUE TITLE
pbmarkdup sources

### ISSUE THREAD

**Issue by tahashmi** [PacificBiosciences/pbbioconda#308]
Hi all,

I am working on Spark-based implementation of long reads alignments, sorting, and mark duplicate tools. I am not able to see https://github.com/PacificBiosciences/pbmarkdup sources. Can someone help where I can find PacBio pbmarkdup implementation? Thanks.

**Comment by armintoepfer** [comment]
Hi there!

The implementation is closed source. Finding duplicates is no magic, there are just a few tricks how to improve run time.

Armin
