### ISSUE TITLE
Improved Phased Assembler failing at ovl_filt

### ISSUE THREAD

**Issue by nblouin** [PacificBiosciences/pbbioconda#309]
Hi there-

I am attempting to use IPA on our RHEL 7.6 HPC and Slurm.
As a test, I have used an RSII dataset I have laying around.

**Package name**

┌─[09:49:25]─[nblouin@tlog2]─[~/scratch/ModuleTests/IPA]
└──> ipa --version
ipa (wrapper) version=1.0.3

'''
**Describe the bug**
All appears to be running OK up to the point of ovl_filt where I get a warning:
"Bad value: "--max-diff" for option "max-cov"; expecting int" and then:
"Error in rule ovl_filter".

From looking at the call (portion of the out file pasted below)  it appears the pipeline is setting a value for _--max-diff_ and _--max-cov_ twice in the same call and that I do not have control over that step. Any advice would be great.

**Error message**
...
....
Computed maximum allowed coverage: 
+ ln -sf ../phasing_merge/ovl.phased.m4 .
++ basename ../phasing_merge/ovl.phased.m4
+ local local_m4=ovl.phased.m4
+ IPA_TIME log.ovl_filter.m4filt.memtime falconc m4filt --n-proc 16 --in ovl.phased.m4 --out ovl.chimerfilt.m4 --keepIntermediates --max-diff 80 --max-cov 100 --min-cov 2 --bestn 10 --min-len 4000 --gapFilt --minDepth 4 --idt-stage2 98 --max-cov --max-diff --filter-log m4-readfilt.log
+ local local_out_memtime=log.ovl_filter.m4filt.memtime
+ shift
+ [[ Linux == Linux ]]
**+ /usr/bin/time '--format=cmd: %C\nreal_time: %e s\nuser_time: %U s\nsys_time: %S s\nmax_rss: %M kB\nexit_status: %x' -o log.ovl_filter.m4filt.memtime falconc m4filt --n-proc 16 --in ovl.phased.m4 --out ovl.chimerfilt.m4 --keepIntermediates --max-diff 80 --max-cov 100 --min-cov 2 --bestn 10 --min-len 4000 --gapFilt --minDepth 4 --idt-stage2 98 --max-cov --max-diff --filter-log m4-readfilt.log**
Bad value: "--max-diff" for option "max-cov"; expecting int
m4filt [required&optional-params] 
Run the multi-stage m4 overlap filter (for HiFi Asm). Take only one m4 file,
inFn. If in+'.idx' exists, that is the index. In stage one, reads that trigger a
filter are marked including containment, gaps in coverage along the A-read, and
repeat reads. In stage two the filters are applied and the N-best overlaps are
kept for the 5prime and 3prime of each read.
Options:
  -h, --help                                 print this cligen-erated help
  --help-syntax                              advanced: prepend,plurals,..
  -i=, --idt-stage1=       float   90.0      Stage one percent identity filter,
                                             formatted as percentage, overlaps <
                                             %idt are skipped
  --idt-stage2=            float   90.0      Stage two percent identify filter
  -m=, --min-len=          int     6000      Minimum read length, reads shorter
                                             than minLen will be discarded
  --min-cov=               int     2         Minimum number of overlaps on
                                             either side of a read
  --max-cov=               int     200       Maximum number of overlaps on
                                             either side of a read
  --max-diff=              int     100       Reads are skipped is abs(5p-3p)
                                             overlap counts > maxDiff
  -b=, --bestn=            int     10        Keep N best overlaps at 5prime AND
                                             3prime of a read
  --min-overhang=          int     0         Minimum amount of overhang bases in
                                             an overlap to keep the overlap
  --min-depth=             int     2         Depths lower than minDepth are
                                             considered gaps
  -g, --gap-filt           bool    false     Run depth filter, takes a little
                                             more time
  -k, --keepIntermediates  bool    false     set keepIntermediates
  -n=, --n-proc=           int     24        Number of processes to run locally
  --in-fn=                 string  REQUIRED  M4 overlaps file
  -f=, --filter-log-fn=    string  REQUIRED  Write read filter stats to this
                                             file
  -o=, --out-fn=           string  REQUIRED  Final m4 overlaps file
0.04user 0.04system 0:00.09elapsed 91%CPU (0avgtext+0avgdata 6940maxresident)k
0inputs+0outputs (0major+8778minor)pagefaults 0swaps
[Fri Jun 26 10:20:36 2020]
Error in rule ovl_filter:
    jobid: 7
    output: ovl_filter/ovl.final.m4, ovl_filter/ovl.chimerfilt.m4
    shell:
        
        wd=$(dirname ovl_filter/ovl.final.m4)
        mkdir -p $wd
        cd $wd
        rel=..

        input_m4="$rel/phasing_merge/ovl.phased.m4"         output_m4_final=$(basename ovl_filter/ovl.final.m4)         output_m4_chimerfilt=$(basename ovl_filter/ovl.chimerfilt.m4)         params_num_threads=16         params_config_sh_fn="$rel/generate_config/generated.config"         params_log_level="INFO"         params_tmp_dir="/tmp"             time ipa2-task ovl_filter
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /pfs/tsfs1/gscratch/nblouin/ModuleTests/IPA/GORYtester/.snakemake/log/2020-06-26T095853.691230.snakemake.log
CWD:/pfs/tsfs1/gscratch/nblouin/ModuleTests/IPA/GORYtester
NPROC:16
NPROC_SERIAL:16
config:{'advanced_options': '', 'coverage': 0, 'genome_size': 0, 'max_nchunks': 40, 'nproc': 16, 'phase_run': 1, 'polish_run': 1, 'reads_fn': 'GORYtester/input.fofn', 'tmp_dir': '/tmp'}
Done

**To Reproduce**

Here is how I am running IPA:

**#!/bin/bash
#SBATCH --job-name t-IPA
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=0
#SBATCH --time=108:00:00

#SBATCH -D /gscratch/nblouin/ModuleTests/IPA

echo "SLURM_JOB_ID:" $SLURM_JOB_ID
echo "SLURM_JOB_NAME:" $SLURM_JOB_NAME
echo "SLURM_JOB_PARTITION" $SLURM_JOB_PARTITION
echo "SLURM_JOB_NUM_NODES:" $SLURM_JOB_NUM_NODES
echo "SLURM_JOB_NODELIST:" $SLURM_JOB_NODELIST
echo "SLURM_JOB_CPUS_PER_NODE:" $SLURM_JOB_CPUS_PER_NODE
echo "SLURM_TASKS_PER_NODE:" $SLURM_TASKS_PER_NODE
echo "SLURM_CPUS_PER_TASK:" $SLURM_CPUS_PER_TASK
echo "SLURM_CPUS_ON_NODE:" $SLURM_CPUS_ON_NODE

echo "Starting"

module load  singularity/2.5.2 ipa

echo "Modules loaded:"
echo "Starting IPA"

srun ipa local --verbose --run-dir GORYtester --nthreads 16 --njobs 1 \
-i XNBUW_20181115_S54024R1_PL100107678-1_C01.subreads.fastq.gz \
-i XNBUW_20181115_S54024R1_PL100107678-1_B01.subreads.fastq.gz 

echo "Done**

**Expected behavior**

**Comment by zeeev** [comment]
I'm guessing this call failed:

falconc ovl-cov-stats --in-fn=ovl.fofn

can you check the content of 

covstat.json in the same folder.

**Comment by nblouin** [comment]
Thanks for the reply.
Let me know if you need to peek at any other files.
Here you go:

┌─[14:22:03]─[nblouin@tlog2]─[~/scratch/ModuleTests/IPA]
└──> cat !$
cat GORYtester/ovl_filter/covstat.json
{
    "mean": 0.0,
    "std": nan,
    "median": 0.0,
    "min": 0,
    "max": 0,
    "n": 0
}

**Comment by isovic** [comment]
Hi @nblouin,
I assume your RSII dataset is CLR and not >Q20 CCS (i.e. HiFi)?
IPA is intended for HiFi reads of very high accuracy, so CLR would not work with it.

Best regards,
Ivan.

**Comment by nblouin** [comment]
Hi Ivan-
My mistake. I thought this test set was HiFi (I only looked at the run time and assumed it was not a CLR library as it ran for 30 hrs).
I have now tested my installation  with a known HiFi set of reads and it ran without a hitch.
Thanks for the help and apologies for the rookie error.

┌─[10:55:57]─[✗:5]─[nblouin@tlog2]─[~/scratch/ModuleTests/IPA/SRR11606869Tester]
└──> tail /pfs/tsfs1/gscratch/nblouin/ModuleTests/IPA/SRR11606869Tester/.snakemake/log/2020-06-30T091952.143514.snakemake.log
[Tue Jun 30 18:53:08 2020]
localrule finish:
    input: final/final.p_ctg.fasta, final/final.a_ctg.fasta
    jobid: 0
    reason: Input files updated by another job: final/final.p_ctg.fasta, final/final.a_ctg.fasta

[Tue Jun 30 18:53:08 2020]
Finished job 0.
52 of 52 steps (100%) done
Complete log: /pfs/tsfs1/gscratch/nblouin/ModuleTests/IPA/SRR11606869Tester/.snakemake/log/2020-06-30T091952.143514.snakemake.log

**Comment by pb-cdunn** [comment]
Thanks for posting. We should fail early on CLR input.
