### ISSUE TITLE
pb-assembly UnsatisfiableError

### ISSUE THREAD

**Issue by jellila** [PacificBiosciences/pbbioconda#311]
Hello.
I am trying to download pb-assembly through miniconda on Mac but I keep getting the same error. This is what I do:

(base) BIOL-15QJ1GC:~ Laura$ conda create -n pb
Collecting package metadata (current_repodata.json): done
Solving environment: done

 Package Plan 

  environment location: /Users/Laura/opt/miniconda3/envs/pb

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

 To activate this environment, use

     $ conda activate pb

 To deactivate an active environment, use

   $ conda deactivate

(base) BIOL-15QJ1GC:~ Laura$ conda activate pb
(pb) BIOL-15QJ1GC:~ Laura$ conda install pb-assembly
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: 

I also tried to "git clone" the package in the environment. Although it seems to work in the terminal, when I open the folder in Finder there is nothing in it.

I have also tried to install pb-assembly in environments with different versions of python but then this is what I get:

(base) BIOL-15QJ1GC:~ Laura$ conda install -n pb pb-assembly
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Could anyone please help me?

Thank you!

Cheers,

Laura

**Comment by armintoepfer** [comment]
It's not supported on MacOS.
