### ISSUE TITLE
gcpp exits silently with status 1 and no output.

### ISSUE THREAD

**Issue by mchaisso** [PacificBiosciences/pbbioconda#312]
**Operating system**
Centos

**Package name**
>gcpp --version
gcpp 1.9.0-SL-release-8.0.0+1-37-gd7b188d

**Conda environment**

# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
aioeasywebdav             2.4.0                 py37_1000    conda-forge
aiohttp                   3.6.2            py37h516909a_0    conda-forge
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.12                   py37_1  
appdirs                   1.4.3                      py_1    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcftools                  1.9                  h68d8f2e_9    bioconda
bcrypt                    3.1.7            py37h8f50634_1    conda-forge
beautifulsoup4            4.9.1            py37hc8dfbb8_0    conda-forge
bedops                    2.4.39               hc9558a2_0    bioconda
bedtools                  2.29.2               hc088bd4_0    bioconda
binutils                  2.34                 h53a641e_0    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_5    conda-forge
bioawk                    1.0                  hed695b0_5    bioconda
biopython                 1.76             py37h516909a_0    conda-forge
blasr                     5.3.3                h018d624_2    bioconda
blast                     2.5.0                hc0b0e79_3    bioconda
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
boost                     1.73.0           py37h429e714_0    conda-forge
boost-cpp                 1.73.0               h6c875cf_0    conda-forge
boto3                     1.14.1             pyh9f0ad1d_0    conda-forge
botocore                  1.17.1             pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bwa                       0.7.17               hed695b0_7    bioconda
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cachetools                4.1.0                      py_1    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
circos                    0.69.8                        0    bioconda
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloog                     0.18.0                        0    anaconda
clustalw                  2.1                  hc9558a2_5    bioconda
clyent                    1.2.2                      py_1    conda-forge
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-build               3.19.2           py37hc8dfbb8_1    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-package-handling    1.6.0            py37h8f50634_2    conda-forge
conda-verify              3.1.1           py37hc8dfbb8_1001    conda-forge
configargparse            1.2.3              pyh9f0ad1d_0    conda-forge
crc32c                    2.0              py37h516909a_0    conda-forge
cryptography              2.9.2            py37hb09aad4_0    conda-forge
curl                      7.69.1               h33f0ec9_0    conda-forge
datrie                    0.8.2            py37h8f50634_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
docutils                  0.15.2                   py37_0    conda-forge
dropbox                   10.1.1             pyh9f0ad1d_0    conda-forge
entrez-direct             13.3            pl526h375a9b1_0    bioconda
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
falcon-kit                1.8.1                    pypi_0    pypi
falcon-phase              1.2.0                    pypi_0    pypi
falcon-unzip              1.3.7                    pypi_0    pypi
fftw                      3.3.8           mpi_mpich_h3f9e1be_1010    conda-forge
filechunkio               1.8                        py_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
flye                      2.7.1            py37he513fc3_0    bioconda
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freebayes                 1.3.2            py37hc088bd4_0    bioconda
freetype                  2.10.2               he06d7ca_0    conda-forge
ftputil                   3.4                        py_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
gcc                       4.8.5                         7    anaconda
gdk-pixbuf                2.36.12           h3f25603_1005    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
ghostscript               9.22              hf484d3e_1001    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.3                      py_0    conda-forge
glib                      2.64.3               h6f030ca_0    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
gobject-introspection     1.64.1           py37h619baee_1    conda-forge
google-api-core           1.20.0                   pypi_0    pypi
google-auth               1.16.1                   pypi_0    pypi
google-cloud-core         1.3.0                      py_0    conda-forge
google-cloud-storage      1.28.1             pyh9f0ad1d_0    conda-forge
google-resumable-media    0.5.1              pyh9f0ad1d_0    conda-forge
googleapis-common-protos  1.52.0                   pypi_0    pypi
graphite2                 1.3.13            he1b5a44_1001    conda-forge
graphmap                  0.6.3                he513fc3_0    bioconda
graphviz                  2.38.0            hf68f40c_1011    conda-forge
gsl                       2.5                  h294904e_1    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
imagemagick               7.0.8_54        pl526h39023e4_0    conda-forge
importlib-metadata        1.6.1            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.1                         0    conda-forge
ipykernel                 5.3.0            py37h43977f1_0    conda-forge
ipython                   7.15.0           py37hc8dfbb8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isl                       0.12.2                        0    anaconda
jbig                      2.1               h516909a_2002    conda-forge
jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json5                     0.9.4              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
jupyterlab                2.1.4                      py_0    conda-forge
jupyterlab_server         1.1.5                      py_0    conda-forge
krb5                      1.17.1               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libarchive                3.3.3             h3a8160c_1008    conda-forge
libblas                   3.8.0               11_openblas    conda-forge
libcblas                  3.8.0               11_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcroco                  0.6.13               h8d621e5_1    conda-forge
libcurl                   7.69.1               hf7181ac_0    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         h46ee950_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgd                     2.2.5             h307a58e_1007    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               11_openblas    conda-forge
liblief                   0.9.0                hf8a498c_1    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libopenblas               0.3.6                h6e990d7_6    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libprotobuf               3.12.3               h8b12597_0    conda-forge
librsvg                   2.44.14              h11c8777_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.9.0                hab1572f_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                hf4e8a37_4    conda-forge
libwebp-base              1.1.0                         2    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
libxslt                   1.1.33               h31b3aaa_0    conda-forge
longshot                  0.4.1                h80880c6_0    bioconda
lz4-c                     1.9.2                he1b5a44_1    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
meme                      4.11.2          py37pl526h3eee39e_5    bioconda
minimap2                  2.17                 h8b12597_1    bioconda
mistune                   0.8.4           py37h8f50634_1001    conda-forge
mpc                       1.1.0             h04dde30_1006    conda-forge
mpfr                      4.0.2                he80fd80_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.3.2                hc856adb_0    conda-forge
multidict                 4.7.5            py37h8f50634_1    conda-forge
mummer                    3.23            pl526he1b5a44_11    bioconda
mummer4                   4.0.0beta2      pl526he1b5a44_5    bioconda
mysql-connector-c         6.1.11            h876a3cc_1006    conda-forge
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
ncbi-ngs-sdk              2.10.4               hdf6179e_0    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
nettle                    3.3                           0    conda-forge
networkx                  2.4                        py_1    conda-forge
nim-falcon                1.3.0                h1341992_0    bioconda
notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.18.1           py37h8960a57_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.6                h6e990d7_6    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
ossuuid                   1.6.2             hf484d3e_1000    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.0.4            py37h0da4684_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14           he7ab937_1005    conda-forge
parallel                  20200522                      0    conda-forge
paramiko                  2.7.1                    py37_0    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
patchelf                  0.11                 he1b5a44_0    conda-forge
pb-assembly               0.0.8                         0    bioconda
pb-dazzler                0.0.1                h516909a_0    bioconda
pb-falcon                 2.2.4            py37hed50d52_0    bioconda
pb-falcon-phase           0.1.0                h3889886_0    bioconda
pbbam                     1.0.7                h8e3dc82_0    bioconda
pbgcpp                    1.9.0                         0    bioconda
pbmm2                     1.3.0                h56fc30b_0    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-autoloader           5.74                    pl526_2    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-cgi                  4.44            pl526h14c3975_1    bioconda
perl-clone                0.42            pl526h516909a_0    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-config-general       2.63                    pl526_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-digest-perl-md5      1.9                     pl526_1    bioconda
perl-dynaloader           1.25                    pl526_1    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-font-ttf             1.06                    pl526_0    bioconda
perl-gd                   2.71            pl526he860b03_0    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-template        2.97                    pl526_1    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-string            1.08                    pl526_3    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-math-bezier          0.01                    pl526_1    bioconda
perl-math-round           0.07                    pl526_1    bioconda
perl-math-vecstat         0.08                    pl526_1    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-module-implementation 0.09                    pl526_2    bioconda
perl-module-runtime       0.016                   pl526_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-number-format        1.75                    pl526_3    bioconda
perl-params-validate      1.29            pl526h14c3975_1    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-readonly             2.05                    pl526_0    bioconda
perl-regexp-common        2017060201              pl526_0    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-set-intspan          1.19                    pl526_1    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-statistics-basic     1.6611                  pl526_2    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-svg                  2.84                    pl526_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-text-format          0.59                    pl526_2    bioconda
perl-text-soundex         3.05                 pl526_1000    conda-forge
perl-time-hires           1.9760          pl526h14c3975_1    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-libxml           2.0132          pl526h7ec2d77_1    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526ha1d75be_1002    conda-forge
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.1.2            py37h718be6c_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkg-config                0.29.2            h516909a_1006    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
plink                     1.90b6.12            heea4ae3_0    bioconda
prettytable               0.7.2                      py_3    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
protobuf                  3.12.2                   pypi_0    pypi
psutil                    5.7.0            py37h8f50634_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-lief                   0.9.0            py37he1b5a44_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                    pypi_0    pypi
pycosat                   0.6.3           py37h8f50634_1004    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyfaidx                   0.5.8                      py_1    bioconda
pygments                  2.6.1                      py_0    conda-forge
pygraphviz                1.5             py37h8f50634_1002    conda-forge
pynacl                    1.3.0           py37h516909a_1001    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py37h8685d9f_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py37h8f50634_0    conda-forge
pysam                     0.16.0           py37ha9a96c6_0    bioconda
pysftp                    0.2.9                      py_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h8356626_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-edlib              1.3.8.post1      py37h99015e2_1    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-irodsclient        0.8.2                      py_0    conda-forge
python-libarchive-c       2.9                      py37_0    conda-forge
python-msgpack            0.6.1            py37h99015e2_2    bioconda
python-sortedcontainers   2.2.2              pyh9f0ad1d_0    bioconda
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyvcf                     0.6.8           py37hc8dfbb8_1001    conda-forge
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
pyzmq                     19.0.1           py37hac76be4_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
racon                     1.4.13               he513fc3_0    bioconda
ratelimiter               1.2.0           py37hc8dfbb8_1001    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
regtools                  0.6.0                he513fc3_0    bioconda
requests                  2.23.0             pyh8c360ce_2    conda-forge
ripgrep                   12.1.1               h516909a_0    conda-forge
rmblast                   2.9.0                h2d02072_0    bioconda
rsa                       4.6                pyh9f0ad1d_0    conda-forge
ruamel_yaml               0.15.80         py37h8f50634_1001    conda-forge
s3transfer                0.3.3            py37hc8dfbb8_1    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
send2trash                1.5.0                      py_0    conda-forge
setuptools                47.1.1           py37hc8dfbb8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
snakemake                 5.7.4                         0    bioconda
snakemake-minimal         5.7.4                      py_0    bioconda
soupsieve                 2.0.1            py37hc8dfbb8_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
sra-tools                 2.10.7          pl526haddd2b5_1    bioconda
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.46.1             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
ucsc-bigbedtobed          357                           1    bioconda
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
vcftools                  0.1.16               he860b03_3    bioconda
wcwidth                   0.2.4              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
whatshap                  0.18             py37h6bb024c_0    bioconda
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py37_0    conda-forge
wrapt                     1.12.1           py37h8f50634_1    conda-forge
xmlrunner                 1.7.7                      py_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xopen                     0.9.0            py37hc8dfbb8_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.3.0           py37h516909a_1000    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h6597ccf_3    conda-forge

**Describe the bug**
I am running gcpp on a bam from partitioned reads, so I manually generated the bam with a special pipeline. It runs on quite a few bams/files, but one bam it just ends with status 1, with no error message and no output. When I run with debug logging, the output is:
gcpp /panfs/qcb-panasas/mchaisso/NA12878/chr2.2.assembly.fasta.bam -j 16 -r /panfs/qcb-panasas/mchaisso/NA12878/chr2.2.raw_assembly.fasta -o chr2.2.assembly.consensus.fasta  --log-level DEBUG

>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_99:[0-281761)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_97:[0-914710)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_95:[0-1367172)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_949:[0-81918)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_948:[0-130798)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_944:[0-152626)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_943:[0-535605)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_942:[0-390363)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_94:[0-1239891)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_939:[0-376961)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_938:[0-106371)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_937:[0-84803)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_934:[0-169785)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_931:[0-181855)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_930:[0-83775)
>|> 20200706 18:18:07.866 -|- INFO -|- ParseFilterWindows -|- 0x7fa1c4933780|| -|- Running consensus on contig_93:[0-1173967)

**Error message**
No error.

**To Reproduce**
I'm mainly looking for something to look for to help debug, since no output is produced.

**Expected behavior**
Consensus would be produced.

**Comment by pb-dseifert** [comment]
Hi @mchaisso 
thanks for reporting this. Would you be willing to share your data? All data shared with PacBio is treated strictly confidentially, and this makes debugging (and fixing) a lot easier for us.

**Comment by mchaisso** [comment]
Yes, how do I upload?

**Comment by mchaisso** [comment]
I ran outside conda, and got the error:
    binding kit:        100372700
    sequencing kit:     100612400
    basecaller version: 2.3.0.3.154799
Is it possible to map this with gcpp or do I have to track down an old
arrow?

**Comment by pb-dseifert** [comment]
@mchaisso are you trying to polish RSII data?

**Comment by mhsieh** [comment]
@mchaisso Hi Mark, this is MJ, regarding the file sharing, can you use our portal and share with ? Just press dropoff and share with dseifert 's pacb email. Please let me know if you see any issue with this sharing method.

**Comment by mchaisso** [comment]
yes -- I didn't realize how old the data was, is it possible to still use
gcpp?

**Comment by pb-dseifert** [comment]
nope, RSII has been removed long ago. If you're lucky, you might be able to fish some old version out of the bioconda archives, but we can't support RSII anymore at this point.
