### ISSUE TITLE
pbreport

### ISSUE THREAD

**Issue by nservant** [PacificBiosciences/pbbioconda#313]
Hi there,
Any chance to provide the `pbreport` package in bioconda ?
Many thanks
Nicolas

**Comment by armintoepfer** [comment]
Hi Nicolas,

Thank you for reaching out. At this point in time, there are no plans to deploy `pbreports` to bioconda.
Alternatively, you can only install SMRT tools via the SMRT Link installer. Give that a try.

Armin
