### ISSUE TITLE
Quick question regarding QV

### ISSUE THREAD

**Issue by shaniAmare** [PacificBiosciences/pbbioconda#319]
Hi,

I was wondering whether the QV values are not generated by the latest version of `ccs`?

I ran the following on my `rsII subreads`:
`ccs ${BAM} ${OUT_DIR}/ccs.bam --min-rq 0.95 --num-threads 0 --log-level DEBUG --log-file ${OUT_DIR}/process.log`

While exploring the data I tried using the tool [LongQC ](https://github.com/yfukasawa/LongQC) to generate the QV plots similar to the ones described in the repo, but I get an empty plot. I have double checked and can confirm that LongQC actually works on the data (it has generated some other plots in the process and plotted the QV plot for data from other technologies).

I'm just wondering whether I see this "empty" QV plot for my ccs.bam because the QV are actually 0? I saw [this post](https://github.com/PacificBiosciences/IsoSeq_SA3nUP/issues/5#issuecomment-299599575) which implies no polishing results in 0 QV, and in an IsoSeq3 upgrade I saw that [**polish dropped support from RSII** ](https://github.com/PacificBiosciences/IsoSeq).

Am I connecting the dots right here? Or am I a lot more confused? :D 

If above is not sufficient information for you to make an informed decision, I am happy to provide more info.

Many thanks,
Shani.

**Comment by YibiChen** [comment]
Hi Shani,

I think LongQC is to get QVs from the subreads.bam (the one for raw reads), not the ccs.bam. In fact, if you enabled polishing in `ccs` (which is the default in the the lastest version), it would calculate QV values and write them into the bam file. Here is an example line from my ccs.bam file:
`
m64123_200501_095314/2/ccs      4       *       0       255     *       *       0       0       GCAATGAAGTCGCAGGGTTGGGGGAGGTGAAAAGTGAAGAGCAGACCATTCTGGCCCTGCACATGGGCCACGATTCCAGCATCGCCATCACCCGCAACGGCCGCGTGCAGTGCATTTTGGAACTGGAGCGGCTGTTTGAAGTCCGCTACTTTGCTCCTCCGGTGAAGGACTGGACGAAGTTTCGAAAGGATTGGACCCATGCACTGAAGACGGTGCAGCGGAGGTGTGTTTGTGAGGATGGATGGATACCTTCCCACTTCACGGATGCCGTATTGCTCTTCCCTGGCTTTGCACAAGAGCAATTCATTTTGATCCATCTGGCGGAGAAAGTCTTTAGCATTGACAGATGGCACTACTGCGACCATCACCAGGCCCATGCGTTGGCAGCGTACTATTCATCACCCTTCCGGTCTGCTCTCGTGGTGTCCTACGATTCGACCGGCAACGATGGTACCTTCAATGTCTATCTGGGTTCCTTTGACAAAATGCAGAGGATCGCACAACTGGACTACAGTTTGGGCAGTGCCTATGAACAGCTGGCCACTCTCTTGCCCGAGGTTACCGGGTCTCCCCTTGAGGCCTTTTTTGATTGTGACCAGATCAATGTCACTGAAGTTAGTGAGGTTGGCGAGATGGTTGGCCCACACACCCTCTACTTCACGACGCATTCATCTTTGCCCTGGGCCGGGAAGTTGATGGGATATGCCGCAATCGCGGAACCCATCGAAGATCTTCGGCCCTTGGTGCGTTTCTACCTGGAAGTCTCTGGAAGCCCAGGGCATGGCAATTATCCCGCGCCGCTGCTGCGTGCAGCTTGTGAATCCGTGGAAGGTCAACGTGCTTTGGGTGCCACCATCCAGTTGGAGTTTGAGAATTTTGTGGAAGAGCGAGTCAAAGCTCTTCTGGAGCATGTGGGTCACCAGGAGGTTGAGGGTATTGCCCTCACAGGCGGCTGTGCTCTGAACGTCCTGGCAAATCAACGCATCTACGACTTGGTCACCAATGGCTCGTCCGGTTCGGCCGGTTCAGTGTTGGATGTCTATGTGCCACCTGCACCCAATGACAGCGGACTGAGCTTAGGGGCCACCTGGTCCGTAGCACCTCCAAAGGTGCGACAACCGCTGCAATACCTGGGCTTTCCCTTATGGGATGAAGGCAGGTTGCTACGATATGCCAGAAACAGAGGTGCGAAGCGTCTCTCGAGCCTGGGAGGGGTGGAATACTTGGCCGATTTGTTGGCTGGAGGTGATCCCTGGCTCAGGCAGCGCAATAGTAGTGCTGAGAAGCCGATTGTGGCCGTGGTGCGAGGTCGCCAGGAATTTGGTCCGCGGGCCCTGGGGCATCGCTCCTTATTGGCGGTCCCGGACAGCCACCAGATGCGCGAGCGCATGAATCGTCTCAAGGCACGACAGTGGTACCGCCCCGTGGCGCCCATGATCGCTGAGGAAGCGCTGGGACAGGTCTTTGGTCGTCATGTCTCGTCCCCATTCATGACCATGGCCCCCCAGGTGTTGCCCGAGACCCGTCGCAGCTTCCCGGCGCTTTCCCATTTGGACGGCACGGCGCGGCATCAGTCGGTGGCACGGACGGAAGAGCCCTGGATCCATGCCCTGCTGATGGCGGTGGGGAAGCGAACGGGCTTGGCTGCACTCATCAACACGAGCTTCAACACCAAGGGCAAACCCATCGTAAACAAAATAAGCGAATGTTTGAGCATGTTGGACGATTTGCCTGACTTGGACTTTGTCGTCATCGAAGATTGGATCTTCCGCAAGCGCAACGTGGGAGGGCAGCGCCCCTGGTGATCGGCTGTGGGAAGCCACGGGATGATCGGATGGCGGAATGGACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGTACTCTGCGTTGATACCACTGCTT    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~>~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    RG:Z:8cd60e10   ec:f:69.7       np:i:69 rq:f:0.999999   sn:B:f,12.719,19.1996,4.32744,7.87167   zm:i:2

`

However, there is no explaination about the scale of these QV values. I assume they are using the same format as Sanger (Phred+33), which is suggested by the stardard practice of SAM/BAM format (see http://samtools.github.io/hts-specs/SAMv1.pdf). If this is true, then for this sequence, I have Phred quality score range from 29(>) to 93 (~).  I hope the developer can make the point more clear.

Cheers,
Yibi

**Comment by armintoepfer** [comment]
Hi all,

1. Reads in the subreads.bam have no meaningful per-base QVs as they are filled via a placeholder `!`.
2. CCS reads, generated by CCS, have per-base QVs in Phred Scale, per SAM spec.

Armin
