### ISSUE TITLE
download link for model.json needed for unanimity

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/pbbioconda#32]
The page https://github.com/PacificBiosciences/unanimity describes how to place a file named model.json in a given location

In such cases, download the latest version of the model parameters and place them in a subdirectory of ${SMRT_CHEMISTRY_BUNDLE_DIR}:

but I find nowhere a link to download that file and do not find it in my SMRTLink tree either.

**Comment by pb-dseifert** [comment]
Those instructions are mainly meant for people using SMRTtools from the tarball. Bioconda releases of consensuscore2 always include the latest chemistry, so you should in general never have to sideload the chemistry information, only keep your bioconda installation up-to-date.
