### ISSUE TITLE
IPA/falconc Unknown subcommand "ipa2-construct-config".  It is not similar to defined subcommands.

### ISSUE THREAD

**Issue by schellt** [PacificBiosciences/pbbioconda#320]
Hi,
I am having trouble running IPA. The error message is
`Unknown subcommand "ipa2-construct-config".  It is not similar to defined subcommands.`
This comes from falconc. I am using falconc 0.1.2 which doesn't have this subcommand. Which version of falconc should be used?
Thanks a lot.
Best,
Tilman

**Operating system**
centos7

**Package name**
Which package / tool is causing the problem?
IPA
Which version are you using, use `tool --version`.
1.1.2
Have you updated to the latest version `conda update package`?
No for IPA / yes for falconc - not using conda.
Have you updated the complete env by running `conda update --all`?
Not using conda.
Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?
Not using conda.

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)
Not using conda. This is the output of IPA for the dependencies:
```
snakemake version=5.20.1
ipa2-task 0.4.1 (commit ce56df1670fa91ebf462a3946800fc86e6fab059)
 Machine name: 'Linux'
0.2.1+git.fatal: Not a git repository (or any of the parent directories): .git
Nighthawk 0.1.0 (commit e5048b9*)
pancake 0.2.0 (commit 881d3bc*)
pblayout 0.1.0 (commit 64f78e5*)
racon version=v1.4.3
samtools 1.10
Using htslib 1.10
ipa_purge_dups
```

**Describe the bug**
When running IPA falconc 0.1.2 crashes with
`Unknown subcommand "ipa2-construct-config".  It is not similar to defined subcommands.`
which causes IPA to crash.

**Error message**
`Unknown subcommand "ipa2-construct-config".  It is not similar to defined subcommands.`

**To Reproduce**
```
$ falconc ipa2-construct-config --help
Unknown subcommand "ipa2-construct-config".  It is not similar to defined subcommands.

Run again with subcommand "help" to get detailed usage.
```

**Expected behavior**
(The correct verions of?) falconc knows the subcommand ipa2-construct-config.

**Comment by pb-cdunn** [comment]
```
When running IPA falconc 0.1.2
```
Way too old. It's possible that when you updated **pbipa**, you didn't get an update for **nim-falcon**. Try `conda update --all`. Otherwise, try to update **nim-falcon** directly.
