### ISSUE TITLE
IPA bad extension for .fa .fq .fa.gz and .fq.gz files

### ISSUE THREAD

**Issue by tbenavi1** [PacificBiosciences/pbbioconda#326]
Hello,

I received the following error when running the IPA assembler:

ERROR: Bad extension for "reads.fa". Reads must have one of the following extensions: ['.fasta', '.fastq', '.bam', '.xml', '.fasta.gz', '.fastq.gz']

Would it be possible to add ".fa", ".fq", ".fa.gz", and ".fq.gz" as acceptable extensions? Thanks.

**Comment by gconcepcion** [comment]
a reasonable ask, but you can also just rename your file to one of the accepted formats

**Comment by isovic** [comment]
Hi @tbenavi1 ,
Thank you for your suggestion!
We just implemented the support for these extensions, it will appear in versions >=1.3.1 when they become available on Bioconda.
Until then, I would suggest applying the solution suggested by @gconcepcion .

Best regards,
Ivan.

**Comment by tbenavi1** [comment]
Thanks!

**Comment by pb-cdunn** [comment]
This will be available in a few minutes.

* https://github.com/bioconda/bioconda-recipes/pull/24553

I delayed to try to add some nice testing, but we ran into a disk-usage problem on the Bioconda-build servers. It should work fine for you though.
