### ISSUE TITLE
pbipa version 1.3 purge_dup questions

### ISSUE THREAD

**Issue by jbh-cas** [PacificBiosciences/pbbioconda#327]
I've run ipa version 1.1.2 on a couple of HiFI datasets, tho with recent changes I am going to rerun with version 1.3.0

My first question is: are there any settings needed or warranted to trigger the purge_dup usage on p_ctg.fasta that seems to be available now.

Second question relates the the a_ctg.fasta. I saw in the supplement to the Asian giant hornet assembly that the alternative contigs from purge_dup run were appended to the a_ctg assembly and then purge_dups was run on this to create an improved a_ctg.fasta. Is this done in the current workflow. If not, how can the pbipa versions of the purge_dup facilities be best marshalled for this.

Thanks so much for the tool and the work you all have put into it.

**Comment by isovic** [comment]
Hi @jbh-cas,

The latest version (1.3.0) has the `purge_dups` tool integrated and enabled by default.
(Before this version it was still an experimental feature and intentionally turned off.)
So, no settings needed to switch it on.

For the Asian giant hornet, `purge_dups` was run manually because at the time the workflow didn't yet have this stage implemented.
Our embedded implementation differs from the approach you described above - IPA will run only one round of `purge_dups` (only on the primary contigs, `p_ctg.fasta`). The haplotigs that are extracted by `purge_dups` will get merged with the original `a_ctg.fasta` file (which was generated before the `purge_dups` stage) BUT `purge_dups` will not be run again on this merged file. An additional round of `purge_dups` could be run by hand on this resulting haplotigs file (`RUN/18-purge_dups/final_purged_haplotigs.fasta`).

Additionally, if you really need a custom run of `purge_dups`, this can always be achieved manually after the assembly is done.
Use the polished contigs as the input for this. They be found here: `RUN/14-separate/*_ctg.fasta`.

Best regards,
Ivan.

**Comment by jbh-cas** [comment]
Ivan,

Thanks very much for the quick heads-up.

I'm having problems updating all the 1.3 components. I know conda is the correct way and it is how I created the initial environment. Unfortunately our conda shared system was wrecked with a conda update (which seems all too familiar from a web search).  In the next month or so I will probably be able to migrate to another working copy but I had hoped to use version 1.3 before then.

I downloaded the pbipa release and manually updated binaries and snakemake /etc file.

Running it I received  `util.nim(18) Error: unhandled exception: Unknown config parameters specified: @["config_purge_map_opt"] [PbError]` since reasonably enough falconc 1.8 from the earlier version does not know about purge_dups.

I downloaded nim-falconc which should be version 1.10 as opposed to the earlier 1.8 binary.

It is looking for an nim htslib wrapper and as you can see that is not found.

```
(ipa) jhenderson@rosalindf:~/.conda/envs/ipa$ wa falconc
/home/jhenderson/.conda/envs/ipa/bin/falconc
(ipa) jhenderson@rosalindf:~/.conda/envs/ipa$ falconc version
could not import: sam_hdr_destroy
```
I'm tussling enough with rust these days and don't have much bandwidth for another language environment. Is it possible to relatively easily update these components or need I wait for a working conda environment.

thanks for any guidance,
Jim

**Comment by jbh-cas** [comment]
Ivan,

I was able to rsync files of concern and install a local copy of anaconda and get v 1.3 updated.
At least got to this `falconc version=1.10.1+git.e2d7e29fe141ea499184b818b4c1acd7f53a34d7, nim-version=1.3.5` so I think I might be able to execute this version.

Thanks again,
Jim

**Comment by isovic** [comment]
Hi Jim,
thanks for the update!
Any luck with your latest setup?
Updating Conda packages can be troublesome and break stuff unfortunately...

Best regards,
Ivan.

**Comment by pb-cdunn** [comment]
2 mistakes people often make with conda updates:
```
% conda update
```
You probably want `conda update --all` instead. I'm not sure why, but it might be related to other problem:
```
% conda create -n foo <channels ...>
...
% conda update
```
If you create with channels, you need to update with channels also. It's simpler to put the channels into your `.condarc`.

Most of the conda/bioconda problems have been fixed in conda-forge, but you still have to be careful about the channels.

**Comment by jbh-cas** [comment]
Thanks Christopher.
No that wasn't it. I am familiar with those aspects of conda. Our central conda installation was hosed after an update (apparently not uncommon) and reported missing modules on attempted env updates in a SystemExit message.
As workaround, I just installed my own
version of anaconda and set .condarc to use my already existing envs directory and was back in business.
I did finally get my 2 taxa assembled with IPA, and I have a couple of questions:
1) I've run into the ulimit -n setting issue with not enough file handles a couple of times when
forgetting to set that in my screen session. The resume capability is great btw. I'm curious what setting you typically use for that. Our system soft default of 1024 file handles is not enough but would 32000 be enough when running IPA 4x16 i.e. with 64 threads.
2) Question above future
developments: are there plans to integrate the use of HiC reads into the IPA pipeline using Falcon Phase or the like?
Also, integrating the purge_dups step in to the workflow is tremendous, thanks.
best,
Jim Henderson
---------------------------- Original Message ----------------------------

Subject: Re: [PacificBiosciences/pbbioconda] pbipa version 1.3 purge_dup questions (#327)

From: "Christopher Dunn" 

Date: Sat, September 26, 2020 6:48 am

To: "PacificBiosciences/pbbioconda" 

Cc: "jbh-cas" 

"Mention" 

--------------------------------------------------------------------------




 
2 mistakes people often make with conda updates:

% conda update 

You probably want conda update --all instead. I'm not sure why, but it might be related to other problem:

% conda create -n foo <channels ...> ... % conda update 

If you create with channels, you need to update with channels also. It's simpler to put the channels into your .condarc.
Most of the conda/bioconda problems have been fixed in conda-forge, but you still have to be careful about the channels.—

**Comment by pb-cdunn** [comment]
Which step/executable exceeds 1024 file-handles? Is that only when running locally on a single machine? I'm surprised that we're getting anywhere near that, so I'd definitely want to know what causes it.

**Comment by jbh-cas** [comment]
Christopher,
This file handle setting for job completion has always been needed with FALCON so I bet it is in similar code. Probably failure to close a file after it is no longer needed. I think you can take snapshots of open files but I haven't been down that path in a while.
The
resume log starts at the 06 phasing prepare step and I remember that it got most of the shards done before it ran into the file handle limit. Here's the top of the log as it resumed. It redid all of step 06 though quite a few had been completed (not complaining just fyi as to where file handles
would be consumed -- I think the resume as is is very nice).
The machine is a server into which we ssh and login. The one I used has 128 cores (256 threads) and 2GB of memory running Ubuntu 20.04. So it is a single machine but not local. I've set my default ulimit -n to 32K for future needs
but the default soft setting is 1024 for users and that is where I ran into trouble.
Top of resumed log:
INFO: /home/jhenderson/.conda/envs/ipa/bin/ipa local --nthreads 16 --njobs 3 --verbose -i
XBSCA_20191203_S64049_PL100145243B-1_A01.ccs.fastq.gz -i XBSCA_20191211_S64049_PL100145243B-1_A01.ccs.fastq.gz -i XBSCA_20191211_S64049_PL100145243B-1_B01.ccs.fastq.gz -i XBSCA_20191220_S64049_PL100145243B-1_A01.ccs.fastq.gz --resume
INFO: ipa.py ipa (wrapper) version=1.3.0 ... Checking dependencies ...

INFO: Dependencies

/home/jhenderson/.conda/envs/ipa/bin/python3

/home/jhenderson/.conda/envs/ipa/bin/ipa2-task

/home/jhenderson/.conda/envs/ipa/bin/falconc

/home/jhenderson/.conda/envs/ipa/bin/minimap2

/home/jhenderson/.conda/envs/ipa/bin/nighthawk

/home/jhenderson/.conda/envs/ipa/bin/pancake

/home/jhenderson/.conda/envs/ipa/bin/pblayout

/home/jhenderson/.conda/envs/ipa/bin/pbmm2

/home/jhenderson/.conda/envs/ipa/bin/racon

/home/jhenderson/.conda/envs/ipa/bin/samtools

/home/jhenderson/.conda/envs/ipa/bin/ipa_purge_dups

/home/jhenderson/.conda/envs/ipa/bin/ipa_purge_dups_split_fa

snakemake version=5.22.1

ipa2-task 1.0.1 (commit ee24fea975e69b2799ff26efa1a767819217be5e)

 Machine name: 'Linux'

falconc version=1.10.1+git.e2d7e29fe141ea499184b818b4c1acd7f53a34d7, nim-version=1.3.5

minimap2 version=2.17-r941

Nighthawk 0.1.0 (commit a3ede16*)

pancake 0.2.0 (commit 3a65cc4*)

pblayout 0.1.0 (commit bdfac31*)

pbmm2 1.3.0 (commit 1.3.0)

racon version=v1.4.13

samtools 1.10

Using htslib 1.10.2

ipa_purge_dups Version: 1.2.3



Wrote "RUN/config.yaml".

advanced_options: ''

coverage: 0

genome_size: 0

m4filt_high_copy_sample_rate: 1.0

max_nchunks: 40

nproc: 16

phase_run: 1

polish_run: 1

purge_dups_calcuts: ''

purge_dups_run: 1

reads_fn: RUN/input.fofn

tmp_dir: /tmp





To run this yourself:

/home/jhenderson/.conda/envs/ipa/bin/python3 -m snakemake -j 3 -d RUN -p -s /home/jhenderson/.conda/envs/ipa/etc/ipa.snakefile --configfile RUN/config.yaml --reason



Starting snakemake ...

Building DAG of jobs...

Updating job 13 (ovl_asym_merge).

Using shell: /bin/bash

Provided cores: 3

Rules claiming more threads will be scaled down.

Job counts:

    count    jobs

    1    assemble

    1    final

    1    finish

    1    ovl_filter

    1    phasing_merge

    1    phasing_prepare

    1    polish_merge

    1    polish_prepare

    1    purge_dups_map_merge

    1    purge_dups_map_prepare

    1    purge_dups_paf

    1    separate_p_from_a

    12



[Sun Sep 20 14:01:18 2020]

checkpoint phasing_prepare:

    input: 02-build_db/reads.seqdb, 05-ovl_asym_merge/ovl.nonlocal.m4, 01-generate_config/generated.config

    output: 06-phasing_prepare/shards

    jobid: 14

    reason: Missing output files: 06-phasing_prepare/shards

Downstream jobs will be updated after completion.





        rm -f 06-phasing_prepare/shards

        mkdir -p 06-phasing_prepare/shards

        cd 06-phasing_prepare/shards

        rel=../..



        input_m4="$rel/05-ovl_asym_merge/ovl.nonlocal.m4"         output_shard_ids=./all_shard_ids         output_pwd=./pwd.txt        
params_config_sh_fn="$rel/01-generate_config/generated.config"         params_max_nchunks="40"         params_log_level="INFO"        
params_tmp_dir="/tmp"             time ipa2-task phasing_prepare
    

+ rm -f 06-phasing_prepare/shards

        mkdir -p 06-phasing_prepare/shards

+ mkdir -p 06-phasing_prepare/shards

        cd 06-phasing_prepare/shards

+ cd 06-phasing_prepare/shards

        rel=../..

+ rel=../..



        input_m4="$rel/05-ovl_asym_merge/ovl.nonlocal.m4"         output_shard_ids=./all_shard_ids         output_pwd=./pwd.txt        
params_config_sh_fn="$rel/01-generate_config/generated.config"         params_max_nchunks="40"         params_log_level="INFO"        
params_tmp_dir="/tmp"             time ipa2-task phasing_prepare
+ input_m4=../../05-ovl_asym_merge/ovl.nonlocal.m4

+ output_shard_ids=./all_shard_ids

+ output_pwd=./pwd.txt

+ params_config_sh_fn=../../01-generate_config/generated.config

+ params_max_nchunks=40

+ params_log_level=INFO

+ params_tmp_dir=/tmp

+ time ipa2-task phasing_prepare

    :*7=\E[1;2F:#2=\E[1;2H:#3=\E[2;2~:#4=\E[1;2D:%c=\E[6;2~:\

    :@7=\E[4~:kN=\E[6~:kP=\E[5~:kI=\E[2~:kD=\E[3~:ku=\EOA:\

    :ac=\140\140aaffggjjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~..--++,,hhII00:\
best,
JIm
---------------------------- Original Message ----------------------------

Subject: Re: [PacificBiosciences/pbbioconda] pbipa version 1.3 purge_dup questions (#327)

From: "Christopher Dunn" 

Date: Sat, October 3, 2020 5:09 pm

To: "PacificBiosciences/pbbioconda" 

Cc: "jbh-cas" 

"Mention" 

--------------------------------------------------------------------------




 
Which step/executable exceeds 1024 file-handles? Is that only when running locally on a single machine? I'm surprised that we're getting anywhere
near that, so I'd definitely want to know what causes it.—

**Comment by jbh-cas** [comment]
btw I meant 2 TB of memory so that is not an issue here
---------------------------- Original Message ----------------------------

Subject: Re: [PacificBiosciences/pbbioconda] pbipa version 1.3 purge_dup questions (#327)

From: jbh@jbhmail.com

Date: Mon, October 5, 2020 4:27 pm

To: "PacificBiosciences/pbbioconda" 

Cc: "PacificBiosciences/pbbioconda" 

"Mention" 

--------------------------------------------------------------------------

**Comment by pb-cdunn** [comment]
Interesting. Please look in `RUN/06-phasing_prepare/shards`/ How many shards and chunks are there?

**Comment by jbh-cas** [comment]
Christopher,
Here's some info. Not out of the ordinary. I don't think I need a work-around, I'm happy permanently bumping up the max open file count. The 1024 is an artifact of by-gone days.
We definitely ran into this using the FALCON pipeline earlier this year which included using
FALCON-Unzip. A couple of us needed to set this value and I'm pretty sure that we were told to do this by someone at PacBio but that conversation was with a colleague of mine who relayed the information to me.
I also noticed it mentioned in a closed Issue #9 for FALCON_unzip where you were a
respondent. Perhaps that issue crept back into the code -- it happens.
Let me know if you would like any more info. Also I'm still curious about any plans to fold in FALCON-Phase using HiC reads into the pipeline.
best,
jim
INFO:
The primary genome is
~2.4Gbp with with 776 contigs. The a_ctg is 1.7Gbp with 8253 contigs.
jhenderson@rosalindf:~/neotoma/ipa1.3_Nfusc/06-phasing_prepare/shards$ ls shard* |wc -l
40

jhenderson@rosalindf:~/neotoma/ipa1.3_Nfusc/06-phasing_prepare/shards$ cat shard* | wc -l

2618

jhenderson@rosalindf:~/neotoma/ipa1.3_Nfusc/06-phasing_prepare/shards$ ls chunk* |wc -l

2618



jhenderson@rosalindf:~/neotoma/ipa1.3_Nfusc/01-generate_config$ cat generated.config.sh

config_autocomp_max_cov=1

config_block_size=4096

config_cleanup=0

config_coverage=0

config_existing_db_prefix=''

config_genome_size=0

config_m4filt_high_copy_sample_rate=1.0

config_max_polish_block_mb=100

config_ovl_filter_opt='--max-diff 80 --max-cov 100 --min-cov 2 --bestn 10 --min-len 4000 --gapFilt --minDepth 4 --idt-stage2 98'

config_ovl_min_idt=98

config_ovl_min_len=1000

config_ovl_opt='--one-hit-per-target --min-idt 96'

config_phase_run=1

config_phasing_opt=''

config_phasing_split_opt='--split-type noverlaps --limit 3000000'

config_polish_min_len=50000

config_polish_run=1

config_purge_dups_calcuts=''

config_purge_dups_run=1

config_purge_map_opt='--min-map-len 1000 --min-idt 98.0 --bestn 5'

config_seeddb_opt='-k 30 -w 80 --space 1'

config_seqdb_opt='--compression 1'

config_use_hpc=0

config_use_seq_ids=1



 


---------------------------- Original Message ----------------------------

Subject: Re: [PacificBiosciences/pbbioconda] pbipa version 1.3 purge_dup questions (#327)

From: "Christopher Dunn" 

Date: Tue, October 6, 2020 8:04 am

To: "PacificBiosciences/pbbioconda" 

Cc: "jbh-cas" 

"Mention" 

--------------------------------------------------------------------------




 
If the number of "chunks" is > 1024 in phasing_prepare, we could offer a work-around, but we think it's
unusual.
Please also post the content of RUN/01-generate_config/generated.config.sh.—

**Comment by pb-cdunn** [comment]
`2618` chunks? Good. That explains it.

We are surprised that you would ever need so many chunks. I will format your config so that a colleague can take a look later.

**Comment by pb-cdunn** [comment]
```sh
jhenderson@rosalindf:~/neotoma/ipa1.3_Nfusc/01-generate_config$ cat generated.config.sh

config_autocomp_max_cov=1
config_block_size=4096
config_cleanup=0
config_coverage=0
config_existing_db_prefix=''
config_genome_size=0
config_m4filt_high_copy_sample_rate=1.0
config_max_polish_block_mb=100
config_ovl_filter_opt='--max-diff 80 --max-cov 100 --min-cov 2 --bestn 10 --min-len 4000 --gapFilt --minDepth 4 --idt-stage2 98'
config_ovl_min_idt=98
config_ovl_min_len=1000
config_ovl_opt='--one-hit-per-target --min-idt 96'
config_phase_run=1
config_phasing_opt=''
config_phasing_split_opt='--split-type noverlaps --limit 3000000'
config_polish_min_len=50000
config_polish_run=1
config_purge_dups_calcuts=''
config_purge_dups_run=1
config_purge_map_opt='--min-map-len 1000 --min-idt 98.0 --bestn 5'
config_seeddb_opt='-k 30 -w 80 --space 1'
config_seqdb_opt='--compression 1'
config_use_hpc=0
config_use_seq_ids=1
```
