### ISSUE TITLE
Heteroduplex insertions with --by-strand

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#328]
How are heteroduplex insertions filtered in ccs when using the --by-strand option?
Does it still look at both strands even though --by-strand is on?

**Comment by armintoepfer** [comment]
Do you have an example where it does not work as expected? None of the filters are deactivated explicitly, but the one referenced should not kick in implicitly.
My working theory is that --by-strand rescues all strand-specific nuances.

**Comment by gevro** [comment]
I don't have a specific example. I was just wondering in principle what happens?
Because --by-strand treats each strand separately, whereas 'heteroduplex insertion' filtering would have to take into account both strand.

So I don't know internally in ccs if activating --by-strand would mess up the way that ccs 'heteroduplex insertion' filtering happens.

I can report that I still see ZMWs being filtered out by 'heteroduplex insertion' when using --by-strand.

Also, another question: Is there any way to change the threshold of '20' bases different for the 'heteroduplex insertion' filter?

**Comment by armintoepfer** [comment]
I likely found the bug that caused this strange behaviour.

**Comment by gevro** [comment]
Thanks! When will this be fixed?

Also, is the current behavior only falsely reporting them as 'filtered', or are heteroduplex insertions actually being filtered with --by-strand? If so, is it only if > 20 bases different?

I'm asking because this affects our analysis.

**Comment by armintoepfer** [comment]
No release date yet.

If this affects your analysis, please reach out to PacBio's tech support.

**Comment by armintoepfer** [comment]
Release of next CCS will be in Q1 2021. Since you are not sharing any data, I can't guarantee that your problems will be fixed.
