### ISSUE TITLE
IPA snakemake cmd aborts: Error in rule generate_config

### ISSUE THREAD

**Issue by grendon** [PacificBiosciences/pbbioconda#329]
**Operating system**

$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

**Package name**

  1) Miniconda3/4.7.12.1   
  2) pbipa/1.3.0

**Conda environment**
$ conda list
# packages in environment at /home/apps2/software/pbipa/1.3.0:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
appdirs                   1.4.4                      py_0
attrs                     20.2.0                     py_0
brotlipy                  0.7.0           py38h7b6447c_1000
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2020.7.22                     0
certifi                   2020.6.20                py38_0
cffi                      1.14.2           py38he30daa8_0
chardet                   3.0.4                 py38_1003
configargparse            1.2.3                      py_0
cryptography              3.1              py38h1ba5d50_0
datrie                    0.8.2            py38h7b6447c_0
decorator                 4.4.2                      py_0
docutils                  0.16                     py38_1
gitdb                     4.0.5                      py_0
gitpython                 3.1.3                      py_1
htslib                    1.10.2               hd3b49d5_1    bioconda
idna                      2.10                       py_0
importlib-metadata        1.7.0                    py38_0
importlib_metadata        1.7.0                         0
ipython_genutils          0.2.0                    py38_0
jsonschema                3.2.0                    py38_0
jupyter_core              4.6.3                    py38_0
k8                        0.2.5                he513fc3_0    bioconda
krb5                      1.18.2               h173b8e3_0
ld_impl_linux-64          2.33.1               h53a641e_7
libcurl                   7.71.1               h20c2e04_1
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libssh2                   1.9.0                h1ba5d50_1
libstdcxx-ng              9.1.0                hdf63c60_0
minimap2                  2.17                 hed695b0_3    bioconda
nbformat                  5.0.7                      py_0
ncurses                   6.2                  he6710b0_1
networkx                  2.5                        py_0
nim-falcon                1.10.1               h8912ca2_0    bioconda
openssl                   1.1.1g               h7b6447c_0
pbipa                     1.3.0                hee625c5_0    bioconda
pbmm2                     1.3.0                h56fc30b_1    bioconda
pcre                      8.44                 he6710b0_0
pip                       20.2.2                   py38_0
psutil                    5.7.2            py38h7b6447c_0
pycparser                 2.20                       py_2
pyopenssl                 19.1.0                     py_1
pyrsistent                0.17.3           py38h7b6447c_0
pysocks                   1.7.1                    py38_0
python                    3.8.5                h7579374_1
python_abi                3.8                      1_cp38    conda-forge
pyyaml                    5.3.1            py38h7b6447c_1
racon                     1.4.13               he513fc3_0    bioconda
ratelimiter               1.2.0           py38h32f6830_1001    conda-forge
readline                  8.0                  h7b6447c_0
requests                  2.24.0                     py_0
samtools                  1.10                 h2e538c0_3    bioconda
setuptools                49.6.0                   py38_0
six                       1.15.0                     py_0
smmap                     3.0.4                      py_0
snakemake-minimal         5.16.0                     py_0    bioconda
sqlite                    3.33.0               h62c20be_0
tk                        8.6.10               hbc83047_0
toposort                  1.5                        py_3    conda-forge
traitlets                 4.3.3                    py38_0
urllib3                   1.25.10                    py_0
wheel                     0.35.1                     py_0
wrapt                     1.12.1           py38h7b6447c_1
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h7b6447c_3

**Describe the bug**

It doesn't even get started. It stops during the initial stage of setting up the run. It fails to generate a file called generate_config

**Error message**
Error in rule generate_config:
    jobid: 5
    output: 01-generate_config/generated.config
    shell:

        wd=$(dirname 01-generate_config/generated.config)
        mkdir -p $wd
        cd $wd
        rel=..

        params_advanced_opt=""         params_coverage="0"         params_genome_size="0"         params_polish_run="1"         params_phase_run="1"         params_purge_dups_run="1"         params_purge_dups_calcuts=""         params_m4filt_high_copy_sample_rate="1.0"         params_log_level="INFO"         params_tmp_dir="/scratch/melon_assembly"         output_fn="generated.config.sh"         sentinel_fn="generated.config"             time ipa2-task generate_config_from_workflow

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /scratch/melon_assembly/test/.snakemake/log/2020-09-18T122503.768218.snakemake.log
ERROR: Command '/home/apps2/software/pbipa/1.3.0/bin/python3 -m snakemake -j 2 -d /scratch/melon_assembly/test -p -s /home/apps2/software/pbipa/1.3.0/etc/ipa.snakefile --configfile /scratch/melon_assembly/test/config.yaml --reason' returned non-zero exit status 1.
Exiting.

**To Reproduce**

$ ipa local --nthreads 12 --njobs 2 --run-dir ${PWD}/test --tmp-dir ${PWD} -i tiny_HiFi.fasta

**Expected behavior**

I expected the tool to run and produce an assembly in the path ${PWD}/test

**Comment by grendon** [comment]
Forgot to append files to my previous post

[tiny_HiFi.fa.txt](https://github.com/PacificBiosciences/pbbioconda/files/5247217/tiny_HiFi.fa.txt)
[ipa.log](https://github.com/PacificBiosciences/pbbioconda/files/5247220/ipa.log)

[2020-09-18T122503.768218.snakemake.log](https://github.com/PacificBiosciences/pbbioconda/files/5247222/2020-09-18T122503.768218.snakemake.log)

**Comment by pb-cdunn** [comment]
1. Always start with `--dry-run`.
1. Actually, always try `ipa validate` before that.
1. If you look at the top of `ipa` output, you can see the actual `snakemake` command. You can run that directly to aid debugging.
1. Use `ipa local -verbose ...` to see the error in stderr.

I'll see if I can find the error in your logs, but I suspect it is an environment problem....

**Comment by pb-cdunn** [comment]
Well, your environment seems ok. Try running with `--verbose` and maybe we will at least see which component failed.

**Comment by armintoepfer** [comment]
Lack of feedback. Closing

**Comment by ranlib** [comment]
I have the same issue
I made a docker image like so:

> 
FROM continuumio/miniconda3 
RUN apt-get update
RUN conda config --add channels bioconda && conda config --add channels conda-forge
RUN conda install pbipa


Then I run the script:

#!/usr/bin/env bash
shopt -s expand_aliases
alias ipa='docker run --rm -it -v $PWD:/mnt -w /mnt dbest/ipa ipa'
if [ ! -f ecoli.fastq.gz ] ; then 
    curl -L -o ecoli.fastq https://sra-pub-src-1.s3.amazonaws.com/SRR10971019/m54316_180808_005743.fastq.1
    gzip ecoli.fastq
fi
ipa validate
ipa local --nthreads 1 --njobs 1 --verbose -i ecoli.fastq.gz
exit 0

Attached the log file.
Any ideas what I did wrong?

[2021-03-16T223941.749938.snakemake.log](https://github.com/PacificBiosciences/pbbioconda/files/6152637/2021-03-16T223941.749938.snakemake.log)

**Comment by pb-cdunn** [comment]
```
reason: Missing output files: 01-generate_config/generated.config
```
This is a very early crash, so it is probably a configuration problem. You can best debug this yourself by going into the `01-generate_config` directory and running that command yourself in your own shell. There are ways to get snakemake to tell you what it's doing so you can reproduce the problem. It's likely a very simple problem, but it's hard for us to debug integration problems remotely.

Also, you can try running with `--dry-run`.

**Comment by ranlib** [comment]
I am making a docker image, see Dockerfile in my previous post, so you can try it easily yourself, I am not doing anything in addition. If there is some additional setup to be done, let me know.
I also attached the snakemake log in my post, let me know if you can pinpoint what the issue might be.
I am happy to have a zoom meeting any time so we can go over what I am doing.

**Comment by pb-cdunn** [comment]
I suspect that your docker image is using an old snakemake version. IIRC, the problem was that a snakemake update broke Snakemake in Bioconda. Our env still worked because we actually use **snakemake-minimal**, but when a user has both **snakemake** and **snakemake-minimal** in their environment, then the newer broken `snakemake` would be used. But that's just a guess.

If you debug this within your Docker image and discover the problem, please let us know!
