### ISSUE TITLE
ccs ERROR: [pbbam] chemistry compatibility ERROR: unsupported sequencing chemistry combination

### ISSUE THREAD

**Issue by cwarden45** [PacificBiosciences/pbbioconda#330]
Hi,

I am running some commands within pbbioconda on a Slurm cluster.

I have been able to successfully run *bax2bam*, *blasr*, and *quiver/arrow*.

However, I get the following error message when I try to run `ccs`:

```
| 20200923 20:06:07.943 | FATAL | ccs ERROR: [pbbam] chemistry compatibility ERROR: unsupported sequencing chemistry combination:
    binding kit:        100372700
    sequencing kit:     100612400
    basecaller version: 2.3.0.3.154799
```

These are the commands that I am using to run the program (and I have generated a new input file for the program):

```
module load pbbioconda/20200921
module load SAMtools/1.9-foss-2018b

#convert raw file format
BAXH5C1=$H5PREFIX.1.bax.h5
BAXH5C2=$H5PREFIX.2.bax.h5
BAXH5C3=$H5PREFIX.3.bax.h5
bax2bam -o $UNALIGNEDPREFIX $BAXH5C1 $BAXH5C2 $BAXH5C3

UNALIGNED=$UNALIGNEDPREFIX.subreads.bam

#3x CCS
CCSBAM=$CCSPREFIX.ccs.3x.bam
CCSFQ=$CCSPREFIX.ccs.3x.fq
ccs --num-threads=16 $UNALIGNED $CCSBAM
samtools bam2fq $CCSBAM $CCSFQ
```

I have seen the following tickets:

https://github.com/PacificBiosciences/IsoSeq_SA3nUP/issues/14

https://github.com/PacificBiosciences/pitchfork/issues/415

However, I think unanimity got converted back to ccs?  Also, I don't think I completely understand the problem.

I can get arrow and quiver to work, so the problem is different than described in this ticket:

https://github.com/PacificBiosciences/pbbioconda/issues/81

**Can you please help me troubleshoot?**

Thank you very much.

Sincerely,
Charles

**Comment by pb-dseifert** [comment]
RSII is completely unsupported using our bioconda utilities. If you need RSII support, please use smrttools in SMRTLink 7.

**Comment by cwarden45** [comment]
Hi David,

Thank you for the feedback.

We have SMRT Link 8, and I was trying to get the functions to work on a cluster (which can be used for anybody, for re-analysis of raw data).

There is an earlier version of `ccs` that I got working in a Docker image:

https://hub.docker.com/r/cwarden45/general-pacbio/

I think I encountered some issues running Docker through Singularity on the cluster, but I will look into that for this image.

I was going to ask if I could try separate installation through the [ccs repository](https://github.com/PacificBiosciences/ccs), but it looks like that documentation has changed and bioconda is the recommended installation method.

Thank You,
Charles

**Comment by cwarden45** [comment]
If others are interested in how to generate CCS reads in a similar situation, I was able to create an interactive Singularity Docker shell as follows:

```
singularity pull docker https://hub.docker.com/r/cwarden45/general-pacbio/
singularity shell --bind /path/to/folder:/mnt/folder /home/cwarden/.singularity/cache/oci-tmp/[longID]/general-pacbio_latest.sif
```

I could also run that specific command mixed with other commands as follows:

```
UNALIGNED=$UNALIGNEDPREFIX.subreads.bam
CCSBAM=$CCSPREFIX.ccs.5x.bam
SINGCCSBAM=/mnt/user_data/$MIDFOLDER/$CCSPREFIX.ccs.5x.bam
singularity exec --bind /path/to/folder:/mnt/folder /home/cwarden/.singularity/cache/oci-tmp/[longID]/general-pacbio_latest.sif /opt/unanimity/build/ccs --numThreads=16 --minPasses=3 $SINGUNALIGNED $SINGCCSBAM
```

Best wishes to all of the other researchers!
