### ISSUE TITLE
IPA to use only one block/shard for polishing

### ISSUE THREAD

**Issue by jelber2** [PacificBiosciences/pbbioconda#331]
I am using
`pbipa                     1.3.0                hee625c5_1    bioconda`

to run `ipa` and was wondering if it is possible to run all reads on the entire draft assembly during the polish step. I have tried `--advanced-opt "config_block_size=350000" --nshards 1`, but at least for the assembly I am working on, it generates at least 3 blocks.

`ipa local --advanced-opt "config_block_size=350000" --nshards 1 --tmp-dir /dev/shm/ --no-purge-dups --nthreads 75 --njobs 1 --no-phase -i ../hifi.fasta > ipa.log 2>&1 &`

Maybe I am wrong, but it seems like in some scenarios, it would be best to map all reads against the entire draft assembly, hence the request for this feature.

I was able to do it manually by deleting from the 12-polish_run directories onward and then modifying the following in the directory `RUN/11-polish_prepare/shards/`

    ipa local --advanced-opt "config_block_size=350000" --nshards 1 \
    --tmp-dir /dev/shm/ --no-purge-dups --nthreads 75 --njobs 1 --no-phase -i \
    ../hifi.fasta > ipa.log 2>&1

    cd ipa-new5/RUN
    rm -r 1{2..9}-*/ assembly-results
    cd 11-polish_prepare/shards
    cat block.0.reads block.1.reads block.2.reads > block.012.reads
    cat block.0.ctg_id block.1.ctg_id block.2.ctg_id > block.012.ctg_id
    rm block.?.reads 
    rm block.?.ctg_id 
    mv block.012.reads block.0.reads
    mv block.012.ctg_id block.0.ctg_id
    head -n1 shard.0.block_ids > tmp2 && mv tmp2 shard.0.block_ids

    cd ../../../

    ipa local --advanced-opt "config_block_size=350000" --nshards 1 \
    --tmp-dir /dev/shm/ --no-purge-dups --nthreads 75 --njobs 1 --no-phase -i \
    ../hifi.fasta --resume > ipa.log 2>&1 &

Then restarting with `--resume`

I can confirm that one gets different results when using one or by default in this case three blocks.

**Comment by isovic** [comment]
Hi @jelber2,

IPA doesn't bluntly align all reads to the contigs, but it instead tracks the reads and assigns them to contigs based on overlaps. This is important to preserve the phasing information which would get lost if all reads were simply mapped to all contigs. So running `pbmm2`/`minimap2`/other aligner to map the reads to all contigs directly will very likely produce worse consensus.

That being said, in the case you shared, it looks like you are still using the assignment information.
Aside from read tracking, the only explanations that I can think of for getting different results in case of one block or multiple blocks are: (1) Minimap2, which will have a larger reference to map to and may filter out some repetitive kmers based on the frequency thresholds; or (2) Pbmm2, the new feature for assignment based mapping may produce different results in case the underlying Minimap2 mapper produces a different set of alignments and the assigned contig is not a preferred one.

The `config_block_size=350000` option changes the block size for overlapping, it's not related to sharding of other stages.
There is another option you may try to produce different block sizes for polishing:
```
config_max_polish_block_mb = 100
```

> I can confirm that one gets different results when using one or by default in this case three blocks.

How do the results compare concretely?

Best regards,
Ivan.

**Comment by jelber2** [comment]
@isovic thx. I will try to upload the Quast results soon.   From what I remember it was only mismatches and indels that were different.

**Comment by jelber2** [comment]
@isovic I am sorry, but I don't have the "raw results" to compare 1-block/shard versus defaults. I only have a comparison of the assemblies after combining p_ctg and a_ctg then running purge_dups (I did use the same coverage cut-offs for purge dups for the 1-block versus default assemblies). Also, these assemblies are based off of simulated HiFi reads.

    Assembly                     ipa.new.diploid.nophase.fasta.winnow.2.purged  ipa.new.diploid.1block.nopurge.nophase.fasta.winnow.2.purged
    # contigs (>= 0 bp)          83                                             71
    # contigs (>= 1000 bp)       83                                             71
    # contigs (>= 5000 bp)       76                                             69
    # contigs (>= 10000 bp)      66                                             65
    # contigs (>= 25000 bp)      61                                             62
    # contigs (>= 50000 bp)      60                                             61
    Total length (>= 0 bp)       136224915                                      136193477
    Total length (>= 1000 bp)    136224915                                      136193477
    Total length (>= 5000 bp)    136203056                                      136187421
    Total length (>= 10000 bp)   136130728                                      136156263
    Total length (>= 25000 bp)   136052871                                      136114611
    Total length (>= 50000 bp)   136015142                                      136076883
    # contigs                    83                                             71
    Largest contig               27944747                                       27944748
    Total length                 136224915                                      136193477
    Reference length             140694204                                      140694204
    Reference GC (%)             42.05                                          42.05
    N50                          21354718                                       21354718
    NG50                         21354718                                       21354718
    N90                          1064652                                        1064648
    NG90                         597780                                         597780
    L50                          3                                              3
    LG50                         3                                              3
    L90                          14                                             14
    LG90                         19                                             19
    # misassemblies              0                                              0
    # misassembled contigs       0                                              0
    Misassembled contigs length  0                                              0
    # local misassemblies        1                                              1
    # scaffold gap ext. mis.     0                                              0
    # scaffold gap loc. mis.     0                                              0
    # unaligned mis. contigs     0                                              0
    # unaligned contigs          0 + 0 part                                     0 + 0 part
    Unaligned length             0                                              0
    Genome fraction (%)          96.513                                         96.552
    Duplication ratio            1.003                                          1.003
    # N's per 100 kbp            0.00                                           0.00
    # mismatches per 100 kbp     984.84                                         983.96
    # indels per 100 kbp         50.32                                          50.08
    Largest alignment            27944747                                       27944748
    Total aligned length         136224841                                      136193436
    NA50                         21354716                                       21354716
    NGA50                        21354716                                       21354716
    NA90                         1064644                                        1064640
    NGA90                        597780                                         597780
    LA50                         3                                              3
    LGA50                        3                                              3
    LA90                         14                                             14
    LGA90                        19                                             19

    # Quality scores estimated with YAK (https://github.com/lh3/yak)
    # Used simulated Illumina reads off the same reference for the simulated HiFi reads
    Sequences_or_assembly                                                        raw_quality_value  adjusted_quality_value
    ../ipa-new3/ipa.new.diploid.nophase.fasta.winnow.2.purged.fa                 47.774             48.657
    ../ipa-new5/ipa.new.diploid.1block.nopurge.nophase.fasta.winnow.2.purged.fa  48.398             49.437

**Comment by jelber2** [comment]
Okay, so I just reran it without purge_dups using the default p_ctgs for comparison with the 3 blocks (ipa.default.block) and 1 block (ipa.1.block)

    Sequences_or_assembly             raw_quality_value  adjusted_quality_value
    ../ipa.default.block.p_ctg.fasta  48.095             49.043
    ../ipa.1.block.p_ctg.fasta        48.099             49.050

    Assembly                     ipa.1.block.p_ctg  ipa.default.block.p_ctg
    # contigs (>= 0 bp)          184                184
    # contigs (>= 1000 bp)       184                184
    # contigs (>= 5000 bp)       184                184
    # contigs (>= 10000 bp)      184                184
    # contigs (>= 25000 bp)      184                184
    # contigs (>= 50000 bp)      184                184
    Total length (>= 0 bp)       276225586          276225607
    Total length (>= 1000 bp)    276225586          276225607
    Total length (>= 5000 bp)    276225586          276225607
    Total length (>= 10000 bp)   276225586          276225607
    Total length (>= 25000 bp)   276225586          276225607
    Total length (>= 50000 bp)   276225586          276225607
    # contigs                    184                184
    Largest contig               27944748           27944747
    Total length                 276225586          276225607
    Reference length             140694204          140694204
    Reference GC (%)             42.05              42.05
    N50                          17466920           17467102
    NG50                         21354718           21354718
    N90                          673327             673327
    NG90                         18476623           18476621
    L50                          7                  7
    LG50                         3                  3
    L90                          33                 33
    LG90                         6                  6
    # misassemblies              6                  6
    # misassembled contigs       3                  3
    Misassembled contigs length  250088             250087
    # local misassemblies        4                  5
    # scaffold gap ext. mis.     0                  0
    # scaffold gap loc. mis.     0                  0
    # unaligned mis. contigs     0                  0
    # unaligned contigs          0 + 2 part         0 + 2 part
    Unaligned length             11104              11104
    Genome fraction (%)          98.273             98.273
    Duplication ratio            1.998              1.998
    # N's per 100 kbp            0.00               0.00
    # mismatches per 100 kbp     957.67             957.83
    # indels per 100 kbp         48.81              48.82
    Largest alignment            27944748           27944747
    Total aligned length         276203269          276203290
    NA50                         17466920           17467102
    NGA50                        21354716           21354716
    NA90                         673327             673327
    NGA90                        18476623           18476621
    LA50                         7                  7
    LGA50                        3                  3
    LA90                         33                 33
    LGA90                        6                  6
