### ISSUE TITLE
pbcore not in pip3 (but pip2)

### ISSUE THREAD

**Issue by kibanez** [PacificBiosciences/pbbioconda#332]
**Operating system**
Which operating system and version are you using?

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Package name**
`pbcore` -- not available for pip3 (python v3)
And since `apps-scripts/RepeatAnalysisTools` has been updated to python3 - pbcore is not working

**Conda environment**
`pbcore` has been installed via bioconda:

# packages in environment at /home/driuser/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
aioeasywebdav             2.4.0                 py37_1000    conda-forge
aiohttp                   3.6.2            py37h516909a_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
atk                       2.36.0                        2    conda-forge
atk-1.0                   2.36.0               h516909a_2    conda-forge
attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
bcrypt                    3.2.0            py37h8f50634_0    conda-forge
biopython                 1.78             py37h8f50634_0    conda-forge
boto3                     1.15.2             pyh9f0ad1d_0    conda-forge
botocore                  1.18.2             pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bwa                       0.7.17               hed695b0_7    bioconda
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cachetools                4.1.1                      py_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.3           py37h2b28604_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1007    conda-forge
conda                     4.8.5            py37hc8dfbb8_1    conda-forge
conda-package-handling    1.7.0            py37h8f50634_5    conda-forge
configargparse            1.2.3              pyh9f0ad1d_0    conda-forge
crc32c                    2.0              py37h516909a_0    conda-forge
cryptography              3.1              py37hb09aad4_0    conda-forge
curl                      7.71.1               he644dc0_6    conda-forge
cycler                    0.10.0                     py_2    conda-forge
datrie                    0.8.2            py37h8f50634_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
docutils                  0.16             py37hc8dfbb8_1    conda-forge
dropbox                   10.4.1             pyh9f0ad1d_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fftw                      3.3.8           nompi_h7f3a6c3_1111    conda-forge
filechunkio               1.8                        py_2    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      2.001                hab24e00_0    conda-forge
font-ttf-source-code-pro  2.030                hab24e00_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h1056068_1002    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
fribidi                   1.0.10               h516909a_0    conda-forge
ftputil                   4.0.0                      py_0    conda-forge
gdk-pixbuf                2.38.2               h3f25603_4    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
ghostscript               9.53.1               he1b5a44_0    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
git-lfs                   2.10.0                        0    conda-forge
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.8                      py_0    conda-forge
glib                      2.66.0               h0dae87d_0    conda-forge
gobject-introspection     1.64.1           py37h619baee_1    conda-forge
google-api-core           1.22.2           py37hc8dfbb8_0    conda-forge
google-auth               1.21.2                     py_0    conda-forge
google-cloud-core         1.4.1              pyh9f0ad1d_0    conda-forge
google-cloud-storage      1.31.0             pyh9f0ad1d_0    conda-forge
google-crc32c             1.0.0            py37h193935f_0    conda-forge
google-resumable-media    1.0.0              pyh9f0ad1d_0    conda-forge
googleapis-common-protos  1.51.0           py37hc8dfbb8_2    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
graphviz                  2.42.3               h6939c30_1    conda-forge
grpcio                    1.31.0           py37hb0870dc_0    conda-forge
gtk2                      2.24.32              h194ddfc_3    conda-forge
gts                       0.7.6                h08bb679_0    conda-forge
harfbuzz                  2.7.2                hee91db6_0    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagemagick               7.0.10_28       pl526h201ca68_0    conda-forge
importlib-metadata        1.7.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.7.0                         0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jbig                      2.1               h516909a_2002    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcrc32c                 1.1.1                he1b5a44_2    conda-forge
libcurl                   7.71.1               hcdd3856_6    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h24d8f2e_16    conda-forge
libgfortran-ng            7.5.0               hdf63c60_16    conda-forge
libgomp                   9.3.0               h24d8f2e_16    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libprotobuf               3.13.0               h8b12597_0    conda-forge
librsvg                   2.50.0               h33a7fed_0    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               hdf63c60_16    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libtool                   2.4.6             h516909a_1005    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.1.0                h56121f0_4    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
lima                      1.11.0                        0    bioconda
lz4-c                     1.9.2                he1b5a44_3    conda-forge
mappy                     2.17                     pypi_0    pypi
markupsafe                1.1.1            py37h8f50634_1    conda-forge
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py37hd478181_0    conda-forge
minimap2                  2.15                 ha92aebf_0    bioconda/label/cf201901
multidict                 4.7.5            py37h8f50634_1    conda-forge
nanofilt                  2.6.0                      py_0    bioconda
nanoget                   1.15.0                     py_0    bioconda
nanomath                  1.0.0                      py_0    bioconda
nanoplot                  1.29.0                     py_0    bioconda
nbformat                  5.0.7                      py_0    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
networkx                  2.5                        py_0    conda-forge
numpy                     1.19.1           py37h7ea13bd_2    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pandas                    1.1.2            py37h3340039_0    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pauvre                    0.1.86                     py_1    bioconda
pbccs                     4.2.0                         1    bioconda
**pbcore                    2.1.2                      py_2    bioconda**
pbmm2                     1.3.0                h56fc30b_0    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pillow                    7.2.0            py37h718be6c_1    conda-forge
pip                       20.2.3                     py_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pkg-config                0.29.2            h516909a_1006    conda-forge
plotly                    4.10.0             pyh9f0ad1d_0    conda-forge
prettytable               0.7.2                      py_3    conda-forge
protobuf                  3.13.0           py37h3340039_0    conda-forge
psutil                    5.7.2            py37h8f50634_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycosat                   0.6.3           py37h8f50634_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.1                      py_0    conda-forge
pygraphviz                1.3              py37h14c3975_1  
pynacl                    1.3.0           py37h516909a_1001    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py37h8f50634_0    conda-forge
pysam                     0.16.0.1         py37hc334e0b_1    bioconda
pysftp                    0.2.9                      py_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6                h0371630_2  
python-dateutil           2.8.1                      py_0    conda-forge
python-irodsclient        0.8.2                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
ratelimiter               1.2.0           py37hc8dfbb8_1001    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rsa                       4.6                pyh9f0ad1d_0    conda-forge
ruamel_yaml               0.15.80         py37h8f50634_1002    conda-forge
s3transfer                0.3.3            py37hc8dfbb8_1    conda-forge
scipy                     1.5.2            py37hb14ef9d_0    conda-forge
seaborn                   0.11.0                        0    conda-forge
seaborn-base              0.11.0                     py_0    conda-forge
setuptools                49.6.0           py37hc8dfbb8_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
snakemake                 5.14.0                        0    bioconda
snakemake-minimal         5.14.0                     py_1    bioconda
sqlite                    3.33.0               h62c20be_0  
statsmodels               0.12.0           py37h8f50634_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toposort                  1.5                        py_3    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.49.0             pyh9f0ad1d_0    conda-forge
traitlets                 5.0.4                      py_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wrapt                     1.12.1           py37h8f50634_1    conda-forge
xmlrunner                 1.7.7                      py_0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxpm               3.5.13               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.3.0           py37h516909a_1000    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge

**Describe the bug**
When running one of the reports function, plotCounts for instance, 
apps-scripts/RepeatAnalysisTools/plotCounts.py

We get the following issue:

**Traceback (most recent call last):
  File "/home/driuser/sw/apps-scripts/RepeatAnalysisTools/plotCounts.py", line 8, in <module>
    from pbcore.io import FastaReader,FastqReader
ModuleNotFoundError: No module named 'pbcore'**

This is the list of packages/libraries installed in our virtual environment (python3.7):

certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
idna==2.10
joblib==0.16.0
kiwisolver==1.2.0
mappy==2.17
matplotlib==3.3.2
numpy==1.19.2
pandas==1.1.2
Pillow==7.2.0
pkg-resources==0.0.0
pyparsing==2.4.7
pysam==0.16.0.1
python-dateutil==2.8.1
pytz==2020.1
requests==2.24.0
resources==0.0.1
scikit-learn==0.23.2
scipy==1.5.2
seaborn==0.11.0
six==1.15.0
sklearn==0.0
staty==1.2.4
threadpoolctl==2.1.0
urllib3==1.25.10

**Error message**
Traceback (most recent call last):
  File "/home/driuser/sw/apps-scripts/RepeatAnalysisTools/plotCounts.py", line 8, in <module>
    from pbcore.io import FastaReader,FastqReader
ModuleNotFoundError: No module named 'pbcore'

We try to install from pip repo:

pip3.7 install pbcore
Collecting pbcore
  Using cached pbcore-1.2.10.tar.gz (10.0 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/driuser/sw/apps-scripts/RepeatAnalysisTools/venv_python3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-b0nb34ww/pbcore/setup.py'"'"'; __file__='"'"'/tmp/pip-install-b0nb34ww/pbcore/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-46b7bxse
         cwd: /tmp/pip-install-b0nb34ww/pbcore/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-b0nb34ww/pbcore/setup.py", line 9
        print "pbcore requires Python 2.7"
                                         ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("pbcore requires Python 2.7")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output

But it's still for python2.7, and not python3

**To Reproduce**
Just run https://github.com/PacificBiosciences/apps-scripts/tree/master/RepeatAnalysisTools with python3, and you'll get the error if you don't have `pbcore` in your pip repo.

**Expected behavior**
We would like to have `pbcore` library in pip repo

Thanks a lot, 
kristina

**Comment by jrharting** [comment]
Hi Kristina,

Can you try to install pbcore using the 'conda' installation tool with the 'bioconda' channel?  The repository that pip uses is not up to date at this time.

https://github.com/PacificBiosciences/pbbioconda#installation


Best,
John

**Comment by kibanez** [comment]
Hello John, 

Many thanks for your prompt reply on this.
What I can see is that when I installed `pbcore` with conda before, v2.1.2 was installed but for Build pythonv2 (I guess this from`py_2`).

conda list | grep pbcore
pbcore                    2.1.2                      py_2    bioconda

So, thanks to Bas at PacBio I did:

conda search pbcore
Loading channels: done
# Name                       Version           Build  Channel             
pbcore                        1.2.10          py27_0  bioconda            
pbcore                        1.2.10          py27_1  bioconda            
pbcore                        1.2.10          py27_2  bioconda            
pbcore                         1.5.1          py27_0  bioconda            
pbcore                         1.5.1          py27_1  bioconda            
pbcore                         1.5.1          py27_2  bioconda            
pbcore                         1.6.5          py27_0  bioconda            
pbcore                         1.7.1          py27_0  bioconda            
**pbcore                         2.1.2          py37_0  bioconda**            
**pbcore                         2.1.2          py37_1  bioconda**            
pbcore                         2.1.2            py_2  bioconda            


and install either of the packages with Build=py37:

conda install -c bioconda pbcore=2.1.2=py37_1

and checked again conda list:

conda list | grep pbcore
pbcore                    2.1.2                    py37_1    bioconda


But I still get the issue when running:

python /home/driuser/sw/apps-scripts/RepeatAnalysisTools/plotCounts.py -m  -i {} -o /home/driuser/output/PacBio/NoAmp_HTT_gDNA_17_09_2020/reports/reports/{/.} 1>/dev/null ::: /home/driuser/output/PacBio/NoAmp_HTT_gDNA_17_09_2020/reports/fastq/*HTT*fastq

**Traceback (most recent call last):
  File "/home/driuser/sw/apps-scripts/RepeatAnalysisTools/plotCounts.py", line 8, in <module>
    from pbcore.io import FastaReader,FastqReader
ModuleNotFoundError: No module named 'pbcore'**

Hope you can help me.
Many thanks!
kristina

**Comment by kibanez** [comment]
Hello again, 

I finally fixed this issue as follows:

1 - Deactivate conda virtual environment
2 - Install conda `pbcore` with python3 build
3 - Activate conda virtual environment
4 - Not activate our python3 virtual environment, and just run with the default python3 conda version

Now it's running. Closing this ticket.
Thanks for your support.
Kristina
