### ISSUE TITLE
pbmerge - sort order

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#333]
What sort order does pbmerge use - position or read name? Can this be modified?
If not, can I use samtools merge?

**Comment by natechols** [comment]
https://pacbiofileformats.readthedocs.io/en/9.0/BAM.html#bam-sorting-conventions
`samtools merge` will certainly run with our BAM files, but I can't promise that other PacBio tools will still read the output without complaining if you change the sort order.  (But if you're planning to run a 3rd-party tool, then no problem.)

**Comment by gevro** [comment]
I want to run ccs (with chunking) -> merge -> lima to demultiplex.
Will pbmerge work in this step? Because it is not yet aligned. So what sort order will pbmerge use?

What is the best way to do this?

**Comment by armintoepfer** [comment]
Yes, just use pbmerge on the ccs chunks. After that demux the merged ccs bam file.
