### ISSUE TITLE
Bug in lima

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#334]
Hi, I found a bug in lima (lima 1.11.0 (commit v1.11.0))
If lima is run after ccs, it is not retaining the full read name.

After ccs --by-strand, the read name is in the format:
m54312U_200904_200413/44/ccs/fwd 

After lima, the read name is in the format:
m54312U_200904_200413/81/ccs

The 'fwd' and 'rev' signifiers are removed. This is a definite bug.

There is no reason that the read name should be modified by lima. It should be forwarded exactly as it is.

Can you please fix this?
Thanks.

**Comment by armintoepfer** [comment]
I'll have a look at it.

**Comment by armintoepfer** [comment]
Please use the latest lima, version 2.0.0. It has been fixed using BAM as in and output.
