### ISSUE TITLE
ccs - Heteroduplex insertions when running by-strand

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#335]
What is the meaning of the ccs 'heteroduplex insertion' filter when running --by-strand?
It still seems to use this filter, but technically, the heteroduplex filter should not be active when running --by-strand.

**Comment by armintoepfer** [comment]
Opening multiple tickets does not have a positive effect on me replying quicker.

**Comment by gevro** [comment]
I put each issue in a separate ticket. Sorry if it was too many and next time I can pool all the issues together in one post. However, is there an answer to the above?
