### ISSUE TITLE
lima removed bam file name

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#336]
Hi, The lima documentation says that the output filename of --dump-removed should be prefix.lima.removed.bam. However, it appears to be saving as prefix.removed.bam.

This is with lima 2.0

**Comment by armintoepfer** [comment]
Thanks. I'll fix that, but it's not an urgent must fix release :)

**Comment by armintoepfer** [comment]
Internally fixed. Will be part of the next release.
