### ISSUE TITLE
Unable to pbmerge barcoded chunked ccs files

### ISSUE THREAD

**Issue by KatyMunson** [PacificBiosciences/pbbioconda#338]
**Operating system**
CentOS7 on SGE cluster

**Package name**
ccs, pbmerge

**Describe the bug**
Trying to run ccs v5 on an old SMRT Link 8.0-demultiplexed subreadset. Trying to run in `--chunk` mode gave error that I couldn't use chunk and filters at the same time. The only filter in the subreadset.xml was for bq. I removed the filter from the .xml file and ran ccs in chunks, but trying to merge the chunks with `pbmerge` I'm getting 
```[kmiyamot@e137 bcAd1002T]$ pbmerge -o bcAd1002T.ccs.bam */*.consensusreadset.xml
pbmerge ERROR: BamFileMerger: could not get movie name from file: [[path]]/ccs_v5/bcAd1002T/chunk_11/bcAd1002T.11.bam (reason = BamHeader: read group ID not found: da37d352/1--1)
```
The `@RG` header in the .bam file starts `@RG     ID:da37d352     PL:PACBIO`

**commands**
```
[for 24 chunks]
cd chunk_${chunk}
ccs --chunk ${chunk}/${totalchunks} --all --subread-fallback -j 8 ../lima.bcAd1002T--bcAd1002T.subreadset.xml bcAd1002T.$chunk.consensusreadset.xml
cd -
[at the end]
pbmerge -o bcAd1002T.consensusreadset.xml chunk_*/bcAd1002T.*.consensusreadset.xml
```

**Comment by natechols** [comment]
Maybe you need to update pbmerge/pbbam?  We've been using the new barcoded `@RG` names for a while now.

**Comment by KatyMunson** [comment]
That was it. According to the person who updated this software for me, the conda version we were working with pulled new builds for all packages except `pbbam`. He rebuilt with a newer conda and specified 1.6.0 as the `pbbam` version and `pbmerge` appears to be working now. Thanks @natechols !
