### ISSUE TITLE
Falcon: too many jobs in daligner-runs folder, increases the space usage

### ISSUE THREAD

**Issue by jayceejiao** [PacificBiosciences/pbbioconda#34]
Hi,

I have two plant genomes with similar genome size (1Gb), repeat content (~70%) and PacBio coverage (90-100X), and I used falcon (falcon-kit 1.2.3, from pb-assembly installed through conda) to assemble both. The pipeline was completed without any issues for only one of them. And the assembly is good. The other one was far more slower than the finished one and generated 1049 jobs in daligner-runs (occupying 11T) and 500 jobs (200 jobs occupy 4T) in las-merge-runs. I had to kill the jobs because the server was almost out off space. Then I added the repeat filter option in the configuration file, deleted the output files and started the pipeline again, I found I still have 1049 jobs in daligner-split/daligner-scripts/. I am running the job locally.  Is there any thing I can do to reduce the job number? Here is my configure file:

```
[General]
job_type = local
input_fofn=input.fofn
input_type=raw
pa_DBdust_option=true
pa_fasta_filter_option=streamed-median

pa_HPCTANmask_option =
#pa_HPCREPmask_option =
pa_REPmask_code=0,300;0,300;0,300

#Data Partitioning   large genomes
pa_DBsplit_option=-x500 -s200
ovlp_DBsplit_option=-x500 -s200

#Pre-assembly
genome_size=923000000
seed_coverage=40
length_cutoff=-1
pa_HPCdaligner_option=-v -B128 -M24
pa_daligner_option=-e0.8 -l2000 -k18 -h256 -w8 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 3 --max-n-read 300 --n_core 8
falcon_sense_greedy=False

#Pread overlapping
ovlp_daligner_option=-e.93 -k24 -l1800 -h600 -s100
ovlp_HPCdaligner_option=-v -B128 -M24

#Final Assembly
overlap_filtering_setting=--max-diff 100 --max-cov 300 --min-cov 4 --n_core 12
fc_ovlp_to_graph_option=
length_cutoff_pr=4000

# job concurrency settings for...
# all jobs
default_concurrent_jobs = 64
# preassembly
pa_concurrent_jobs = 64
# consensus calling of preads
cns_concurrent_jobs = 64
# overlap detection
ovlp_concurrent_jobs = 64

jobqueue = your_queue
sge_option_da = -pe smp 4 -q %(jobqueue)s
sge_option_la = -pe smp 20 -q %(jobqueue)s
sge_option_pda = -pe smp 6 -q %(jobqueue)s
sge_option_pla = -pe smp 16 -q %(jobqueue)s
sge_option_fc = -pe smp 24 -q %(jobqueue)s
sge_option_cns = -pe smp 8 -q %(jobqueue)s
```

**Comment by gconcepcion** [comment]
What repeat option did you add? you have `pa_REPmask_code=0,300;0,300;0,300` but that's the no-op "don't filter repeats" option.  

You should set the Group Size & Coverage according to Gene Myer's blog here if you want to effectively filter out repeats 
https://dazzlerblog.wordpress.com/2016/04/01/detecting-and-soft-masking-repeats/
`pa_REPmask_code=group_size,coverage;group_size,coverage;group_size,coverage`

What option did you have for the one that worked? Are the plants similar in biology, (e.g. closely related species?) or only in genome size?  I'm wondering why one would result would be so different.

**Comment by jayceejiao** [comment]
Hi,

Thanks for your help. I read the link you provided and edited this option to "pa_REPmask_code=**1,1300;2,195;3,20**",  and "pa_DBsplit_option=**-x1000** -s200. In my case, with -s200, 1 block will represent 0.5X coverage. So the three runs of repeat masking will mask regions representing 2500X, 187X and 13X, respectively. And with -x1000, I think reads less than 1kb will also be removed. Now the three runs of the REPmask were finished, but I still got 1049 jobs under this folder 0-rawreads/daligner-split/daligner-scripts/. Does that mean the reads were not filtered by the repeat masking step and 1kb option?

**Comment by pb-cdunn** [comment]
The number of jobs is completely unrelated to repeat-masking. What REPmask (and TANmaks and DBdust) does is pretty simple: It produces a "mask-track", which **daligner** uses to avoid generating kmers for some regions. The result is lower memory and fewer comparisons.

But the daligner jobs are partitioned to do all-pairs comparisons of the blocks in your DB, and the number of blocks is determined solely by data-size and `DBsplit` parameters.

So this is all as expected.

I'm glad you found useful settings for `pa_REPmask_code`.
