### ISSUE TITLE
Runing with CCS with a single chunk looses reads

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [PacificBiosciences/pbbioconda#340]
**Operating system**
Docker container

**Package name**
quay.io/biocontainers/pbccs:4.2.0--0

**Conda environment**
Not applicable

**Describe the bug**
When I run CCS with `--chunk 1/1"`, I get fewer reads in the `report.txt` than when I simply run CCS without the chunk argument.

**Error message**
Not applicable

**To Reproduce**
Run CCS on a bamfile with and without `--chunk 1/1`, and notice the difference in number of reads in the report.txt file and the actual output bamfile.

**Expected behavior**
Using `--chunk` should not lead to fewer reads.

**Comment by armintoepfer** [comment]
Please use the latest version and try again

**Comment by Redmar-van-den-Berg** [comment]
This no longer happens with version 5.0.0
