### ISSUE TITLE
Question: What is the meaning of the new "ZMWs shortcut filters" statistic for CCS?

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [PacificBiosciences/pbbioconda#342]
When comparing the output between CCS version 4.2 and 5.0.0, I noticed that there is a new entry called `ZMWs shortcut filters` in the text report (`id: zmw_2_pass_shortcut` in the json report)

How should this number be interpreted? I'm writing a MultiQC module for CCS, should `ZMWs pass filters` + `ZMWs fail filters` + `ZMWs shortcut filters` be equal to `ZMWs input`?

In version 4.2, the text report had letters for the sections (`ZMWs filtered       (C)`), which made it possible to know which sections belong together. In the new report, these section letters have been removed, and the json format has all values in a single list under `attributes`. Is there an overview somewhere of all entries that can be present in the `attributes` and their interpretation?

**Comment by armintoepfer** [comment]
https://ccs.how/faq/reports-aux-files.html
https://ccs.how/faq/mode-all.html#how-does---all-work

Knock yourself out with the new docs. If they don't answer your questions, let's work together on clarifying.

**Comment by Redmar-van-den-Berg** [comment]
Thank you for the link to the FAQ, the example report really helps interpreting the values.

I still have questions about where the `ZMWs with tandem repeats` field fits. All values under `
Exclusive counts for ZMWs failing filters` sum to `ZMWs fail filters`, and `ZMWs pass filters + ZMWs fail filters  + ZMWs shortcut filters = ZMWs input`. Is `ZMWs with tandem repeats` part of `ZMWs shortcut filters`?

I also noticed that the `--min-tandem-repeat-length` is not listed when you run CCS version 5 with `ccs --help`.

**Comment by armintoepfer** [comment]
The identified tandem repeats are not exclusive and the percentage is with respect to `ZMWs input`.

There are many options not explicitly stated in `--help`, ~75 overall, as they would overwhelm the average user. More experienced users, use the official documentation to tune further.
