### ISSUE TITLE
Pbsv discover ERROR: map::at

### ISSUE THREAD

**Issue by SongboWangGit** [PacificBiosciences/pbbioconda#345]
Hi

I met 'Pbsv discover ERROR: map::at' when I use PbSV on a ONT format BAM file. 
The command line is: pbsv discover mybam out.pbsv.svsig.gz
But this error didn't happen when I ran any other BAMs with Pbsv.

**Comment by armintoepfer** [comment]
This is strange, but I can't guarantee PacBio software running properly on ONT data. Can you reproduce it on a small BAM file and share that with me?

**Comment by adbeggs** [comment]
Same problem here.. happy to share a compacted BAM file if helpful?
