### ISSUE TITLE
lima tag definitions

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#346]
Hi,
I can't find definitions for tags added by lima. Can you please provide definitions for these?
qs
qe
bc
bq
cx
bl
bt
ql
qt
bx

**Comment by armintoepfer** [comment]
https://pacbiofileformats.readthedocs.io/en/10.0/BAM.html

**Comment by gevro** [comment]
Thanks, but some tags are not listed there:
bl, bt, ql, qt

Additionally, lima is adding non-zero qs and qe tags, which shouldn't be there. I am running lima after ccs, and according to PacBio formats page, qs and qe should be absent in CCS BAM files.

**Comment by armintoepfer** [comment]
We'll add those in the next round.

The spec says CCS BAM files don't include them. The spec doesn't state anything demultiplexed CCS BAM files ;) Feel free to ignore them.
