### ISSUE TITLE
TLEN = 0 in BAM file after pbmm2

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#347]
TLEN (9th column in BAM file) always equals 0 after pbmm2. I know that this is not required to be set according to SAM specs. However, why isn't this set by pbmm2? It would be easier for assessing insert sizes than calculating from CIGAR.

**Comment by armintoepfer** [comment]
As you said, it's not required and likely mm2 also didn't set it, when I created the frontend. I will see to add it to the next version

**Comment by zeeev** [comment]
Hi @gevro, we are now populating TLEN.

**Comment by gevro** [comment]
Hi, I found an incorrect TLEN in an alignment:
m84190_250131_200610_s2/223940317/ccs/rev       2048    chrM    15872   60      4468S70=1X122=1X19=1X116=1X52=1X39=1I212=2D61=1694S     *       0       700

SEQ = TTTTTTCCCAAACTCATTTACAGAACTTTTACTTACATCTCATTTCGCTAAAACATAGTCATGTAATTATACCTAGCAACTAGGGAACCTGAGGAATGTAATCTATCATCTGGATTACAGTGTGTCCGGCTAAAAGTCAGGTTTCCTATTACTAAAGAAGAAGGCAAAAATGTATATTGGGAGGCAATTAGTAGTCTCTGCCACACACAAAAAACAGAAATGCAAAATAAACTTCAATGAGTAATGCCTTTAGCCTATCAGATTGACAGAACAAACAAATCAAAGACCAAAAGTTTTGGAGAAACAGGTGCTCTCTTGTTATTGAGAATGGCCTAAATTGATAAAACCTCTGTGGGCTATAATTAATTAACATCTATCAAAATTTTTAAAATATATATCTTTTGATGCAACCAAATTTTGTACATATGTACAAAGTTATTTATTGCGGTGTGATTTGAAAAATAGCGAAAACTTACAAAGAAAACTGTCAAAGAATATGGGATTAATTTAATACATTATAATCCATTCATTCAATTTAATACTATGTAGCCGTTAAGAAGAATGAGGTAGTTCTGTATGTACTAATGAGGTATGATCTCAAGAACACACCATCAGTCCCCCTCCCCCAGGAAAACTTTTTAAAGAATACACTAATGGCCAGGCGTGGTGGCTCACACCTGTAATCCCAGCACTTTGCAAGGCCAAAGTGGATGGATCACTTGAGGCCAGGGGTTTGAGACCAGCCTGGCCAACATGGCAAAACCCCATCTCTACTAAAAATACAAAAAATTAGCCTGGCATGGTGACATGCTTCTGTAATCCCAGCTACTCCAGAGGCTGAGGCAGGAGAATCACTGGAACCTGGGAGACACAGGTTGCAGTGAGCTGAGATCGCGCCACAGCACTCCAGCCTGGGCAACAGAGCATGACTGTGTCTCAAAAATAATAATAATAATAATAATAATAATAATAATAATAATACATTATTAAATTAAGTGTAAAGGTATATTCAGAACAGTGTTTATAGGATGTTCCCATGTATTATTAAAATGTATAACTTTGGGAGGCCAAGGTGGTTGGATCACTTGAGGTCAGGAGTTCGAGACCATCCTAGCCAACATGATGAAACCCCCTCTCTACTAAAAAACACAAAAATTAGCTGGGCGTGGTGGCGCATGTCCATAGTCCCAGCTACTCAGGAGGTTGAGGCAGGAGAATCATTTGAACCCAGGAGGCAGAGGTTGCAGTGAGTTGTGATCGTGCCACTGCACTCAAATCTGGGTGACAAAGCGAGACTGTCTCAAAAAATATTATTTGAGACAAAAAAAAAAATAGAATAATTTTTTTTGTTCGTTTGAGACAAAGTACCGCTCTGTCGCCCAGGCTAAAGTGTAGTGGCGTGATCTCAGCTCACTGCAACCTCCGCCTTCTGGGTTCAAGCAGTTCTTCTGCCTCAACCTCCCAAGTAGCTGGGACTACAGGTGCCCGCCACCATGCCTGGCTAATTTTTGTATTTTTAGTAGAGACAGGATCTCACCATGTTGCCCAGGCTGGTCTTGAACTCCTGACCTCAAGTGATCTGCCTGCCTCGGCCTCCCAAAGTGCTGGGATTCTAGACATGAGCCACCACACCAGGCCTAAATAAAATTATTGAGACTAGGTGGGACTCCAAAAATAAATAGCAAAAAAATTAAATTAAACATAAAATAAAACTAATTGACCAGTTGAGATTTTGGTTCTGGAAGTAAATTCATTGCTTTTTTGAATTCCTATAATTTTGTAACTTTGTCAGAGAAGTTTGCTGTGGGTGACAAGGCAGTATTCAAACAGACCTTAAAAATTAAATTTTTTAGCTGGTCATGGCATACACACCTATAGTCCCAATTTCTCAGGGGACTGAGGTGGGAAGATTCCTTGAGCCTCAGGACACTCCAGCCCACTGCATTCTAGCCTGGGCAACATAGTGAGACCCTGTCTCTAAAAAAAAAAAGTTTTCTTTTATTTTAAAAAGTCTAGAATGAATGTGTGTGTGTATGTGTGAAATAATTCTATAAACCTTCCCTTCTCTCCTTCACCTCTAGTGTACACACTCTACCTTTCATGACTTTTCTCCTATTTCAGCTCTCCTTATATTTAACCCCAAATCACTAATCTCAATGTACCAGGGAGGAGGATGATATAGAATTAAGAATGGGCCAGGCACGGTGGCTCACGCCTGTAATCCCAGCACTTTGGGAGGCCAAGGCTGGCAGATCCCAAGGTCAGGAGATCGAGACCATCCTAGCCAACATGGTGAAACCCCGTCCCTACTAAAAATACAAAAAAATTAGCTGGGCGTGTTGTCACACACCTGTAATCCCAGCTATTCGGGAGGCTGAGGCAGGAGAATCACTTGAACCCAGGAGGTGGAGGTTGCAGTGAGCCAAGATCACGCCACTGCACTCCAGCCCTCTAGCCTGGGCGACACAGCAAGACTCCATCTCAAAAAAAAAAAAGAAAAAAGAATTAAGAATGAAGCTTATGTTATTTCCTTCACTAAGAAAGCACCTAGAAGGCTGTATCAGTCAAAATTCTTTTTAGCCACAAGTGGCAGAAACACAGGGCAATCCGGCTTAAGCCCATAAAACCAGTAAGTCTAGGGTATGGCTGGATTCAGAGGCTCAAATGATATTGTCAACATTCTGGCTCTGTCTCATCTTTCAGTTCTGCCTTCTTTACAGTAAGTTTATTTCTCAGACAGACTCTCCCTTTGCACTAGCAACATGGCTGCTGGCAGCCTTAGATTCTTATTCTCATAACAGAACCATCTCAGCCAAGAGAACTTGGCCTGGGTTATGTGTCTAGTCCTTGAGTGAGTATCCTGACCAGATCACGTGGACTGAGGGAATGAAGGGAAACCCAGGTGCTTTTATACCAGAAGGAGGAATGGCTACAGGTGAGGGCTAGTCCCTGGGCCTGTTTGCCCCACTTCAGAAGCTCTGCTCTGTATTGCTGGGAGGGCTGGCTCCTACAGGATACATTCCTCAAGCTCCAGGTCACCTGGTTCCTGGTTATGATGGCCTATTGCGAGACACTGATGAGAGACTAGAGGGAGGGAGAAGGCAAGGAGTTTCCTCCCCTCCTCTTTACTGCATGATTTCTCCAGCAATGGTAGTTGTTGCCTTCCTGGCCCCATCTCCCACTGGATAAATACTCCATGTTTCTTTCTTTTTTTCTTTTTTTCTTTTTTTTTTTTTTGAGACAGAATTTCACTCTGTCACCCAGGCTGGAGTGCAGTGGCGCAATCTCAGCTCACTGCAGCCTCCACCTCCCGGGTTCAAGCGATTCTCCTGCCTCAGCCTCCCAAGTAGCTGGGATTACAGGTGCCCACCACCACGCCTCGCTAATTTTTGTGTTTTTAGTAGAGATGAGGTTTCACTGTGTTGTTTAGGCTGGTCTCAAACTCCTGACCTCAGGTAATCCACCTGCCTCAGCCTCCCAAGGTGCTGGGATTATAGACGTGAGCCACCGCACCCAGCTAATGTTTCTTGATTCTCTGGGTAAACCTACCTCCAGACCTCTGGATATACCACCTCCACCTTTTGTTTCTCCAGCCTCAGGAAGTTAATGCCTTCCTGCTGTTGCTAATCTCTAGATTGCCTCATGGTACCCAGTAGGCCTCTCAGCTCTTCCATTATAAATGTAACCAAGTGCCTGTATTACATTACCCCTCTTTTCAATATCCAGAGTGGTTTCTATTTTCCTGACTGATATATGCAGGAAAATATCCACTCCAAACTCCCCTAAGCAAGGCCCCTATGTCTCAACATTGTGCTCATTGGTCTGGAGAGAAGCTTCTGGAATTCCATCCCTGCTCCCAGAATTTGTGCCTCAGGATGAATTAGCCAAAGGAGAAAAAGGCAAGTCATTTAACTCCTCTGGGCCTCAGTTTCCTCCTCTATAAATTTGGGATGATACCATTTGTGGGAGACTGAATACATGGCAGCCTCCAAAAGGTATATTCAAGTCCTAATCCCCAGAACCTGTAAATACTGCCTTATTTGGACAAAGGGCTTTACAAATGTAATTAGGGTAAGGATTTTGAGATGAGGAGATCTTCCTGGATTATCTAGGTGGACCCTAAGTCCCAGGACAAGTGCCCTTATGAGAGAGACACACAGAGAATGCATACAGAGAAGAGAAGCAATGTGACCACAGAGATAGAGATTGGAGTGATGCAGCCACAAACCAAGGAGTGCTGACAGCTACTAGAAGCCAAAAGAGGCAAGGAACCGATTCTTCCCCAGAGGTATGGGAGGCAGTGAAGCTCCTACGACACCTTGATGACAGACTTTTCGCCTCAAGCACTGTGCGAAAATAAGCTTCAATTGTTTTCAACCACCAAGTTTGGGATAATTTGTTACAGCAGGCACAGGAAATTAATACACCGTTTTACTTCATAGGGTCGTTGTATTTGTTTGCTAGAGCTCGCTCCGGGCCCATAACACTTGGGGGTAGCTAAAGTGAACTGTATCCGACATCTGGTTCCTACTTCAGGGCCATAAAGCCTAAATAGCCCACACGTTCCCCTTAAATAAGACATCACGATGGATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTTCGTCTGGGGGGTGTGCACGCGATAGCATTGCGGGACGCTGGAGCCGGAGCACCCTATGTCGCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATTACAGGCGAACATACTTACTAAAGTGTGTTGATTAATTAATGCTTGTAGGACATAATAATAACAATTGAATGTCTGCACAGCCGCTTTCCACACAGACATCATAACAAAAAATTTCCACCAAACCCCCCCCTCCCCCCGCTTCTGGCCACAGCACTTAAACACATCTCTGCCAAACCCCAAAAACAAAGAACCCTAACACCAGCCTAACCAGATTTCAAATTTTATCTTTTGGCGGTATGCACTTTTAACAGTCACCCCCCAACTAACACATTATTTTCCCCTCCCACTCCCATACTACTAATCTCATCAATACAACCCCCGCCCATCCTACCCAGCACACACACCGCTGCTAACCCCATACCCCGAACCAACCAAACCCCAAAGACACCCCCCACAGTTTATGTAGCTTACCTCCTCAAAGCAATACACTGAAAATGTTTAGACGGGCTCACATCACCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTAAGATTACACATGCAAGCATCCCCATTCCAGTGAGTTCACCCTCTAAATCACCACGATCAAAAGGGACAAGCATCAAGCACGCAGCAATGCAGCTCAAAAACGCTTAGCCTAGCCACACCCCCACGGGAAACAGCAGTGATTAACCTTTAGCAATAAACGAAAGTTTAACTAAGCTATACTAACCCCAGGGTTGGTCAATTTCGTGCCAGCCACCGCGGTCACACGATTAACCCAAGTCAATAGAAGCCGGCGTAAAGAGTGTTTTAGATCACCCCCTCCCCAATAAAGCTAAAACTCACCTGAGTTGTAAAAAACTCCAGTTGACACAAAATAGACTACGAAAGTGGCTTTAACATATCTGAACACACAATAGCTAAGACCCAAACTGGGATTAGATACCCCACTATGCTTAGCCCTAAACCTCAACAGTTAAATCAACAAAACTGCTCGCCAGAACACTACGAGCCACAGCTTAAAACTCAAAGGACCTGGCGGTGCTTCATATCCCTCTAGAGGAGCCTGTTCTGTAATCGATAAACCCCGATCAACCTCACCACCTCTTGCTCAGCCTATATACCGCCATCTTCAGCAAACCCTGATGAAGGCTACAAAGTAAGCGCAAGTACCCACGTAAAGACGTTAGGTCAAGGTGTAGCCCATGAGGTGGCAAGAAATGGGCTACATTTTCTACCCCAGAAAACTACGATAGCCCTTATGAAACTTAAGGGTCGAAGGTGGATTTAGCAGTAAACTGAGAGTAGAGTGCTTAGTTGAACAGGGCCCTGAAGCGCGTACACACCGCCCGTCACCCTCCTCAAGTATACTTCAAAGGACATTTAACTAAAACCCCTACGCATTTATATAGAGGAGACAAGTCGTAACATGGTAAGTGTACTGGAAAGTGCACTTGGACGAACCAGAGTGTAGCTTAACACAAAGCACCCAACTTACACTTAGGAGATTTCAACTTAACTTGACCGCTCTGAGCTAAACCTAGCCCCAAACCCACTCCACCTTACTACCAGACAACCTTAGCCAAACCATTTACCCAAATAAAGTATAGGCGATAGAAATTGAAACCTGGCGCAATAGATATAGTACCGCAAGGGAAAGATGAAAAATTATAACCAAGCATAATATAGCAAGGACTAACCCCTATACCTTCTGCATAATGAATTAACTAGAAATAACTTTGCAAGGAGAGCCAAAGCTAAGACCCCCGAAACCAGACGAGCTACCTAAGAACAGCTAAAAGAGCACACCCGTCTATGTAGCAAAATAGTGGGAAGATTTATAGGTAGAGGCGACAAACCTACCGAGCCTGGTGATAGCTGGTTGTCCAAGATAGAATCTTAGTTCAACTTTAAATTTGCCCACAGAACCCTCTAAATCCCCTTGTAAATTTAACTGTTAGTCCAAAGAGGAACAGCTCTTTGGACACTAGGAAAAAACCTTGTAGAGAGAGTAAAAAATTTAACACCCATAGTAGGCCTAAAAGCAGCCACCAATTAAGAAAGCGTTCAAGCTCAACACCCACTACCTAAAAAATCCCAAACATATAACTGAACTCCTCACACCCAATTGG

TLEN = 700 here. But it should be 698 based on the CIGAR.

This is causing this alignment to extend past the end of chrM.

There must be some bug in calculating TLEN.
