### ISSUE TITLE
lima doesn't work when there's special characters in primers

### ISSUE THREAD

**Issue by maoge2333** [PacificBiosciences/pbbioconda#349]
**Operating system**
ubuntu

**Package name**
lima

**Describe the bug**
I have primer pair saved in fasta file:
`> CDS-3p`
`5'-AAGCAGTGGTATCAACGCAGAGTACT(30)VN-3' `
`> PCR_5p`
`5'-AAGCAGTGGTATCAACGCAGAGT-3' `

The primer contains special characters V and N. In fasta format, V represents A/G/T/C, and N represents A/G/C. 
It seems lima was unable to interpret the special characters, and gave the error message.

**Error message**
|> 20201102 18:03:33.969 -|- FATAL -|- Run -|- 0x7f2da3d1bb80|| -|- lima ERROR: invalid base!

**Expected behavior**
hopefully lima could accept special characters in primers, and trim them properly.

**Comment by armintoepfer** [comment]
This is not possible with the current implementation.
You should remove anything except for unambiguous nucleotides. It seems like you have a stretch of 30x ambiguous nucleotides. Such a degenerated design, common for UMIs, can't be trimmed by lima.
