### ISSUE TITLE
ccs discover ERROR: map::at

### ISSUE THREAD

**Issue by mkyriak** [PacificBiosciences/pbbioconda#351]
Hello,
I am trying to run ccs command on my subread.bam files in order to generate the consensus sequence, however I am getting this error: 
 ccs m54204U_200930_105506.subreads.bam m54204U_200930_105506.ccs.bam   # this is the command I am running

20201107 00:22:48.860 -|- FATAL      -|- operator() -|- 0x7fd010d72780|| -|- caught exception: "map::at"     
                                                                                                  20201107 00:22:48.860 -|- FATAL      -|- operator() -|- 0x7fd010d72780|| -|- caught SIGABRT                                                                                                                    Aborted

I have the indeces of the BAMs (.pbi). I am not sure what's happening.

Does anyone have any idea of what to do?

Thank you in advance,
Maria

**Comment by armintoepfer** [comment]
What CCS version are you using?

**Comment by mkyriak** [comment]
Hello @armintoepfer , I am using the latest version (5.0.0), which I downloaded using bioconda.

**Comment by armintoepfer** [comment]
Then please tell us

$ samtools view -H input.subreads.bam

**Comment by mkyriak** [comment]
Thank you, this is what I get:

@HD	VN:1.5	SO:unknown	pb:3.0.7
@RG	ID:6c559006	PL:PACBIO	DS:READTYPE=SUBREAD;Ipd:CodecV1=ip;PulseWidth:CodecV1=pw;BINDINGKIT=101-789-500;SEQUENCINGKIT=101-826-100;BASECALLERVERSION=5.0.0;FRAMERATEHZ=100.000000	PU:m54204U_200927_021422	PM:SEQUELII
@PG	ID:baz2bam	PN:baz2bam	VN:8.0.0.78867	CL:/opt/pacbio/ppa-8.0.0/bin/baz2bam /data/pa/m54204U_200927_021422.baz -o /data/pa/m54204U_200927_021422 --metadata /data/pa/.m54204U_200927_021422.metadata.xml -j 32 -b 8 --inlinePbi --progress --silent --minSubLength 50 --minSnr 2.000000 --adapters /data/pa/m54204U_200927_021422.adapters.fasta --controlAdapters /data/pa/m54204U_200927_021422.controls.adapters.fasta --controls /data/pa/m54204U_200927_021422.controls.fasta --maxInputQueueZMW 300000 --zmwBatchSize 75000 --zmwHeaderBatchSize 1000000 
@PG	ID:bazFormat	PN:bazformat	VN:1.6.0
@PG	ID:bazwriter	PN:bazwriter	VN:8.0.0
@PG	ID:samtools	PN:samtools	PP:baz2bam	VN:1.10	CL:samtools view -H m54204U_200927_021422.subreads.bam
@PG	ID:samtools.1	PN:samtools	PP:bazFormat	VN:1.10	CL:samtools view -H m54204U_200927_021422.subreads.bam
@PG	ID:samtools.2	PN:samtools	PP:bazwriter	VN:1.10	CL:samtools view -H m54204U_200927_021422.subreads.bam

**Comment by armintoepfer** [comment]
Can you please upload a minimal test case to reproduce? Feel free to send directly to me armin (at) pacb dot com

**Comment by mkyriak** [comment]
Hello @armintoepfer and thank you for your help. I realized that there were two versions of ccs on the server and they were interfering (v5.0.0 and v3.0.0). I removed both and I re-installed the v5.0.0. Now it works fine.
