### ISSUE TITLE
errors in polishing after clustering

### ISSUE THREAD

**Issue by DongnaMa** [PacificBiosciences/pbbioconda#352]
**Operating system**
Which operating system and version are you using?
Linux
**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?
isoseq3
**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)
it went wrong when i did polishing after clustering demo data from isoseq3. 
**Describe the bug**

**Error message**
Paste the error message / stack.
>|> 20201115 13:21:42.367 -|- ERROR -|- operator() -|- 0x2b2763668700|| -|- Could not find ZMWs for cluster transcript/6
>|> 20201115 13:21:42.368 -|- ERROR -|- operator() -|- 0x2b276406d700|| -|- Could not find ZMWs for cluster transcript/11
>|> 20201115 13:21:42.368 -|- ERROR -|- operator() -|- 0x2b276426e700|| -|- Could not find ZMWs for cluster transcript/12
>|> 20201115 13:21:42.384 -|- ERROR -|- operator() -|- 0x2b2763065700|| -|- Could not find ZMWs for cluster transcript/4
>|> 20201115 13:21:42.384 -|- ERROR -|- operator() -|- 0x2b2762e64700|| -|- Could not find ZMWs for cluster transcript/2
>|> 20201115 13:21:42.386 -|- ERROR -|- operator() -|- 0x2b276446f700|| -|- Could not find ZMWs for cluster transcript/13
>|> 20201115 13:21:42.387 -|- ERROR -|- operator() -|- 0x2b2764c73700|| -|- Could not find ZMWs for cluster transcript/17
>|> 20201115 13:21:42.388 -|- ERROR -|- operator() -|- 0x2b2762c63700|| -|- Could not find ZMWs for cluster transcript/1
>|> 20201115 13:21:42.388 -|- ERROR -|- operator() -|- 0x2b2764a72700|| -|- Could not find ZMWs for cluster transcript/16
>|> 20201115 13:21:42.388 -|- ERROR -|- operator() -|- 0x2b2763467700|| -|- Could not find ZMWs for cluster transcript/5
>|> 20201115 13:21:42.389 -|- ERROR -|- operator() -|- 0x2b2763266700|| -|- Could not find ZMWs for cluster transcript/3
**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!
ccs m64065_201020_094110.subreads.2--2.bam ccs.isoseq.bam -j 40 --skip-polish --min-rq 0.9
lima ccs.isoseq.bam primers.fasta demux.ccs.bam -j 20 --isoseq --peek-guess --no-pbi
isoseq3 refine demux.ccs.primer_5p--primer_3p.bam primers.fasta Isoseq.flnc.bam -j 20 --require-polya
isoseq3 cluster Isoseq.flnc.bam Isoseq.clustered.unpolished.bam --verbose 
isoseq3 polish Isoseq.clustered.unpolished.bam m64065_201020_094110.subreads.2--2.bam Isoseq.polished.bam -j 20 

There is an error in step 5, and I have tried many existing solutions on the web without solving the problem!

**Expected behavior**
finishing the polishing successfully.

**Comment by armintoepfer** [comment]
I'll have a look

**Comment by armintoepfer** [comment]
Can you please verify that the input to ccs is already demuxed and thus you are trying an unsupported workflow?

**Comment by DongnaMa** [comment]
yes，I sure that the input to ccs is already demuxed. The workflow is as follows:

ccs m64065_201020_094110.subreads.2--2.bam ccs.isoseq.bam -j 40 --skip-polish --min-rq 0.9
lima ccs.isoseq.bam primers.fasta demux.ccs.bam -j 20 --isoseq --peek-guess --no-pbi
isoseq3 refine demux.ccs.primer_5p--primer_3p.bam primers.fasta Isoseq.flnc.bam -j 20 --require-polya
isoseq3 cluster Isoseq.flnc.bam Isoseq.clustered.unpolished.bam --verbose
isoseq3 polish Isoseq.clustered.unpolished.bam m64065_201020_094110.subreads.2--2.bam Isoseq.polished.bam -j 20

**Comment by litao1503** [comment]
Hi @DongnaMa 
Has your problem been solved? 
I have encountered the same problem on multiple datasets. Unfortunately, I have not yet found a solution.

**Comment by DongnaMa** [comment]
Hi @litao1503 
Because I used HIFI sequencing, the accuracy is very high, so I did not polish
