### ISSUE TITLE
gcpp:terminate called without an active exception

### ISSUE THREAD

**Issue by yunshu1218** [PacificBiosciences/pbbioconda#354]
**Operating system**
CentOS
**Package name**
gcpp 2.0.0-v2.0.0
**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
aragorn                   1.2.38               h516909a_3    bioconda
barrnap                   0.9                           3    bioconda
bedtools                  2.29.2               hc088bd4_0    bioconda
blast                     2.10.1          pl526he19e7b1_2    bioconda
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.16.1               h516909a_3    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
cairo                     1.16.0            h3fc0475_1005    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
certifi                   2020.11.8        py38h578d9bd_0    conda-forge
cffi                      1.14.0           py38he30daa8_1    defaults
chardet                   3.0.4                 py38_1003    defaults
conda                     4.9.2            py38h578d9bd_0    conda-forge
conda-package-handling    1.6.1            py38h7b6447c_0    defaults
cryptography              2.9.2            py38h1ba5d50_0    defaults
curl                      7.71.1               he644dc0_8    conda-forge
entrez-direct             13.9            pl526h375a9b1_0    bioconda
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h7e3eb15_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
freetype                  2.10.4               h7ca028e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fribidi                   1.0.10               h36c2ea0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
giflib                    5.2.1                h36c2ea0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
glib                      2.66.1               h92f7085_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
graphite2                 1.3.13            h58526e2_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
graphviz                  2.42.3               h0511662_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
harfbuzz                  2.7.2                hee91db6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
hmmer                     3.3.1                he1b5a44_0    bioconda
htslib                    1.10.2               hd3b49d5_1    bioconda
icu                       67.1                 he1b5a44_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
idna                      2.9                        py_1    defaults
infernal                  1.1.3                h516909a_0    bioconda
jpeg                      9d                   h36c2ea0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
krb5                      1.17.1               h173b8e3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdb                     6.2.32               he1b5a44_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libdeflate                1.6                  h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libedit                   3.1.20181209         hc058e9b_0    defaults
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_1    defaults
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgd                     2.2.5             h341251c_1008    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libidn11                  1.34                 h1cef754_0    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libpng                    1.6.37               h21135ba_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h4f3a223_6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libtool                   2.4.6             h58526e2_1007    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libuuid                   2.32.1            h14c3975_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp                   1.1.0                h76fa15c_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libwebp-base              1.1.0                h36c2ea0_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxcb                    1.13              h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxml2                   2.9.10               h68273f3_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libxslt                   1.1.33               h572872d_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
lz4-c                     1.9.2                he1b5a44_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
minced                    0.4.2                         0    bioconda
ncurses                   6.2                  he6710b0_1    defaults
openjdk                   11.0.1            h516909a_1016    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pango                     1.42.4               h7062337_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
parallel                  20200922                      0    conda-forge
pbgcpp                    2.0.0                         0    bioconda
pbmm2                     1.4.0                h56fc30b_0    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
perl-aceperl              1.92                    pl526_2    bioconda
perl-algorithm-diff       1.1903                  pl526_2    bioconda
perl-algorithm-munkres    0.08                    pl526_1    bioconda
perl-apache-test          1.40                    pl526_1    bioconda
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-appconfig            1.71                    pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-array-compare        3.0.1                   pl526_1    bioconda
perl-autoloader           5.74                    pl526_2    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-bio-asn1-entrezgene  1.73                    pl526_1    bioconda
perl-bio-featureio        1.6.905                 pl526_2    bioconda
perl-bio-phylo            0.58                    pl526_2    bioconda
perl-bio-samtools         1.43            pl526h1341992_1    bioconda
perl-bioperl              1.6.924                       6    bioconda
perl-bioperl-core         1.007002                pl526_2    bioconda
perl-bioperl-run          1.007002                pl526_4    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-cache-cache          1.08                    pl526_0    bioconda
perl-capture-tiny         0.48                    pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-cgi                  4.44            pl526h14c3975_1    bioconda
perl-class-data-inheritable 0.08                    pl526_1    bioconda
perl-class-inspector      1.34                    pl526_0    bioconda
perl-class-load           0.25                    pl526_0    bioconda
perl-class-load-xs        0.10            pl526h6bb024c_2    bioconda
perl-class-method-modifiers 2.12                    pl526_0    bioconda
perl-clone                0.42            pl526h516909a_0    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-convert-binary-c     0.78            pl526h6bb024c_3    bioconda
perl-convert-binhex       1.125                   pl526_1    bioconda
perl-crypt-rc4            2.02                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-data-optlist         0.110                   pl526_2    bioconda
perl-data-stag            0.14                    pl526_1    bioconda
perl-date-format          2.30                    pl526_2    bioconda
perl-db-file              1.855           pl526h516909a_0    bioconda
perl-dbd-sqlite           1.64            pl526h516909a_0    bioconda
perl-dbi                  1.642                   pl526_0    bioconda
perl-devel-globaldestruction 0.14                    pl526_0    bioconda
perl-devel-overloadinfo   0.005                   pl526_0    bioconda
perl-devel-stacktrace     2.04                    pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-digest-perl-md5      1.9                     pl526_1    bioconda
perl-digest-sha1          2.13            pl526h6bb024c_1    bioconda
perl-dist-checkconflicts  0.11                    pl526_2    bioconda
perl-dynaloader           1.25                    pl526_1    bioconda
perl-email-date-format    1.005                   pl526_2    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-error                0.17027                 pl526_1    bioconda
perl-eval-closure         0.14            pl526h6bb024c_4    bioconda
perl-exception-class      1.44                    pl526_0    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-slurp-tiny      0.004                   pl526_1    bioconda
perl-file-sort            1.01                    pl526_2    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-file-which           1.23                    pl526_0    bioconda
perl-font-afm             1.20                    pl526_2    bioconda
perl-font-ttf             1.06                    pl526_0    bioconda
perl-gd                   2.71            pl526he860b03_0    bioconda
perl-getopt-long          2.50                    pl526_1    bioconda
perl-graph                0.9704                  pl526_1    bioconda
perl-graphviz             2.24            pl526h734ff71_0    bioconda
perl-html-element-extended 1.18                    pl526_1    bioconda
perl-html-entities-numbered 0.04                    pl526_1    bioconda
perl-html-formatter       2.16                    pl526_0    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tableextract    2.13                    pl526_2    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tidy            1.60                    pl526_0    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-html-treebuilder-xpath 0.14                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-image-info           1.38                    pl526_1    bioconda
perl-image-size           3.300                   pl526_2    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-sessiondata       1.03                    pl526_1    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-string            1.08                    pl526_3    bioconda
perl-io-stringy           2.111                   pl526_1    bioconda
perl-io-tty               1.12                    pl526_1    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-ipc-run              20180523.0              pl526_0    bioconda
perl-ipc-sharelite        0.17            pl526h6bb024c_1    bioconda
perl-jcode                2.07                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-lib                  0.63                    pl526_1    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-libxml-perl          0.08                    pl526_2    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-lwp-simple           6.15            pl526h470a237_4    bioconda
perl-mailtools            2.21                    pl526_0    bioconda
perl-math-cdf             0.1             pl526h14c3975_5    bioconda
perl-math-derivative      1.01                    pl526_0    bioconda
perl-math-random          0.72            pl526h14c3975_2    bioconda
perl-math-spline          0.02                    pl526_2    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mime-lite            3.030                   pl526_1    bioconda
perl-mime-tools           5.508                   pl526_1    bioconda
perl-mime-types           2.17                    pl526_0    bioconda
perl-mldbm                2.05                    pl526_1    bioconda
perl-module-implementation 0.09                    pl526_2    bioconda
perl-module-runtime       0.016                   pl526_1    bioconda
perl-module-runtime-conflicts 0.003                   pl526_0    bioconda
perl-moo                  2.003004                pl526_0    bioconda
perl-moose                2.2011          pl526hf484d3e_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-mro-compat           0.13                    pl526_0    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-ole-storage_lite     0.19                    pl526_3    bioconda
perl-package-deprecationmanager 0.17                    pl526_0    bioconda
perl-package-stash        0.38            pl526hf484d3e_1    bioconda
perl-package-stash-xs     0.28            pl526hf484d3e_1    bioconda
perl-params-util          1.07            pl526h6bb024c_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-parse-recdescent     1.967015                pl526_0    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-pdf-api2             2.035                   pl526_0    bioconda
perl-pod-escapes          1.07                    pl526_1    bioconda
perl-pod-usage            1.69                    pl526_1    bioconda
perl-postscript           0.06                    pl526_2    bioconda
perl-role-tiny            2.000008                pl526_0    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-set-scalar           1.29                    pl526_2    bioconda
perl-soap-lite            1.19                    pl526_1    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-sort-naturally       1.03                    pl526_2    bioconda
perl-spreadsheet-parseexcel 0.65                    pl526_2    bioconda
perl-spreadsheet-writeexcel 2.40                    pl526_2    bioconda
perl-statistics-descriptive 3.0702                  pl526_0    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-sub-exporter         0.987                   pl526_2    bioconda
perl-sub-exporter-progressive 0.001013                pl526_0    bioconda
perl-sub-identify         0.14            pl526h14c3975_0    bioconda
perl-sub-install          0.928                   pl526_2    bioconda
perl-sub-name             0.21                    pl526_1    bioconda
perl-sub-quote            2.006003                pl526_1    bioconda
perl-sub-uplevel          0.2800          pl526h14c3975_2    bioconda
perl-svg                  2.84                    pl526_0    bioconda
perl-svg-graph            0.02                    pl526_3    bioconda
perl-task-weaken          1.06                    pl526_0    bioconda
perl-template-toolkit     2.26                    pl526_1    bioconda
perl-test                 1.26                    pl526_1    bioconda
perl-test-deep            1.128                   pl526_1    bioconda
perl-test-differences     0.67                    pl526_0    bioconda
perl-test-exception       0.43                    pl526_2    bioconda
perl-test-harness         3.42                    pl526_0    bioconda
perl-test-leaktrace       0.16            pl526h14c3975_2    bioconda
perl-test-most            0.35                    pl526_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-test-warn            0.36                    pl526_1    bioconda
perl-text-diff            1.45                    pl526_0    bioconda
perl-threaded             5.26.0                        0    bioconda
perl-tie-ixhash           1.23                    pl526_2    bioconda
perl-time-hires           1.9760          pl526h14c3975_1    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-timedate             2.30                    pl526_1    bioconda
perl-tree-dag_node        1.31                    pl526_0    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-type-tiny            1.004004                pl526_0    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-unicode-map          0.112           pl526h6bb024c_3    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-dom              1.46                    pl526_0    bioconda
perl-xml-dom-xpath        0.14                    pl526_1    bioconda
perl-xml-filter-buffertext 1.01                    pl526_2    bioconda
perl-xml-libxml           2.0132          pl526h7ec2d77_1    bioconda
perl-xml-libxslt          1.94                    pl526_1    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526ha1d75be_1002    conda-forge
perl-xml-regexp           0.04                    pl526_2    bioconda
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-sax-writer       0.57                    pl526_0    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xml-twig             3.52                    pl526_2    bioconda
perl-xml-writer           0.625                   pl526_2    bioconda
perl-xml-xpath            1.44                    pl526_0    bioconda
perl-xml-xpathengine      0.14                    pl526_2    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
perl-yaml                 1.29                    pl526_0    bioconda
pip                       20.0.2                   py38_3    defaults
pixman                    0.38.0            h516909a_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prodigal                  2.6.3                h516909a_2    bioconda
prokka                    1.13                          2    bioconda
pthread-stubs             0.4               h14c3975_1001    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pycosat                   0.6.3            py38h7b6447c_1    defaults
pycparser                 2.20                       py_0    defaults
pyopenssl                 19.1.0                   py38_0    defaults
pysocks                   1.7.1                    py38_0    defaults
python                    3.8.3                hcff3b4d_0    defaults
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  h7b6447c_0    defaults
requests                  2.23.0                   py38_0    defaults
ruamel_yaml               0.15.87          py38h7b6447c_0    defaults
setuptools                46.4.0                   py38_0    defaults
six                       1.14.0                   py38_0    defaults
sqlite                    3.31.1               h62c20be_1    defaults
tbl2asn                   25.7                          0    bioconda
tidyp                     1.04                 h516909a_2    bioconda
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.46.0                     py_0    defaults
urllib3                   1.25.8                   py38_0    defaults
wheel                     0.34.2                   py38_0    defaults
xorg-kbproto              1.0.7             h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libice               1.0.10               h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libsm                1.2.3             h84519dc_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libx11               1.6.12               h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxau               1.0.9                h14c3975_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxext              1.3.4                h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxpm               3.5.13               h516909a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxrender           0.9.10            h516909a_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-libxt                1.1.5             h516909a_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xorg-xproto               7.0.31            h14c3975_1007    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.5                h6597ccf_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
**Describe the bug**
I am trying to polish a assembly of a staphylococcus epidermidis genome (about2.5M) with gcpp,and I see the error about terminate called without an active exception after running several hours, with output file 105Consensus.fasta.tmp

**Error message**
terminate called without an active exception
Aborted (core dumped)

**To Reproduce**

gcpp -j8 -r /pub/yuanjian/lsd/Biosoft/canu-2.1.1/output/105_1/105.contigs.fasta -o 105Variants.gff -o 105Consensus.fasta /pub/yuanjian/lsd/Biosoft/polishout/mapout/105.bam

**Expected behavior**
I hope I can polish the assembly genome seccessfully! Thank you so much !

**Comment by akiledal** [comment]
I'm getting the same error message while polishing a _Bacillus_ genome. However, it's working just fine for two other bacterial genomes (another _Bacillus_ and a _Rhodococcus_) with identical pre-processing.

**Operating system**
Fedora 31
**Package name**
gcpp 2.0.0-v2.0.0
**Conda environment**
```
# packages in environment at /work/akiledal/isolate_genomes2/.snakemake/conda/c0f2acec:
#
# Name                    Version                   Build  Channel
pbgcpp                    2.0.0                         0    bioconda
```

End of the log file:
```
>|> 20210213 04:00:11.660 -|- INFO -|- AddResult -|- 0x7fc8ca7fc700|| -|- Processed 5742500/5748923 (99%) bases of contig 'contig_1'
>|> 20210213 04:00:11.717 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8d36ef700|| -|- Coverage (all reads) in window "contig_1 [5744495, 5745005)": 90
>|> 20210213 04:00:12.235 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8cbfff700|| -|- Coverage (all reads) in window "contig_1 [5744995, 5745505)": 91
>|> 20210213 04:00:12.427 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8cb7fe700|| -|- Coverage (all reads) in window "contig_1 [5745495, 5746005)": 90
>|> 20210213 04:00:12.821 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8d21ee700|| -|- Coverage (all reads) in window "contig_1 [5745995, 5746505)": 93
>|> 20210213 04:00:13.002 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8d09eb700|| -|- Coverage (all reads) in window "contig_1 [5746495, 5747005)": 91
>|> 20210213 04:00:13.412 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8caffd700|| -|- Coverage (all reads) in window "contig_1 [5746995, 5747505)": 92
>|> 20210213 04:00:14.273 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8d19ed700|| -|- Coverage (all reads) in window "contig_1 [5747495, 5748005)": 94
>|> 20210213 04:00:14.985 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8d11ec700|| -|- Coverage (all reads) in window "contig_1 [5747995, 5748505)": 92
>|> 20210213 04:00:15.130 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8d36ef700|| -|- Coverage (all reads) in window "contig_1 [5748495, 5748923)": 96
>|> 20210213 04:00:15.539 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8cbfff700|| -|- Coverage (all reads) in window "contig_3 [0, 505)": 95
>|> 20210213 04:00:16.163 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8d21ee700|| -|- Coverage (all reads) in window "contig_3 [495, 1005)": 92
>|> 20210213 04:00:16.257 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8cb7fe700|| -|- Coverage (all reads) in window "contig_3 [995, 1505)": 92
>|> 20210213 04:00:16.381 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8d09eb700|| -|- Coverage (all reads) in window "contig_3 [1495, 2005)": 94
>|> 20210213 04:00:16.838 -|- INFO -|- AddResult -|- 0x7fc8ca7fc700|| -|- Processed 5748000/5748923 (99%) bases of contig 'contig_1'
>|> 20210213 04:00:16.937 -|- DEBUG -|- ConsensusForAlignments -|- 0x7fc8caffd700|| -|- Coverage (all reads) in window "contig_3 [1995, 2505)": 92
>|> 20210213 04:00:17.530 -|- INFO -|- MaybeFlushContig -|- 0x7fc8ca7fc700|| -|- Finished contig 'contig_1' with 5748923 expected bases
terminate called without an active exception
/usr/bin/bash: line 1: 766859 Aborted                 (core dumped) gcpp --log-level TRACE -j 8 -r data/assembly/C11_flye/C11_fixstart.fasta -o data/assembly/C11_flye/C11_polished.fasta data/assembly/C11_flye/C11_aligned.bam
```

**Comment by elcortegano** [comment]
I am also getting this error when polishing green alga genomes. The error appears after a call to "Calling variants for contig":

```
...
>|> 20210218 13:53:26.648 -|- INFO -|- AddResult -|- 0x7efc226e5700|| -|- Processed 51500/52007 (99%) bases of contig 'contig_133_1|arrow'
>|> 20210218 13:53:26.649 -|- INFO -|- AddResult -|- 0x7efc226e5700|| -|- Processed 52000/52007 (99%) bases of contig 'contig_133_1|arrow'
>|> 20210218 13:53:26.649 -|- INFO -|- MaybeFlushContig -|- 0x7efc226e5700|| -|- Finished contig 'contig_133_1|arrow' with 52007 expected bases
>|> 20210218 13:53:26.651 -|- INFO -|- MaybeFlushContig -|- 0x7efc226e5700|| -|- Calling variants for contig: contig_133_1|arrow
terminate called without an active exception
Aborted
```
It breaks for all our samples.

**Comment by akiledal** [comment]
pbgcpp 1.0.0-0 successfully polishes the same genome. @elcortegano, might be worth trying

**Comment by pb-dseifert** [comment]
If you're willing to boil down your data to a simple reproducing example and are willing to share it (which we obviously treat confidentially), we will have a look.

**Comment by armintoepfer** [comment]
You can upload data here https://portal.pacificbiosciences.com/ and send me the info to following mail: armin at pacb.com

**Comment by elcortegano** [comment]
Thank you all for the feedback. I am willing to submit files, so will prepare a zip shortly and submit it there (it should be smaller than 20GB in size) together with the commands used and the log generated.

Following @akiledal 's post, I was running now arrow from variantCaller 2.3.3, and seems to run well.

**Comment by armintoepfer** [comment]
We received your file and will report back with our findings.

**Comment by pb-dseifert** [comment]
With the help of @elcortegano we could finally fix the bug causing this. Version 2.0.2 includes the fixes. https://github.com/bioconda/bioconda-recipes/pull/27434
