### ISSUE TITLE
High heterozygosity organisms and (spurious) duplications

### ISSUE THREAD

**Issue by jensbast** [PacificBiosciences/pbbioconda#356]
Hi,
I think this topic is probably worth opening a separate issue.

I am assembling an organisms with high heterozygosity (2.4%) and probably complex genome structure.
This results in (spurious) duplications in the primary contigs assembly.

Running IPA v1.3.1, the purge_dups already included, it gives me a primary contig assembly, that has many duplications (BUSCO D: 75%) and total assembly size is very inflated compared to kmer genome size estimates (>1.5 fold).
Now as I understand, it can happen during assembly that highly diverged alleles/haplotypes get incorporated as duplicates instead of being represented as haplotigs in the alternative contigs.
I can solve this with my assembly by running another purge_dups round on the 19_final primary output, but not with running it on the data (14) again the internal purge_dups is running on (gives similar results as IPA internal purge).
Is this valid to run purge_dups again on the 19_final primary assembly or will it introduce other errors?
For me it seemed to work on the surface, because we get only 4% (expected) duplication after and primary and alternative contig total size is about the same. KAT analyses seem ok.

One other option to solve potentially solve this problem, I guess, is to give heterozygosity directly as parameter. This is implemented in FALCON, but not IPA. 
Is something like this planned for the IPA roadmap?

Many thanks again and best wishes,
Jens

**Comment by armintoepfer** [comment]
Closing to due lack of activity.
