### ISSUE TITLE
Sharding in polish_run stage of IPA requires substantially variable resources

### ISSUE THREAD

**Issue by ASLeonard** [PacificBiosciences/pbbioconda#357]
**Operating system**
Linux 

**Package name**
pbipa, the tool says `ipa (wrapper) version=1.3.1`, but the version reported by conda is 1.3.2.

**Conda environment**
Relevant pb conda packages are 
```
pb-falconc                1.10.3               he513fc3_0    bioconda
pbipa                     1.3.2                hee625c5_0    bioconda
pbmm2                     1.4.0                h56fc30b_0    bioconda
```

**Describe the bug**
This potentially isn't a bug, and just a feature of the data/pipeline, but some sharded tasks, specifically the *12-polish_run* tasks, can require substantially different resources. One task (s36.b41) required 356 cpu hours and 89 gb ram, while the majority of shards ran in <10 cpu hours and 20 gb ram. It doesn't appear this was occurring in other checkpoints, which had some variation but nothing as significant as the polish_run. 

The majority of the time and memory was in the pbmm2 step. I noticed in another wiki page for assembling hifi data that the `--ignore-indels` option in `overlap_filtering_setting` should always be used for hifi data in FALCON-Unzip3. This isn't a default in the IPA config advanced option `config_ovl_filter_opt`, while `--gapFilt` was. I wasn't sure if these different options might be causing pbmm2 to spike in memory/time through e.g. repeats?

My main concern was that this pbmm2 step for a single shard was requiring more resources than using e.g. minimap2 to map all reads back to an assembly.

Thanks,
Alex

**Comment by pb-cdunn** [comment]
Yes, in some cases **pbmm2** takes a long time, and we don't know a good way to predict when that might occur. The good news is that soon (next week or the week after) we will push a version that does not run **pbmm2** at all.

The shards are balanced by total bases in the reads. That should work pretty well after we upgrade.

**Comment by armintoepfer** [comment]
It's a `minimap2` limitation for low-complexity regions.

**Comment by ASLeonard** [comment]
Okay thanks, I'm looking forward to trying next release as these results were already quite promising.
