### ISSUE TITLE
ccs ERROR: Could not open file for reading:

### ISSUE THREAD

**Issue by Mpaperlee** [PacificBiosciences/pbbioconda#358]
I was using CCS 5.0.0 on my pacbio data, CentOS 7 ,and It report this BUG:
| 20201125 15:26:57.246 | FATAL | ccs ERROR: Could not open file for reading: /mnt/data/home/lzz/project/2020-9-22-CBRA_lung_scRNA-seq/results/lineage_tree_results/m64061_201109_091854/thread.0_1020.m64061_201109_091854.R1.ccs.raw.zmw

I try to less thread.0_1020.m64061_201109_091854.R1.ccs.raw.zmw, it can be found.

so I subset some data to run, it works; but when I use all my data, it happen agian, please help !!

**Comment by armintoepfer** [comment]
It's s file system issue. Please talk to your IT.

**Comment by CharlesARoy** [comment]
@armintoepfer could you elaborate on what might cause this issue (if you know)?

I've only found two other threads on the web ([here](https://www.biostars.org/p/9470362/) and [here](https://www.breathinglabs.com/monitoring-feed/genetics/isoseq-ccs-error-caught-io-problem-handling-zmw-file/)) that mention this issue and neither have a solution or any tips that would help IT figure this out.

In my case, I am able to run ccs 6.0.0 (commit v6.0.0-2-gf165cc26) on most files, but a few give me similar errors, which is strange.

**Comment by CharlesARoy** [comment]
Ultimately, I was able to resolve the issue by running the jobs on a drive that supported faster read/write speeds.

**Comment by armintoepfer** [comment]
Glad to hear
