### ISSUE TITLE
Somatic variant calling with pbsv and ploidy consideration

### ISSUE THREAD

**Issue by bingreily** [PacificBiosciences/pbbioconda#359]
I've read that pbsv supports multiple sample calling. Does this mean I can give a normal-cancer pair as input and do somatic variant calling? Or is germline variant calling of multiple samples the only provided feature right now? (pbsv 2.2.2)

Also, does pbsv consider ploidy when detecting copy number variants? (ex. for chrY, chrX)
If I get a copy number of "1" in chrX, am I supposed to translate this as a copy number gain or loss?

**Comment by zeeev** [comment]
Closed due to inactivity. Please reopen if needed.
