### ISSUE TITLE
Need a mechanism to better control what filesystems are used for running certain steps.

### ISSUE THREAD

**Issue by bruc** [PacificBiosciences/pbbioconda#36]
Our Linux cluster has two types of storage, Isilon and Lustre. We have found from running a previous version of Falcon that certain steps require Lustre and other require the Isilon. In particular, LA4Falcon is not happy running on the Isilon -- the seeks to find specific reads can take 100ms on average, whereas our Lustre based filesystem has much better seek performance (single ms or less). 

Handling this issue generally is probably too much, but would it be possible to specify an alternative location for running LA4Falcon and having pb-assembly copy the needed files to that location? It's also important that the copy operation not try to copy all the .las files in parallel -- our Lustre filesystem can handle only about 20 simultaneous copying processes at once.

**Comment by pb-cdunn** [comment]
> We have found from running a previous version of Falcon that certain steps require Lustre and other require the Isilon.

> In particular, LA4Falcon is not happy running on the Isilon -- the seeks to find specific reads can take 100ms on average, whereas our Lustre based filesystem has much better seek performance (single ms or less).

Ah! That explains a problem another user has seen. His work-around was always to try to run from `/dev/shm`. For him, we added these hidden options:
```cfg
LA4Falcon_pre = your-setup-script
LA4Falcon_post = your-cleanup-script
LA4Falcon_dbdir = /dev/shm/whatever
```
You can provide a pre-script which copies the DB into `/dev/shm/whatever`, and a post-script to delete it. For help with writing those hooks, here is the content of our ``:
```py
"""
This is meant to be used for LA4Falcon_pre/post hooks.
dbdir is probably /dev/shm.
"""
import os, shutil, sys

# We will ignore track files (.anno/.data).
suffixes = ('.idx', '.bps')

def log(msg):
    print(msg)
def rm(bn, dn):
    """Remove bn from directory.
    Skip silently if not found.
    Leave the directory tree.
    """
    fn = os.path.join(dn, bn)
    if os.path.exists(fn):
        log('rm -f "{}"'.format(fn))
        os.remove(fn)
def cp(bn, src_dn, dst_dn):
    """Copy bn from src to dst.
    Create dirs for dst_dn as needed.
    Over-write if exists in dst.
    Raise Exception if bn is not found in src_dn.
    """
    src_fn = os.path.join(src_dn, bn)
    dst_fn = os.path.join(dst_dn, bn)
    if not os.path.exists(src_fn):
        msg = 'Nothing found at "{}"'.format(src_fn)
        raise Exception(msg)
    if not os.path.isdir(dst_dn):
        log('mkdir -p "{}"'.format(dst_dn))
        os.makedirs(dst_dn)
    if os.path.exists(dst_fn):
        log('WARNING: {!r} already exists. Deleting and re-copying.'.format(dst_fn))
        rm(bn, dst_dn)
    log('cp -f "{}" "{}"'.format(src_fn, dst_fn))
    shutil.copy2(src_fn, dst_fn)
def clean(db, dbdir):
    """
    Remove db and dot-db files from dbdir.
    Assume the same basename was used.
    """
    bn = os.path.basename(db)
    assert bn.endswith('.db'), '{} does not end in .db'.format(bn)
    dbname = bn[:-3] # drop .db
    rm(bn, dbdir)
    for suffix in suffixes:
        bn = '.'+dbname+suffix
        rm(bn, dbdir)
def copy(db, dbdir):
    """
    Copy db and dot-db files into dbdir.
    (dbdir is probably /dev/shm.)
    """
    dn, bn = os.path.split(db)
    assert bn.endswith('.db'), '{} does not end in .db'.format(bn)
    dbname = bn[:-3] # drop .db
    cp(bn, dn, dbdir)
    for suffix in suffixes:
        bn = '.'+dbname+suffix
        cp(bn, dn, dbdir)
def main(prog, subcmd, db, dbdir):
    cmd2func = {'clean': clean, 'copy': copy}
    func = cmd2func[subcmd]
    func(db, dbdir)

if __name__ == "__main__":
    main(*sys.argv)  # pylint: disable=no-value-for-parameter
```
Good luck!

(In future, we will switch from **pypeflow** to **Cromwell**, which creates a whole new set of such problems, much harder to solve.)
