### ISSUE TITLE
bam2fastx conda package has pbindex that isn't compatible with latest data

### ISSUE THREAD

**Issue by cmfield** [PacificBiosciences/pbbioconda#361]
**Operating system**
Unix

**Package name**
bam2fastx

**Describe the bug**
In order to run bam2fasta or bam2fastq a .pbi index file is required. The conda package installs pbindex as part of pbbam, version 1.0.6 but this does not work on the most recent bam files because the read group ID (@RG ID:) in the header is not the same as the read group ID given in each read line (RG:Z:) where it is appended by /xx--xx where xx is a number

I tried an environment containing both bam2fastx 1.3.0 and pbbam 1.6.0 which solves the pbindex problem but then libpbbam is not usable by bam2fasta or bam2fastq. So I need two environments to do one essential job.

I also noticed that if you try to install more tools in the same environment such as blasr or lima, there are incompatbilities between the conda packages that make it impossible.

**Comment by conchoecia** [comment]
See issue https://github.com/PacificBiosciences/pbbioconda/issues/321 for bam2fastx issue

**Comment by pb-cdunn** [comment]
Should be fixed with bam2fastx-1.3.1. Please re-open if not.
