### ISSUE TITLE
pbmarkdup: Add parsable output format

### ISSUE THREAD

**Issue by Redmar-van-den-Berg** [PacificBiosciences/pbbioconda#365]
**Package name**
pbmarkdup 

```bash
pbmarkdup --version
pbmarkdup 1.0.2 (commit v1.0.2)
```

**Describe the bug**
I would like to parse the pbmarkdup summary output, but this is hard to do since the report is visually aligned using spaces.

**Expected behavior**
It would be nice if the summary output was tab/comma separated, or in json format, so that is is easier to parse automatically.

**Comment by armintoepfer** [comment]
You are correct. It is hard, but we don't plan to change it. You are better off to write a quick and dirty parser for the human-readable output.
