### ISSUE TITLE
IPA performance and ultra low protocol 

### ISSUE THREAD

**Issue by ptranvan** [PacificBiosciences/pbbioconda#366]
Hi,

I have data from the ultra low protocol. 
Then I ran IPA with the default parameters using trimmed and deduplicated HIFI reads (theoretical coverage: 50X) :

`ipa local --nthreads 20 --njobs 1 --tmp-dir tmp -i ../raw_fastq/deduplicated.ccs.fastq.gz`

However my assembly is very poor:

```
final.p_ctg.fasta: 
G.size: 65Mbp
# Contigs: 793
BUSCO: C:32.7%[S:32.0%,D:0.7%],F:2.1%,M:65.2%,n:1367

final.a_ctg.fasta:
G.size: 22Mbp
# Contigs: 873
```

The genome size is far from what I expect (450Mbp) and the BUSCO score is very low. 

1) My assumption is that the ultra low protocol cause too much coverage bias. Do you have some recommended parameters to look at ?

2) How IPA deals with coverage bias ? the regions with very low coverage: are they discarded ?

**Comment by zeeev** [comment]
Hi @ptranvan,

Can you check the contiguity statistics in the 10-assembly folder? It's possible that purge-dups is too stringent in this case and over-purging. Also in the 09 folder there's a coverage json file, can you post the contents here?

Best wishes,

Zev

**Comment by ptranvan** [comment]
hi @zeeev, thanks for your prompt answer. Indeed, it's a bit better but still incomplete:

```
10-assemble/p_ctg.fasta
G size: 318 Mbp
# Contigs: 12093
BUSCO: C:71.6%[S:68.2%,D:3.4%],F:6.9%,M:21.5%,n:1367 
```

```
10-assemble/a_ctg.fasta
G size: 12 Mbp
# Contigs: 971
BUSCO: C:2.3%[S:2.3%,D:0.0%],F:1.3%,M:96.4%,n:1367 
```

```
cat 09-ovl_filter/covstat.json 
{
    "mean": 140.5564024514024,
    "std": 276.631181941281,
    "median": 73.0,
    "min": 0,
    "max": 4453,
    "n": 4180758
}
```

**Comment by ptranvan** [comment]
Hi @zeeev, did you have the time to look at it ? Thanks !

**Comment by rob123king** [comment]
Try hifiasm, I had a poor assembly using ipa with little of genome assembled, it was 24x coverage but using hifiasm it did a good job. Might be a coverage issue that your 50x isn't 50x and ipa struggles with lower coverage?

**Comment by zeeev** [comment]
Hi @ptranvan,

I do not see anything out of the ordinary in the stats provided above. Given that HiFi assembly tools are really fast, I'd take @rob123king's suggestion. Which assembler will generate better stats depends on the genomes, I've seen it go either way. We'd be curious to see a comparison on your genome.

Thanks for reminding me about this ticket.

Best wishes,

Zev
