### ISSUE TITLE
genome circular issue about pb_assembly?

### ISSUE THREAD

**Issue by wanjinhu** [PacificBiosciences/pbbioconda#369]
what is the method of pb_assembly to identity the “circular” of genome?

**Comment by wanjinhu** [comment]
'''FALCON-Unzip  Improved Haplotig Extraction -algorithm and data structure improvements reduce haplotype switching and improve extraction -can now handle circular contigs!'''

**Comment by pb-cdunn** [comment]
A clear cycle in the assembly graph for an entire contig?
