### ISSUE TITLE
SMRTLink minor analysis vs CLI: shortcomings

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/pbbioconda#373]
I have a multiplex amplicon run (19 HIFI) which I submitted to CCS+demux.

The resulting data, when submitted in SMRTLink to minor analysis outputs a single result for all samples mixed (I took the CCS input demux with 19 samples).

Also, I did not find the way to upload my target_config.json (which works at CLI) in SMRTLink, resulting in frameshift in the reported codons. 

How can we upload custom target_config.json to SMRTLink?

By contrast the SMRTLINK version outputs a nice _minor_variants.report.csv_ file reporting all variants like in the html output which is good and what I need from CLI.

The CLI version worked well and I could use my custom target_config.json, giving 19 separate analyses but only html and json outputs and no _minor_variants.report.csv_.

Is it possible to convert the CLI json result files to a usable CSV table like in the GUI and do you have a script for that?

 _maybe a magic jq command?_

I need to compare my 19 samples for overlapping variants and using the html or raw json outputs is impossible (for me)

Thanks in advance
Stephane

<hr> 

PS: After hacking in the SMRTLink log and code I found this

```
python3 \
  -m pbreports.report.minor_variants \
  --log-level INFO \
  /data/pacbio/sequel/jobs_root.default/cromwell-executions/pb_mv_ccs/fdb61fc6-d186-487e-9b88-93dd99f87b0c/call-minorvariants/minorvariants/63a12dcf-ff25-40e6-8b00-19cce8461d24/call-pbreports_minor_variants/inputs/-102225952/minor_variants_data.json \
  minor_variants.report.json \
  minor_variants.report.csv
```

but I do not kn owwhat to do with it and do not find the _pbreports.report.minor_variants_ module

**Comment by armintoepfer** [comment]
For SMRT Link questions, please refer to https://www.pacb.com/support/technical-support/. Nobody on this board is working on SMRT Link.

I, as the minor variant author, don't have a gather script. Tech support might be able to tell you how to use the pbreports script.
