### ISSUE TITLE
pbipa updated version hasn't been released publicly  

### ISSUE THREAD

**Issue by ASLeonard** [PacificBiosciences/pbbioconda#374]
Hi,
I wanted to follow up on a previous comment exchange with @pb-cdunn without further hijacking issue #367.

In that issue, as well as #357, there are two comments ([here](https://github.com/PacificBiosciences/pbbioconda/issues/357#issuecomment-733245467) and [here](https://github.com/PacificBiosciences/pbbioconda/issues/367#issuecomment-766371929)) suggesting that a new version of `pbipa` will be or has been released, specifically a version that doesn't use `pbmm2`. Both the [IPA](https://github.com/PacificBiosciences/pbipa) and the conda version are predate these issues (last changed in October).

I'm hoping to present a comparison with `pbipa` at an upcoming virtual PacBio day, so I wanted to follow up and see if the new version has been publicly released yet, or how to otherwise access it.

Thanks,
Alex

**Comment by zeeev** [comment]
Hi  @ASLeonard, I know this reply is late, but we've updated the versions to v1.5.0.
