### ISSUE TITLE
tools to error correct single-pass reads

### ISSUE THREAD

**Issue by dcopetti** [PacificBiosciences/pbbioconda#376]
Hello,

This is a methodological question.
I have some single pass (Sequel II) reads that I would like to error correct with CCS reads, to combine the length and the accuracy.
Do you have any tool or method to recommend?
I am thinking of:
- alignment (minimap/winnowmap)
- consensus (arrow/medaka/pilon)
I am not up to date with the tools to handle PacBio data, so if there is anything nice and efficient, it would be very much appreciated.
Thanks,

Dario

**Comment by armintoepfer** [comment]
We don't have a recommended way. You could use methods similar to what people are doing to correct CLR with short reads.
It's an open question, but none that we plan to support.
