### ISSUE TITLE
bax2bam Error

### ISSUE THREAD

**Issue by lemontealala** [PacificBiosciences/pbbioconda#378]
I have downloaded a dataset from PacBio public database, and it contains metadata.xml, bas.h5, and bax.h5 files. I want to fetch subread fastq files from these using **bax2bam** package, but it fails and I don't konwn why. Here is my command:

`````
]$bax2bam --subread m141013_011508_sherri_c100709962550000001823135904221533_s1_p0.1.bax.h5 m141013_011508_sherri_c100709962550000001823135904221533_s1_p0.2.bax.h5 m141013_011508_sherri_c100709962550000001823135904221533_s1_p0.3.bax.h5 ``
**ERROR, could not read quality metrics for FASTQ Sequence** 
```


What is wrong with my command? Thanks if someone can help.

**Comment by rob123king** [comment]
I have the same issue with the tool using legacy data I downloaded..so good to here a response

**Comment by armintoepfer** [comment]
Please provide a link to the dataset.

**Comment by rob123king** [comment]
https://bigd.big.ac.cn/bioproject/browse/PRJCA001194

**Comment by pbjd** [comment]
I reproduced the error. The command is fine, it's a problem with `bax2bam` in bioconda and its ancient library dependencies that may be beyond repair at this point. A faster, more reliable route would be to pick up a copy from our official [SMRT Link software release](https://downloads.pacbcloud.com/public/software/installers/smrtlink_8.0.0.80529.zip). Install SMRT Tools only following the [installation docs](https://www.pacb.com/wp-content/uploads/SMRT-Link-Software-Installation-v8.0.pdf) and run `bax2bam` from there.

**Comment by lemontealala** [comment]
> Please provide a link to the dataset.

https://github.com/PacificBiosciences/DevNet/wiki/E.-coli-Bacterial-Assembly

It's an old dataset from PacBio RS II.

**Comment by lemontealala** [comment]
> I reproduced the error. The command is fine, it's a problem with `bax2bam` in bioconda and its ancient library dependencies that may be beyond repair at this point. A faster, more reliable route would be to pick up a copy from our official [SMRT Link software release](https://downloads.pacbcloud.com/public/software/installers/smrtlink_8.0.0.80529.zip). Install SMRT Tools only following the [installation docs](https://www.pacb.com/wp-content/uploads/SMRT-Link-Software-Installation-v8.0.pdf) and run `bax2bam` from there.

Thanks. But I didn't find 'bax2bam' in the latest release 'SMRT Link Tool v9.0', only bam2fasta/bam2fastq were found. Should I install the older version or SMRT Portal? And I checked my linux system, 
`
]$cat /proc/version 
Linux version 3.10.0-957.el7.x86_64 (mockbuild@x86-040.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) ) #1 SMP Thu Oct 4 20:48:51 UTC 2018
`
Is this linux system compatible with SMRT current version? Because I see 'SMRT Link server software is supported on English-language CentOS 6.x; 7.x and Ubuntu 16.04; 18.04 64-bit Linux® distributions. (This also applies to SMRT Link compute nodes.) ' from its release notes which didn't mention REDHAT. Thank you!

**Comment by pbjd** [comment]
`bax2bam` was removed in 9.0. The installations/instruction links I provided were for the 8.0 software, which includes that command. Check that out and see if it works. It should work fine with that distribution.

**Comment by lemontealala** [comment]
> `bax2bam` was removed in 9.0. The installations/instruction links I provided were for the 8.0 software, which includes that command. Check that out and see if it works. It should work fine with that distribution.

Thanks! I have downloaded SMRT Link_v7.0 and it works.

**Comment by rob123king** [comment]
I have a new error, shall I open another ticket? I'm trying to run ISOseq3 with the resulting bams but get the below
20210302 18:51:35.867 | FATAL | ccs ERROR: [pbbam] chemistry compatibility ERROR: unsupported sequencing chemistry combination:
    binding kit:        100372700
    sequencing kit:     100612400
    basecaller version: 2.3.0.3.154799

**Comment by pb-dseifert** [comment]
yup, the current CCS doesn't support RSII anymore. You'll have to use `ccs` from SMRT Link 7.0 or earlier.

**Comment by rob123king** [comment]
Okay, almost there at least
