### ISSUE TITLE
ccs ERROR: Missing base features: IPD or PulseWidth

### ISSUE THREAD

**Issue by rob123king** [PacificBiosciences/pbbioconda#379]
**Operating system**
3.10.0-862.14.4.el7.x86_64 - linux slurm

**Package name**
ccs 4.2.0 (commit v4.2.0)

**Conda environment**
`# packages in environment at /home/data/bioinf_resources/programming_tools/anaconda27/envs/isoseq:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
atk                       2.36.0                        1    conda-forge
atk-1.0                   2.36.0               haf93ef1_1    conda-forge
biopython                 1.77             py38h1e0a361_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.16.1               h516909a_0    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
canu                      2.0                  he1b5a44_0    bioconda
certifi                   2020.11.8        py38h578d9bd_0    conda-forge
chrpath                   0.16              h14c3975_1001    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
fribidi                   1.0.10               h516909a_0    conda-forge
gdk-pixbuf                2.38.2               h3f25603_4    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.65.0               h6f030ca_0    conda-forge
gnuplot                   5.2.7                h0fb2448_3    conda-forge
gobject-introspection     1.64.1           py38h03d966d_1    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
gtk2                      2.24.32              h586f36d_1    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
htslib                    1.10.2               hd3b49d5_1    bioconda
icu                       64.2                 he1b5a44_1    conda-forge
isoseq3                   3.3.0                         0    bioconda
jpeg                      9d                   h516909a_0    conda-forge
krb5                      1.17.1               hfafb76e_2    conda-forge
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.71.1               hcdd3856_4    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         h46ee950_1    conda-forge
libev                     4.33                 h516909a_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgd                     2.2.5             h307a58e_1007    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libllvm9                  9.0.1                he513fc3_1    conda-forge
libnghttp2                1.41.0               hab1572f_1    conda-forge
libopenblas               0.3.10               h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
lima                      1.11.0                        0    bioconda
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nspr                      4.27                 he1b5a44_0    conda-forge
nss                       3.47                 he751ad9_0    conda-forge
numpy                     1.18.5           py38h8854b6b_0    conda-forge
openjdk                   11.0.1            hacce0ff_1021    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
pbbam                     1.3.0                h5b7e6e0_1    bioconda
pbccs                     4.2.0                         1    bioconda
pbgcpp                    2.0.0                         0    bioconda
pbmm2                     1.4.0                h56fc30b_0    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-filesys-df           0.92            pl526h14c3975_3    bioconda
pip                       20.1.1                     py_1    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.8.3           cpython_he5300dc_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
readline                  8.0                  h46ee950_1    conda-forge
setuptools                49.1.0           py38h32f6830_0    conda-forge
sqlite                    3.32.3               hcee41ef_1    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.2.0                h516909a_0    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
`

**Describe the bug**
This command which worked fine on previous data but new data set from new provider didn't
srun ccs -j 20 --noPolish --minPasses 1 m64086e_210212_052746.reads.bam ccs.bam

**Error message**
ccs ERROR: Missing base features: IPD or PulseWidth

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**
ccs.bam produced

**Comment by armintoepfer** [comment]
m64086e_210212_052746.reads.bam contains CCS reads :) Your provider was nice enough to use the new SQIIe instrument that generates CCS on the instrument. Please have a look what this file contains https://ccs.how/faq/mode-all, in particular the section `Output will be a reads.bam that contains`

**Comment by rob123king** [comment]
ah ok thanks. So I've got all the reads including poor quality ones though but guess as its used for annotation I can just convert to fasta and use as is.
Output will be a reads.bam that contains:

HiFi Reads (≥Q20)
Lower-quality but still polished consensus reads (<Q20)
Unpolished consensus reads (rq = -1)
0- or 1-pass subreads unaltered (rq = -1)

**Comment by rob123king** [comment]
would be better to filter for passes. I see all the reads though with bam2fasta and no options to filter with this tool. Is there a tool to filter for pass reads before converting? I can't see any information how to do that..

**Comment by williamrowell** [comment]
If the service provider sent the dataset xml, you can use dataset commands to extract the subset of HiFi reads.

```bash
dataset filter m64086e_210212_052746.reads.xml m64086e_210212_052746.hifi_reads.xml 'rq>0.99'
dataset consolidate m64086e_210212_052746.hifi_reads.xml m64086e_210212_052746.hifi_reads.bam m64086e_210212_052746.hifi_reads.consolidated.xml
```

If they only sent the BAM, you can use [bamtools](https://github.com/pezmaster31/bamtools).

```bash
bamtools filter -tag 'rq':'>=.99' -in m64086e_210212_052746.reads.bam -out m64086e_210212_052746.hifi_reads.bam
```
