### ISSUE TITLE
ERROR - Was waiting for '0-rawreads/tan-split/tan-uows.json'

### ISSUE THREAD

**Issue by rozaimirazali** [PacificBiosciences/pbbioconda#38]
Hi,

Could anyone please give an insight to why I am getting the following error?

> 2018-10-16 06:58:34,551 - root:74 - DEBUG - Checking existence of '0-rawreads/tan-split/tan-uows.json' with timeout=30
> 2018-10-16 06:59:04,589 - root:70 - ERROR - Was waiting for '0-rawreads/tan-split/tan-uows.json'
> Traceback (most recent call last):
>   File "/gpfs/software/genomics/pb-falcon/src/lib/python2.7/site-packages/pypeflow/do_task.py", line 68, in wait_for
>     _wait_for(fn, timeout)
>   File "/gpfs/software/genomics/pb-falcon/src/lib/python2.7/site-packages/pypeflow/do_task.py", line 84, in _wait_for
>     raise Exception('Timed out waiting for {!r}'.format(fn))
> Exception: Timed out waiting for '0-rawreads/tan-split/tan-uows.json'

My config file as as follows:

#### Input
[General]
input_fofn=input.fofn
input_type=raw
pa_DBdust_option=
pa_fasta_filter_option=streamed-median
target=assembly
skip_checks=False
LA4Falcon_preload=false

#### Data Partitioning
pa_DBsplit_option=-x500 -s400
ovlp_DBsplit_option=-s400

#### Repeat Masking
pa_HPCTANmask_option=
pa_REPmask_code=0,300;0,300;0,300

#### Pre-assembly
genome_size=3000000000
seed_coverage=50
length_cutoff=-1    
pa_HPCdaligner_option=-v -B128 -M24
pa_daligner_option= -k18 -e0.75 -l1200 -h256 -w8 -s100
falcon_sense_option=--output-multi --min-idt 0.70 --min-cov 4 --max-n-read 200
falcon_sense_greedy=False

#### Pread overlapping
ovlp_HPCdaligner_option=-v -B128 -M24 
ovlp_daligner_option=-k24 -e.92 -l1800 -h600 -s100

#### Final Assembly
length_cutoff_pr=1000
overlap_filtering_setting=--max-diff 100 --max-cov 100 --min-cov 2
fc_ovlp_to_graph_option=

[job.defaults]
job_type=lsf
pwatcher_type=blocking
JOB_QUEUE=fatnode
MB=999999
NPROC=20
njobs=240
submit = bsub -q fatnode -P fatnode -J ${JOB_NAME} -o ${JOB_STDOUT} -e ${JOB_STDERR} ${JOB_SCRIPT}

[job.step.da]
NPROC=20
MB=999999
njobs=240
[job.step.la]
NPROC=20
MB=999999
njobs=240
[job.step.cns]
NPROC=20
MB=999999
njobs=240
[job.step.pda]
NPROC=20
MB=999999
njobs=240
[job.step.pla]
NPROC=20
MB=999999
njobs=240
[job.step.asm]
NPROC=20
MB=999999
njobs=240

**Comment by akaraw** [comment]
Hi @rozaimirazali  Did you find the answer for this?

**Comment by huangyixian123** [comment]
Hi @rozaimirazali Did you find the answer for this?
