### ISSUE TITLE
Lima - not counting passes correctly 

### ISSUE THREAD

**Issue by deborahmleigh** [PacificBiosciences/pbbioconda#380]
**Operating system**
Linux
**Package name**
lima 2.0.0 (commit v2.0.0)
**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
avro-python2              1.9.0                      py_0    bioconda
bam2fastx                 1.3.0                         0    bioconda
bcftools                  1.10.2               hd2cd319_0    bioconda
bzip2                     1.0.8                h516909a_3    conda-forge
c-ares                    1.11.0               h470a237_1    bioconda
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
cffi                      1.14.0           py27hd463f26_0    conda-forge
chardet                   3.0.4           py27h8c360ce_1006    conda-forge
cryptography              2.8              py27h2c19f6a_2    conda-forge
curl                      7.71.1               he644dc0_8    conda-forge
cython                    0.29.15          py27haf22ab1_1    conda-forge
enum34                    1.1.10           py27h8c360ce_1    conda-forge
genomicconsensus          2.3.3                      py_1    bioconda
gsl                       2.5                  h294904e_1    conda-forge
h5py                      2.9.0           py27h31fdc65_1000    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
htslib                    1.10.2               hd3b49d5_1    bioconda
idna                      2.10               pyh9f0ad1d_0    conda-forge
ipaddress                 1.0.23                     py_0    conda-forge
iso8601                   0.1.13             pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               hfafb76e_3    conda-forge
ld_impl_linux-64          2.35                 h769bd43_9    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libnghttp2                1.41.0               hab1572f_1    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_4    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
lima                      2.0.0                         0    bioconda
linecache2                1.0.0                      py_1    conda-forge
ncurses                   6.2                  he1b5a44_1    conda-forge
numpy                     1.16.5           py27h95a1406_0    conda-forge
openssl                   1.1.1j               h7f98852_0    conda-forge
pbbam                     1.6.0                h5b7e6e0_0    bioconda
pbccs                     6.0.0                         1    bioconda
pbcommand                 1.1.1                      py_3    bioconda
pbcopper                  1.8.0                h3e4de3e_0    bioconda
pbcore                    1.7.1                    py27_0    bioconda
pblaa                     2.4.2                         2    bioconda
pbmm2                     1.4.0                h56fc30b_0    bioconda
perl                      5.30.3               h516909a_1    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysam                     0.16.0.1         py27ha863e18_1    bioconda
pysocks                   1.7.1            py27h8c360ce_1    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-consensuscore      1.1.1            py27h55c140c_4    bioconda
python-consensuscore2     3.4.1                    py27_0    bioconda
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
requests                  2.13.0                   py27_0    conda-forge
samtools                  1.7                           1    bioconda
setuptools                44.0.0                   py27_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h4cf870e_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.12                     py27_0    bioconda
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge

**Describe the bug**
I have sequel II data that is the output of the command ccs -all (run defacto by the sequencer). I am trying to demultiplex my reads and apply a minimum passes threshold, but the Lima report states that all reads only have 1 ccs pass. This doesn't match our QC metrics from the sequencer or the _np_ tags. 

**Error message**
Example report file: 
cut -f 28 lima.report | uniq
_NumPasses
1_

but when I look at the tags in the sam convert of a random bam file output from the lima command I have: 
np:i:49	rq:f:0.999995
np:i:29	rq:f:0.999988
np:i:33	rq:f:0.999875

**To Reproduce**
lima File.bam     barcodes.fasta   output.bam  --different --ccs --dump-clips --min-length=3000 --min-score 26  --split-named 

**Expected behavior**
I would expect there to be at least some variation in the number of passes so I think there might be a bug? But I'm not too sure.

**Comment by armintoepfer** [comment]
`lima` is agnostic of additional BAM tags. If you use subreads as input, it will count the subreads per ZMW and save them as passes. For ccs data, you have exactly one sequence per ZMW and for lima that's one pass.

I can note it as a feature request, but don't get too excited :)

In general, internally we've moved away from number of passes as a filter, but rather rely on predicted accuracy `rq` BAM tag.
I also recommend that you set `--min-score 80` for CCS data.

**Comment by deborahmleigh** [comment]
Hi Armin, 

Ah! OK that makes a lot more sense. I was thinking it probably was something on my end. Thanks for letting me know. Might be a good feature request because I would like to remove everything with a very low pass number. But until the next upgrade it might be enough to note it in the manual? I guess more people will have pre-processed ccs data and might get confused. Previously I have always generated the ccs reads myself, so this data change is forcing me to alter my pipeline, hence the confusion. 

What program do you recommend for rq filtering? 

Thanks!

**Comment by armintoepfer** [comment]
https://ccs.how/faq/reads-bam.html#bamtools
