### ISSUE TITLE
IPA documentation - missing information on outputs

### ISSUE THREAD

**Issue by marchoeppner** [PacificBiosciences/pbbioconda#383]
Hi,

I have been using the IPA assembler; with good success. However, I noticed that the documentation is spare (i.e. missing) when it comes to the output and what it means, which assembly fasta file to use etc. There are some hints in the Falcon documentation, but still...

It would also be nice if the documentation could include some pointers on how to proceed from the final assembly, for example how to generate a primary (haploid) assembly and so on. 

Cheers,
Marc

**Comment by zeeev** [comment]
Thanks @marchoeppner, that's a fair point, and we will work toward better documentation.
