### ISSUE TITLE
fc_run configure file!

### ISSUE THREAD

**Issue by sunnycqcn** [PacificBiosciences/pbbioconda#384]
when I run fc_run, I always met the error as following:
`[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/home/AAFC-AAC/fuf/miniconda3/envs/pacbio/lib/python3.8/site-packages/pwatcher/blocking.py'>
[INFO]job_type='local', (default)job_defaults={'job_type': 'local', 'pwatcher_type': 'blocking', 'submit': '/bin/bash -c "${JOB_SCRIPT}" > "${JOB_STDOUT}" 2> "${JOB_STDERR}"', 'use_tmpdir': '/isilon/saskatoon-rdc/users/fuf/striga/genome/rawgenome/fc/tmp/', 'MB': '32768', 'NPROC': '4', 'njobs': '2'}, use_tmpdir='/isilon/saskatoon-rdc/users/fuf/striga/genome/rawgenome/fc/tmp/', squash=False, job_name_style=0
[INFO]Setting max_jobs to 2; was None
[INFO]Num unsatisfied: 2, graph: 2
[INFO]About to submit: Node(0-rawreads/build)
[INFO]Popen: '/bin/bash -c "/home/AAFC-AAC/fuf/miniconda3/envs/pacbio/lib/python3.8/site-packages/pwatcher/mains/job_start.sh" > "/isilon/saskatoon-rdc/users/fuf/striga/genome/rawgenome/fc/0-rawreads/build/run-Pd2f24b42f2be07.bash.stdout" 2> "/isilon/saskatoon-rdc/users/fuf/striga/genome/rawgenome/fc/0-rawreads/build/run-Pd2f24b42f2be07.bash.stderr"'
[INFO](slept for another 0.0s -- another 1 loop iterations)
[INFO](slept for another 0.30000000000000004s -- another 2 loop iterations)
[INFO](slept for another 1.2000000000000002s -- another 3 loop iterations)
[INFO](slept for another 2.9999999999999996s -- another 4 loop iterations)
[INFO](slept for another 6.0s -- another 5 loop iterations)
[INFO](slept for another 10.500000000000002s -- another 6 loop iterations)
[INFO](slept for another 16.800000000000004s -- another 7 loop iterations)
[INFO](slept for another 25.20000000000001s -- another 8 loop iterations)
[INFO](slept for another 36.000000000000014s -- another 9 loop iterations)
[INFO](slept for another 49.499999999999986s -- another 10 loop iterations)
[INFO](slept for another 65.99999999999994s -- another 11 loop iterations)
[INFO](slept for another 85.7999999999999s -- another 12 loop iterations)
[INFO](slept for another 109.19999999999983s -- another 13 loop iterations)
[ERROR]Task Node(0-rawreads/build) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(0-rawreads/build)}
[ERROR]ready: set()
        submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/home/AAFC-AAC/fuf/miniconda3/envs/pacbio/bin/fc_run", line 33, in <module>
    sys.exit(load_entry_point('falcon-kit==1.8.1', 'console_scripts', 'fc_run')())
  File "/home/AAFC-AAC/fuf/miniconda3/envs/pacbio/lib/python3.8/site-packages/falcon_kit/mains/run1.py", line 706, in main
    main1(argv[0], args.config, args.logger)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/pacbio/lib/python3.8/site-packages/falcon_kit/mains/run1.py", line 71, in main1
    run(wf, config,
  File "/home/AAFC-AAC/fuf/miniconda3/envs/pacbio/lib/python3.8/site-packages/falcon_kit/mains/run1.py", line 219, in run
    gen_parallel_tasks(
  File "/home/AAFC-AAC/fuf/miniconda3/envs/pacbio/lib/python3.8/site-packages/falcon_kit/pype.py", line 106, in gen_parallel_tasks
    wf.refreshTargets()
  File "/home/AAFC-AAC/fuf/miniconda3/envs/pacbio/lib/python3.8/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/AAFC-AAC/fuf/miniconda3/envs/pacbio/lib/python3.8/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(0-rawreads/build)}
`
I used local server to run.
`[General]

# list of files of the initial bas.h5 files
input_fofn = input.fofn
#input_fofn = preads.fofn

input_type = raw
#input_type = preads

#openending = True

# The length cutoff used for seed reads used for initial mapping
length_cutoff = 1000
genome_size = 1400000000
#seed_coverage = 60

# The length cutoff used for seed reads usef for pre-assembly
length_cutoff_pr = 1000

pa_REPmask_code = 1,300;0,300;0,300
pa_daligner_option   = -e.8 -l3200 -k18 -h480  -w8 -s100
ovlp_daligner_option = -e.9 -l2500 -k24 -h1024 -w6 -s100
pa_HPCdaligner_option   =  -v -B128 -M24
ovlp_HPCdaligner_option =  -v -B128 -M24
pa_HPCTANmask_option = -k18 -h480 -w8 -e.8 -s100
pa_HPCREPmask_option = -k18 -h480 -w8 -e.8 -s100

pa_DBsplit_option = -x500 -s200
ovlp_DBsplit_option = -x500 -s200

falcon_sense_option = --output-multi --min-idt 0.70 --min-cov 2 --max-n-read 200 --n-core 16
overlap_filtering_setting = --max-diff 120 --max-cov 120 --min-cov 2 --n-core 20

#dazcon = 1

[job.defaults]

job_type = local
pwatcher_type=blocking
submit = /bin/bash -c "${JOB_SCRIPT}" > "${JOB_STDOUT}" 2> "${JOB_STDERR}"
#job_type = string
use_tmpdir = /isilon/saskatoon-rdc/users/fuf/striga/genome/rawgenome/fc/tmp/
MB=32768
NPROC=20
njobs=2
#submit = qsub -S /bin/bash -cwd -sync y -V \
 # -N ${JOB_NAME}      \
  #-o "${JOB_STDOUT}"  \
  #-e "${JOB_STDERR}"  \
  #-pe smp ${NPROC}    \
  #"${JOB_SCRIPT}"

NPROC=4
#njobs=1
[job.step.da]
[job.step.pda]
[job.step.la]
#NPROC=1
[job.step.pla]
#NPROC=1
[job.step.cns]
#njobs=1
NPROC=8
[job.step.asm]
NPROC=20
`
I did not know what it is wrong? Coudl  you help me check the configure file is correct?
Thanks,
Fuyou

**Comment by pb-cdunn** [comment]
You would have to step into the `0-rawreads/build/` directory and examine stderr to debug this. It is almost always a software integration/versioning problem. Very difficult for us to debug remotely. Good luck!
