### ISSUE TITLE
IPA: confused about the results of the Haploid assembly with polishing.

### ISSUE THREAD

**Issue by ptranvan** [PacificBiosciences/pbbioconda#385]
Hi,

This is the command I used:

`ipa local --no-phase -i <myreads.fastq>`

However I got `final.a_ctg.fasta` and `final.p_ctg.fasta` in `assembly-results`.

because of the `--no-phase` option I would have expected primary contigs only so how is it possible to get the haplotigs ?

Thanks

**Comment by isovic** [comment]
Hi Patrick,

Even without phasing, the layout stage extracts alternative bubble paths from the graph and stores them to the haplotigs file.
These bubbles are the product of larger variation between haplotypes (such as structural variation) which enables the overlapper to do some preliminary separation at these loci.
Additionally, if you used the `purge_dups` stage, it's possible that it moved some of the contigs to the haplotigs pile.

Best regards,
Ivan.
