### ISSUE TITLE
getting segmentation error isoseq3 -cluster: similar to old unresolved issue

### ISSUE THREAD

**Issue by abrantesas** [PacificBiosciences/pbbioconda#386]
Hello,
I got a very similar error to this unresolved thread:
https://github.com/PacificBiosciences/pbbioconda/issues/310

The post is fairly old, is there any new advice or insight with regards to this issue?

I am also running isoseq3 cluster but on version 3.4.0.
I am trying to cluster multiple cells on a 1TB RAM Redhat 7 computing node and it appears to be using around 400GB of the RAM.

It crashed after running almost 2 days. 

It got through the Read, Convert, and Sort steps then does a lot of Aligning Linear steps and ends with the following output:

Aligning Linear          : (1000) 323us 719ns  (805) 21ms 883us  (68743) 44ms 286us 
Aligning Linear          : 4h 1m                                               
Read to clusters
/var/spool/slurmd/job14326978/slurm_script: line 13: 82662 Segmentation fault 

Thanks!
Anthony Abrantes

**Comment by armintoepfer** [comment]
Hi! Could you please tell us how many SMRT cells you've used as input, including the number of CCS reads as input to Iso-Seq? Also please add all the calls of that workflow, including the ccs calls. 

Thanks you

**Comment by ramin-shirali** [comment]
Hi, I'm experiencing the same issue. I don't believe this is due to memory. I'm receiving this error while running isoseq3 collapse and it immediately crashes.
