### ISSUE TITLE
pbalign maximum memory per thread hard coded to 4G

### ISSUE THREAD

**Issue by charmichaeld** [PacificBiosciences/pbbioconda#39]
Hi,
During the pbalign samtools sort step, there are two lines where the memory per thread is hard coded to 4G. Can this be updated to allow the user to control this value?
**Package name**
pbalign version 0.3.1
.conda/envs/arrow/lib/python2.7/site-packages/pbalign/bampostservice.py

```
        if _stvmajor >= 1:
            cmd = 'samtools sort --threads {t} -m 4G -o {sortedBamFile} {unsortedBamFile}'.format(
                t=nproc, sortedBamFile=sortedBamFile, unsortedBamFile=unsortedBamFile)
        else:
            cmd = 'samtools sort --threads {t} -m 4G {unsortedBamFile} {prefix}'.format(
                t=nproc, unsortedBamFile=unsortedBamFile, prefix=sortedPrefix)
        Execute(self.name, cmd)
```

**Comment by ylipacbio** [comment]
Thank you very much for reporting this bug.

Yes, we are aware of that latest samtools preclaims 4G*t member in the begining of job excution, and make memory outage errors. 

We will fix this.

**Comment by pb-dseifert** [comment]
We've reduced this to `768MiB` for now.
