### ISSUE TITLE
bax2bam fails with "ERROR, could not read quality metrics for FASTQ Sequence"

### ISSUE THREAD

**Issue by vlpotapov** [PacificBiosciences/pbbioconda#398]
**Operating system**
CentOS Linux 7 (Core)

**Package name**
```
$ bax2bam --version
0.0.11
```

**Conda environment**
```
$ conda list
# Name                    Version                   Build  Channel
bax2bam                   0.0.11                        0    bioconda
pbccs                     6.0.0                h9ee0642_2    bioconda
recalladapters            9.0.0                h9ee0642_1    bioconda
```

**Describe the bug**
I have PacBio sequencing data coming from the RSII instrument (movie.1.bax.h5, movie.2.bax.h5, movie.3.bax.h5). I would like to convert it to the BAM format. When I run bax2bam, it fails with an error message "could not read quality metrics for FASTQ Sequence" (see below). Interestingly, when I use bax2bam that comes with SMRT Link 5.0 (version 0.0.8) and use the same input, everything works fine.

```
$ cat input.fofn 
movie.1.bax.h5
movie.2.bax.h5
movie.3.bax.h5

$ bax2bam -o movie2 --fofn input.fofn 
ERROR, could not read quality metrics for FASTQ Sequence 
```

**Error message**
```
ERROR, could not read quality metrics for FASTQ Sequence 
```

**To Reproduce**
See above

**Expected behavior**
The expected output is movie.scraps.bam and movie.subreads.bam files.

**Comment by hhzhao713** [comment]
have you solved the problem?

**Comment by hhzhao713** [comment]
i can't do that yet

**Comment by pb-dseifert** [comment]
See
https://github.com/PacificBiosciences/pbbioconda/issues/378#issuecomment-786787795
https://github.com/PacificBiosciences/pbbioconda/issues/441#issuecomment-946772353
