### ISSUE TITLE
Unable to run my PacBio data

### ISSUE THREAD

**Issue by wjj666** [PacificBiosciences/pbbioconda#400]
I convert sequel bams to fasta (using bam2fasta) and use them as input for falcon. But I got an error like this:

> ValueError: Error tokenizing FASTA header

Referring to this issue, I tried the snakemake workflow, but there was another error:

> File "/XXX/Anaconda3/envs/falcon/lib/python3.7/site-packages/falcon_kit/io.py", line 147, in deserialize
>     raise Exception('Unknown extension for {!r}'.format(fn))
> Exception: Unknown extension for '../../fc_run.cfg'

The snakemake cmd I used was:

> snakemake --config input_fofn=input.fofn config_fn=fc_run.cfg MAKEDIR=/tmp/local/csjjwang/data/NA12878/1_asm/pacbiofalcon --cores 64 -s falcon.clr.snakemake --verbose -p

Could you please help solve these problems and help me assembly my pacbio data with falcon?

Thank you very much.

**Comment by cement-head** [comment]
Are you using the <subreads.bam> file as your staring (input) file?

**Comment by wjj666** [comment]
> https://github.com/PacificBiosciences/pb-assembly

I can run the EXAMPLE DATA SET my another Pacbio data successfully.

But the fc_run dose not work on this Pacbio data. I downloaded the bam file and convert the bam to fasta, then used the fasta as the input file. When I run **fc_run fc_run.cfg**, it reported this error:
`ValueError: Error tokenizing FASTA header`

The bam file is: 
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NA12878_PacBio_MtSinai/sorted_final_merged.bam

The convert cmd is:
samtools view input.bam | awk '{OFS="\t"; print ">"$1"\n"$10}' - > output.fasta
NA12878_pacbio.fasta

This is the Pacbio data I used:
https://drive.google.com/file/d/1-1UPEu5cJPlsex97UO4PHuoPChDN10QL/view?usp=sharing

Is there something wrong when I convert the bam to fasta or any other problem?

**Comment by cement-head** [comment]
It could be the chemistry of the original BAM file.  Do you know what instrument it was collected/generated on?  If it's an older dataset (RSII) then you may have to use an older tool to perform the conversion.

I would **NOT** use SAMTOOLS for this conversion.  The type of BAM that pacbio generates is specific to PacBio, and SAMTOOLS won't convert this properly.  You should be using PacBio's own toolset.

Here is the tool: https://github.com/PacificBiosciences/bam2fastx

You install locally with CONDA; follow these instructions: https://github.com/PacificBiosciences/pbbioconda

**Comment by pb-cdunn** [comment]
It's the same problem as this old issue: https://github.com/PacificBiosciences/FALCON/issues/695

Usually, people are running FALCON because they have old CLR reads. FALCON is very difficult for us to support because of all the moving dependencies in Bioconda. We normally recommend using IPA instead. It's much, much faster and more accurate. But that will not work on CLR data.

However, I suspect that you have CCS data. In that case, simply adopt **pbipa**. This should help:

* https://github.com/PacificBiosciences/pbipa
* https://github.com/PacificBiosciences/pbbioconda/wiki/Improved-Phased-Assembler
