### ISSUE TITLE
Is FALCON-Unzip broken with the F1 BULL Tutorial dataset?

### ISSUE THREAD

**Issue by cement-head** [PacificBiosciences/pbbioconda#401]
**Operating system**
```
$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.8.2003 (Core)
Release:	7.8.2003
Codename:	Core
```

**Package name**
`pbgcpp                    2.0.2                h9ee0642_1    bioconda`

**Conda environment**
```
$ conda list
# packages in environment at /home/username/miniconda2/envs/denovo_asm:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
avro                      1.8.2             h05e4be9_1000    conda-forge
bedtools                  2.30.0               h7d7f7ad_1    bioconda
blasr                     5.3.5                         0    bioconda
bwa                       0.7.17               h5bf99c6_8    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
decorator                 5.0.7              pyhd8ed1ab_0    conda-forge
falcon-kit                1.8.1                    pypi_0    pypi
falcon-phase              1.2.0                    pypi_0    pypi
falcon-unzip              1.3.7                    pypi_0    pypi
future                    0.18.2           py38h578d9bd_3    conda-forge
htslib                    1.10.2               hd3b49d5_1    bioconda
jansson                   2.13.1               h7f98852_0    conda-forge
k8                        0.2.5                h9a82719_1    bioconda
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.76.1               hc4aaa36_0    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
minimap2                  2.18                 h5bf99c6_0    bioconda
mummer4                   4.0.0rc1        pl5262h1b792b2_1    bioconda
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.5                        py_0    conda-forge
nim-falcon                3.0.2                h18d090a_1    bioconda
numpy                     1.20.2           py38h9894fe3_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pb-assembly               0.0.8                hdfd78af_1    bioconda
pb-dazzler                0.0.1                h779adbc_1    bioconda
pb-falcon                 2.2.4            py38h1bd3507_1    bioconda
pb-falcon-phase           0.1.0                h8e334b0_1    bioconda
pbbam                     1.6.0                h5b7e6e0_0    bioconda
pbgcpp                    2.0.2                h9ee0642_1    bioconda
pbmm2                     1.4.0                h56fc30b_0    bioconda
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pysam                     0.16.0.1         py38hbdc2ae9_1    bioconda
python                    3.8.8           hffdb5ce_0_cpython    conda-forge
python-edlib              1.3.8.post2      py38h8c62d01_1    bioconda
python-intervaltree       3.1.0              pyh864c0ab_0    bioconda
python-msgpack            0.6.1            py38h8c62d01_4    bioconda
python-sortedcontainers   2.3.0              pyh3252c3a_0    bioconda
python_abi                3.8                      1_cp38    conda-forge
racon                     1.4.20               h9a82719_1    bioconda
readline                  8.0                  he28a2e2_2    conda-forge
samtools                  1.10                 h2e538c0_3    bioconda
setuptools                49.6.0           py38h578d9bd_3    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.35.4               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
```

**Describe the bug**
The last step of FALCON-Unzip crashes (see below and attched stderr file) when gcpp attempts to run the 4-polish step of pipeline. It appears from the stderr output to be a **CHEMISTRY INCOMPATIBILITY** problem. Digging around GitHub and looking at some of the comments both @pb-cdunn and @gconcepcion have made - is it possible that the F1 BULL Tutorial Dataset is RS II chemistry and that is incompatible with the latest (April 16th, 2021) install of FALCON-Unzip (pbgcpp)? Can someone (a) confirm that this is a Tutorial Dataset incompatibility, or else my install is broken (worked with the example dataset), and (b) possibly update the F1 BULL Tutorial dataset so that we can properly complete the pipeline installation tests? TIA

**Error message**
```
set +e
+ set +e
gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j $nproc -r ../../../quiver-split/refs/000001F/ref.fasta aln-000001F.bam            -o ${fasta_fn},${fastq_fn},cns.vcf
+ gcpp --algorithm=arrow -x 5 -X 120 -q 0 -j 1 -r ../../../quiver-split/refs/000001F/ref.fasta aln-000001F.bam -o cns.fasta,cns.fastq,cns.vcf
>|> 20210416 14:44:04.104 -|- FATAL -|- Run -|- 0x2b14e0a98300|| -|- gcpp ERROR: [pbbam] chemistry compatibility ERROR: unsupported sequencing chemistry combination:
    binding kit:        100-862-200
    sequencing kit:     100-861-800
    basecaller version: 4.0.0.189308
See SMRT Link release documentation for details about consumables compatibility or contact PacBio Technical Support.
```

Full stderr.txt file attached: [stderr.txt](https://github.com/PacificBiosciences/pbbioconda/files/6326425/stderr.txt)

**To Reproduce**
Download and install pb-assembly into a conda environment by following the TUTORIAL: https://github.com/PacificBiosciences/pb-assembly#tutorial

**Expected behaviour**
Run FALCON => wait to successfully complete => check run metrics with TUTORIAL to validate install.
Run FALCON-Unzip => wait to successfully complete => check run metrics with TUTORIAL to validate install.
Run FALCON-Phase => wait to successfully complete => check run metrics with TUTORIAL to validate install.

**Comment by pb-cdunn** [comment]
Also posted as https://github.com/PacificBiosciences/FALCON/issues/693

**Comment by cement-head** [comment]
@pb-cdunn Not sure what this answer means.  Does it mean that FALCON-Unzip is broken, or does it mean that pwatcher_type=fs_based is broken, or does it mean that gcpp is broken, or does it mean you don't know?

**Comment by pb-cdunn** [comment]
There are two things that are hard to keep up with: First, when the chemistry changes, we have to update (i.e. re-generate) our test-cases, and we might also need to recompile `gcpp` (maybe). Second, when the conda environment changes, dependencies can become suddenly inconsistent.

It's very difficult to deal with these changes. And **ipa** (on HiFi reads) is so much better than **falcon** (on CLR reads). If you really need falcon, we recommend installing PacBio's "smrtlink" instead of using Bioconda.

**Comment by cement-head** [comment]
Thanks @pb-cdunn  - that clarifies the issue. Cheers.

So, does "smrtlink" run with really **_large_** genomes? >>3 GBp?

**Comment by gconcepcion** [comment]
In theory, SMRTLink should work. However by installing SMRTLink, you are also installing the bundled falcon binaries which can all be found in the `smrttools/current/private/otherbins/internalall/bin/` directory.

So you can still run an assembly on the command line, but with an older bundled / contained version of falcon instead of the latest distributed conda version which does appear to be broken on this last stage with older CLR data.

**Comment by cement-head** [comment]
@gconcepcion Thanks!  That helps - we have recent (last couple of months) SII CLR data, so I'm guessing the CONDA version of FALCON will work.

**Comment by cement-head** [comment]
@gconcepcion @pb-cdunn Noob question; does FALCON create thousands and thousands of small "jobs" during the assembly?  It seems to be working but a lot of these jobs are 2 sec to 5 sec walltime jobs?  This is for a very large frog genome (6 Gbp)

**Comment by gconcepcion** [comment]
depending on how you have things configured, there could definitely be thousands of small jobs. It depends on what stage these jobs are, some stages are quick jobs that only take a couple seconds, others are much longer alignment or consensus jobs that could take hours
