### ISSUE TITLE
ccs operation does not complete 

### ISSUE THREAD

**Issue by yn24** [PacificBiosciences/pbbioconda#402]
**Operating system**
Ubuntu 20.04 on Parallels Desktop 16 for mac Version 16.5.0 (49183) on 
MacOS 10.15.7 (19H524) (MacBook Pro 2.4 GHz 8-Core Intel Core i9, 64 GB 2667 MHz DDR4, 2TB harddrive)

**Package name**
ccs 6.0.0 (commit v6.0.0-2-gf165cc26)
Using:
  unanimity : 6.0.0 (commit v6.0.0-2-gf165cc26)
  pbbam     : 1.6.1 (commit SEQII-release-10.0.0-35-g8fc7d89)
  pbcopper  : 1.8.0 (commit SEQII-release-10.0.0-38-g56f07ff)
  boost     : 1.73
  htslib    : 1.10.2
  zlib      : 1.2.11

conda updated
channel priority set as directed at https://bioconda.github.io/#set-up-channels

**Conda environment**
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abstract-rendering        0.5.1               np110py27_0    https://repo.continuum.io/pkgs/free
alabaster                 0.7.7                    py27_0    https://repo.continuum.io/pkgs/free
anaconda                  2.5.0               np110py27_0    https://repo.continuum.io/pkgs/free
anaconda-client           1.2.2                    py27_0    https://repo.continuum.io/pkgs/free
argcomplete               1.0.0                    py27_1    https://repo.continuum.io/pkgs/free
astropy                   1.1.1               np110py27_0    https://repo.continuum.io/pkgs/free
babel                     2.2.0                    py27_0    https://repo.continuum.io/pkgs/free
backports_abc             0.4                      py27_0    https://repo.continuum.io/pkgs/free
beautifulsoup4            4.4.1                    py27_0    https://repo.continuum.io/pkgs/free
bitarray                  0.8.1                    pypi_0    pypi
blaze-core                0.9.0                    py27_0    https://repo.continuum.io/pkgs/free
bokeh                     0.11.0                   py27_0    https://repo.continuum.io/pkgs/free
boto                      2.39.0                   py27_0    https://repo.continuum.io/pkgs/free
bottleneck                1.0.0               np110py27_0    https://repo.continuum.io/pkgs/free
brotlipy                  0.7.0           py27h516909a_1000    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cairo                     1.12.18                       6    https://repo.continuum.io/pkgs/free
cdecimal                  2.3                      pypi_0    pypi
certifi                   2019.11.28               py27_0    conda-forge
cffi                      1.14.0           py27hd463f26_0    conda-forge
chardet                   3.0.4                 py27_1005    conda-forge
clyent                    1.2.0                    py27_0    https://repo.continuum.io/pkgs/free
colorama                  0.3.6                    py27_0    https://repo.continuum.io/pkgs/free
conda                     4.8.2                    py27_0    conda-forge
conda-build               1.19.0                   py27_0    https://repo.continuum.io/pkgs/free
conda-env                 2.4.5                    py27_0    https://repo.continuum.io/pkgs/free
conda-package-handling    1.6.0            py27h516909a_1    conda-forge
configobj                 5.0.6                    py27_0    https://repo.continuum.io/pkgs/free
cryptography              2.8              py27h72c5cf5_1    conda-forge
curl                      7.45.0                        0    https://repo.continuum.io/pkgs/free
cycler                    0.9.0                    py27_0    https://repo.continuum.io/pkgs/free
cython                    0.23.4                   py27_0    https://repo.continuum.io/pkgs/free
cytoolz                   0.7.5                    py27_0    https://repo.continuum.io/pkgs/free
datashape                 0.5.0                    py27_0    https://repo.continuum.io/pkgs/free
decorator                 4.0.6                    py27_0    https://repo.continuum.io/pkgs/free
docutils                  0.12                     py27_0    https://repo.continuum.io/pkgs/free
dynd-python               0.7.1                    py27_0    https://repo.continuum.io/pkgs/free
enum34                    1.1.9                    py27_0    conda-forge
et_xmlfile                1.0.1                    py27_0    https://repo.continuum.io/pkgs/free
fastcache                 1.0.2                    py27_0    https://repo.continuum.io/pkgs/free
flask                     0.10.1                   pypi_0    pypi
fontconfig                2.11.1                        5    https://repo.continuum.io/pkgs/free
freetype                  2.5.5                         0    https://repo.continuum.io/pkgs/free
funcsigs                  0.4                      py27_0    https://repo.continuum.io/pkgs/free
futures                   3.3.0                    py27_0    conda-forge
gevent                    1.0.2                    py27_0    https://repo.continuum.io/pkgs/free
gevent-websocket          0.9.5                    py27_0    https://repo.continuum.io/pkgs/free
greenlet                  0.4.9                    py27_0    https://repo.continuum.io/pkgs/free
grin                      1.2.1                    pypi_0    pypi
h5py                      2.5.0               np110py27_4    https://repo.continuum.io/pkgs/free
hdf5                      1.8.15.1                      2    https://repo.continuum.io/pkgs/free
idna                      2.10               pyh9f0ad1d_0    conda-forge
ipaddress                 1.0.23                     py_0    conda-forge
ipykernel                 4.2.2                    py27_0    https://repo.continuum.io/pkgs/free
ipython                   4.0.3                    py27_0    https://repo.continuum.io/pkgs/free
ipython-notebook          4.0.4                    py27_0    https://repo.continuum.io/pkgs/free
ipython-qtconsole         4.0.1                    py27_0    https://repo.continuum.io/pkgs/free
ipython_genutils          0.1.0                    py27_0    https://repo.continuum.io/pkgs/free
ipywidgets                4.1.1                    py27_0    https://repo.continuum.io/pkgs/free
itsdangerous              0.24                     py27_0    https://repo.continuum.io/pkgs/free
jbig                      2.1                           0    https://repo.continuum.io/pkgs/free
jdcal                     1.2                      py27_0    https://repo.continuum.io/pkgs/free
jedi                      0.9.0                    py27_0    https://repo.continuum.io/pkgs/free
jinja2                    2.8                      py27_0    https://repo.continuum.io/pkgs/free
jpeg                      8d                            0    https://repo.continuum.io/pkgs/free
jsonschema                2.4.0                    py27_0    https://repo.continuum.io/pkgs/free
jupyter                   1.0.0                    py27_1    https://repo.continuum.io/pkgs/free
jupyter_client            4.1.1                    py27_0    https://repo.continuum.io/pkgs/free
jupyter_console           4.1.0                    py27_0    https://repo.continuum.io/pkgs/free
jupyter_core              4.0.6                    py27_0    https://repo.continuum.io/pkgs/free
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libdynd                   0.7.1                         0    https://repo.continuum.io/pkgs/free
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran               1.0                           0    https://repo.continuum.io/pkgs/free
libgomp                   9.3.0               h2828fa1_19    conda-forge
libpng                    1.6.17                        0    https://repo.continuum.io/pkgs/free
libsodium                 1.0.3                         0    https://repo.continuum.io/pkgs/free
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libtiff                   4.0.6                         1    https://repo.continuum.io/pkgs/free
libxml2                   2.9.2                         0    https://repo.continuum.io/pkgs/free
libxslt                   1.1.28                        0    https://repo.continuum.io/pkgs/free
llvmlite                  0.8.0                    py27_0    https://repo.continuum.io/pkgs/free
lxml                      3.5.0                    py27_0    https://repo.continuum.io/pkgs/free
markupsafe                0.23                     py27_0    https://repo.continuum.io/pkgs/free
matplotlib                1.5.1               np110py27_0    https://repo.continuum.io/pkgs/free
mistune                   0.7.1                    py27_0    https://repo.continuum.io/pkgs/free
mkl                       11.3.1                        0    https://repo.continuum.io/pkgs/free
mkl-service               1.1.2                    py27_0    https://repo.continuum.io/pkgs/free
multipledispatch          0.4.8                    py27_0    https://repo.continuum.io/pkgs/free
nbconvert                 4.1.0                    py27_0    https://repo.continuum.io/pkgs/free
nbformat                  4.0.1                    py27_0    https://repo.continuum.io/pkgs/free
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  1.11                     py27_0    https://repo.continuum.io/pkgs/free
nltk                      3.1                      py27_0    https://repo.continuum.io/pkgs/free
nose                      1.3.7                    py27_0    https://repo.continuum.io/pkgs/free
notebook                  4.1.0                    py27_0    https://repo.continuum.io/pkgs/free
numba                     0.23.1              np110py27_0    https://repo.continuum.io/pkgs/free
numexpr                   2.4.6               np110py27_1    https://repo.continuum.io/pkgs/free
numpy                     1.10.4                   py27_0    https://repo.continuum.io/pkgs/free
odo                       0.4.0                    py27_0    https://repo.continuum.io/pkgs/free
openpyxl                  2.3.2                    py27_0    https://repo.continuum.io/pkgs/free
openssl                   1.1.1k               h7f98852_0    conda-forge
pandas                    0.17.1              np110py27_0    https://repo.continuum.io/pkgs/free
patchelf                  0.8                           0    https://repo.continuum.io/pkgs/free
path.py                   8.1.2                    py27_1    https://repo.continuum.io/pkgs/free
patsy                     0.4.0               np110py27_0    https://repo.continuum.io/pkgs/free
pbccs                     6.0.0                h9ee0642_2    bioconda
pep8                      1.7.0                    py27_0    https://repo.continuum.io/pkgs/free
pexpect                   3.3                      py27_0    https://repo.continuum.io/pkgs/free
pickleshare               0.5                      py27_0    https://repo.continuum.io/pkgs/free
pillow                    3.1.0                    py27_0    https://repo.continuum.io/pkgs/free
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pixman                    0.32.6                        0    https://repo.continuum.io/pkgs/free
ply                       3.8                      py27_0    https://repo.continuum.io/pkgs/free
psutil                    3.4.2                    py27_0    https://repo.continuum.io/pkgs/free
ptyprocess                0.5                      py27_0    https://repo.continuum.io/pkgs/free
py                        1.4.31                   py27_0    https://repo.continuum.io/pkgs/free
pyasn1                    0.1.9                    py27_0    https://repo.continuum.io/pkgs/free
pycairo                   1.10.0                   py27_0    https://repo.continuum.io/pkgs/free
pycosat                   0.6.3           py27h516909a_1002    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1                    pypi_0    pypi
pycurl                    7.19.5.3                 py27_0    https://repo.continuum.io/pkgs/free
pyflakes                  1.0.0                    py27_0    https://repo.continuum.io/pkgs/free
pygments                  2.1                      py27_0    https://repo.continuum.io/pkgs/free
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.0.3                    py27_0    https://repo.continuum.io/pkgs/free
pyqt                      4.11.4                   py27_1    https://repo.continuum.io/pkgs/free
pysocks                   1.7.1                    py27_0    conda-forge
pytables                  3.2.2               np110py27_0    https://repo.continuum.io/pkgs/free
pytest                    2.8.5                    py27_0    https://repo.continuum.io/pkgs/free
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python-dateutil           2.4.2                    py27_0    https://repo.continuum.io/pkgs/free
pytz                      2015.7                   py27_0    https://repo.continuum.io/pkgs/free
pyyaml                    3.11                     py27_1    https://repo.continuum.io/pkgs/free
pyzmq                     15.2.0                   py27_0    https://repo.continuum.io/pkgs/free
qt                        4.8.7                         1    https://repo.continuum.io/pkgs/free
qtconsole                 4.1.1                    py27_0    https://repo.continuum.io/pkgs/free
readline                  8.0                  he28a2e2_2    conda-forge
redis                     2.6.9                         0    https://repo.continuum.io/pkgs/free
redis-py                  2.10.3                   py27_0    https://repo.continuum.io/pkgs/free
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rope                      0.9.4                    py27_1    https://repo.continuum.io/pkgs/free
ruamel_yaml               0.15.80         py27h516909a_1000    conda-forge
scikit-image              0.11.3              np110py27_0    https://repo.continuum.io/pkgs/free
scikit-learn              0.17                np110py27_2    https://repo.continuum.io/pkgs/free
scipy                     0.17.0              np110py27_0    https://repo.continuum.io/pkgs/free
setuptools                44.0.0                   py27_0    conda-forge
simplegeneric             0.8.1                    py27_0    https://repo.continuum.io/pkgs/free
singledispatch            3.4.0.3                  py27_0    https://repo.continuum.io/pkgs/free
sip                       4.16.9                   py27_0    https://repo.continuum.io/pkgs/free
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           1.2.1                    py27_0    https://repo.continuum.io/pkgs/free
sockjs-tornado            1.0.1                    py27_0    https://repo.continuum.io/pkgs/free
sphinx                    1.3.5                    pypi_0    pypi
sphinx_rtd_theme          0.1.9                    py27_0    https://repo.continuum.io/pkgs/free
spyder                    2.3.8                    py27_0    https://repo.continuum.io/pkgs/free
spyder-app                2.3.8                    py27_0    https://repo.continuum.io/pkgs/free
sqlalchemy                1.0.11                   py27_0    https://repo.continuum.io/pkgs/free
sqlite                    3.35.4               h74cdb3f_0    conda-forge
ssl_match_hostname        3.4.0.2                  py27_0    https://repo.continuum.io/pkgs/free
statsmodels               0.6.1               np110py27_0    https://repo.continuum.io/pkgs/free
sympy                     0.7.6.1                  py27_0    https://repo.continuum.io/pkgs/free
terminado                 0.5                      py27_1    https://repo.continuum.io/pkgs/free
tk                        8.6.10               hed695b0_1    conda-forge
toolz                     0.7.4                    py27_0    https://repo.continuum.io/pkgs/free
tornado                   4.3                      py27_0    https://repo.continuum.io/pkgs/free
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
traitlets                 4.1.0                    py27_0    https://repo.continuum.io/pkgs/free
unicodecsv                0.14.1                   py27_0    https://repo.continuum.io/pkgs/free
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
util-linux                2.21                          0    https://repo.continuum.io/pkgs/free
werkzeug                  0.11.3                   py27_0    https://repo.continuum.io/pkgs/free
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xlrd                      0.9.4                    py27_0    https://repo.continuum.io/pkgs/free
xlsxwriter                0.8.4                    py27_0    https://repo.continuum.io/pkgs/free
xlwt                      1.0.0                    py27_0    https://repo.continuum.io/pkgs/free
xz                        5.0.5                         0    https://repo.continuum.io/pkgs/free
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.1.3                         0    https://repo.continuum.io/pkgs/free
zlib                      1.2.11            h516909a_1010    conda-forge
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**

ccs run stops when a bam.tmp file size reaches up to 50.6 MB.  "run stop" means that CPU usage becomes <3% while RAM remains max usage. No file update after reaching 50.6 MB and after >8 hours of run.

**Error message**
no error message 

**To Reproduce**
I ran
ccs movie.subreads.bam movie.ccs.bam

I also tried chunking to run a 1/10 piece at a time, and got a same result.
ccs movie.subreads.bam movie.ccs.1.bam --chunk 1/10 -j 1

this create two files:
thread.0_0.name-of-file.ccs.1.bam.tmp
thread.0_0.name-of-file.ccs.1.zmw

When thread.0_0.name-of-file.ccs.1.bam.tmp file size reaches 50.6 MB, CPU urase drops from ~30% to <3%.

Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!
The file is 3.7 GB and cannot attach - I don't know how to split BAM file.

**Expected behavior**
It is possible to run it in other platform than I have (Ubuntu 20.04 on Parallels desctop for Mac on MacOS) - if you have any recommendation, I would greatly appreciate it.

Thank you very much for your help!
Yuko

**Comment by armintoepfer** [comment]
Try again with the latest version and give feedback if it still halts
