### ISSUE TITLE
ccs-kinetics-bystrandify not getting installed with conda install pbbam

### ISSUE THREAD

**Issue by ddubocan** [PacificBiosciences/pbbioconda#403]
Hi,

I have tried updating and reinstalling pbbam to ensure I have the newest version, but there is still no ccs-kinetics-bystrandify executable being installed. The other pbbam executables are present, but this one seems to be absent.

Is there any other straightforward way to install this executable?

**Comment by xzhuo** [comment]
Hi, I am having the same problem. I noticed that conda installed pbbam 1.3 instead of the latest (1.6). 
I tried `conda install -c bioconda pbbam=1.6 --force-reinstall` , and it complained:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package openssl conflicts for:
python=2.7 -> openssl[version='1.0.*|>=1.0.2m,<1.0.3a|>=1.0.2n,<1.0.3a|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.0.2l,<1.0.3a']
pbbam=1.6 -> htslib[version='>=1.12,<1.13.0a0'] -> openssl[version='>=1.1.1a,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1j,<1.1.2a|>=1.1.1k,<1.1.2a']

Package libgcc-ng conflicts for:
pbbam=1.6 -> libgcc-ng[version='>=7.5.0|>=9.3.0']
pbbam=1.6 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.3.0']
```
Is there a quick fix?

**Comment by ddubocan** [comment]
I still have been unable to find a fix for this, and have been unable to use the ccs-kinetics-bystrandify functionality.

**Comment by armintoepfer** [comment]
We will address it in the next update of pbbam. Thank you.

**Comment by armintoepfer** [comment]
We are replacing the binaries from within `pbbam` with a new `pbtk` package. Please try installing that one.
