### ISSUE TITLE
Clarification Regarding Secondary Alignments

### ISSUE THREAD

**Issue by CharlesARoy** [PacificBiosciences/pbbioconda#415]
**Operating system**
OS: CentOS Linux
Version: 7 (Core)

**Package name**
Tool: pbmm2
Version: pbmm2 1.4.0 (commit 1.4.0)

**Describe the bug**
I am confused by the documentation regarding secondary alignments. My goal is to reproduce the default behavior of minimap2 which retains at most 5 secondary alignments. In [the GitHub documentation](https://github.com/PacificBiosciences/pbmm2) for pbmm2 under the section "What other special parameters are used implicitly?" it states that:
> no secondary alignments are produced with --secondary=no

I've tried setting --secondary=yes, but as described [here](https://github.com/PacificBiosciences/pbbioconda/issues/407), doing so causes pbmm2 to throw this error:

> terminate called after throwing an instance of '(anonymous namespace)::CommandLineParserException'
>   what():  [pbcopper] command line parser ERROR: unknown option 'secondary'

In the command-line documentation for the parameters `-N,--best-n` it states that:
> Output at maximum N alignments for each read, 0 means no maximum. [0]

In the command-line documentation for minimap2, the -N parameter is described as follows:

> retain at most INT secondary alignments [5]

When I set -N to 5 with pbmm2, I don't seem to get any secondary alignments in the output. Does this mean that pbmm2 uses the same flag (-N) as minimap2 to mean something different, e.g. supplementary alignments instead of secondary alignments? This sort of seems like the implication of [this thread](https://github.com/PacificBiosciences/pbbioconda/issues/128) but if so, this is quite confusing!

If there's currently no way to include secondary alignments with pbmm2, this option should be included. Some researchers use secondary alignments.

**Comment by armintoepfer** [comment]
There are no secondary alignments with pbmm2 and you can't change that behavior. All you can parametrize is the the output of additional supplementary alignments. If you need secondary alignments, please use another alignment tool.
