### ISSUE TITLE
workflow problem - lima  demultiplex （primer.fasta construction)

### ISSUE THREAD

**Issue by hchen815** [PacificBiosciences/pbbioconda#416]
Hi, I am new here.  We have a project for genome de novo assembly. I got my subread.bam from the company, and used Pbccs to generate the ccs. bam. I have trouble on lima demultiplex.  The company did not supply the primer. fasta file, but we have a .xml file. When I check it, the left and right primer shared the same sequence but with different adapter, I attached the .xml file here.  My question is if I need make the primer fasta with adapter and primer by myself. Moreover, what's the function of the attached .xml
file?
[m64200e_210512_135018.subreadset.xml.docx](https://github.com/PacificBiosciences/pbbioconda/files/6705757/m64200e_210512_135018.subreadset.xml.docx)

**Comment by armintoepfer** [comment]
Hi. This problem is not related to our bioconda binaries. Please contact your local field application specialist or PacBio's technical support at https://www.pacb.com/support/technical-support/
