### ISSUE TITLE
pbsv repository only offering PNGs and BEDs?

### ISSUE THREAD

**Issue by smoe** [PacificBiosciences/pbbioconda#418]
**Operating system**
Looked at the github pbsv repository at https://github.com/PacificBiosciences/pbsv and have the same experience after a download of https://github.com/PacificBiosciences/pbsv/archive/refs/tags/v2.6.2.tar.gz

**Package name**
pbsv

**Conda environment**
I aim at rebuilding from scratch on Debian Linux - and providing a package for it.

**Describe the bug**

No C/C++/_any language_ source files found in the archive or the repository as presented via github, presuming an errant filter while exporting from your internal repository:
```
$ tar xzvf v2.6.2.tar.gz 
pbsv-2.6.2/
pbsv-2.6.2/LICENSE
pbsv-2.6.2/README.md
pbsv-2.6.2/annotations/
pbsv-2.6.2/annotations/human_GRCh38_no_alt_analysis_set.trf.bed
pbsv-2.6.2/annotations/human_hs37d5.trf.bed
pbsv-2.6.2/img/
pbsv-2.6.2/img/pbsv-breakends.png
pbsv-2.6.2/img/pbsv-deletion-workflow.png
pbsv-2.6.2/img/pbsv-duplication.png
pbsv-2.6.2/img/pbsv-insertion-criteria.png
pbsv-2.6.2/img/pbsv-inversion-igv.png
pbsv-2.6.2/img/pbsv-stage-workflow.png
pbsv-2.6.2/img/pbsv-translocation-circa.png
pbsv-2.6.2/img/sv2.png
```
**Error message**
No error message, only me having nothing to compile.

**To Reproduce**
```
wget -O - https://github.com/PacificBiosciences/pbsv/archive/refs/tags/v2.6.2.tar.gz | tar ztf -
```

**Expected behavior**
A regular source tree of pbsv was expected from which the binary could be built.

**Comment by armintoepfer** [comment]
We offer the binary via bioconda. pbsv is not open source and there are no plans to change that.
