### ISSUE TITLE
FR: temp directory parameter for ccs

### ISSUE THREAD

**Issue by sklages** [PacificBiosciences/pbbioconda#425]
**Operating system**
Linux

**Package name**
```
$ ccs --version
ccs 6.0.0 (commit v6.0.0-1-gf46fa2d1)

Using:
  unanimity : 6.0.0 (commit v6.0.0-1-gf46fa2d1)
  pbbam     : 1.6.1 (commit SEQII-release-10.0.0-32-g7d263b7)
  pbcopper  : 1.8.0 (commit SEQII-release-10.0.0-37-gb3a6004)
  boost     : 1.73
  htslib    : 1.10.2
  zlib      : 1.2.11
```
**Issue**
Would be nice to have an option for temp file creation/storage a la `--temp-dir`. Temporary data which will be removed after succesful `ccs` run. Just to reduce I/O on local file systems ...

This may probably apply to other PB tools as well.

**Comment by armintoepfer** [comment]
That's a good idea. `pbmm2` is already using `TMPDIR` and I will add that to ccs.

**Comment by armintoepfer** [comment]
Latest CCS v6.2 now supports this

**Comment by sklages** [comment]
Great thanks. I'll give it a try these days :+1:
