### ISSUE TITLE
Introduction of N's during polishing with Arrow

### ISSUE THREAD

**Issue by nicolasalexandre21** [PacificBiosciences/pbbioconda#426]
Hello,

After assembling the genome with Falcon Unzip, the assembly does not contain N's. In the final assembly submitted to Genbank, I received a notification of gaps. I then looked at the number of N's at each step of assembly and find that these N's were introduced after running arrow.

faCount 3-unzip/all_p_ctg.fasta 
faCount 4-polish/cns-output/cns_p_ctg.fasta
faCount arrow.fa

#seq    len     	A       	C       	G       	T       	N       cpg
total	699512654	221410002	128291489	128294697	221516466	0	16042632
total	697564538	220782858	127964867	127945052	220871761	0	15989738
total	697569805	220782858	127964867	127945052	220871761	5267	15989730

The following are the commands used to polish:

	source activate falcon
	module load samtools
	pbmm2 index arrow.fa arrow.mmi
	pbmm2 align arrow.mmi m64044_191209_131236.subreads.bam pbm.bam --sort -j 14 -J 6
	pbindex pbm.bam #creates .pbi file
	samtools faidx arrow.fa #creates.fai file
	
	conda create -n arrow
	source activate arrow
	conda install -c bioconda pbgcpp
	gcpp -j 48 --algorithm=arrow pbm.bam -r arrow.fa -o variants.gff, consensus.fasta, consensus.fastq 

Genbank asks:

* Do any of the N's represents gaps of completely unknown size (the gap size was NOT estimated by an assembly program and a single value, eg 100, was used)?

Can you help me answer this question?

Thank you!

**Comment by armintoepfer** [comment]
Please contact PacBio's tech support. We are phasing out CLR support.
