### ISSUE TITLE
isoseq3 cluster

### ISSUE THREAD

**Issue by rsalz** [PacificBiosciences/pbbioconda#43]
Running isoseq3 v3.0.0 on Ubuntu 16.04 with conda as in this tutorial: https://github.com/PacificBiosciences/IsoSeq_SA3nUP/wiki/Tutorial:-Installing-and-Running-Iso-Seq-3-using-Conda

I am following the tutorial down to the letter and cannot get the isoseq3 cluster step to work, no matter what options I use. When I run it without arguments I get the help page, which leads me to believe it must be functional. But every time I put any input in, I get "Illegal instruction". I have the command as requested; "isoseq3 cluster demux.P5--P3.bam unpolished.bam", with and without extra options. Still no luck.

Does anyone know what the problem could be?

**Comment by armintoepfer** [comment]
https://github.com/PacificBiosciences/IsoSeq3/blob/master/README.md#the-binary-does-not-work-on-my-linux-system

Your system does not support the SIMD instructions we use, because it's too old.
