### ISSUE TITLE
pbalign docs: outdated 

### ISSUE THREAD

**Issue by nick-youngblut** [PacificBiosciences/pbbioconda#431]
It appears that the script docs listed at https://github.com/PacificBiosciences/pbalign/blob/master/doc/howto.rst do not actually match the most up-to-date pbalign on bioconda (v0.3.2).

Also, it would be great if pbalign supported fastq input files. I'm surprised that it doesn't according to `Input can be a
fasta, pls.h5, bas.h5 or ccs.h5 file or a fofn`, given all of the other inputs allowed. There's also no info on whether the input read file can be compressed.

**Comment by armintoepfer** [comment]
Hi! `pbalign` has been deprecated. We are not going to make any changes to the software nor documentation. Please use `pbmm2` to align FASTQ files.
