### ISSUE TITLE
ccs ERROR: Missing base features: IPD or PulseWidth

### ISSUE THREAD

**Issue by shiwg-eco** [PacificBiosciences/pbbioconda#432]
**Operating system**
 Ubuntu 20.04.2 LTS

**Package name**
ccs 6.0.0 (commit v6.0.0-2-gf165cc26)

**Conda environment**
https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

**Describe the bug**
I encountered this error while processing PacBio data with subreads
ccs  m64165_210714_075530.subreads.bam m64168e_210625_201404.ccs.fastq.gz

**Error message**
ccs ERROR: Missing base features: IPD or PulseWidth

**Expected behavior**
Is there something wrong with the software or is there something wrong with the data?

**Comment by armintoepfer** [comment]
Are you sure the input are subreads? Do they include the `pw` and `ip` tags?
