### ISSUE TITLE
pbipa conda update?

### ISSUE THREAD

**Issue by marchoeppner** [PacificBiosciences/pbbioconda#433]
Hi,

according to the git page for pbipa, there is a new and apparently greatly improved version 1.5.0 for IPA. This was about a month ago and so far this version has not found its way into conda. I was hoping to use this new version in a genome project we are working on (and the stand-alone installation is distinctly un-fun...).

https://github.com/PacificBiosciences/pbipa/releases/tag/v1.5.0

Thanks!
Marc

**Comment by zeeev** [comment]
Thanks for mentioning this. We are currently working on publishing a new release in the next two weeks.

**Comment by zeeev** [comment]
Hello @nitishnih and @marchoeppner Just finished releasing v1.5.0 to bioconda.
