### ISSUE TITLE
Computer requirements 

### ISSUE THREAD

**Issue by Paula27222** [PacificBiosciences/pbbioconda#435]
Hello, 
I have a human diploid genome sequenced with 1 SMRT 8M and the following characteristics: 

HiFi Reads 1,659,340 
HiFi Yield (bp)29,448,885,239 
HiFi Read Length (mean, bp) 17,747 
HiFi Read Quality (median) Q30 
HiFi Number of Passes (mean)10

I would like to ask exactly what are the minimum requirements for phased polished assembly with IPA (in terms of RAM memory, nº of CPU and TB of memory). How much time would it take, approximately? How big are the output files?

Thanks in advance for your answer.

**Comment by zeeev** [comment]
See compute requirements for SMRT Link. 

https://www.pacb.com/wp-content/uploads/SMRT_Link_Installation_v701.pdf
