### ISSUE TITLE
pbsv call ERROR: Unknown file type for input number 0 with file name

### ISSUE THREAD

**Issue by amv33576** [PacificBiosciences/pbbioconda#439]
**Operating system**
Linux 

**Package name**
pbsv 2.6.2

**Conda environment**
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
bamtools                  2.5.1                h9a82719_9    bioconda
biopython                 1.79             py38h497a2fe_0    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.2               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py38h578d9bd_0    conda-forge
cffi                      1.14.6           py38ha65f79e_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.10.3           py38h578d9bd_2    conda-forge
conda-package-handling    1.7.3            py38h497a2fe_0    conda-forge
cryptography              35.0.0           py38ha5dfef3_0    conda-forge
csvtk                     0.23.0               h9ee0642_0    bioconda
deprecated                1.2.13             pyh6c4a22f_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
htslib                    1.12                 h9093b5e_1    bioconda
idna                      3.1                pyhd3deb0d_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
krb5                      1.19.2               hcc1bbae_2    conda-forge
last                      1238                 h2e03b76_0    bioconda
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
ldc                       1.20.0               h9a1ace1_1    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libblas                   3.9.0           12_linux64_openblas    conda-forge
libcblas                  3.9.0           12_linux64_openblas    conda-forge
libcurl                   7.79.1               h2574ce0_1    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
liblapack                 3.9.0           12_linux64_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libopenblas               0.3.18          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.3.0                hf544144_1    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
nanofilt                  2.8.0                      py_0    bioconda
nanoget                   1.16.1                     py_0    bioconda
nanomath                  1.2.1              pyhdfd78af_0    bioconda
nanosv                    1.2.4                      py_0    bioconda
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.21.2           py38he2449b9_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
pandas                    1.3.3            py38h43a58ef_0    conda-forge
parallel                  20210822             ha770c72_0    conda-forge
pbmm2                     1.7.0                hdcc8f71_0    bioconda
pbsv                      2.6.2                h9ee0642_0    bioconda
perl                      5.32.1          1_h7f98852_perl5    conda-forge
pillow                    8.3.2            py38h8e6f84c_0    conda-forge
porechop                  0.2.4                    pypi_0    pypi
pycosat                   0.6.3           py38h497a2fe_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pysam                     0.17.0           py38hf7546f9_0    bioconda
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
python                    3.8.5                h7579374_1  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyvcf                     0.6.8           py38h32f6830_1002    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py38h497a2fe_1004    conda-forge
sambamba                  0.8.1                h41abebc_0    bioconda
seqkit                    2.0.0                h9ee0642_0    bioconda
seqtk                     1.3                  h5bf99c6_3    bioconda
setuptools                58.2.0           py38h578d9bd_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h9cd32fc_2    conda-forge
tabix                     1.11                 hdfd78af_0    bioconda
tk                        8.6.11               h27826a3_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wrapt                     1.13.2           py38h497a2fe_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge

**Describe the bug**
**pbsv call** did not work.

sequence of commands:
**pbmm2 align** scaffold1.mmi reads.ccs.fastq scaffold1.pbmm2.sr.bam --preset CCS --sort -j 16 -J 8  --rg '@RG\tID:myid\tSM:scaffold1'
-> This worked, I can see the alignments

**pbsv discover** scaffold1.pbmm2.sr.bam scaffold1.pbmm2.svsig.gz
--> Run, not error message

**pbsv call** --ccs scaffold1.fas scaffold1.pbmm2.svsig.gz scaffold1.pbmm2.vcf
--> it did not run.

**Error message**
**>|> 20211016 05:51:57.299 -|- FATAL -|- Run at ../subprojects/pbcopper/src/cli2/CLI.cpp:139 -|- 0x7f61115cd780|| -|- pbsv call ERROR: Unknown file type for input number 0 with file name "scaffold1.fas"**

**To Reproduce**
I am aligning the reads to one scaffold of a butterfly genome. 

**Expected behavior**
Call structural variants from structural variant signatures.

**Comment by armintoepfer** [comment]
There's no support for .fas, rename it to .fasta

amv33576 ***@***.***> schrieb am Sa., 16. Okt. 2021, 07:54:
