### ISSUE TITLE
pbccs handling of mixed bases at position

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#440]
Hi,
How does pbccs handle the following two situations?
1) At the same consensus position, there is a different base at high quality on each strand.
2) At the same consensus position with pbccs -by-strand, one of the strands has two different bases (on average ~1/2 of the strand subreads has one base, and the other half have another base)

The above may technically happen with DNA damage or modified DNA bases.

The question is conceptually how does pbccs handle this? What final consensus base will be emitted? How will it affect read quality? How will it affect base quality?

**Comment by armintoepfer** [comment]
The base with the higher probability, given the model parameters, is chosen as the consensus. The per-base and read QV will reflect the reduction in quality, if there are ambiguity present.
