### ISSUE TITLE
I cannot run bax2bam, ERROR, could not open hdf.

### ISSUE THREAD

**Issue by PavitaKae** [PacificBiosciences/pbbioconda#441]
**Operating system**
Linux

**Package name**
bax2bam

**Conda environment**
'''
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
bax2bam                   0.0.11                        0    bioconda
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sqlite                    3.36.0               h9cd32fc_2    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge)
'''
**Describe the bug**
I run command 
bax2bam m140717_215757_00127_c100661112550000001823130211271425_s1_p0.1.bax.h5 m140717_215757_00127_c100661112550000001823130211271425_s1_p0.2.bax.h5 m140717_215757_00127_c100661112550000001823130211271425_s1_p0.3.bax.h5 
-o ERR2282005

**Error message**
ERROR, could not open hdf filem140717_215757_00127_c100661112550000001823130211271425_s1_p0.1.bax.h5, exiting.

**Expected behavior**
BAM file

**Comment by pH2Oo** [comment]
> Please use `bax2bam` from SL8, `bax2bam` from Bioconda is not supported anymore is known to be broken.

Hello! I'm wondering how to get bax2bam from SL8? Thanks

**Comment by armintoepfer** [comment]
https://www.pacb.com/support/software-downloads/
