### ISSUE TITLE
Extracting subreads from PacBio BAM using CCS ZMW name

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#443]
Hi,
Is there a rapid way to extract subreads from PacBio subreads BAM file using a list of CCS ZMW names?

Just using grep -f is too slow.

Thanks.

**Comment by natechols** [comment]
I don’t think it’s in bioconda but the tool “bamsieve” in the full SMRT
Link distribution was written for exactly this purpose, although it’s not
blazingly fast either.

**Comment by gevro** [comment]
bamsieve is actually slower than grep. I'm trying to find something faster. I think a solution might be with 'join' using the hole numbers, but haven't quite figured it out yet.

**Comment by derekwbarnett** [comment]
We have a tool just for this in bioconda - "zmwfilter" (available for linux-only)

`$ zmwfilter --include <zmws.txt> <in.bam> <out.bam>`
"zmws.txt" should be contain one ZMW ID number per line. 

If you only have the full read names, you can extract these with:
`$ cut -f 2 -d '/' read_names.txt > zmws.txt`

**Comment by gevro** [comment]
I think this might work:
Assuming holeslist and subreads-bam holes are numerically sorted

```
awk 'BEGIN{idx=1;matched=0}{if(FNR==NR){holes[NR]=$1}else{split($1,hole,"/");if(hole[2]==holes[idx]){print $0;matched=1}else{if(matched==1){idx++;matched=0}}}}' holeslist <(samtools view subreads.bam) > output
```

Then need to combine the final output with a header file and turn it back into a BAM.

**Comment by gevro** [comment]
> zmwfilter

Thanks! I will try that too.

**Comment by gevro** [comment]
Do the ZMW hole numbers in --include includezmws.txt need to be sorted numerically, or at all?

**Comment by derekwbarnett** [comment]
No, any order is fine. Duplicates are ok too. Just has to be one per line.
