### ISSUE TITLE
ccs bug report

### ISSUE THREAD

**Issue by niradsp** [PacificBiosciences/pbbioconda#444]
**Operating system**
Linux
**Package name**
The pbccs package.
I am using the latest version, which is version 6.2.0.

**Error message**
BAM file truncated

**To Reproduce**
Two files with the same name.  
For example:
sample1_run1/sample1.subreads.bam
and
sample1_run2/sample1.subreads.bam

The command basically is:
ccs input output

**Expected behavior**

What happens is that if the filenames are the same, when they are being processed in the temporary folder, one file overwrites the other.  As a result, this ends in a truncated bam file error.  
To rectify this issue, I had to rename the second file as sample1_run2.subreads.bam

There are situations though where two files will have the same name.  So I think what needs to happen is, in the temporary folder, maybe two folders can be created, so that the different files are placed in different folders.  If it is processed this way, the error message should go away.

**Comment by armintoepfer** [comment]
Thanks for reporting. You can set the `TMPDIR` env variable manually to avoid this problem. We'll discuss internally if this feature should make it into production.
