### ISSUE TITLE
lima bug: terminate called after throwing an instance of 'PacBio::BarcodingAbort'

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#445]
Note my updated post for bug #258. I have also replicated this a second time.

**Comment by gevro** [comment]
Replicated on lima 2.4.0, but it throws the error with different wording:
```
terminate called after throwing an instance of 'PacBio::Utility::AlarmException'
```

**Comment by armintoepfer** [comment]
This is very likely a filesystem issue. Are you running on a local disk or a network file system?
The `demux.bam.tmp` will be renamed first to `demux.bam` and then the `.pbi` gets created. If it fails to create the `.pbi` and the `demux.bam.tmp` remains, it could be that the file system is a bit too slow.

**Comment by gevro** [comment]
I'm running it on a network file system as:
lima --same --split-bam-named --dump-removed alignedsubreads.bam barcodes.fasta alignedsubreads.demux.bam

When it crashes, the output directory contains:
- removed.bam
- removed.bam.pbi -> Looks intact (several megabytes in size), but not sure
- all the demultiplexed bc####--bc####.bam.tmp

Is that consistent with your hunch of what is going on? Because I think that is different from the step you suggest.

When it crashed on lima 2.0, it gave this error:
```
terminate called after throwing an instance of 'PacBio::BarcodingAbort'
  what():  Could not generate PBI file for BAM file alignedsubreads.demux.removed.bam
```

But at that point the removed.bam existed and removed.bam.pbi file was already several megabytes in size. So that is weird that it is saying it cannot generate a PBI for removed.bam when it already was in the process or it finished making it. Sounds like some internal lima sync problem too?

In any case, can you push a bug fix so lima checks that .bam exists before it tries to create the .pbi, or some other fix? We cannot run lima at all on our network system due to this bug. And network file systems are used by most users.

**Comment by armintoepfer** [comment]
I'll look into a solution, but so far this issue is limited to users with slow network filesystems.

**Comment by armintoepfer** [comment]
Please have a try with this develop version.
[lima.zip](https://github.com/PacificBiosciences/pbbioconda/files/7641622/lima.zip)

**Comment by gevro** [comment]
That fixed it. Can you include this fix in the next official release?

**Comment by armintoepfer** [comment]
Yes that's in the next release. Good to hear.
