### ISSUE TITLE
Simple Q: can ccs stream Google Buckets

### ISSUE THREAD

**Issue by SHuang-Broad** [PacificBiosciences/pbbioconda#449]
Hi,

I've a simple question, can ccs accept streamed BAM stored in Google buckets?
Because I see the following from https://ccs.how/faq/sqiie.html

```
/opt/pacbio/pa-ccs/current/bin/ccs \ # binary
  ...
  --streamed \ # do not use a BAM file as input, but a BAM input stream
  ...
  --bam /data/pa/m64012_201202_224049.reads.bam \ # explicit BAM file name
```

If so (that'd super nice), do I just provide the gs-path to `--bam`?

Thanks!
Steve

**Comment by armintoepfer** [comment]
Hi Steve,

the `--bam` option is for the output file. If you use `--streamed` then there is no explicit input file, but it uses stdin. Quick example:

```
samtools view -h input.bam | ccs out.bam --log-level INFO --streamed
```

If you can call `samtools` with your file from your cloud source, then it should work. Does that make sense to you?
