### ISSUE TITLE
error occurred in  3-unzip/2-htigs step of falcon_unzip.

### ISSUE THREAD

**Issue by lee123lee** [PacificBiosciences/pbbioconda#45]
**Error message**
the message in 3-unzip/2-htigs/chunk_002716F/run-P3105148f148918.bash.stderr:
`[ERROR 2018-11-05 02:39:40] Failure in generate_haplotigs_for_ctg((u'002716F', u'../../0-phasing/002716F/uow-00/proto', './uow-002716F', u'../../..', False))
Traceback (most recent call last):
  File "~/miniconda2/envs/assembly/lib/python2.7/site-packages/falcon_unzip/mains/graphs_to_h_tigs_2.py", line 74, in run_generate_haplotigs_for_ctg`

  .........skipping...........

`raise Exception(msg)
Exception: Skipping additional subgraphs of the primary contig: 002716F. The graph has multiple primary components.`

How can I fix it? Or, how to skip the contig(002716F)? Actually, I have three similar contig that make me can't go on .

**Comment by marcopessoa** [comment]
#31

**Comment by marcopessoa** [comment]
Looks like the same issue reported in #31

**Comment by lee123lee** [comment]
Thanks for your response. 
This issue really looks like #31, but I can not find the solution for the repeated issue under #31. So I open the new issue. 
Do you have any idea about the issue? Thanks.

**Comment by marcopessoa** [comment]
Not really, there was no response in #31, I am currently using a previous commit of FALCON-integrate from march 2018 to continue my project.

**Comment by lee123lee** [comment]
oh! I checked the problem `fc_run` assembly in my item when I saw your comment under #31. I found the same configure, `fc_run` is `falcon-kit 1.2.4`, and `fc_unzip` is '`falcon-kit 1.2.3'. Interestingly, the cause of all this is that I update the `pb-assembly` after  `fc_run` as well. So, now I am running a new assembly by the same version `pb-assembly`. 
Maybe this is the solution. good luck to us!

**Comment by isovic** [comment]
Hi,
Thank you for reporting this issue - it indeed its the same as #31.
We addressed it and it should have been resolved in `falcon-unzip 1.1.4` available in `pb-falcon>=0.2.4` and `pb-assembly>=0.0.2`.
Do you manage to finish your assembly process using the latest version?

**Comment by marcopessoa** [comment]
My run is in the final polishing step with Arrow, so I would say yes. Thanks for the feedback!

**Comment by isovic** [comment]
Thank you as well!
Ok, I will close both this issue and issue #31. In case there are more failures like this, don't hesitate to reopen one of the two.
Best regards,
Ivan.
