### ISSUE TITLE
--hifi-kinetics with --by-strand

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#452]
Hi,
For ccs 6.2.0, is it possible to run --hifi-kinetics with --by-strand? Will the output make sense and be formatted correctly?
Thanks.

**Comment by armintoepfer** [comment]
They are mutually exclusive. If you try it, you should get an error.

**Comment by gevro** [comment]
Is it possible to add this as a feature request? It would be very useful to see the different sequences of each strand as well as their different kinetics.

**Comment by gevro** [comment]
Hi, Just following up if this could be possible? Kinetics + by-strand is a far more useful and formally correct way to analyze kinetics. Because kinetics is for strand-specific modifications and damage.

And CCS consensus of by-strand won't necessarily match up to consensus dsDNA consensus, so there is no simple way to annotate --by-strand ccs reads with --hifi-kinetics tag data.

**Comment by pb-dseifert** [comment]
yes, we're aware that kinetics in by-strand mode is an interesting feature for people. We're looking into it, but can't give an ETA.

**Comment by gevro** [comment]
Ok. This would be hugely important in my opinion. I can’t think of a more impactful and interesting feature for ccs than this. Very much hope you all prioritize this soon.

Doing this manually by aligning subreads to ccs consensus for each strand is a headache… rather than this being a native feature of by-strand ccs.

**Comment by armintoepfer** [comment]
The latest CCS v6.4.0 allows it.

**Comment by gevro** [comment]
Wonderful!!! Thank you
