### ISSUE TITLE
laa with CCS

### ISSUE THREAD

**Issue by sagnikbanerjee15** [PacificBiosciences/pbbioconda#453]
I have CCS generated by the latest Sequel machine. Hence, I do not have subreads file. How do I run laa with CCS?

Thanks

**Comment by armintoepfer** [comment]
You can't. LAA runs on subreads.

**Comment by sagnikbanerjee15** [comment]
Thanks for your reply. How do I generate consensus from the CCS reads?

Thanks.

**Comment by zeeev** [comment]
pbAA is the correct tool for hifi amplicon analysis

https://github.com/PacificBiosciences/pbAA

**Comment by sagnikbanerjee15** [comment]
Great thanks
