### ISSUE TITLE
SVSIG format specification

### ISSUE THREAD

**Issue by RenzoTale88** [PacificBiosciences/pbbioconda#455]
Hello,
I was wondering, would it be possible to have some additional details about the content of the svsig file? Something in the line of a specification file with the example of each line.
Thank you in advance
Andrea

**Comment by armintoepfer** [comment]
Hi Andrea,

The svsig file is an intermediate file and its format is subject to constant change. Since this is heavily implementation specific, I don't feel comfortable writing down a spec.

Armin
