### ISSUE TITLE
PacBio sequence: synthesized strand or copied strand?

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#458]
Hi,
I have a very technical, but simple question: when the PacBio instrument records DNA sequences in the raw subreads file, are those the sequences of the DNA that is being synthesized, or the DNA that is being copied?

Additionally, after running pbccs with the --by-strand option, do the /fwd and /rev labels refer to the strand physically being synthesized by the polymerase, or is there a reverse complement step somewhere in the instrument code or in pbccs that transforms it to the sequence of the strand being copied?

Thanks.

**Comment by armintoepfer** [comment]
We are reporting the base present in the molecule.

Regarding by-strand: https://github.com/PacificBiosciences/pbbioconda/issues/458

If that's not enough detail, please reach out to your field application specialist or tech support.
