### ISSUE TITLE
lima: peek-guess not giving results

### ISSUE THREAD

**Issue by jhcaddisfly** [PacificBiosciences/pbbioconda#459]
Hi,

I am not really reporting a bug but rather have a question on the peek-guess option.
Please delete if inappropriate. 

**Operating system**
CentOS Linux 8 (Core)

**Package name**
lima/2.2.0

**Describe the bug**
The following command failed:
lima --ccs mx.ccs.bam barcode.fasta resultsx.ccs.bam --peek-guess --same --split-bam-named --bam-handles 4 --bam-handles-verbose --min-score 26 --num-threads 34  

When I run it without --peek-guess it is working and it gives the following results:
lima --ccs mx.ccs.bam barcode.fasta resultsmx.ccs.bam --same --split-bam-named --bam-handles 4 --bam-handles-verbose --min-score 26 --num-threads 34  

IdxFirst        IdxCombined     IdxFirstNamed   IdxCombinedNamed        Counts  MeanScore
0       0       bc1001_BAK8A_OA bc1001_BAK8A_OA 565740  62
1       1       bc1002_BAK8A_OA bc1002_BAK8A_OA 7       31
2       2       bc1003_BAK8A_OA bc1003_BAK8A_OA 25      40
3       3       bc1008_BAK8A_OA bc1008_BAK8A_OA 522909  62
4       4       bc1009_BAK8A_OA bc1009_BAK8A_OA 95      51
5       5       bc1010_BAK8A_OA bc1010_BAK8A_OA 471050  62
6       6       bc1011_BAK8A_OA bc1011_BAK8A_OA 429204  66
7       7       bc1012_BAK8A_OA bc1012_BAK8A_OA 5       32
Am I correct that the peek-guess option removes spurious barcode hits? The barcodes which were used are bv1001, bc1008, bc1010, bc1011. What does that mean?

**Error message**
| FATAL | ERROR: Could not find matching barcodes! Check that the set of barcodes contains the used sequences and the correct mode has been selected: same or different.

Thanks,
J.

**Comment by armintoepfer** [comment]
Looks like your barcodes are of really low quality. CCS results should have >80. It's not a technical issue, but your days qualify seems low.
