### ISSUE TITLE
ccs ERROR: Missing base features: IPD or PulseWidth

### ISSUE THREAD

**Issue by fafaris39** [PacificBiosciences/pbbioconda#460]
**Operating system**
Ubuntu 20.04.3 LTS

**Package name**
bioinfo/SMRTLink_v9.0.0

**files**
file.bam ( subreads file)
file.bam.pbi

**Describe the bug**
 I encountered this error while processing PacBio data with the cammand below:
ccs file.bam   file.ccs.bam   --noPolish --minPasses 1

**Error message**
ccs ERROR: Missing base features: IPD or PulseWidth

**Expected behavior**
I used the same command from the workflow of isoseq3,  did i use the wrong  file ? what should i do?

**Comment by armintoepfer** [comment]
Yes, it sounds like you've used the wrong file. In addition, we are not
maintaining the package your are referring to.

fafaris39 ***@***.***> schrieb am Di., 11. Jan. 2022, 16:21:
