### ISSUE TITLE
zmwfilter very slow

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#461]
Hi,
Filtering 14,000 ZMW holes from an 800 Gb subreads BAM file using 'zmwfilter' is taking > 3 hours. That seems too slow. Is there any speed improvement, or any other way to do this?

**Comment by armintoepfer** [comment]
It's very likely your file system. There's nothing I can think of. You could parallelize by having maybe 100x 140 ZMWs and then samtools merge?

**Comment by gevro** [comment]
I don't think so. I'm on an SSD drive. Filtering a small number of variants is super fast, i.e. < 1 minute. Increasing to thousands of variants causes a stand-still.

Also reported by another user: https://github.com/PacificBiosciences/zmwfilter/issues/1

**Comment by armintoepfer** [comment]
I'll file it internally. We'll come back when we have a solution.

**Comment by gevro** [comment]
Thanks. This is a bit urgent for me, because I can't complete my analysis without this. So I appreciate any help.

**Comment by gevro** [comment]
Note some more data, and a work-around I found in the meantime:

1. Some more tests show the time per hole extraction is linear, ~0.2 sec/hole on the fastest disk/machine. However, this is too slow for large numbers of holes. It would take 5.5 hours for 100,000 holes.

2. A single pass through the full subreads.BAM using this awk script is faster than trying to extract about > 20,000 holes with zmwfilter. This script below takes the same amount of time regardless of the number of holes that are extracted, but is slower for about < 20,000 holes than using zmwfilter.
```
samtools view -@8 -h subreads.bam | awk 'BEGIN{idx=1;matched=0}{if(FNR==NR){holes[NR]=$1}else{split($1,hole,"/");if(hole[2]==holes[idx]){print $0;matched=1}else{if(matched==1){idx++;matched=0;if(hole[2]==holes[idx]){print $0;matched=1}}}}}' holes.txt - | samtools view -b - > output.sam

#holes.txt = numerically sorted hole numbers, one per line
```

**Comment by armintoepfer** [comment]
I've rebuild with the latest dependencies. 20k ZMWs are now being filtered in 45s on my machine. Please let me know if that works and I'll upload to bioconda:

https://github.com/PacificBiosciences/zmwfilter/releases/tag/v1.0.0

**Comment by gevro** [comment]
Works great! Please let me know once on bioconda.

**Comment by gevro** [comment]
Actually, there's some issue I think. I'm trying to 'samtools index' the resulting BAM, but it isn't working. It outputs a 16 byte BAM index. Maybe something is malformed in the BAM output.

**Comment by armintoepfer** [comment]
`samtools index` on an unaligned BAM always results in an empty BAI.

**Comment by gevro** [comment]
Ah, yes, correct. My mistake.

**Comment by armintoepfer** [comment]
It's in bioconda. Still as version 1.0.0, though the internal version is 1.2.0. Will correct that at some point.

**Comment by gevro** [comment]
Just confirming, 1.0.0 on bioconda now is the same as the release version you linked to in github?
(i.e. 1.2.0 is just a labeling issue, and not a different version?)
Thanks.

**Comment by gevro** [comment]
Oh, nevermind. I see that it is labeled in bioconda as 1.0.0, but the binary version output is 1.2.0.
