### ISSUE TITLE
pbindexdump - uses a lot of memory

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#465]
pbindexdump uses a large amount of RAM. It crashes out of memory with 64 G RAM on a 2.7Gb pbi file. Seems like it should not take that much RAM to dump an index file.

It also sometimes crashes with "Bus error".

Also, it runs very slowly.

Perhaps this is the cause of zmwfilter being slow, if it is using the same underlying pbindexdump code

**Comment by armintoepfer** [comment]
pbindexdump is an internal tool and not used in production pipelines. We will have a look, but this is low priority. Will ping here if we find something

**Comment by gevro** [comment]
FYI: Bug doesn't seem to happen when doing --format cpp. Issue is probably in the json conversion.
