### ISSUE TITLE
ccs_reports.txt: by-strand Definitions

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#466]
Hello,
For ccs 6.2.0, the reports output when running --by-strand ccs_reports.txt, has two items that are not defined in the documentation:

1) Inputs:```
                           Single-Strand Reads
Inputs                   :       9313 (86.38%)
```
 => How is 'Inputs' < 100%? Shouldn't Inputs = 100%? What does inputs mean exactly if it does not include all the reads? If it doesn't include all the reads, what filter is being applied before ccs?

2) Are the counts in the reports file showing subread counts, or zmw counts?

Thank you.

**Comment by armintoepfer** [comment]
It's described in the ccs.how docs
