### ISSUE TITLE
Error in rule phasing_prepare:

### ISSUE THREAD

**Issue by ardy20** [PacificBiosciences/pbbioconda#467]
Dear All

I run IPA via conda and I get a error at phsing_prepare stage. Can anyone help me to udnerstand what is the problem?

The error is as follows:

Nighthawk 0.1.0 (commit SL-release-10.1.0-7-gbe5dfb1*)
>|> 20220207 05:12:28.191 -|- INFO -|- SplitOverlapsBySimilarity -|- 0x2ad9380edc80|| -|- Getting read name to id.
>|> 20220207 06:03:19.781 -|- INFO -|- SplitOverlapsBySimilarity -|- 0x2ad9380edc80|| -|- Getting hash to name.
>|> 20220207 06:53:54.389 -|- INFO -|- SplitOverlapsBySimilarity -|- 0x2ad9380edc80|| -|- Getting counts per chunk.
>|> 20220207 06:53:54.907 -|- INFO -|- SplitOverlapsBySimilarity -|- 0x2ad9380edc80|| -|- Assigning names to chunks.
>|> 20220207 06:53:58.229 -|- INFO -|- SplitOverlapsBySimilarity -|- 0x2ad9380edc80|| -|- Writing chunk files.
>|> 20220207 06:54:01.017 -|- FATAL -|- Run -|- 0x2ad9380edc80|| -|- split ERROR: [pbbam] text file writer ERROR: could not open plain text file:
  file: chunk.1020.m4
  reason: Too many open files
5854.95user 185.74system 1:41:33elapsed 99%CPU (0avgtext+0avgdata 1164188maxresident)k
64inputs+8outputs (1major+9457808minor)pagefaults 0swaps
[Mon Feb  7 16:54:01 2022]
Error in rule phasing_prepare:
    jobid: 15
    output: 06-phasing_prepare/shards, 06-phasing_prepare/shards/pwd.txt
    shell:

        sharddir=$(dirname 06-phasing_prepare/shards/pwd.txt)
        rm -rf $sharddir
        mkdir -p $sharddir
        cd $sharddir
        rel=../..

        input_m4="$rel/05-ovl_asym_merge/ovl.nonlocal.m4"         output_shard_ids=./all_shard_ids         output_pwd=./pwd.txt         params_config_sh_fn="$rel/01-generate_config/generated.config"         params_max_nchunks="40"         params_log_level="INFO"         params_tmp_dir="/tmp"             time ipa2-task phasing_prepare

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job phasing_prepare since they might be corrupted:
06-phasing_prepare/shards
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /scratch/project_mnt/S0030/ipa2/RUN/.snakemake/log/2022-02-07T151227.090544.snakemake.log
ERROR: Command '/scratch/project/qaafi-cnafs/ipa2/bin/python3 -m snakemake -j 1 -d /scratch/project/qaafi-cnafs/ipa2/RUN -p -s /scratch/project/qaafi-cnafs/ipa2/etc/ipa.snakefile --configfile /scratch/project/qaafi-cnafs/ipa2/RUN/config.yaml --reason' returned non-zero exit status 1.
Exiting.

**Comment by zeeev** [comment]
The error message states: ```reason: Too many open files```. Adjust the number of files the system allows to be open.
