### ISSUE TITLE
IPA 1.5 install issues

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/pbbioconda#470]
Working on my SMRT Link server (ubuntu 20)
relates to #448

I installed IPA from the instruction on [https://github.com/PacificBiosciences/pbipa](https://github.com/PacificBiosciences/pbipa) but It seems that the IPA page is not listing all required dependencies  OR that they do not install correctly when running ```conda install pbipa```

I had first an error ```samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory```

which **I thought** I fixed with ```sudo apt install libcrypto++-dev```

The next run crashed with ```ImportError: cannot import name 'parse_uri' from 'smart_open' ``` 

I installed ```conda install smart_open``` which updated it from 1.8 to 5.1.0 !!!!

IPA is now running but samtools keeps complaining about ssl and I hope that the assembly will complete.

I meanwhile discovered ```ipa validate``` which is still reporting libcrypto issues

```
INFO: /opt/miniconda3/envs/pb_ipa/bin/ipa validate
INFO: ipa.py ipa (wrapper) version=1.5.0 ... Checking dependencies ...
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
INFO: Dependencies
/opt/miniconda3/envs/pb_ipa/bin/python3
/opt/miniconda3/envs/pb_ipa/bin/ipa2-task
/opt/miniconda3/envs/pb_ipa/bin/falconc
/opt/miniconda3/envs/pb_ipa/bin/minimap2
/opt/miniconda3/envs/pb_ipa/bin/nighthawk
/opt/miniconda3/envs/pb_ipa/bin/pancake
/opt/miniconda3/envs/pb_ipa/bin/pblayout
/opt/miniconda3/envs/pb_ipa/bin/racon
/opt/miniconda3/envs/pb_ipa/bin/samtools
/opt/miniconda3/envs/pb_ipa/bin/ipa_purge_dups
/opt/miniconda3/envs/pb_ipa/bin/ipa_purge_dups_split_fa
snakemake version=6.3.0
ipa2-task 1.5.0 (commit c875fce13bdacbafc2f4f750c6438f4453e1354d)
 Machine name: 'Linux'
Copyright (C) 2004-2021     Pacific Biosciences of California, Inc.
This program comes with ABSOLUTELY NO WARRANTY; it is intended for
Research Use Only and not for use in diagnostic procedures.

falconc version=1.13.1+git.f9d1b5651e891efe379bd9727a0fa0931b875d7b, nim-version=1.5.1
minimap2 version=2.24-r1122
Nighthawk 0.1.0 (commit SL-release-10.1.0-7-gbe5dfb1*)
pancake 1.3.0 (commit SEQII-release-10.1.0-432-gf2693fd*)
pblayout 1.0.0 (commit SL-release-10.1.0-152-g66936d1*)
racon version=v1.4.20
ipa_purge_dups Version: 1.2.5
```

When I try the **samtools 1.9 reinstall solution** from [https://github.com/merenlab/anvio/issues/1479](https://github.com/merenlab/anvio/issues/1479) 

```conda install -c bioconda samtools=1.9 --force-reinstall```

I get notifications about pacbio package changes which make me fear the worse!

It seems that IPA 1.5 is bound to samtools 1.7 and that this samtools misses the libcrypto in conda. 

Upgrading samtools to 1.9 downgrades IPA which is not what one wants!

```The following NEW packages will be INSTALLED:

  nim-falcon         bioconda/linux-64::nim-falcon-3.0.1-h1341992_0
  pbmm2              bioconda/linux-64::pbmm2-1.3.0-h56fc30b_0

The following packages will be REMOVED:

  pb-falconc-1.13.1-h6e72b04_0

The following packages will be UPDATED:

  samtools                                            1.7-1 --> 1.9-h10a08f8_12

The following packages will be SUPERSEDED by a higher-priority channel:

  krb5                    pkgs/main::krb5-1.19.2-hac12032_0 --> conda-forge::krb5-1.19.2-hcc1bbae_0
  libedit            pkgs/main::libedit-3.1.20210910-h7f87~ --> conda-forge::libedit-3.1.20191231-h46ee950_2
  python                pkgs/main::python-3.7.11-h12debd9_0 --> anaconda::python-3.7.6-h0371630_2

The following packages will be DOWNGRADED:

  htslib                                    1.14-h9093b5e_0 --> 1.9-h4da6232_3
  ncurses                                    6.3-h7f8727e_2 --> 6.1-he6710b0_1
  pbipa                                    1.5.0-hc9f452f_1 --> 1.1.2-hed695b0_0
  readline                                 8.1.2-h7f8727e_1 --> 7.0-h7b6447c_5
  sqlite                                  3.37.2-hc218d9a_0 --> 3.31.1-h7b6447c_0
```

Thanks for a fix which will work

**Comment by splaisan** [comment]
I followed the fix from [zyllifeworld](https://github.com/zyllifeworld) posted on [https://github.com/bioconda/bioconda-recipes/issues/12100#issuecomment-450289642 ](https://github.com/bioconda/bioconda-recipes/issues/12100#issuecomment-450289642) and now `ipa validate` does not return an error.
My run is however still assembling and after 3 days so I do not dare to stop it. 
I will try running ipa again with the aliased lib after this run finishes.
I wonder why we cannot upgrade samtools to version 11 without downgrading IPA to 1.3, seems weird to have to step back here.

**Comment by ardy20** [comment]
Hello

I suggest you to use HiFiasm and totally free yourself. It gives much better N50 and Busco etc.

https://github.com/chhylp123/hifiasm

**Comment by splaisan** [comment]
reinstalled after reordering the conda repos and it installed samtools 1.15

**Comment by isovic** [comment]
Hi @splaisan,

Thank you for investigating this and reporting the solutions!
I documented this in the new Troubleshooting section here:
https://github.com/PacificBiosciences/pbipa/blob/master/README.md

Best regards,
Ivan.
