### ISSUE TITLE
Illegal instruction while running pbmm2 on hifi isoseq reads

### ISSUE THREAD

**Issue by unique379r** [PacificBiosciences/pbbioconda#471]
Hi
I am running pbmm2 for hifi data but strange thing is that for some samples its done without any error but for some it says **"Illegal instruction"** and i am not able to run it. Please help.

**For CCS reads:**
`pbmm2 align $genome sample.CCS.bam sample.pbmm2_align.sort.bam -j 4 --preset CCS --sort `

**For HQ reads (isoseq3 output):**
` pbmm2 align $genome sample.fastq.gz sample.pbmm2_align.sort.bam -j 4 --preset ISOSEQ --sort --rg "@RG\tID:PCD_NISTRM\tSM:sample"`

-->> Any idea? who to resolve this issue ? 
-->> Also while using fastq reads, i am getting warning message too : **"WARN -|- CheckPositionalArgs -|- 0x2b1e8e267360|| -|- Input is FASTQ. Output BAM file cannot be used for polishing with GenomicConsensus!"** 

Can you please explain this too.

-best
Rupesh Kesharwani

**Comment by armintoepfer** [comment]
`Illegal instruction` -> your CPU does not support SSE4.1

You can ignore the warning, it only tells you that you can't do polishing using GenomicConsensus.

**Comment by unique379r** [comment]
Thank you i really dont know what SSE4.1 is but hows that possible for some samples i have the results (both for CCs reads and for isoseq3 reads) but for some No !? Any comment on this ?

**Comment by armintoepfer** [comment]
On the same machine?

**Comment by unique379r** [comment]
of-course  but i guess i get it now why some random samples are failing because "when we submit the job to cluster, system randomly assign nodes / machine when some nodes might not have the SSE4.1 thing.", its just a guess, i might be wrong.
