### ISSUE TITLE
Very Low value in ZMWs pass filters When Using ccs Comand

### ISSUE THREAD

**Issue by xbx-xbx-1208** [PacificBiosciences/pbbioconda#473]
**Operating system**
Which operating system and version are you using?
system: CentOS 
version: Linux 7 (Core)

**Package name**
Which package / tool is causing the problem?  -- pbccs/ccs
Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? --ccs 6.3.0 (commit v6.3.0)
Have you updated the complete env by running `conda update --all`?  Yes
Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels? Yes

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**
After I used command "ccs" in pbccs to generate hifireads from **.subreads.bam, I found very low value at "ZMWs pass filters", only 0.503%. My "ZMWs input" is 6045691.

**Error message**
Paste the error message / stack.
This is from my log file.
ZMWs input               : 6045691         

ZMWs pass filters        : 30418 (0.503%)
ZMWs fail filters        : 6015273 (99.50%)
ZMWs shortcut filters    : 0 (0.000%)

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!
My command: ccs m64064_201022_084349.subreads.bam ppe.ccs.fastq.gz --report-file ccs_report.txt
I just want to get some help on the adjustment for the parameters to get much higher value for passing-filter data, if it is possible.

**Expected behavior**
I hope I can get some advise on if the low value I described above is normal; if not, how can I correct it !
Thank you.

**Comment by zeeev** [comment]
Can you provide the repot log, which shows the reasons reads fail?

**Comment by xbx-xbx-1208** [comment]
Thank you for your kind reply! In fact, I may describe my question not so clear. The command ccs seems ran normally but got somewhat weird results. So I am sorry but I can't truly understand how to find where shows the reasons reads fail...
I got two reports in total, one is in .txt format, while another in .json.gz format. Each ZMW in the latter fail have the status "status": "TOO_FEW_PASSES" .For the json.gz file was so big that I will only show the first 1000 lines here with name zmw_metrics.1000.txt. Here are they.
[ccs_ppe.txt](https://github.com/PacificBiosciences/pbbioconda/files/8084888/ccs_ppe.txt)
[zmw_metrics.1000.txt](https://github.com/PacificBiosciences/pbbioconda/files/8084971/zmw_metrics.1000.txt)
Waiting for your nice answer!

**Comment by armintoepfer** [comment]
```
Lacking full passes      : 5923399 (98.47%)
```

There are not enough passes. What is the insert size and movie time?

**Comment by xbx-xbx-1208** [comment]
> ```
> Lacking full passes      : 5923399 (98.47%)
> ```
> 
> There are not [enough passes](https://ccs.how/faq/reports-aux-files.html#how-do-i-read-the-ccs_reporttxt-file). What is the insert size and movie time?

Sorry... But I can't find my insert size from my bam file or report file... I wonder how can I find this information if you have some options, thank you.

**Comment by xbx-xbx-1208** [comment]
> ```
> Lacking full passes      : 5923399 (98.47%)
> ```
> 
> There are not [enough passes](https://ccs.how/faq/reports-aux-files.html#how-do-i-read-the-ccs_reporttxt-file). What is the insert size and movie time?

I have got my avg_length via Seqkit, which is 20,530; and my max_length is 290,571. Whether should I adjust parameters to get better values or not?

**Comment by armintoepfer** [comment]
There's nothing you can do via parametrization. Please reach out to your local PacBio field application specialist or PacBio tech support to troubleshoot the sequencing run.
