### ISSUE TITLE
pbmm2 align sort

### ISSUE THREAD

**Issue by fengli-eGen** [PacificBiosciences/pbbioconda#474]
**Operating system**
AWS

**Package name**
I have issues for running pbmm2 align. It was installed using conda.

**Describe the bug**
Temp alignment files seemed gone before sorting started

**Error message**
>|> 20220216 19:55:41.265 -|- INFO -|- AlignSettings -|- 0x7fec49357740|| -|- Using 56 threads for alignments, 8 threads for sorting, and 24G bytes RAM for sorting.
>|> 20220216 19:55:41.265 -|- INFO -|- CheckPositionalArgs -|- 0x7fec49357740|| -|- READ input file: /scratch/data/raw_reads/wt/2_B01/m54328U_211124_054213.subreads.bam
>|> 20220216 19:55:41.265 -|- INFO -|- CheckPositionalArgs -|- 0x7fec49357740|| -|- REF  input file: /scratch/data/reference/index/pbmm2/ref.mmi
>|> 20220216 19:55:41.266 -|- INFO -|- CheckPositionalArgs -|- 0x7fec49357740|| -|- Reference input is an index file. Index parameter override options are disabled!
>|> 20220216 19:55:41.266 -|- INFO -|- Index -|- 0x7fec49357740|| -|- Start reading/building index
>|> 20220216 19:55:59.282 -|- INFO -|- Index -|- 0x7fec49357740|| -|- Finished reading/building index
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Minimap2 parameters based on preset: SUBREAD
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Kmer size              : 19
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Minimizer window size  : 10
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Homopolymer compressed : true
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Gap open 1             : 5
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Gap open 2             : 56
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Gap extension 1        : 4
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Gap extension 2        : 1
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Match score            : 2
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Mismatch penalty       : 5
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Z-drop                 : 400
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Z-drop inv             : 50
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Bandwidth              : 2000
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Max gap                : 5000
>|> 20220216 19:56:02.612 -|- DEBUG -|- PostInit -|- 0x7fec49357740|| -|- Long join flank ratio  : 0.5
>|> 20220216 19:56:03.863 -|- DEBUG -|- CreateTmpFile -|- 0x7febc6ec1700|| -|- Trying pipe /tmp/fileTAIvGB
>|> 20220216 19:56:03.870 -|- DEBUG -|- operator() -|- 0x7feb94ffc700|| -|- [TMPDIR] Could not find environment variable, using working directory: /scratch/data/raw_reads/wt/align_ref
>|> 20220216 19:56:08.744 -|- DEBUG -|- operator() -|- 0x7febc6ec1700|| -|- #Reads, #Aln, #RPM: 3074, 3200, 30740
>|> 20220216 19:56:14.808 -|- DEBUG -|- operator() -|- 0x7febc06b4700|| -|- #Reads, #Aln, #RPM: 12965, 14300, 64825
>|> 20220216 19:56:20.848 -|- DEBUG -|- operator() -|- 0x7febb1e97700|| -|- #Reads, #Aln, #RPM: 22660, 25000, 75533
>|> 20220216 19:56:26.881 -|- DEBUG -|- operator() -|- 0x7febc4ebd700|| -|- #Reads, #Aln, #RPM: 32653, 36100, 81633
.... a bunch of lines as above
In the end of the log file, it says
>|> 20220216 23:57:50.824 -|- DEBUG -|- operator() -|- 0x7febaee91700|| -|- #Reads, #Aln, #RPM: 16656040, 18924400, 68884
>|> 20220216 23:57:50.854 -|- DEBUG -|- Runner -|- 0x7fec49357740|| -|- Alignment finished, merging sorted chunks using 64 threads.
**samtools sort: failed to create "/scratch/data/raw_reads/wt/2_B01/QC_HiFi/align_ref/wt_2B01_ref.bam": No such file or directory
terminate called after throwing an instance of 'PacBio::Utility::AlarmException'
Aborted (core dumped)**

**To Reproduce**
pbmm2 align ref.mmi <movie>.subreads.bam aligned.bam --log-file $PWD/pbmm2.log --log-level DEBUG --sort -m 3G

**Expected behavior**
I have observed the temp files generated but when I checked the result folder after the program completes, nothing was left but my log file. I'm wonder why the bam file was deleted before it tried to sort.

Thanks!

**Comment by armintoepfer** [comment]
Looks like your `TMPDIR` environment variable is set to a non-existing path. Please unset it or set it to an existing path.
