### ISSUE TITLE
ccs hifi-kinetics documentation - missing information

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#481]
Hi,
For ccs 6.3.0, the documentation for hifi-kinetics tags is missing information required for using the data.

After doing ccs --hifi-kinetics, BEFORE pbmm2 alignment, what is the orientation of the rp and ri tags? Is the order of values listed relative to the forward or reverse direction of the sequence in the BAM SEQ column (column 10 of BAM file)?

For example, if SEQ column = ACTGT and rp = 11,15,12,8,20:
  => Does the number 11 in the rp tag refer to the 'A' at position 1, or to 'T' at position 5?
  => Same question for the ri tag

Regarding fp and fi tags, I am assuming they correspond to the direction of SEQ per the documentation: "Forward is defined with respect to the orientation represented in SEQ and is considered to be the native orientation." But the documentation does not specify the rp and ri direction.

Another way to state this question: Does the first value of the fp/fi tag arrays correspond to the same base as the first or the last value of the rp/ri tag arrays?

Thanks.

**Comment by armintoepfer** [comment]
You will find that in our PacBio BAM spec https://pacbiofileformats.readthedocs.io/en/11.0/BAM.html#use-of-read-tags-for-hifi-per-read-base-kinetic-information
