### ISSUE TITLE
lima and ccs - Missing documentation on --ignore-missing-adapters and ma/ac tags

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#482]
Hi,
There is some missing documentation for lima and ccs required for demultiplexing:

1) The exact function of --ignore-missing-adapters is not documented anywhere.
https://lima.how/faq/hifi-presets
 - What does this do? Does it use ma and/or ac tags from ccs? If so which tag(s) does it use? And what cutoff threshold exactly does it use?

2) How is the ma tag calculated by ccs?
https://ccs.how/faq/missing-adapters.html

Thanks

**Comment by armintoepfer** [comment]
Please go through PacBio tech support, who will channel and coordinate.
