### ISSUE TITLE
lima 2.5.0 - "Fixes to support stranded HiFi BAM input"

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#483]
Hello,
This was mentioned in the lima 2.5.0 changelog, but not explained:
"Fixes to support stranded HiFi BAM input"

What exactly was changed?

Previously I was using lima <= 2.4.0 with ccs --by-strand and it seemed to work.

**Comment by armintoepfer** [comment]
Please go through PacBio tech support, who will channel and coordinate.
