### ISSUE TITLE
lima - report ZMW count incorrect

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#484]
Hi,
I ran ccs 6.2.0 --by-strand with chunks, then pbmerge, and then lima 2.4.0.

Issue: The ZMW counts in the lima report are not correct.

I manually counted the number of ZMWs in the ccs BAM input to lima, using this code = 3921534 ZMWs
pbindexdump --format cpp ccs.bam.pbi | grep holeNumber | tr ',' '\n' | sed 's/.*{//;s/}.*//' | uniq | wc -l

But the lima report shows this:
ZMWs input                (A) : 7654444
ZMWs above all thresholds (B) : 7441355 (97.22%)
ZMWs below any threshold  (C) : 213089 (2.78%)

ZMW marginals for (C):
Below min length              : 1138 (0.53%)
Below min score               : 153198 (71.89%)
Below min end score           : 18146 (8.52%)
Below min passes              : 0 (0.00%)
Below min score lead          : 164 (0.08%)
Below min ref span            : 147951 (69.43%)
Without SMRTbell adapter      : 0 (0.00%)
Undesired diff pairs          : 203 (0.10%)

ZMWs for (B):
With same pair                : 7441355 (100.00%)
Coefficient of correlation    : 8.60%

ZMWs for (A):
Allow diff pair               : 7654444 (100.00%)
Allow same pair               : 7654444 (100.00%)

Reads for (B):
Above length                  : 7441468 (100.00%)
Below length                  : 0 (0.00%)

Does the lima report count ZMWs, or strands?

**Comment by armintoepfer** [comment]
You are likely using by strand in ccs and lima processes each strand as an individual ZMW.
