### ISSUE TITLE
Unrecognized pbaa executable

### ISSUE THREAD

**Issue by malonge** [PacificBiosciences/pbbioconda#488]
**Operating system**
MacOS Monterey M1 Max and Ubuntu 16.04.7 LTS

**Package name**
pbaa - latest version

**Conda environment**
```
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
libcxx                    13.0.1               hc203e6f_0    conda-forge
libffi                    3.2.1                         1    bioconda
libzlib                   1.2.11            h6c3fc93_1014    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
openssl                   1.1.1n               h6c3fc93_0    conda-forge
pbaa                      1.0.3                hdfd78af_0    bioconda
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
python                    2.7.15          h8e446fc_1011_cpython    conda-forge
python_abi                2.7                     1_cp27m    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sqlite                    3.37.1               hb516253_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h6c3fc93_1014    conda-forge
```

**Describe the bug**
After installation, the executable is not recognized. Changing OS or python version does not seem to resolve it.

**Error message**
`zsh: exec format error: pbaa`

**To Reproduce**
```
conda create -n pbaaenv
conda activate pbaaenv
conda install pbaa 
pbaa 
```

**Expected behavior**
I expect to see a help message or some other indication that the executable is properly installed.

**Comment by zeeev** [comment]
Hi @malonge,

That's odd, what happens if you grab the same binary from GitHub? Let's see if I can reproduce. 

https://github.com/PacificBiosciences/pbAA/releases/tag/1.0.3

**Comment by zeeev** [comment]
Was not able to reproduce via bioconda.

**Comment by malonge** [comment]
Thanks! I downloaded the binary and I get the same error, so you are right that it is not conda related. I will see if I can figure out what's happening but is there a better pace (issue tracker) to proceed if I continue to have problems?

**Comment by zeeev** [comment]
I reopened the issue, here is a fine place to communicate :-).

**Comment by zeeev** [comment]
`conda create -p ./test -c bioconda -c conda-forge pbaa`



`XXXX in vm-XXXX in ~/scratch/test_pbaa took 1m55s
❯ conda activate /home/UNIXHOME/XXXX/scratch/test_pbaa/test

XXXX in vm-login7-02 in ~/scratch/test_pbaa via   test
❯ pbaa --version
pbaa 1.0.3 (commit SL-release-10.1.0-31-gbef95c5)

wrowell in vm-login7-02 in ~/scratch/test_pbaa via   test
❯ pbaa --help
pbaa - PacBio HiFi Amplicon Analysis.

Usage:
  pbaa <tool>

  -h,--help    Show this help and exit.
  --version    Show application version and exit.

Tools:
  cluster    Run clustering tool.
  bampaint   Add color tags to BAM records, based on pbaa clusters.

Copyright (C) 2004-2021     Pacific Biosciences of California, Inc.
This program comes with ABSOLUTELY NO WARRANTY; it is intended for
Research Use Only and not for use in diagnostic procedures.`

**Comment by malonge** [comment]
Thanks for your help! I am running out the door but I'll quickly add that I downloaded the binary to my 2017 Mac and I got a similar error when trying to runt he exectuable:

`-bash: ./pbaa: cannot execute binary file`

**Comment by williamrowell** [comment]
Hi @malonge, I don't believe that we create arm binaries at the moment.  Have you set up a "rosetta" environment for running x86_64 binaries on your M1? There are some basic instructions [here](https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/).  Please let us know if this works, or if you find a better tutorial for setting up a rosetta terminal.

**Comment by malonge** [comment]
Thanks! I thought that I had set that up already but when I download the executable to a centOS machine it now works just fine. I'll have to look into why my environment is not working on my Mac but Linux will work just fine for me. Thanks for your help!

**Comment by zeeev** [comment]
Always happy to help. Glad you got it running in a linux environment. Let us know how the analyses go :-).
