### ISSUE TITLE
BAI index generated failed by pbmm2

### ISSUE THREAD

**Issue by maxineliu** [PacificBiosciences/pbbioconda#490]
**Operating system**
GNU/Linux on cluster

**Package name**
pbmm2 --version 1.3.0

**Conda environment**
Conda is forbidden on the cluster I use. I have to package pbmm2 in a singularity image. That's why I use pbmm2 -1.3.0.

**Describe the bug**
BAI index generated failed.

**Error message**
>|> 20220408 21:07:39.037 -|- INFO -|- Close -|- 0x2b2e7163dec0|| -|- Generating BAI
>|> 20220408 21:12:00.360 -|- FATAL -|- Close -|- 0x2b2e7163dec0|| -|- pbmm2 align ERROR: BAI Index Generation: Failed to create index for ref.subreads.bam

**To Reproduce**
The command I use is:
`pbmm2 align ref_genome.mmi input.subreads.bam ref.subreads.bam --sample xxxx --median-filter --log-level INFO --sort -j 31 -J 6`

**Expected behavior**
Because the next step I'm going to use the sorted aligned bam file to detect SVs using pbsv, is the BAI index necessary? It seems like pbsv doesn't need BAI file. Or Can I generate BAI index file after this point?

**Comment by armintoepfer** [comment]
You can generate BAI on your own if use pbsv with the --region option. Otherwise, no need to generate it.

**Comment by maxineliu** [comment]
> You can generate BAI on your own if use pbsv with the --region option. Otherwise, no need to generate it.

Thank you for your help!
