### ISSUE TITLE
Can pbbioconda provide an arm pre-compiling version ？

### ISSUE THREAD

**Issue by shengxinzhuan** [PacificBiosciences/pbbioconda#491]
Hello，pbbioconda developer！
I’m working on an arm v8.2  HPC system. I was successful transplants the hifiasm on the arm HPC system. But now I wanne to refilter the ccs data. But I found that ccs do not provide source code or an pre-compiling version on arm. Can it provide an pre-compiling version on arm?

**Comment by armintoepfer** [comment]
Hi! We are currently not offering ARM binaries, as the demand isn't there yet. We are revisiting what systems to support on a regular basis.

If you want to filter existing ccs BAM files, please use samtools in combination with grep. What exactly  are you trying to achieve?
