### ISSUE TITLE
ccs 6.4.0 reproducibility with 6.3.0 and 6.2.0

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#493]
Hi,
I have a complex pipeline developed with ccs 6.2.0.

I have refrained from upgrading to the latest version of ccs due to concern that consensus sequence and quality scores won't be exactly reproducible, specifically for "--by-strand ccs"

 => Question: Is ccs 6.4.0 --by-strand producing the same exact 1) consensus sequences 2) base quality scores, 3) rq scores as ccs 6.2.0 ?
   Assume this run command: ccs --by-strand --min-rq 0.99 --top-passes 0

Thanks.

**Comment by armintoepfer** [comment]
They might differ slightly as we are constantly swapping internal algorithms and their implementations to enable future speedups.

**Comment by gevro** [comment]
Ok thanks.
