### ISSUE TITLE
Primrose by-strand

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#495]
Hi,
Some questions about the new primrose tool:
1) Does it work on CCS by-strand data?
2) Is there a way to extend this tool to other base modifications?
3) How does this perform differently from https://www.pnas.org/doi/10.1073/pnas.2019768118 ?

Thanks

**Comment by armintoepfer** [comment]
It's been trained with double-strand kinetics, relying on HiFi kinetics tags fi, fp, ri, rn from both strands. We have not tested single-stranded reads, treat it as undefined behavior, no guarantees.

Yes, it can be extended by us in future releases.

It's a similar model, yet different. Can't tell you more about implementation details than what is already provided in the documentation.

**Comment by gevro** [comment]
Thanks. I think would be very interesting to extend to single strand analysis in the future, given that methylation is a single strand modification.

**Comment by sjin09** [comment]
Hello, I wanted to catch up on this issue.

I expected primrose to work on single-strand consensus sequence based on PW and IP tag, but to my surprise, primrose reports the error `primrose ERROR: Missing HiFi kinetics` and doesn't generate MM and ML tag. Single-strand methylation calling is a biologically important process to investigate and I was wondering whether primrose could be updated to reflect this.
