### ISSUE TITLE
FATAL error for "isoseq3 collapse"

### ISSUE THREAD

**Issue by CeciliaDeng** [PacificBiosciences/pbbioconda#498]
**Operating system**
Operating system: CentOS Linux 7

**Package name**
isoseq3 3.5.0 (commit SL-release-10.2.0)

**Conda environment**
miniconda3_4.10.3

**Describe the bug**
Input data: HighQualityIsoforms.fasta provided by the Sequencing Service Provider (SSP)

`isoseq3 collapse $alignSrtBam $gff` failed with FATAL error

**Error message**
>|> 20220503 08:21:07.815 -|- FATAL -|- operator() -|- 0x2b883fc2d580|| -|- Read G_01_HQ_transcript/224147 does not have Tag im
>|> 20220503 08:21:07.815 -|- FATAL -|- Run -|- 0x2b883fc2d580|| -|- isoseq collapse ERROR: std::exception

**To Reproduce**
Step 1: Finished ok
`pbmm2 index $genome $idx`

Step 2: Aligned completed ok. Bam and Bai files were created
`pbmm2 align $idx HighQualityIsoforms.fa $algnSrtBam -j $thread --preset ISOSEQ --sort --log-level INFO`

Step 3: Failed with FATAL error described above. I suspect Tag was not available in the dataset supplied by the SSP.
`isoseq3 collapse $alignSrtBam $gff`

**Expected behavior**
Generate a bunch of ***.collapsed.*** files, including collapsed.report.json, collapsed.abundance.txt, collapsed.read_stat.txt, collapsed.group.txt, collapsed.gff and collapsed.fasta

**Comment by jmattick** [comment]
Hi @CeciliaDeng and @amdreamer,

The `im` tag is introduced during the `isoseq3 cluster` step of the bulk workflow or the `isoseq3 groupdedup/dedup` step of the single cell workflow. We have example workflows here:
https://isoseq.how/getting-started.html

We also recently updated `isoseq3` to `v3.8.0`. This version should allow datasets without the `im` tag to run through `collapse`, however running `collapse` without the `cluster` or `groupdedup` step is currently untested. 

-Jessica

**Comment by Ollipolli1909** [comment]
Hi, same here, with version 4.0.0 - after running cluster on service provider supplied hifi reads. All outputs empty

>|> 20230823 05:56:18.093 -|- WARN -|- BamRecordIsGood -|- 0x7f42fa455d40|| -|- Read transcript/563 does not have tag im or is. Reads without im or is will be assumed to be a single molecule.

**Comment by Logan-Wallace** [comment]
I observed a similar behavior when working with a bam file from a sequencing core aligned using Sentieon Minimap2. After going back to the unaligned bam and using pbmm2 to align I had success. Best of luck!

**Comment by bhaggal** [comment]
>|> 20251023 10:59:44.560 -|- WARN -|- BamRecordIsGood -|- 0x71b4aad70280|| -|- Read m84230_241218_133621_s4/19138640/ccs/1024_2633 does not have tag im or is. Reads without im or is will be assumed to be a single molecule.


Hi there,
Has this been resolved?

steps followed till here :
1. removal of polyA
2. aligned using pbmm2, and [reference from PacBio](https://downloads.pacbcloud.com/public/dataset/MAS-Seq/REF-pigeon_ref_sets/Mouse_mm39_Gencode_vM28/)
3. isoseq collapse produces this error.

Please reply, if someone was able to fix this.

Many thanks
