### ISSUE TITLE
hifi-kinetics ipd/pw variance and distribution

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#499]
Hi,
Based on a paper by PacBio (https://genome.cshlp.org/content/23/1/129.full) the distribution of ipd and pw has occasional abnormally long pauses. Therefore, a simple average (I think this is what ccs does) of ipd/pw may not be as informative as other measures, such as variance and median, or excluding these outlier pauses.

"The process of a DNA polymerase enzyme sampling nucleotides during active synthesis to identify the appropriate base for incorporation has previously been shown to be a Poisson process, so that the waiting time between incorporation events (the IPDs) is exponentially distributed. There is a highly significant quadratic relationship between the IPD mean and variance that supports the IPDs as exponentially distributed random variables (Supplemental Fig. 1). However, direct observation of the P-value distribution in the control data of the 5-mC set under the null hypothesis that the IPDs are exponentially distributed, gave rise to a strong anticonservative distribution (Supplemental Fig. 2A), whereas a uniform P-value distribution was expected. We have previously noted that during the synthesis process, the DNA polymerase enzyme may pause at times for abnormally long intervals ([Flusberg et al. 2010](https://genome.cshlp.org/content/23/1/129.full#ref-10)). We suspected that the nonuniform P-value distribution could be driven by such events. Therefore, we set an IPD threshold to treat very long IPD values as missing data (given that the translocation kinetics in these cases are obscured by enzyme-pausing issues), which was effective in producing a uniform P-value distribution under the null hypothesis of no kinetic rate variation (Supplemental Fig. 2B)."

Does ccs exclude outliers from the reported ccs ipd and pw values, or do anything more sophisticated due to the above? Or is there any other facile way to get information about the variance in ipd/pw for any given base in any given ccs read, instead of just the reported average ipd/pw?

Thanks.

**Comment by armintoepfer** [comment]
HiFi kinetics are weighted according to their statistical contributions of the incorporated nucleotide. It's not a simple mean.

**Comment by gevro** [comment]
Can you document how it is calculated exactly? Important for users to know for downstream analyses.

Also, is it normalized in any way for sequence context?

Thanks.

**Comment by armintoepfer** [comment]
It is sequence-context agnostic. I can't say more than I've already provided.
