### ISSUE TITLE
Isoseq3 lima to remove primers of Clontech library

### ISSUE THREAD

**Issue by wyzhangMPI** [PacificBiosciences/pbbioconda#50]
Hi everyone,
     Did someone try to use the lima to remove the primers for the sequencing data based on the Clontech library? This is one issue because the 5'primer and 3'primer are very similar (reverse complemented, and only 6 more bases for 5primer):
         >primer_5p
       AAGCAGTGGTATCAACGCAGAGTACATGGGG
       >primer_3p
       GTACTCTGCGTTGATACCACTGCT

The result for the orientation is not good, as a high percentage (42%) of CCS reads are either 5p--5p or 3p--3p, possibly because the program cannot well distinguish 5'primer and 3'primer. Does anyone know how to fix this issue? Thanks!

ZMWs input                (A) : 600131
ZMWs above all thresholds (B) : 349504 (58%)
ZMWs below any threshold  (C) : 250627 (42%)

ZMW marginals for (C):
Below min length              : 468 (0%)
Below min score               : 0 (0%)
Below min end score           : 44890 (18%)
Below min passes              : 205 (0%)
Below min score lead          : 0 (0%)
Below min ref span            : 37100 (15%)
Without adapter               : 205 (0%)
Undesired 5p--5p pairs        : 58600 (23%)
Undesired 3p--3p pairs        : 174946 (70%)
Undesired no hit              : 205 (0%)

ZMWs for (B):
With different barcodes       : 349504 (100%)
Coefficient of correlation    : 0%

ZMWs for (A):
Allow diff barcode pair       : 599926 (100%)
Allow same barcode pair       : 599926 (100%)

Reads for (B):
Above length                  : 349504 (100%)
Below length                  : 0 (0%)

**Comment by armintoepfer** [comment]
Good libraries get >75% passing ZMWs. This looks like a sample prep problem, unless you show that a majority of the not passing ZMWs are mislabeled.

**Comment by wyzhangMPI** [comment]
After checking the "real-world" example data, I also realized that the problem could come from our sample prep, as around 81% of passing ZMWs found for the example data.
Thanks for the explanation.
 
From: Armin Töpfer
Date: 2018-11-18 20:02
To: PacificBiosciences/pbbioconda
CC: wyzhangMPI; Author
Subject: Re: [PacificBiosciences/pbbioconda] Isoseq3 lima to remove primers of Clontech library (#50)
Good libraries get >75% passing ZMWs. This looks like a sample prep problem, unless you show that a majority of the not passing ZMWs are mislabeled.
