### ISSUE TITLE
pbmm2 (pbsv) on hifi fastq data (no bam available)

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/pbbioconda#500]
Hi,
I downloaded hifi reads from SRA (SRR18210286) and do not have the matched movie.bam file.
Can I apply pbsv to HiFi fastq only? How?
Thanks
S

**Comment by armintoepfer** [comment]
Align using pbmm2 and then run pbsv. Should work, if I recall correctly.

**Comment by splaisan** [comment]
my mistake, I took the bam argument as an input while it is the output, running now. I post back when the command had succeeded but likely OK
Thanks
