### ISSUE TITLE
 Could not find ZMWs for cluster transcript

### ISSUE THREAD

**Issue by jia-wu-feng** [PacificBiosciences/pbbioconda#502]
**Operating system**
Which operating system and version are you using?
Linux

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?
Isoseq3 polish 

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**

**Error message**
Paste the error message / stack.

isoseq3 polish bc1013_clustered.bam ../reads/split.bc1013--bc1013.subreads.bam bc1013.polished.bam
>|> 20220512 16:27:32.399 -|- ERROR -|- operator() -|- 0x7ff13457f700|| -|- Could not find ZMWs for cluster transcript/53
>|> 20220512 16:27:32.419 -|- ERROR -|- operator() -|- 0x7ff137585700|| -|- Could not find ZMWs for cluster transcript/46
>|> 20220512 16:27:32.421 -|- ERROR -|- operator() -|- 0x7ff14edb4700|| -|- Could not find ZMWs for cluster transcript/2
>|> 20220512 16:27:32.465 -|- ERROR -|- operator() -|- 0x7ff1455a1700|| -|- Could not find ZMWs for cluster transcript/19
>|> 20220512 16:27:32.469 -|- ERROR -|- operator() -|- 0x7ff134d80700|| -|- Could not find ZMWs for cluster transcript/52
>|> 20220512 16:27:32.473 -|- ERROR -|- operator() -|- 0x7ff144da0700|| -|- Could not find ZMWs for cluster transcript/20
>|> 20220512 16:27:32.497 -|- ERROR -|- operator() -|- 0x7ff135d82700|| -|- Could not find ZMWs for cluster transcript/50
>|> 20220512 16:27:32.499 -|- ERROR -|- operator() -|- 0x7ff133d7e700|| -|- Could not find ZMWs for cluster transcript/54
>|> 20220512 16:27:32.501 -|- ERROR -|- operator() -|- 0x7ff1465a3700|| -|- Could not find ZMWs for cluster transcript/18

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**

<img width="1819" alt="image" src="https://user-images.githubusercontent.com/24247803/168123912-b87bfef0-2db4-4e1b-888a-c9a7feb6770c.png">

In this step, will the obtained data affect the polishing process?
I got these barcoded subreads directly from the sequencing company.
Could it be that these data labels are not original subreads causing the problem?
A lot of my previous data was successful, here I don't know what caused it, only this step in the file is different from before.

**Comment by armintoepfer** [comment]
Seems like there's not pbi file for your subreads.
