### ISSUE TITLE
missing the 'pw' tag, which is required for Arrow

### ISSUE THREAD

**Issue by tiramisutes** [PacificBiosciences/pbbioconda#503]
Dear,
I get hifi reads using ccs by add `--hifi-kinetics` parameter. But I get error with `missing the 'pw' tag` when `pbmm2 align` and input into `gcpp`.  After reading documents of ccs software, I find the pw tag is change to fp and rp for both strands.
So, how to use the hifi reads to polished with gcpp or arrow?

Thanks.

**Comment by armintoepfer** [comment]
You can't polish using gcpp. HiFi reads are already of sufficient accuracy.
