### ISSUE TITLE
pb-assmebly and pb-falcon have a common error

### ISSUE THREAD

**Issue by ruoyu1123** [PacificBiosciences/pbbioconda#509]
**Operating system**
ubuntu 20.04

**Package name**
pb-assembly

**Conda environment**
a new conda env to install pb=assembly

**Describe the bug**
`[ERROR]Task Node(1-preads_ovl/build) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(1-preads_ovl/build)}
[ERROR]ready: set()
        submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.`

Exception: Some tasks are recently_done but not satisfied: {Node(1-preads_ovl/build)}

**Comment by wzt1417** [comment]
why
