### ISSUE TITLE
tmp_dir change

### ISSUE THREAD

**Issue by ardy20** [PacificBiosciences/pbbioconda#510]
Could you please guide how to change the default tmp_dir?

For example, I need to change it to a folder that I have created myself: /scratch/project/qaafi-cnafs/ipa2/etc/tmp

Because the default one goes to: tmpdir=/nvme/pbs/tmpdir/ which is limited and my IPA assembly fails due to limited space in this area.

**Comment by isovic** [comment]
Hi @ardy20 ,

You can specify a custom tmpdir as a parameter to the `ipa` executable.
Please run `ipa local` or `ipa dist` to see a set of possible options. Among others, there's:
```
  --tmp-dir TMP_DIR     Temporary directory for some disk based operations like sorting. (default: /tmp)
```

Hope this helps,
Best regards,
Ivan.

**Comment by isovic** [comment]
I would suggest specifying `--tmp-dir "./"`.

Best regards,
Ivan.

**Comment by ardy20** [comment]
Hello Ivan

I added both --tmp-dir "./" and also --tmp-dir ${PWD} but unfortunately it did not help. My script is as follows:

ipa local --nthreads 24 --njobs 1 -i T1Caustralis_A_1.ccs.bam -i T1Caustralis_A_2.ccs.bam --tmp-dir "./"  

AND

ipa local --nthreads 24 --njobs 2 -i T1Caustralis_A_1.ccs.bam -i T1Caustralis_A_2.ccs.bam --tmp-dir ${PWD}

The ERROR:

  file: chunk.2044.m4
  reason: Too many open files
18102.15user 594.73system 5:11:38elapsed 99%CPU (0avgtext+0avgdata 1225856maxresident)k
0inputs+8outputs (0major+6483171minor)pagefaults 0swaps
[Thu Jun 16 05:54:13 2022]
Error in rule phasing_prepare:
    jobid: 15
    output: 06-phasing_prepare/shards, 06-phasing_prepare/shards/pwd.txt
    shell:

        sharddir=$(dirname 06-phasing_prepare/shards/pwd.txt)
        rm -rf $sharddir
        mkdir -p $sharddir
        cd $sharddir
        rel=../..

        input_m4="$rel/05-ovl_asym_merge/ovl.nonlocal.m4"         output_shard_ids=./all_shard_ids         output_pwd=./pwd.txt         params_config_sh_fn="$rel/01-generate_config/generated.config"         params_max_nchunks="40"         params_log_level="INFO"         params_tmp_dir="/scratch/project/qaafi-cnafs/ipa3"             time ipa2-task phasing_prepare

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job phasing_prepare since they might be corrupted:
06-phasing_prepare/shards
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-06-14T123041.151111.snakemake.log
ERROR: Command '/scratch/project/qaafi-cnafs/ipa3/bin/python3 -m snakemake -j 2 -d /scratch/project/qaafi-cnafs/ipa3/RUN -p -s /scratch/project/qaafi-cnafs/ipa3/etc/ipa.snakefile --configfile /scratch/project/qaafi-cnafs/ipa3/RUN/config.yaml --reason' returned non-zero exit status 1.
Exiting.
