### ISSUE TITLE
pbmm2 align returns thousands of errors

### ISSUE THREAD

**Issue by elcortegano** [PacificBiosciences/pbbioconda#512]
**Operating system**
A cluster running Linux. `uname -a` returns:

Linux qmaster 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 GNU/Linux

**Package name**

pbmm2 align 1.9.0 (installed from bioconda). Using:

    pbmm2    : 1.9.0 (commit v1.9.0)
    pbbam    : 2.1.0 (commit v2.1.0)
    pbcopper : 2.0.0 (commit v2.0.0-54-g1ce9870)
    boost    : 1.77
    htslib   : 1.15
    minimap2 : 2.15
    zlib     : 1.2.11

**Conda environment**

`conda list` returns:

```
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
ncurses                   6.3                  h7f8727e_2  
pbccs                     6.4.0                h9ee0642_0    bioconda
pbmm2                     1.9.0                h9ee0642_0    bioconda
primrose                  1.3.0                h9ee0642_0    bioconda
samtools                  1.3.1                         0    bioconda
zlib                      1.2.12               h7f8727e_2
```

**Describe the bug**
`pbmm2 align` runs and generates a BAM output file. However it returns thousands of error messages, making it unclear whether that BAM is a valid one or not.

**Error message**
The error message is just "ERROR". Repeated 45908 times.

```
ERROR
ERROR
ERROR
ERROR
...
```

**To Reproduce**
`pbmm2 align` was run with:

    pbmm2 align --num-threads 10 --preset HIFI --sample prefix reference.fa file.ccs_primrose.bam output.bam &> log

The input BAM file used was result of running the `ccs` kinetics (saving kinetics) on a raw subreads file, followed by primrose.

**Expected behavior**

I would expect `pbmm2 align` to end an execution without returning errors, and also resulting in a BAM file of about the same size as reported by other aligners. In my current test, `pbmm2 align` returned a 2GB file, while other aligner returned a 46GB file more in line with our expectations, so I'm worry that the BAM file that returned `pbmm2 align` is truncated.

**Comment by armintoepfer** [comment]
Please provide a minimal example that reproduces your findings. You can find instructions for uploading in the pbbioconda docs. Looking forward to resolving this.

**Comment by elcortegano** [comment]
Thank you for your reply! I just submitted the files, and checked that they reproduce the same error as above. Please let me know if you received the files and if there is anything else I can do.

**Comment by armintoepfer** [comment]
We just had the same internally. Your BAM files are not PacBio BAM spec compliant.

**Comment by elcortegano** [comment]
In case this helps anybody. For me the problem was finally solved when running the `ccs` and `primrose` tools on independent BAM files without merging these at any point (the problem above happened with BAMs coming from different sequencing batches that had been merged).
