### ISSUE TITLE
Assembler for HiFi + HiC data?

### ISSUE THREAD

**Issue by hans-vg** [PacificBiosciences/pbbioconda#514]
Which assembler would you recommend to use for HiFi + HiC data?  I saw a post recommend using IPA rather than Falcon-Phase with HiFi only data.  However, if I have a mixture, should I still use Falcon-Phase?

Thank you.

**Comment by zeeev** [comment]
Hi @hans-vg 

HiFiASM directly integrates Hi-C making it an easy solution. 

https://github.com/chhylp123/hifiasm
