### ISSUE TITLE
Official docker images?

### ISSUE THREAD

**Issue by bbimber** [PacificBiosciences/pbbioconda#516]
Hello - 

are there official docker images for pbmm2/pbsv? I would have expected the standard bioconda ones to work, such as:

docker pull quay.io/biocontainers/pbmm2:<tag>

but i'm getting "manifest unknown" errors when trying to pull that. Any suggestions would be appreciated. I understand there is the option to install via conda, but in some shared environments docker is an easier option.

**Comment by armintoepfer** [comment]
Hi. I have no idea, I'm sorry. We upload static binaries that have no extra dependencies, so they work very well in shared environments.
