### ISSUE TITLE
scIsoSeq best practices?

### ISSUE THREAD

**Issue by acrinklaw** [PacificBiosciences/pbbioconda#519]
So I have another set of scIsoSeq samples that I'm working on, these are 10X 3' chemistry and loaded onto pacbio sequencer. I've worked my way through all of the IsoSeq steps, tried SQANTI on it's own and tried out the new pigeon tool as well and see a high number of isoforms (in the range of 200k+ unique isoforms). Something I haven't seen mentioned in any of the documentation is filtering reads based on "true" cells. Say if I plot the cell barcode ranking and see an inflection point at 10k cells, filtering out isoforms only belonging to the 10k barcodes. Is this something handled explicitly by any of these steps in IsoSeq? In the single cell wiki under the cDNA Cupcake repo it seems like at the BC correction step you're meant to use a whitelist from 10X such as the 3M-february-2018.txt, which I did, but I get a warning that the missing fraction (99%) > threshold of 25%

Here are the steps that I've run. So far no metrics have seemed off except for the final number of isoforms after checking out pigeon report. I'm still quite new to both single cell and long read data in general so apologies if this question is dense :-)

```
lima --isoseq --dump-clips ccs.bam primers.fasta output.bam

isoseq3 tag output.5p--3p.bam output.5p--3p.tagged.bam --design T-12U-16B

isoseq3 refine --require-polya output.5p--3p.tagged.bam primers.fasta output.5p--3p.tagged.refined.bam

# remarks (refine output looks good, fraction of reads filtered, tagging probably correct w/ proper primers)

isoseq3 correct --barcodes 3M-february-2018.txt output.5p--3p.tagged.refined.bam output.5p--3p.tagged.refined.corrected.bam

samtools sort -t CB -O BAM output.5p--3p.tagged.refined.corrected.bam -o output.5p--3p.tagged.refined.corrected.sorted.bam

isoseq3 groupdedup \
   output.5p--3p.tagged.refined.corrected.sorted.bam \
   output.5p--3p.tagged.refined.corrected.sorted.dedup.bam 

pbmm2 align --preset ISOSEQ --sort output.5p--3p.tagged.refined.corrected.sorted.dedup.bam GCF_000001405.39_GRCh38.p13_genomic.fa mapped.bam

isoseq3 collapse mapped.bam collapsed.gff

pigeon sort collapsed.gff -o sorted.gff

pigeon classify sorted.gff GCF_000001405.39_GRCh38.p13_genomic.gtf GCF_000001405.39_GRCh38.p13_genomic.fa --log-level INFO

pigeon filter sorted_classification.txt

pigeon report sorted_classification.filtered_lite_classification.txt saturation.txt

pigeon make-seurat --dedup dedup.fasta --group collapsed.group.txt -d seurat_output
```

my saturation.txt ends up looking like this...
```
reads   unique_genes    unique_transcripts      unique_isoforms
10000   5478    6178    10000
20000   7749    10924   20000
30000   9080    14885   30000
40000   10066   18351   40000
50000   10784   21324   50000
60000   11371   24118   60000
70000   11862   26626   70000
80000   12261   28830   80000
90000   12611   30913   90000
100000  12905   32814   100000
110000  13222   34653   110000
120000  13437   36387   120000
130000  13674   38019   130000
140000  13899   39571   140000
150000  14109   41136   150000
160000  14297   42571   160000
170000  14476   43953   170000
180000  14654   45208   180000
190000  14834   46429   190000
200000  14988   47613   200000
210000  15133   48802   210000
220000  15266   49931   220000
230000  15384   50942   230000
238170  15496   51766   238170
```

**Comment by greensii** [comment]
> it seems like at the BC correction step you're meant to use a whitelist from 10X such as the 3M-february-2018.txt, which I did, but I get a warning that the missing fraction (99%) > threshold of 25%

did you figure this out? i have the same issue. everything looks great up to <isoseq3 correct> where ~60% of my reads get filtered out with an edit distance to a whitelistBC >2. 
from what i can tell, my reads actually contain the actual whitelist cellBC, while <isoseq3 tag> tags the bam entries with the reverse complement of the sequence in the reads.

**Comment by acrinklaw** [comment]
Most of my problems were fixed by using their reference files at [https://downloads.pacbcloud.com/public/dataset/MAS-Seq/](https://downloads.pacbcloud.com/public/dataset/MAS-Seq/).

**Comment by greensii** [comment]
thanks @acrinklaw - the ref files you pointed me to do indeed contain the reverse-complemented 10X barcodes.  i'll see if i can encourage an update to https://isoseq.how/umi/isoseq-correct.html to make this clear!
