### ISSUE TITLE
About the test data

### ISSUE THREAD

**Issue by xiaozhangzaq** [PacificBiosciences/pbbioconda#52]
about the test data:10-fold coverage of the Genome in a Bottle sample HG002
i  call the  vcf  from the given bam is quite different with that vcf you given(https://downloads.pacbcloud.com/public/dataset/HG002/Sequel-201810/GRCh38.HG002_pbsv.vcf)
i use reference genome GCA_000001405.15_GRCh38_no_alt_analysis_set,  do you use the default parameter, or use repeat region with -b. 
Thanks!

**Comment by armintoepfer** [comment]
@amwenger will reply as soon as possible, please stay tuned.

**Comment by amwenger** [comment]
Hi @xiaozhangzaq.  The posted VCF file is from pbsv run through the "Structural Variant Calling" application in SMRT Link 6.0 with default parameters.  SMRT Link 6.0 has `pbsv v2.0.0-6-gc401433`.

SMRT Link does create a tandem repeat file and pass that as `-b` to pbsv.  The BED file it creates is available at https://gist.github.com/amwenger/ae21b1cdf9d24e9dcfb79f95de54319e.

When you say the files are quite different, do you mean that `diff` returns many lines or that the variant calls are very different?

**Comment by xiaozhangzaq** [comment]
i write a script to compare the my vcf(use pbsv2.0.2 and the tr.bed you given) with your vcf(GRCh38.HG002_pbsv.vcf), about 32,000 lines are consistent, 6000 lines are not, variants in my vcf but not in yours , or variants in your vcf but not in mine. I just use the position in vcf (cut -f 1,2, first and second column) to compare.
Thanks

**Comment by amwenger** [comment]
Could you share the specific {{pbsv discover}} and {{pbsv call}} commands you run along with the output VCF?

**Comment by armintoepfer** [comment]
You can reproduce it using SMRT Link UI. The command-line version will give you slightly different results, but not 6000. That has been fixed in the latest version available via bioconda.

**Comment by xiaozhangzaq** [comment]
`pbsv discover -b tr.bed --sample hg002 /home/zhangaq/data/PacBio_HG002/pbsv_test_data/GRCh38.HG002.bam hg002.tr.svsig.gz & pbsv call /home/zhangaq/data/genome/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa hg002.tr.svsig.gz hg002.tr.vcf &`
