### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by kristinalweber** [PacificBiosciences/pbbioconda#524]
(Note: I am a PacBio BFX FAS.)

https://lima.how/get-started.html#example-executions

The correct flag is --hifi-preset not --hifi-prefix. 

For the first example, lima <movie>.hifi_reads.bam barcodes.fasta <movie>.demux.bam --hifi-prefix SYMMETRICS
The correct syntax is --hifi-preset SYMMETRIC not SYMMETRICS

I would also recommend including some of the useful flags in the getting started examples, like --peek-guess, --split-named, and perhaps --store-unbarcoded. 

Thank you!

**Comment by mrvollger** [comment]
Commenting because I also just rediscovered this issue. Thanks in advance.

**Comment by armintoepfer** [comment]
Thank you. Feel free to issue a PR against https://github.com/PacificBiosciences/barcoding/blob/master/docs/get-started.md

**Comment by mrvollger** [comment]
Fixed the typos I had come across in a PR. @kristinalweber can confirm if there are others: https://github.com/PacificBiosciences/barcoding/pull/13
