### ISSUE TITLE
pbsv discover detecting csi incorrectly

### ISSUE THREAD

**Issue by maxineliu** [PacificBiosciences/pbbioconda#525]
**Operating system**
system: CentOS Linux HPC

**Package name**
pbsv 2.8.0

**Conda environment**
I'm not install pbsv via Conda, I use apptainer container of pbsv on cluster. 

**Describe the bug**
When using `--region` flag in `pbsv discover`, pbsv is unable to detect `.csi` index properly. I renamed the XXX.bam.csi to XXX.bam.bai (which I should not have done that), the error disappeared. But there is no error when I run `pbsv dicover` without `--region`, even though the index is in csi format.

**Error message**
```
>|> 20220723 03:14:54.147 -|- FATAL -|- Run -|- 0x2b90551e9b80|| -|- pbsv discover ERROR: Number of index files does not match number of BAM files!
```

**To Reproduce**
```
for i in NC_058080.1 NC_058081.1 NC_058082.1 NC_058083.1 NC_058084.1 NC_058085.1 NC_058086.1 NC_058087.1 NC_058088.1 NC_058089.1 NC_058090.1 NC_008410.1 NW*; do
        pbsv discover --region $i novosort.sample_name.bam \
            novosort.sample_name.$i.svsig.gz \
            --tandem-repeats Trf.bed
done
```
The aligned bam file is very big (1.4T), and the length of chromosome is more than 2^29 bases. I have to store index of bam in csi format.

**Expected behavior**
I guess that the code about detecting the existence and number of csi index is correct in the normal `pbsv discover` chunk, but things changed in `pbsv discover --region`? So I expect that:
1. if renaming csi to bai works, then it is acceptable. 
2. if renaming does not work, will you adapt the code?

Maxine

**Comment by maxineliu** [comment]
if someone experienced a similar situation?

**Comment by armintoepfer** [comment]
I don't think `pbsv` currently supports `csi`.
