### ISSUE TITLE
How can i get the premier.fasta

### ISSUE THREAD

**Issue by Catherine9826** [PacificBiosciences/pbbioconda#527]
**Operating system**
Which operating system and version are you using?

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Describe the bug**

**Error message**
Paste the error message / stack.

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**

**Comment by armintoepfer** [comment]
What are you looking for? premier.fasta?

**Comment by Catherine9826** [comment]
Thanks for your reply. There is a question that has been bothering me. I saw the command as followed， but i didn't find the file “primers.fasta”

. How can i get this file?

 lima --isoseq --dump-clips --no-pbi --peek-guess -j 24 ccs.bam primers.fasta demux.bam







501165128
***@***.***








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PacificBiosciences/pbbioconda"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月2日(星期二) 晚上10:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PacificBiosciences/pbbioconda] How can i get the premier.fasta (Issue #527)





 
What are you looking for? premier.fasta?

**Comment by armintoepfer** [comment]
https://isoseq.how/clustering/cli-workflow.html#step-2---primer-removal-and-demultiplexing
