### ISSUE TITLE
CCS error-- BAM file corrupted

### ISSUE THREAD

**Issue by weinei18** [PacificBiosciences/pbbioconda#528]
Running CCS on Linux and keep getting the error that the BAM file is corrupted/likely truncated, but can't seem to find any issues with it. Installed CCS according to your installation instructions and didn't have any problems there. Directly downloaded the subreads BAM file from the sequencing company and samtools quickcheck suggests it's all there. Any other reason why I'd be getting this error? Any insight would be greatly appreciated!

ERROR MESSAGE:
 | 20220818 20:31:24.249 | FATAL | ccs ERROR: [pbbam] BAM reader ERROR: cannot read from corrupted file:
  file: /home/weinei18/resub-JP-VT-Genome2.r64296e163757F01.subreads.bam
  reason: probably truncated

**Comment by armintoepfer** [comment]
If you run `samtools view -H /home/weinei18/resub-JP-VT-Genome2.r64296e163757F01.subreads.bam` it does indicate a corrupted file?

The file is corrupt or it can't be properly read from your storage. Can you re-download the file?

**Comment by weinei18** [comment]
Hi Armin, thanks for your reply. At least as far as I can tell, running that command does not indicate anything is wrong with file. I can paste the output here if that would be helpful, a second set of eyes couldn't hurt. I have attempted re-downloading the subreads file on multiple occasions... what's interesting is that if I run the command with chunking, the first couple of chunks to run will finish without issue, and then I start getting the above error. However, if I try running without chunking on the newly downloaded version, the same error arises.

**Comment by armintoepfer** [comment]
Either way, the file is corrupt. There's nothing one can do, except for re-downloading.
