### ISSUE TITLE
lima qs, qe, ls tags

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#529]
Hi, lima      : 2.6.0 (commit v2.6.0)

Seems to be outputting undocumented qs, qe, and ls tags. They are absent from ccs, but then created by lima that is run on the CCS bam.

Not documented here: https://lima.how/output/bam.html

**Comment by armintoepfer** [comment]
https://pacbiofileformats.readthedocs.io/en/11.0/BAM.html

**Comment by gevro** [comment]
Thanks, but I'm still unclear. I am doing subreads -> ccs -> lima.

1) I can't find documentation for the 'ls' tag. Maybe I missed it, but I don't see it in the pacbiofileformats page?

2) Subreads have qs/qe/ls, ccs removes these tags, and then lima adds them again. Would be helpful to document these tags for lima here: https://lima.how/output/bam.html, because it is not clear what they mean in terms of lima's function.

**Comment by armintoepfer** [comment]
`qs`/`qe` in ccs reads after demuxing are implementation details.

`ls` is another implementation detail to enable lima-undo https://lima.how/faq/undo#how-does-it-work

We are not always adding every tag to the public docs, if they only serve internal purpose.
