### ISSUE TITLE
missing libpbcopper

### ISSUE THREAD

**Issue by dbtara** [PacificBiosciences/pbbioconda#53]
**Operating system**
Which operating system and version are you using?
CentOS 6.10

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`?
pb-assembly 0.0.2-py27_0 bioconda
**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py27_1003    conda-forge
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  h4da6232_0    bioconda
bedtools                  2.27.1               he941832_2    bioconda
blas                      1.0                         mkl  
blasr                     5.3.2                hac9d22c_3    bioconda
blasr_libcpp              5.3.1                hac9d22c_2    bioconda
bwa                       0.7.17               ha92aebf_3    bioconda
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py27_1000    conda-forge
cffi                      1.11.5           py27h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py27_1003    conda-forge
cryptography              2.3.1            py27hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py27_1000    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
cython                    0.29             py27hfc679d8_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
enum34                    1.1.6                 py27_1001    conda-forge
future                    0.17.0                py27_1000    conda-forge
genomicconsensus          2.3.2                    py27_3    bioconda
h5py                      2.8.0            py27h7eb728f_3    conda-forge
hdf5                      1.10.2               hc401514_2    conda-forge
htslib                    1.7                           0    bioconda
idna                      2.7                   py27_1002    conda-forge
intel-openmp              2019.0                      118  
ipaddress                 1.0.22                     py_1    conda-forge
iso8601                   0.1.12                     py_1    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libdeflate                1.0                  h470a237_0    bioconda
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
linecache2                1.0.0                      py_1    conda-forge
minimap2                  2.14                 ha92aebf_0    bioconda
mkl                       2019.0                      118  
mkl_fft                   1.0.6                    py27_0    conda-forge
mkl_random                1.0.2                    py27_0    conda-forge
mummer4                   4.0.0beta2      pl526hfc679d8_3    bioconda
ncurses                   6.1                  hfc679d8_1    conda-forge
networkx                  2.2                        py_1    conda-forge
nim-falcon                0.0.0                         0    bioconda
numpy                     1.15.0           py27h1b885b7_0  
numpy-base                1.15.0           py27h3dfced4_0  
openssl                   1.0.2p               h470a237_1    conda-forge
pb-assembly               0.0.2                    py27_0    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.4            py27ha92aebf_0    bioconda
pbalign                   0.3.1                    py27_1    bioconda
pbbam                     0.18.0               h1310cd9_1    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcore                    1.6.5                    py27_0    bioconda
perl                      5.26.2               h470a237_0    conda-forge
pip                       18.1                  py27_1000    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py27_1000    conda-forge
pysam                     0.14.1           py27hae42fb6_1    bioconda
pysocks                   1.6.8                 py27_1002    conda-forge
python                    2.7.15               h33da82c_4    conda-forge
python-consensuscore      1.1.1            py27h02d93b8_2    bioconda
python-consensuscore2     3.1.0                    py27_2    bioconda
python-edlib              1.2.3.post1      py27h470a237_0    bioconda
python-intervaltree       2.1.0                      py_0    bioconda
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.0.5                      py_0    bioconda
pytz                      2018.7                     py_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.20.1                py27_1000    conda-forge
samtools                  1.9                  h8ee4bcc_1    bioconda
setuptools                40.6.2                   py27_0    conda-forge
six                       1.11.0                py27_1001    conda-forge
sqlite                    3.25.3               hb1c47c0_0    conda-forge
tk                        8.6.8                ha92aebf_0    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.23                  py27_1001    conda-forge
wheel                     0.32.2                   py27_0    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

**Describe the bug**
I installed pb-assembly using bioconda and was able to run pb-falcon but pb-unzip fails at 4-polish/cns-output step. After investigating further it appears the error actually happened at quiver-run phase where variantCaller failed due to missing libpbcopper.so.4.2, error pasted below.

**Error message**
Paste the error message / stack.
variantCaller --algorithm=arrow -x 5 -X 120 -q 20 -j 24 -r ../../../quiver-split/refs/000000F/ref.fa aln-000000F.bam            -o cns.fasta.gz -o cns.fastq.gz --minConfidence 0 -o cns.vcf
libpbcopper.so.0.4.2: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/scicomp/home/bun3/.local/lib/python2.7/site-packages/pbcommand/cli/core.py", line 138, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/scicomp/home/bun3/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 340, in args_runner
    return tr.main()
  File "/scicomp/home/bun3/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 269, in main
    self._algorithm = self._algorithmByName(options.algorithm, peekFile)
  File "/scicomp/home/bun3/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/main.py", line 57, in _algorithmByName
    from GenomicConsensus.arrow import arrow
  File "/scicomp/home/bun3/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/arrow/__init__.py", line 4, in <module>
    from . import utils
  File "/scicomp/home/bun3/.local/lib/python2.7/site-packages/GenomicConsensus-2.3.2-py2.7.egg/GenomicConsensus/arrow/utils.py", line 11, in <module>
    import ConsensusCore2 as cc
  File "/scicomp/home/bun3/.local/lib/python2.7/site-packages/ConsensusCore2.py", line 17, in <module>
    _ConsensusCore2 = swig_import_helper()
  File "/scicomp/home/bun3/.local/lib/python2.7/site-packages/ConsensusCore2.py", line 16, in swig_import_helper
    return importlib.import_module('_ConsensusCore2')
  File "/scicomp/groups/OID/NCEZID/DSR/BCFB/usr/bin/miniconda2/denovo_asm/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: libpbcopper.so.0.4.2: cannot open shared object file: No such file or directory

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!
This was run on the Exanple Test data greg200k-sv2

**Expected behavior**
I expect the test data to finish running

**Comment by pb-dseifert** [comment]
Your version of CC2 is massively outdated. Have you tried running `conda update --all`? Remember to also update your bioconda channel priorities, as these have changed recently.

**Comment by pb-dseifert** [comment]
just try reinstalling `pb-assembly` and `pb-falcon`, using explicit version specifiers.

**Comment by dbtara** [comment]
ok tried that .. and here is what happens. 

if i try to run it as is. I get the same missing  library.

if i install pbcopper, the varintCaller seg faults.

**Comment by pb-dseifert** [comment]
```
$ ldd miniconda2/lib/python2.7/site-packages/_ConsensusCore2.so
	linux-vdso.so.1 =>  (0x00007ffc6d38d000)
	libpython2.7.so.1.0 => /home/dseifert/miniconda2/lib/python2.7/site-packages/../../libpython2.7.so.1.0 (0x00007f4379b92000)
	libstdc++.so.6 => /home/dseifert/miniconda2/lib/python2.7/site-packages/../../libstdc++.so.6 (0x00007f4379857000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f4379546000)
	libgcc_s.so.1 => /home/dseifert/miniconda2/lib/python2.7/site-packages/../../libgcc_s.so.1 (0x00007f4379334000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4379117000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f4378d56000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4378b52000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f437894e000)
	/lib64/ld-linux-x86-64.so.2 (0x0000559bc6289000)
```
CC2 does not link to pbcopper anymore. But here's a red flag: your normal bioconda installation seems to be in `/scicomp/groups/OID/NCEZID/DSR/BCFB/usr/bin/miniconda2/`, yet you're loading pbcommand from `/scicomp/home/bun3/.local/`. Have you mucked with user-site dir? See my reply in https://github.com/PacificBiosciences/pbbioconda/issues/6#issuecomment-419661454 for a fix.

**Comment by pb-dseifert** [comment]
No feedback, I assume this is fixed with the hint I have in the previous comment.
