### ISSUE TITLE
ccs by-strand ip/pw order

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#532]
Hello,
It is not clear from the documentation, when running ccs --by-strand --hifi-kinetics:

Does ccs output ip and pw in the same orientation as SEQ for both /fwd and /rev ?

i.e. is SEQ for /fwd in the same order as ip and pw for /fwd?
 AND
    SEQ for /rev is in the same order as ip and pw for /rev ?

**Comment by gevro** [comment]
Hi, I am just following up if you all have an answer for this?
Thanks.

**Comment by armintoepfer** [comment]
Tags `ip` and `pw` always in the native orientation of the sequence.
