### ISSUE TITLE
lima 2.6.0  "Support SEGMENT read type". Is there any documentation about is?

### ISSUE THREAD

**Issue by grendon** [PacificBiosciences/pbbioconda#536]
The changelog (https://lima.how/changelog) mentions it.  But I don't find anything else.

**Comment by jmattick** [comment]
Hi @grendon,
Lima now supports s-reads that are output from our new tool [skera](https://skera.how/).
-Jessica

**Comment by zhuyiqin** [comment]
Hi, is there any parameter that is specific to s-reads? I tried the 2.6.99 but it only reports one read for each ZMW. when I add --per-read, it reports each s-read but the location of read name is removed
