### ISSUE TITLE
Free disk space is running out

### ISSUE THREAD

**Issue by Jung19911124** [PacificBiosciences/pbbioconda#537]
I have been trying to assemble a huge genome (6 Tb) using Falcon locally. I started the analysis on a drive with 16 Tb of free space, but the pre-assembly step has already reduced the free space to 1 Tb. 

Pre-assembly will be finished in about two weeks, though, considering the subsequent steps, it would be better to resume the process on a different drive. 

If I interrupt the computation after the pre-assembly, is it possible to move the current directory to another volume and then resume the computation from the pread overlapping step?

Any adovices would be appreciated.
Best,

Jung

**Comment by gconcepcion** [comment]
Hi Jung,
Yes, you can absolutely start from preads on a different disk if that's what you want to do. Once the preads have been generated, you don't need access to the initial overlaps unless you want to run the unzipping module of FALCON, FALCON_unzip

See this link:
https://pb-falcon.readthedocs.io/en/latest/faq.html#can-i-start-from-corrected-reads

**Comment by Jung19911124** [comment]
Hi @gconcepcion, 
Thank you so much for your suggestion. I was so relieved to hear that. 

Thanks again.
