### ISSUE TITLE
Python compatibility update?

### ISSUE THREAD

**Issue by eweinheimer** [PacificBiosciences/pbbioconda#539]
System specs: Ubuntu 18.04 LTS, conda 4.13

I am attempting to build pb-assembly with the command:

```
$ conda install pb-assembly
```

Unable to build with anaconda 4.13, python version 3.9. 
python --version is 2.7.17 in the environment, so I must be doing something else wrong too. Wondering if there are plans to update for python 3.9+
Alternatively, is there a place where I can modify the specifications for python to include 3.9?

Error message: 
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pb-assembly -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - python=3.9 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']

**Comment by armintoepfer** [comment]
We are currently not focusing on improving the existing assembly workflow. Start from a fresh environment only for this package and it will work
