### ISSUE TITLE
Specify default value for the -m (output format) option of BLASR

### ISSUE THREAD

**Issue by Papok** [PacificBiosciences/pbbioconda#54]
Please detail the default value for the -m (output format) option in help, man page, and wiki.
```
-m t   If not printing SAM, modify the output of the alignment.
```
to
```
-m t (1)
       If not printing SAM, modify the output of the alignment.
```

Thanks.

**Comment by armintoepfer** [comment]
Please specify the tool you are using

**Comment by Papok** [comment]
Sorry,
blasr 5.3.2 (bioconda)

**Comment by armintoepfer** [comment]
We are deprecating blasr and won't make any further code changes.
