### ISSUE TITLE
IPA : SNAKEMAKE ERROR (STEP 19)

### ISSUE THREAD

**Issue by sadiqbioinfo** [PacificBiosciences/pbbioconda#540]
**Operating system**
Red Hat Enterprise Linux Server release 6.6 (Santiago)

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version` : ipa (wrapper) version=1.8.0

Have you updated to the latest version `conda update package`? : Yes

Have you updated the complete env by running `conda update --all`? : Yes 

Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels? : Yes

**Conda environment**

        #packages in environment at /apps/miniconda3/envs/ipa:

        Name                    Version                   Build  Channel
        _libgcc_mutex             0.1                 conda_forge    conda-forge
        _openmp_mutex             4.5                       2_gnu    conda-forge
        amply                     0.1.5              pyhd8ed1ab_0    conda-forge
        appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
        attrs                     22.1.0             pyh71513ae_1    conda-forge
        brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
        bzip2                     1.0.8                h7f98852_4    conda-forge
        c-ares                    1.18.1               h7f98852_0    conda-forge
        ca-certificates           2022.9.24            ha878542_0    conda-forge
        certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
        cffi                      1.15.1          py310h255011f_0    conda-forge
        charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
        coin-or-cbc               2.10.8               h3786ebc_0    conda-forge
        coin-or-cgl               0.60.6               h6f57e76_2    conda-forge
        coin-or-clp               1.17.7               hc56784d_2    conda-forge
        coin-or-osi               0.108.7              h2720bb7_2    conda-forge
        coin-or-utils             2.11.6               h202d8b1_2    conda-forge
        coincbc                   2.10.8            0_metapackage    conda-forge
        configargparse            1.5.3              pyhd8ed1ab_0    conda-forge
        connection_pool           0.0.3              pyhd3deb0d_0    conda-forge
        cryptography              38.0.1          py310h597c629_0    conda-forge
        datrie                    0.8.2           py310h6acc77f_3    conda-forge
        docutils                  0.19            py310hff52083_0    conda-forge
        dpath                     2.0.6           py310hff52083_1    conda-forge
        filelock                  3.8.0              pyhd8ed1ab_0    conda-forge
        gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
        gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
        htslib                    1.15.1               h6bc39ce_1    bioconda
        idna                      3.4                pyhd8ed1ab_0    conda-forge
        importlib-metadata        4.11.4          py310hff52083_0    conda-forge
        importlib_resources       5.9.0              pyhd8ed1ab_0    conda-forge
        jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
        jsonschema                4.16.0             pyhd8ed1ab_0    conda-forge
        jupyter_core              4.11.1          py310hff52083_0    conda-forge
        k8                        0.2.5                hd03093a_2    bioconda
        keyutils                  1.6.1                h166bdaf_0    conda-forge
        krb5                      1.19.3               h3790be6_0    conda-forge
        ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
        libblas                   3.9.0           16_linux64_openblas    conda-forge
        libcblas                  3.9.0           16_linux64_openblas    conda-forge
        libcurl                   7.85.0               h7bff187_0    conda-forge
        libdeflate                1.13                 h166bdaf_0    conda-forge
        libedit                   3.1.20191231         he28a2e2_2    conda-forge
        libev                     4.33                 h516909a_1    conda-forge
        libffi                    3.4.2                h7f98852_5    conda-forge
        libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
        libgfortran-ng            12.1.0              h69a702a_16    conda-forge
        libgfortran5              12.1.0              hdcd56e2_16    conda-forge
        libgomp                   12.1.0              h8d9b700_16    conda-forge
        liblapack                 3.9.0           16_linux64_openblas    conda-forge
        liblapacke                3.9.0           16_linux64_openblas    conda-forge
        libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
        libnsl                    2.0.0                h7f98852_0    conda-forge
        libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
        libsqlite                 3.39.4               h753d276_0    conda-forge
        libssh2                   1.10.0               haa6b8db_3    conda-forge
        libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
        libuuid                   2.32.1            h7f98852_1000    conda-forge
        libzlib                   1.2.12               h166bdaf_4    conda-forge
        markupsafe                2.1.1           py310h5764c6d_1    conda-forge
        minimap2                  2.24                 h7132678_1    bioconda
        nbformat                  5.6.1              pyhd8ed1ab_0    conda-forge
        ncurses                   6.3                  h27087fc_1    conda-forge
        networkx                  2.8.7              pyhd8ed1ab_0    conda-forge
        openssl                   1.1.1q               h166bdaf_0    conda-forge
        pb-falconc                1.15.0               h3279499_0    bioconda
        pbipa                     1.8.0                hbd632db_1    bioconda
        pcre                      8.45                 h9c3ff4c_0    conda-forge
        pip                       22.2.2             pyhd8ed1ab_0    conda-forge
        pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
        plac                      1.3.5              pyhd8ed1ab_0    conda-forge
        psutil                    5.9.2           py310h5764c6d_0    conda-forge
        pulp                      2.6.0           py310hff52083_1    conda-forge
        pycparser                 2.21               pyhd8ed1ab_0    conda-forge
        pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
        pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
        pyrsistent                0.18.1          py310h5764c6d_1    conda-forge
        pysocks                   1.7.1              pyha2e5f31_6    conda-forge
        python                    3.10.6          h582c2e5_0_cpython    conda-forge
        python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
        python_abi                3.10                    2_cp310    conda-forge
        pyyaml                    6.0             py310h5764c6d_4    conda-forge
        racon                     1.5.0                h7ff8a90_0    bioconda
        ratelimiter               1.2.0                   py_1002    conda-forge
        readline                  8.1.2                h0f457ee_0    conda-forge
        requests                  2.28.1             pyhd8ed1ab_1    conda-forge
        reretry                   0.11.1             pyhd8ed1ab_0    conda-forge
        samtools                  1.15.1               h1170115_0    bioconda
        setuptools                65.4.1             pyhd8ed1ab_0    conda-forge
        smart_open                6.2.0              pyha770c72_0    conda-forge
        smmap                     3.0.5              pyh44b312d_0    conda-forge
        snakemake-minimal         7.15.1             pyhdfd78af_0    bioconda
        stopit                    1.1.2                      py_0    conda-forge
        tabulate                  0.9.0              pyhd8ed1ab_0    conda-forge
        tk                        8.6.12               h27826a3_0    conda-forge
        toposort                  1.7                pyhd8ed1ab_0    conda-forge
        traitlets                 5.4.0              pyhd8ed1ab_0    conda-forge
        typing_extensions         4.3.0              pyha770c72_0    conda-forge
        tzdata                    2022d                h191b570_0    conda-forge
        urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
        wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
        wrapt                     1.14.1          py310h5764c6d_0    conda-forge
        xz                        5.2.6                h166bdaf_0    conda-forge
        yaml                      0.2.5                h7f98852_2    conda-forge
        yte                       1.5.1           py310hff52083_0    conda-forge
        zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
        zlib                      1.2.12               h166bdaf_4    conda-forge

**Describe the bug**
Getting error and stopped at 19-final

**Error message**

        cp: preserving permissions for `../19-final/final.p_ctg.fasta': Operation not supported
        0.01user 1.05system 0:01.20elapsed 88%CPU (0avgtext+0avgdata 8416maxresident)k
        4680inputs+4688outputs (0major+2254minor)pagefaults 0swaps
        [Thu Oct  6 23:04:10 2022]
        Error in rule final:
            jobid: 1
            output: 19-final/final.p_ctg.fasta, 19-final/final.a_ctg.fasta
            shell:

        wd=$(dirname 19-final/final.p_ctg.fasta)
        mkdir -p $wd
        cd $wd
        rel=..

        input_p_ctg_fasta="$rel/18-purge_dups/final_purged_primary.fasta"         input_a_ctg_fasta="$rel/18-purge_dups/final_purged_haplotigs.fasta"         output_p_ctg_fasta="$rel/19-final/final.p_ctg.fasta"         output_a_ctg_fasta="$rel/19-final/final.a_ctg.fasta"             time ipa2-task final_copy

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

        Removing output files of failed job final since they might be corrupted:
        19-final/final.p_ctg.fasta
        Shutting down, this might take some time.
        Exiting because a job execution failed. Look above for error message
        Complete log: .snakemake/log/2022-10-05T161933.440863.snakemake.log

**Comment by sadiqbioinfo** [comment]
Any help will be appreciated

**Comment by sadiqbioinfo** [comment]
help me please

**Comment by isovic** [comment]
Hi @sadiqbioinfo,
Strange error, I haven't run into something like that before.
However, it is not an IPA error - it looks like it is some kind of an issue with your system.

But in any case, can you share a few more lines of the log above the first line you copied? To show the actual `cp` command line call (if it is shown in Snakemake output)?

Also, if you rerun the workflow, does it manage to finish?

The `final` task is very simple and literally only copies the results produced by other tasks to the `19-final` directory to make it easier to use. The task is composed of literally two `cp` lines.
It copies the fasta files from `18-purge_dups/final_purged_primary.fasta` and `18-purge_dups/final_purged_haplotigs.fasta`.
If those files are available (since all tasks before 19 finished successfully), you can use them for your analyses.

Best regards,
Ivan.
