### ISSUE TITLE
isoseq3 v3.8 doesn't support chaining samples

### ISSUE THREAD

**Issue by rmenafra** [PacificBiosciences/pbbioconda#543]
I updated the isoseq3 to the latest version, but I cannot find anywhere in the docs how to combine multiple sample (old chaining) before the isoforms classification step. Is this supported? 
Thanks

**Comment by Magdoll** [comment]
Hi @rmenafra ,
I think you're thinking about chaining from Cupcake? That was never part of isoseq3.
Current best ideas for chaining samples are here:
https://github.com/Magdoll/cDNA_Cupcake/wiki/Handling-multiple-samples:-Creating-a-master-transcriptome

-Liz

**Comment by rmenafra** [comment]
Hi Liz,
I'm aware it was not part of it, but since collapse (from cupcake) was integrated into isoseq3 I was hoping also chain would be. Your best alternative in my case was talon but I cannot combine all the samples in one mega output because the last step https://github.com/Magdoll/cDNA_Cupcake/wiki/Handling-multiple-samples:-Creating-a-master-transcriptome#vi-linking-talon-combined-transcriptome-back-to-fl-counts will still do the joining per-sample.
