### ISSUE TITLE
Purely website / documentation issue on ccs.how (for now)

### ISSUE THREAD

**Issue by RandyHarr** [PacificBiosciences/pbbioconda#550]
Some of your diagrams in PNG format have transparent backgrounds.  On a dark mode system, you cannot read the black text, arrows, etc as the background is black.  Best to likely fill them in as white or generate JPGs that do not have the transparent feature.

**Comment by armintoepfer** [comment]
Thank you for your input. The website has an explicit bright theme and is not designed for dark mode. If we decide to allow switching between themes, we'll generate new figures
