### ISSUE TITLE
pbmarkdup out of memory error

### ISSUE THREAD

**Issue by gnxsf** [PacificBiosciences/pbbioconda#551]
pbmarkdup is memory efficient but I cannot run a 50 GB bam file on an AWS instance with with 16 GB of RAM:

CPU: 66% (2 cores) * Memory: 6258/15251MB * Storage: 54/445GB * Net: 2↓/0↑MBps
CPU: 67% (2 cores) * Memory: 11981/15251MB * Storage: 54/445GB * Net: 0↓/0↑MBps
systemd invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
Out of memory: Killed process 12921 (pbmarkdup) total-vm:14623616kB, anon-rss:14473760kB, file-rss:0kB, shmem-rss:0kB, UID:100000 pgtables:28524kB oom_score_adj:0

My suspicion is that pbmarkdup is consuming the full 16 GB of RAM and not leaving anything for other system processes, causing the crash (but I don't know how to check this!). Is there a way to restrict pbmarkdup's memory consumption? Similar to the -Xmx12g option that I can specify in Picard's markdup?

**Comment by armintoepfer** [comment]
There's nothing we can do about this right now. We have to read in the full bam, but heavily compressed in memory, to compare reads and find duplicates. Get a memory optimized instance.
