### ISSUE TITLE
isoseq3 refine. ~50% of my input reads contain polyA tail. Do I need to use --require-polya?

### ISSUE THREAD

**Issue by astulaaa** [PacificBiosciences/pbbioconda#554]
Hello, 
I have a general question. ~50% of my input reads contain polyA tail. Do I need to use --require-polya?
Does using "--require-polya" automatically discard reads that do not contain polyA?
How should I process such bam file? should I separate reads that do contain polyA and those that do not contain polyA and process them separately? There is no suggestion in the manual or blogs.

Thank you in advance!

Asta

**Comment by Magdoll** [comment]
Hi @astulaaa ,
Why only 50% of your reads but not all of your reads? How was the cDNA library generated?
-Liz

**Comment by astulaaa** [comment]
@Magdoll rRNA depletion method. To capture complete and truncated transcripts 
-Asta
