### ISSUE TITLE
Latest version of Isoseq3 and Pigeon segmentation fault

### ISSUE THREAD

**Issue by gushiro** [PacificBiosciences/pbbioconda#555]
**Operating system**
Linux64

**Package name**
Isoseq3, Pigeon

**Conda environment**
For pigeon
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ca-certificates           2022.9.24            ha878542_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
ld_impl_linux-64          2.39                 hc81fddc_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.7                h166bdaf_0    conda-forge
pbpigeon                  1.0.0                h9f5acd7_1    bioconda
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
python                    2.7.18               h42bf7aa_3  
python_abi                2.7                    1_cp27mu    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sqlite                    3.40.0               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge

**Describe the bug**
isoseq3 v3.8.2 and pigeon v1.0.0 both produce a "segmentation fault" message. The previous versions of each program runs normal
**Error message**
Segmentation fault

**Expected behavior**
The previous versions of each program runs normal

**Comment by armintoepfer** [comment]
Please have a look if those work for you
https://github.com/PacificBiosciences/pbbioconda/issues/549#issuecomment-1344516742

**Comment by jamestwebber** [comment]
Weirdly I am having a new issue, `lima` is having this issue but it seems like `pigeon` and `isoseq3` are not (I think).

I created a new VM with Ubuntu 20.04 because that is listed as supported. I can install from bioconda and run `pigeon --version` and `isoseq3 --version` (which I couldn't do before, in #549) but `lima --isoseq` segfaults as well as `lima --log-level TRACE`.

At this point my suspicion is that these tools are relying on system libraries that are not being properly checked/versioned for compatibility? `lima` is surprising because it hasn't received an update since I started using it, so it hasn't changed but something else must have.

**Comment by jamestwebber** [comment]
I think I'm tracking down my issue as something else...maybe bad data or bad output that is causing lima to fail (unfortunately without a useful error message). When I know more I'll open a separate issue.

**Comment by gushiro** [comment]
@armintoepfer thank you. This work for me. However, I notice a minor difference in this new version of Isoseq3, particularly for `isoseq3 collapse`. I have now a Warning message` '>|> 20230106 03:24:09.947 -|- WARN -|- Run -|- 0x7f88b4d36d40|| -|- Transcripts do not contain quality values, will not output Id.fastq'`

I should mentioned that the warning did not appear before in previous version of Isoseq3 using the same data.

**Comment by gushiro** [comment]
@armintoepfer also I just notice that Pigen classify split scaffolds into *_classification* and *_junction* but the program seems stuck in the scaffold 45 for hours. My genome ref have 49 scaffolds.

**Comment by armintoepfer** [comment]
Let me ping @derekwbarnett @jmattick for support

**Comment by derekwbarnett** [comment]
Hi @gushiro This sounds like it might be a multithreading issue. Can you re-rerun and see if it hangs at the same point in the data? Let me know what you see. Also, you should know the answer long before 2 days of runtime.

**Comment by armintoepfer** [comment]
In that case, is it possible to provide a minimal working dataset to reproduce the issue? https://github.com/PacificBiosciences/pbbioconda#file-sharing

**Comment by gushiro** [comment]
@armintoepfer yes, where can I send them to you?

**Comment by armintoepfer** [comment]
Please click on the link, everything is explained how to upload data to us

**Comment by armintoepfer** [comment]
@gushiro We've received the data and will triage. Once we have more information, we will update here.

**Comment by astulaaa** [comment]
I am getting the same warning in isoseq3 collapse. Interestingly, after pigeon classify not a single transcript is classified as 'coding'. Any ideas why that would happen? Is it only column 30 annotations are incorrect or all of them? There are many among them annotated as 'full-splice_match' and 'reference_match' and 'canonical' but none of them as 'coding'.

**Comment by jamestwebber** [comment]
> There are many among them annotated as 'full-splice_match' and 'reference_match' and 'canonical' but none of them as 'coding'.

'coding' is not one of [the options](https://isoseq.how/classification/categories.html)

**Comment by astulaaa** [comment]
I'm sorry, I made it unclear. I mean the column 30 "coding". Every isoform is annotated as "non_coding". Even though the column 6 (which you linked the options for) has many "full-splice_match" isoforms. I am confused how is it possible for every transcript to be "non_coding"?

**Comment by gushiro** [comment]
@armintoepfer thanks. To add a little:
I think for non-model species with long UTRs, maybe will be good for pigeon to count genes if the read fall XXXX bp downstream the last exon. I can see in my data a lot of short cDNA and cDNA in utrs that would be classify as intergenic (and therefore not producing a count?). I can see the importance of classifying transcript before (removing antisense reads for example), but I wonder what would happen during the gene count matrix generation if the transcript does fall only in the UTR region.

**Comment by derekwbarnett** [comment]
@gushiro I have identified the problem. In your genome annotations file, the following record is out-of-order:

```
chr46   rRNA    gene    15556622        15556733        .       +       .       gene_id "LSU_316"; gene_id "LSU_316"; gene_id "LSU_316"; gene_id "LSU_316"; gene_id "LSU_316";
chr46   rRNA    exon    15556622        15556733        .       +       .       gene_id "SSU_316"; transcript_id "LSU_316.1";
chr46   rRNA    transcript      15556622        15556733        .       +       .       gene_id "SSU_316"; transcript_id "LSU_316.1"; exon_number "1";
```
The exon entry appears before the transcript. `pigeon` is expecting exon records to be "children" of the transcript. The rest of the file follows this convention. It's just this one record that is different. 

Re-ordering to this, allows `pigeon` to run to completion:
```
chr46   rRNA    gene    15556622        15556733        .       +       .       gene_id "LSU_316"; gene_id "LSU_316"; gene_id "LSU_316"; gene_id "LSU_316"; gene_id "LSU_316";
chr46   rRNA    transcript      15556622        15556733        .       +       .       gene_id "SSU_316"; transcript_id "LSU_316.1"; exon_number "1";
chr46   rRNA    exon    15556622        15556733        .       +       .       gene_id "SSU_316"; transcript_id "LSU_316.1";
```

This situation triggered an internal error state that was not properly handled and suspended processing. I will include a fix in the next release here.

**Comment by gushiro** [comment]
@derekwbarnett thanks, it worked perfect now. 
I still have many "intergenic" transcript. When I check my data, I can see that each gene have many of these small intergenic transcript downstream the gene, spanning between 1000 - 3000 bp. Would it be possible for pigeon make-seurat or any step before to count these short transcript as part of the gene if the gene is "1000 bp" upstream, for example?

**Comment by armintoepfer** [comment]
I have uploaded a new version. If that still segfaults, but not the github binary itself, then conda is corrupting the binary.

**Comment by jamestwebber** [comment]
Just tested and it looks like they work now, thanks for fixing the issue
