### ISSUE TITLE
isoseq3 collapse WARNING Transcripts do not contain quality values, will not output fastq!

### ISSUE THREAD

**Issue by astulaaa** [PacificBiosciences/pbbioconda#558]
**Operating system**
LINUX

**Package name**
isoseq3 collapse  isoseq3 3.8.1 (commit v3.8.1). Updating does not help as isoseq3 3.8.2 has the same issue. 

**Conda environment**
What is the result of `conda list`? 
```
# Name                    Version                   Build  Channel   
_libgcc_mutex             0.1                        main            
fastqc                    0.11.9               hdfd78af_1    bioconda
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0            
fontconfig                2.13.1               h6c09931_0            
freetype                  2.11.0               h70c0345_0            
icu                       58.2                 he6710b0_3            
isoseq3                   3.8.1                h9ee0642_0    bioconda
libgcc-ng                 9.1.0                hdf63c60_0            
libpng                    1.6.37               hbc83047_0            
libstdcxx-ng              9.1.0                hdf63c60_0            
libuuid                   1.0.3                h7f8727e_2            
libxml2                   2.9.14               h74e7548_0            
lima                      2.6.0                h9ee0642_0    bioconda
openjdk                   8.0.152              h7b6447c_3            
pbccs                     6.4.0                h9ee0642_0    bioconda
pbmm2                     1.9.0                h9ee0642_0    bioconda
pbpigeon                  0.1.2                hdfd78af_0    bioconda
perl                      5.26.2               h14c3975_0            
xz                        5.2.5                h7f8727e_1            
zlib                      1.2.12               h7f8727e_2            
```
**Describe the bug**
isoseq3 collapse produces WARNING "Transcripts do not contain quality values, will not output **fastq!" I see from SMRTlink (https://www.pacb.com/wp-content/uploads/SMRT_Tools_Reference_Guide_v10.1.pdf) that HQ isoforms may not contain quality values and a suggestion to run isoseq3 polish, however this function does not exist in isoseq3 v3.8.1 anymore. 

**Error message**
>|> 20230111 08:20:29.003 -|- WARN -|- Run -|- 0x7f736fa9fd40|| -|- Transcripts do not contain quality values, will not output MYFILENAME.fastq!

**To Reproduce**
This chunk of BAM file is sufficient to reproduce the issue
Run isoseq3 collapse with option "--do-not-collapse-extra-5exons"

**Expected behavior**
Either a suggestion how to preprocess the reads to avoid transcripts without quality values being dropped at isoseq3 collapse step or
Suggestion how to get quality values on the isoforms using currently available isoseq3 tools, and in which step
[Achunck_for_test2.zip](https://github.com/PacificBiosciences/pbbioconda/files/10390884/Achunck_for_test2.zip)

**Comment by gyorkeia** [comment]
Same issue here!

**Comment by Ruth-hals** [comment]
Same here!

**Comment by sum732** [comment]
same here.

**Comment by armintoepfer** [comment]
@jmattick please have a look

**Comment by jmattick** [comment]
Hi @astulaaa 
The quality values are dropped prior to the `isoseq3 collapse` step during either `groupdedup` or `cluster`. They are not required for the classification workflow [here](https://isoseq.how/classification/workflow.html#collapse-into-unique-isoforms). This warning will be reduced for the next release. 

You are correct that there is no longer a `polish` step. Please see our updated [Reference Guide](https://www.pacb.com/wp-content/uploads/SMRT_Tools_Reference_Guide_v11.1.pdf) for current recommendations.
