### ISSUE TITLE
BAM2fastx tools not working

### ISSUE THREAD

**Issue by salvatierra8** [PacificBiosciences/pbbioconda#559]
**Operating system**
Ubuntu 22.04.1 LTS

**Package name**
BAM2fastx tools

**Conda environment**
 packages in environment at /home/salvatierra/anaconda3/envs/converters_env:

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bam2fastx                 1.3.1                hb7da652_2    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
htslib                    1.16                 h6bc39ce_0    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdeflate                1.13                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   1.1.1s               h0b41bf4_1    conda-forge
pbbam                     2.1.0                h218f6fc_3    bioconda
pbcopper                  2.0.0                ha04c180_1    bioconda
pbtk                      1.0.0                h9ee0642_0    bioconda
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge

**Error message**
>|> 20230114 16:47:04.209 -|- FATAL -|- Run -|- 0x7fa27e0be3c0|| -|- bam2fastq ERROR: [pbbam] PBI index I/O ERROR: could not open file for reading:
  file: /home/salvatierra/Downloads/H1_1_m64168e_220404_060128.subreads-002.bam.pbi
  reason: No such file or directory

**Describe the issue/bug(?)**
I'm a fresh new user for ubuntu, conda, ngs analysis and any other dependencies for the matter, please have patience. All i understand right now is that i need bam2fastx tool to convert my reads into fastq or fasta in order to assembly em using masurca, there's some error during the process and it's related to the pacbio reads, as another companion and me have to do something similar both used samtools to convert to fasta. I began theorizing that something must be exclusive to the conversion process after trying to analyze the raw reads through bioconductor, i found out that there's no support to do this, and even more someone mentioned in an issue at github that pb data must be analyzed with pb tools to properly convert data obtained from this instruments. So i followed what the github says, and all i get is a file with the name used of 20 bytes, along an error. I do not know what's going on, could be this python 2.7 thing, or maybe a dependency which is not mentioned in the page (like this pbindex which now seems to be pbbam)

Might or might not be important:
If i go to another directory where the bam file is not present and use the command i'll get the same 20 b file in the new directory. So the command is not actually using the file, so this must be related to what "reason:" points out

**To Reproduce**
bam2fastq -o pacbioseq H1_1_m64168e_220404_060128.subreads-002.bam

**Expected behavior**
fastq file corresponding to original bam file

**Comment by armintoepfer** [comment]
For your use-case, use `samtools fasta`. It's much simpler and sufficient for what you are trying to achieve.

**Comment by salvatierra8** [comment]
For anyone using this tool and happens to get a similar error, checksum your file, problem could be related to an unknown issue after downloading the file, as it pointed out that  it was unable to authenticate the file's content. So I just redownload everything again, checksum was ok, and the tool worked.

**Comment by LYC-vio** [comment]
I think this was somehow related to the missing index file for bam random access. Indexing your bam file with pbindex should solve this issue. But just as mentioned above, samtools fasta and samtools fastq could be a quick work around
