### ISSUE TITLE
what does pigeon filter do?

### ISSUE THREAD

**Issue by chilampoon** [PacificBiosciences/pbbioconda#561]
Hi there, I was running the isoseq workflow and I was wondering what does `pigeon filter` do?
Is it the random forest classifier from SQUANTI3 to classify isoforms and artifacts and filter out those artifacts? Thanks

**Comment by chilampoon** [comment]
Oh nvm i saw the filtering reasons [here](https://isoseq.how/classification/pigeon-output.html)

But I am also curious if the program implements the RF classifier

**Comment by armintoepfer** [comment]
Pinging @jmattick @derekwbarnett

**Comment by derekwbarnett** [comment]
No, it only does the equivalent of SQANTI’s “rule filter”, not the RF filter.
