### ISSUE TITLE
Isoseq3 collapse ignored ids

### ISSUE THREAD

**Issue by SziKayLeung** [PacificBiosciences/pbbioconda#563]
Hello, 

Thank you for implementing Liz's Cupcake `collapse_isoforms_by_sam.py` into isoseq3 collapse! 

However, I was wondering if it's possible to output a list of reads that were ignored because they were unmapped or have too low coverage - as was originally generated from `collapse_isoforms_by_sam.py`  as` test.ignored_ids.txt`. 

Across 24 samples, I have noticed over 3 million reads that were present in the aligned sam file, but not in the generated .read_stat.txt or .group.txt file. 

It would therefore be great to trouble shoot and have an understanding of why those transcripts were not collapsed...
Below are the commands used to run isoseq3 collapse and versions. 

Thank you, 
Szi Kay

```
isoseq collapse 3.8.2 (commit v3.8.2)

pbmm2 align --preset ISOSEQ --sort ${GENOME_FASTA} ${fasta} ${samplename}_mapped.bam --log-level TRACE --log-file collapsed.log
isoseq3 collapse ${samplename}_mapped.bam all_merged.gff --do-not-collapse-extra-5exons --log-level TRACE --log-file all_merged_collapsed.log
samtools view -h -o ${samplename}_mapped.sam ${samplename}_mapped.bam
```

```
Using:
  pbbam     : 2.2.0 (commit v2.2.0-1-g8c081f6)
  pbcopper  : 2.1.0 (commit v2.1.0)
  pbmm2     : 1.9.0 (commit v1.9.0-2-gbec8e28)
  minimap2  : 2.15
  parasail  : 2.1.3
  boost     : 1.77
  htslib    : 1.14
  zlib      : 1.2.11

pbmm2 align 1.10.0

Using:
  pbmm2    : 1.10.0 (commit v1.10.0)
  pbbam    : 2.3.0 (commit v2.3.0)
  pbcopper : 2.2.0 (commit v2.2.0)
  boost    : 1.77
  htslib   : 1.15
  minimap2 : 2.15
  zlib     : 1.2.11

```

**Comment by jmattick** [comment]
Hi @SziKayLeung We currently don't output an ignored reads file. We do use the following to filter out alignments so you can see if this explains the transcripts that were not collapsed. 
```
Alignment Filter Options:
  --min-aln-coverage              FLOAT  Ignore alignments with less than minimum query read coverage. [0.99]
  --min-aln-identity              FLOAT  Ignore alignments with less than minimum alignment identity. [0.95]
```

**Comment by MengjunWu** [comment]
Hi, 
I have similar problem with isoseq collapse. While most of my reads (90%) are mapped,  almost half of them are filtered out after isoseq collpase. I was wondering how do you calculate coverage and identify? I want to check if the that's the reason many of my aligments are filtered out.

Many thanks
Mengjun

**Comment by greensii** [comment]
i agree it would be really helpful to be able to see why each read was ignored and/or how the calculations are done.  
i also have a number of samples where a large fraction of mapped reads are not assigned to a collapsed isoform...
eg: 
```
samtools view -h -q30 mapped.bam | cut -f1 | sort | uniq | wc -l
5019771
wc -l collapsed.read_stat.txt
1116007 collapsed.read_stat.txt
```
as i understand it, the only bam file produced is from mapping reads to the full genome, but it's not clear to me how reads are then compared to the isoforms identified in `collapsed.gff`?

thank you!
-sharon greenblum
