### ISSUE TITLE
FATAL ERROR for pigeon sort

### ISSUE THREAD

**Issue by oucstar** [PacificBiosciences/pbbioconda#564]
**Operating system**
CentOS Linux release 7.5.1804 
**Package name**
isoseq3 3.8.1 (commit v3.8.1) and pigeon 1.0.0 (commit -v1.0.0),but always have an error:FATAL | pigeon sort ERROR: 1 - could not read GFF file,could not read  GFF format from IsoSeq collapse.

**Conda environment**

**Describe the bug**
But always have an error:FATAL | pigeon sort ERROR: 1 - could not read GFF file,could not read  GFF format from IsoSeq collapse.

**Error message**
| 20230215 12:09:29.024 | FATAL | pigeon sort ERROR: 1 - could not read GFF file

**To Reproduce**

**Expected behavior**
Help me fix the bug,Thanks!

**Comment by armintoepfer** [comment]
Please post **all** commands that you ran to reproduce this bug.

**Comment by oucstar** [comment]
conda activate PacBio
lima  ../E.ccs.bam ../primers.fasta E.fl.bam --isoseq --peek-guess
lima  ../M.ccs.bam ../primers.fasta M.fl.bam --isoseq --peek-guess
lima  ../N.ccs.bam ../primers.fasta N.fl.bam --isoseq --peek-guess
lima  ../P.ccs.bam ../primers.fasta P.fl.bam --isoseq --peek-guess
lima  ../Z.ccs.bam ../primers.fasta Z.fl.bam --isoseq --peek-guess
ls E.fl.NEB_5p--NEB_Clontech_3p.bam M.fl.NEB_5p--NEB_Clontech_3p.bam N.fl.NEB_5p--NEB_Clontech_3p.bam P.fl.NEB_5p--NEB_Clontech_3p.bam Z.fl.NEB_5p--NEB_Clontech_3p.bam > all.fofn
isoseq3 refine all.fofn ../primers.fasta flnc.bam --require-polya --log-level DEBUG
isoseq3 cluster flnc.bam clustered.bam --use-qvs --verbose 
pbmm2 align --preset ISOSEQ --sort  outs1/clustered.bam  shrimp.genome.fa  mapped.bam 
isoseq3 collapse --do-not-collapse-extra-5exons  mapped.bam  collapsed.gff
pigeon sort  collapsed.gff  -o sorted.gff
| 20230215 12:09:29.024 | FATAL | pigeon sort ERROR: 1 - could not read GFF file

**Comment by oucstar** [comment]
@armintoepfer ,
Sorry to bother you, I have a very confusing question. I used pigeon in isoseq3 to get the gtf file after the sorted isoforms, sorted.filtered_lite.gff file.  But now I want to compare the length and numbers of transcripts between this output file and the gtf annotation file I input in terms of completeness. Do you have supporting software or parameters?  Hope to get your reply, thank you very much!

**Comment by oucstar** [comment]
@armintoepfer @jmattick ,Sorry to bother you, but we have a question that has been bothering us for a long time. We have consulted a lot of data but failed to get an answer. I hope to get some effective reply here.  It was obvious that there were new genes and transcripts identified by the pacbio full-length transcriptome, but I wanted to align this annotated file with the reference annotated file to make the genetic structure annotations more complete, but there was no evidencemodeler to do that. Unfortunately,  evm did not retain these variable splicing bodies, which is a pity. Do you have any suggestions? Thank you very much for your help!

**Comment by armintoepfer** [comment]
@jmattick please have a look

**Comment by oucstar** [comment]
@jmattick ,Could you please answer my question

**Comment by oucstar** [comment]
@armintoepfer ,Sorry to bother you, but we have a question that has been bothering us for a long time. We have consulted a lot of data but failed to get an answer. I hope to get some effective reply here. It was obvious that there were new genes and transcripts identified by the pacbio full-length transcriptome, but I wanted to align this annotated file with the reference annotated file to make the genetic structure annotations more complete, but there was no evidencemodeler to do that. Unfortunately, evm did not retain these variable splicing bodies, which is a pity. Do you have any suggestions? Thank you very much for your help!
