### ISSUE TITLE
FATAL | primrose ERROR

### ISSUE THREAD

**Issue by olaraym** [PacificBiosciences/pbbioconda#571]
**Operating system**
CentOS Linux7 (core)

**Package name**
Primrose the current version

Conda version : 4.6.14

**Describe the bug**
I tried running the primrose package using the hifi reads I have, I followed the instruction in the manual dully. I suspect that the pipeline works well for double-stranded reads but not single-stranded reads. 

**Error message**
FATAL | primrose ERROR: Missing Hifi Kinetics

**To Reproduce**
The file I am working on is very large so I can't share them

**Expected behavior**
I was expecting a more concise error message not just a general message if at all there would be an error message.

**Comment by armintoepfer** [comment]
Yes it does not work with single-stranded reads yet. The next version will, stay tuned
