### ISSUE TITLE
pbmm2 maintaining ip and pw order

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#575]
SAM specifications and expectation of aligners is specified as follows in the Pacbio file formats:
"An aligner is expected to accept BAM input and produce aligned BAM output, where each aligned BAM record in the output preserves intact all tags present in the original record. The aligner should not attempt to orient or complement any of the tags."

However, pbmm2 documentation does not specifically say how it handles kinetic ip and pw tags.

Can you confirm that pbmm2 does not change the orientation of ip and pw tags for reads aligning to the reverse strand?

Thanks.

**Comment by armintoepfer** [comment]
`pbmm2` respects the spec.
