### ISSUE TITLE
Issues with Indexing pbmm2 aligned file

### ISSUE THREAD

**Issue by olaraym** [PacificBiosciences/pbbioconda#577]
**Operating system**
Linux 64

**Package name**
well, I have been using the normal samtools index, I just to find somewhere in my search something like "pbindex" which the source claimed is part of the pbbioconda tools but on my findings on the GitHub page, I didn't find it.  I want to know if this "pbindex" truly exists and how to use it.

**Error message**
[E:: hts_idx_push] chromosome blocks not found

**Comment by armintoepfer** [comment]
Yes, `pbindex` is part of the bioconda package `pbtk`. It's not a replacement for `samtools index`. You can find the `.pbi` spec here: https://pacbiofileformats.readthedocs.io/en/latest/PacBioBamIndex.html
