### ISSUE TITLE
Isoseq3 Error: Segmentation fault

### ISSUE THREAD

**Issue by BenSamy2020** [PacificBiosciences/pbbioconda#581]
**Operating system**
Which operating system and version are you using?

OS:                    Linux
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              48
On-line CPU(s) list: 0-47
Thread(s) per core:  1
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8268 CPU @ 2.90GHz
Stepping:            7
CPU MHz:             3500.093
CPU max MHz:         3900.0000
CPU min MHz:         1200.0000
BogoMIPS:            5800.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-23
NUMA node1 CPU(s):   24-47

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`? Have you updated the complete env by running `conda update --all`? Have you ensured that your channel priorities are set up according to the bioconda recommendations at https://bioconda.github.io/#set-up-channels?

# Name                    Version                   Build  Channel
isoseq3                   3.8.2                h9ee0642_0    bioconda

Additionally, I have set-up channel priorities as per instructions.

**Conda environment**
What is the result of `conda list`? (Try to paste that between [triple backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
isoseq3                   3.8.2                h9ee0642_0    bioconda
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   1.1.1t               h0b41bf4_0    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
readline                  8.2                  h8228510_1    conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sqlite                    3.40.0               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge

**Describe the bug**

When I invoke the command **isoseq3 --help**, I hit the error of Segmentation fault

**Error message**
Paste the error message / stack.

Segmentation fault

**Expected behavior**

It is suppose to provide with all the possible isoseq3 commands when isoseq3 --help is entered.

Regards,
Ben

**Comment by philoel** [comment]
Happening for me too, any solutions incoming?

**Comment by greensii** [comment]
Same here. 
```
~/.conda/pkgs/isoseq3-3.8.2-h9ee0642_0/bin/isoseq3 --version
Segmentation fault
```

**Comment by armintoepfer** [comment]
I have uploaded a new version. If that still segfaults, but not the github binary itself, then conda is corrupting the binary.
