### ISSUE TITLE
Isoseq collapse filtered some reads and I want to know why

### ISSUE THREAD

**Issue by Tianran1** [PacificBiosciences/pbbioconda#584]
**Operating system**
Linux

**Package name**
isoseq3

**Describe the issue**
I downloaded the aligned bam file from the human pbmc MAS-seq (https://downloads.pacbcloud.com/public/dataset/MAS-Seq/DATA-SQ2-PBMC_5kcells/) and I runned the isoseq3 collapse on this bam file. 
Then I checked the aligned bam file  and the collapsed.abundance file for one gene specifically. But the number of molecules found for this gene from these two files is different.  I checked the reason and it showed some are filtered because there are no exonic regions aligned but there are still some missing, which I don't know why. In this case, I want to check the source codes but I couldn't find them. Are they open and where can I take a look at them?
Thanks.

**Comment by jmattick** [comment]
Hi @Tianran1 Can you provide the full set of commands that you used?

**Comment by ywzhang071394** [comment]
Hi, 
I encountered the same issue. Isoseq collapse filtered out some reads with large variants, which is induced by somatic DNA variants. Did you find the reason and solution? Thank you!
