### ISSUE TITLE
Q: replacement for GCpp?

### ISSUE THREAD

**Issue by ptrebert** [PacificBiosciences/pbbioconda#585]
Hi,
I just discovered that the GCpp repository was set to read-only, and I was wondering if there is a dedicated (PacBio) replacement for polishing CLR-based assemblies with CLR reads? Reading through the general readme, I cannot spot any information about that, sorry if I missed that. Thanks.
Best,
Peter

**Comment by armintoepfer** [comment]
You can still use gcpp, but it's no longer being improved.
