### ISSUE TITLE
pbsv call Empty VCF file

### ISSUE THREAD

**Issue by 543090lee** [PacificBiosciences/pbbioconda#586]
Hi,
I am running pbsv on my linux server. I ran pbsv discover HG002.hs37d5_chr17_withRG_sorted_dupMark.bam prac.svsig.gz, to get the prac.svsig.gz file.
Then, (pbsv) bash-4.2$ pbsv call hs37d5.fa prac.svsig.gz prac.vcf. I ran this to get the vcf file, but it threw an error, and gave empty vcf file.

Thanks

**Comment by armintoepfer** [comment]
Mind sharing the error message?

**Comment by 543090lee** [comment]
WHen I run the pbsv call, it didn't print anything, and it just failed. I can share you the prac.svsig file here. #SVSIG	1.7.0
#PBSV_VERSION	2.9.0 (commit v2.9.0-2-gce1559a)
#BIO_SAMPLE_NAMES	HG002	0
#READ_TYPE	subread
#PAD_SIZE	250
#INVERSION_PAD_SIZE	250
#PG	pbsv discover HG002.hs37d5_chr17_withRG_sorted_dupMark.bam prac.svsig.gz
#CONTIG_LENGTH	1	249250621
#CONTIG_LENGTH	2	243199373
#CONTIG_LENGTH	3	198022430
#CONTIG_LENGTH	4	191154276
#CONTIG_LENGTH	5	180915260
#CONTIG_LENGTH	6	171115067
#CONTIG_LENGTH	7	159138663
#CONTIG_LENGTH	8	146364022
#CONTIG_LENGTH	9	141213431
#CONTIG_LENGTH	10	135534747
#CONTIG_LENGTH	11	135006516
#CONTIG_LENGTH	12	133851895
#CONTIG_LENGTH	13	115169878
#CONTIG_LENGTH	14	107349540
#CONTIG_LENGTH	15	102531392
#CONTIG_LENGTH	16	90354753
#CONTIG_LENGTH	17	81195210
#CONTIG_LENGTH	18	78077248
#CONTIG_LENGTH	19	59128983
#CONTIG_LENGTH	20	63025520
#CONTIG_LENGTH	21	48129895
#CONTIG_LENGTH	22	51304566
#CONTIG_LENGTH	X	155270560
#CONTIG_LENGTH	Y	59373566
#CONTIG_LENGTH	MT	16569
#CONTIG_LENGTH	GL000207.1	4262
#CONTIG_LENGTH	GL000226.1	15008
#CONTIG_LENGTH	GL000229.1	19913
#CONTIG_LENGTH	GL000231.1	27386
#CONTIG_LENGTH	GL000210.1	27682
#CONTIG_LENGTH	GL000239.1	33824
#CONTIG_LENGTH	GL000235.1	34474
#CONTIG_LENGTH	GL000201.1	36148
#CONTIG_LENGTH	GL000247.1	36422
#CONTIG_LENGTH	GL000245.1	36651
#CONTIG_LENGTH	GL000197.1	37175
#CONTIG_LENGTH	GL000203.1	37498
#CONTIG_LENGTH	GL000246.1	38154
#CONTIG_LENGTH	GL000249.1	38502
#CONTIG_LENGTH	GL000196.1	38914
#CONTIG_LENGTH	GL000248.1	39786
#CONTIG_LENGTH	GL000244.1	39929
#CONTIG_LENGTH	GL000238.1	39939
#CONTIG_LENGTH	GL000202.1	40103
#CONTIG_LENGTH	GL000234.1	40531
#CONTIG_LENGTH	GL000232.1	40652
#CONTIG_LENGTH	GL000206.1	41001
#CONTIG_LENGTH	GL000240.1	41933
#CONTIG_LENGTH	GL000236.1	41934
#CONTIG_LENGTH	GL000241.1	42152
#CONTIG_LENGTH	GL000243.1	43341
#CONTIG_LENGTH	GL000242.1	43523
#CONTIG_LENGTH	GL000230.1	43691
#CONTIG_LENGTH	GL000237.1	45867
#CONTIG_LENGTH	GL000233.1	45941
#CONTIG_LENGTH	GL000204.1	81310
#CONTIG_LENGTH	GL000198.1	90085
#CONTIG_LENGTH	GL000208.1	92689
#CONTIG_LENGTH	GL000191.1	106433
#CONTIG_LENGTH	GL000227.1	128374
#CONTIG_LENGTH	GL000228.1	129120
#CONTIG_LENGTH	GL000214.1	137718
#CONTIG_LENGTH	GL000221.1	155397
#CONTIG_LENGTH	GL000209.1	159169
#CONTIG_LENGTH	GL000218.1	161147
#CONTIG_LENGTH	GL000220.1	161802
#CONTIG_LENGTH	GL000213.1	164239
#CONTIG_LENGTH	GL000211.1	166566
#CONTIG_LENGTH	GL000199.1	169874
#CONTIG_LENGTH	GL000217.1	172149
#CONTIG_LENGTH	GL000216.1	172294
#CONTIG_LENGTH	GL000215.1	172545
#CONTIG_LENGTH	GL000205.1	174588
#CONTIG_LENGTH	GL000219.1	179198
#CONTIG_LENGTH	GL000224.1	179693
#CONTIG_LENGTH	GL000223.1	180455
#CONTIG_LENGTH	GL000195.1	182896
#CONTIG_LENGTH	GL000212.1	186858
#CONTIG_LENGTH	GL000222.1	186861
#CONTIG_LENGTH	GL000200.1	187035
#CONTIG_LENGTH	GL000193.1	189789
#CONTIG_LENGTH	GL000194.1	191469
#CONTIG_LENGTH	GL000225.1	211173
#CONTIG_LENGTH	GL000192.1	547496
#CONTIG_LENGTH	NC_007605	171823
#CONTIG_LENGTH	hs37d5	35477943
s	0	17	54	302	1	0	0	D00360:95:H2YWMBCXX:2:2114:18239:13559
c	0	17	54	74	0	1
s	0	17	74	323	0	0	0	D00360:97:H2YVMBCXX:2:1208:14077:40507
c	0	17	74	229	1	1
s	0	17	229	478	0	0	0	D00360:97:H2YVMBCXX:2:2114:10793:29318
c	0	17	229	302	2	1
c	0	17	302	321	2	0
c	0	17	321	323	2	1
s	0	17	321	570	1	0	0	D00360:97:H2YVMBCXX:2:1215:6689:80672
c	0	17	323	331	1	1
s	0	17	331	581	0	0	0	HISEQ1:93:H2YHMBCXX:2:1110:11037:45134
c	0	17	331	353	2	1
s	0	17	353	603	0	0	0	D00360:95:H2YWMBCXX:1:2112:2181:65606
c	0	17	353	403	3	1
s	0	17	403	653	1	0	0	D00360:97:H2YVMBCXX:1:1215:9576:94517
c	0	17	403	456	3	2
c	0	17	456	478	3	3
s	0	17	456	706	1	0	0	HISEQ1:93:H2YHMBCXX:2:1106:16705:35291
c	0	17	478	489	2	3
c	0	17	489	570	3	3
s	0	17	489	739	0	0	0	D00360:94:H2YT5BCXX:2:2206:12651:71443
c	0	17	570	581	3	2
c	0	17	581	603	2	2
c	0	17	603	653	1	2
c	0	17	653	706	1	1
c	0	17	706	739	1	0
c	0	17	1044	1088	1	0
s	0	17	1044	1243	0	0	0	D00360:94:H2YT5BCXX:2:2210:4392:68408
c	0	17	1088	1172	2	0
s	0	17	1088	1337	0	0	0	D00360:94:H2YT5BCXX:1:2213:8424:92894
s	0	17	1172	1419	1	1	0	D00360:94:H2YT5BCXX:1:2109:20160:5240
c	0	17	1172	1201	2	1
s	0	17	1201	1451	1	0	0	D00360:97:H2YVMBCXX:1:2107:5555:57174
c	0	17	1201	1243	2	2
c	0	17	1243	1284	1	2
s	0	17	1284	1533	1	0	0	D00360:97:H2YVMBCXX:1:2207:20100:35406
c	0	17	1284	1337	1	3
c	0	17	1337	1408	0	3
s	0	17	1408	1658	0	0	0	D00360:94:H2YT5BCXX:1:1210:13927:83050
c	0	17	1408	1419	1	3
c	0	17	1419	1451	1	2
c	0	17	1451	1533	1	1
c	0	17	1533	1570	1	0
c	0	17	1570	1626	1	1
s	0	17	1570	1818	1	0	0	D00360:97:H2YVMBCXX:1:2112:15357:37242
c	0	17	1626	1628	2	1
s	0	17	1626	1876	0	0	0	HISEQ1:93:H2YHMBCXX:2:2216:5518:26720
c	0	17	1628	1643	3	1
s	0	17	1628	1878	0	0	0	D00360:94:H2YT5BCXX:1:1203:20979:83492
c	0	17	1643	1658	3	2
s	0	17	1643	1893	1	0	0	D00360:95:H2YWMBCXX:2:2207:14806:20013
c	0	17	1658	1818	2	2
c	0	17	1818	1876	2	1
c	0	17	1876	1878	1	1
c	0	17	1878	1893	0	1
c	0	17	2095	2131	1	0
s	0	17	2095	2345	0	0	0	D00360:94:H2YT5BCXX:2:1204:13938:79852
c	0	17	2131	2132	2	0
s	0	17	2131	2376	0	0	1	D00360:94:H2YT5BCXX:1:2202:1921:39537
c	0	17	2132	2255	3	0
s	0	17	2132	2381	0	0	0	D00360:94:H2YT5BCXX:1:2204:20562:88645
c	0	17	2255	2345	4	0
s	0	17	2255	2505	0	0	0	HISEQ1:93:H2YHMBCXX:1:1115:3994:47732
c	0	17	2345	2376	3	0
c	0	17	2376	2381	2	0
c	0	17	2381	2395	1	0
s	0	17	2395	2645	0	0	0	HISEQ1:93:H2YHMBCXX:2:2214:20096:73840
c	0	17	2395	2420	2	0
s	0	17	2420	2670	0	0	0	D00360:96:H2YLYBCXX:1:2113:17914:57489 
These are the first hundred lines.

**Comment by armintoepfer** [comment]
pbsv is for long reads. There's no short read support.
