### ISSUE TITLE
using latest version of minimap2 with pbmm2

### ISSUE THREAD

**Issue by prasundutta87** [PacificBiosciences/pbbioconda#588]
**Operating system**
Linux

**Package name**
pbmm2

**Conda environment**
N/A

**Describe the bug**
Minimap2 has come up with major updates in recet times. However, it seems that pbmm2 still uses an older version of minimap2. How can we go ahead to use the latest version of minimap2 along with its wrapper pbmm2?

**Error message**
N/A

**To Reproduce**
N/A
**Expected behavior**
N/A

**Comment by armintoepfer** [comment]
We are targeting a mm2 update this year. It has to be done in coordination with downstream retrainings, like DeepVariant, to ensure a smooth end to end experience. I'll close this issue as it's already scheduled internally.
