### ISSUE TITLE
Primrose not listed in the table?

### ISSUE THREAD

**Issue by scorreard** [PacificBiosciences/pbbioconda#593]
Hi team,

Is primrose not supported anymore?
It is not available in the table, and I cannot find it on conda anymore.

Thanks,

Solenne

**Comment by armintoepfer** [comment]
We are going to release a new 5mC caller soon. Stay tuned!

**Comment by scorreard** [comment]
This is exciting, but was it necessary to remove primrose in the meantime? That put mot of my analysis to a hard stop.

May I have more details about soon? Are we talking hours? days? 
If it is more than days, I will have to inform my coworkers that the analysis will be delayed.

**Comment by armintoepfer** [comment]
You can get our tools in the meantime via the official SMRTlink bundle https://www.pacb.com/support/software-downloads/

**Comment by armintoepfer** [comment]
https://github.com/PacificBiosciences/jasmine

**Comment by scorreard** [comment]
Thank you!

**Comment by Alipha-Clisa** [comment]
excuses me, but may you kindly tell me that the jasmine is the complete replacement of primrose and all the things done by primrose can also be done by jasmine or there is some other difference?
