### ISSUE TITLE
Identifying variants from de novo assembly files

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/pbbioconda#595]
Hello,

I referred to the PBSV documentation https://github.com/PacificBiosciences/pbsv and could see that aligned bam file was used to identify structural variation signatures. So, using the bam file from Hifiasm (de novo assembly step), I ran the next step:

```
pbsv discover 002-082.asm.GRCh38.bam 002-082.svsig.gz

FATAL RUN 0X2ab3e70c8340. pbsv discover ERROR: Hard clips are not supported
```

Is there a way to identify the structural variants from de novo assembled files (hifiasm)

Thank you

Priya

**Comment by armintoepfer** [comment]
You need to remove cigars `H` from your alignments. I bet there are tools are scripts available.
