### ISSUE TITLE
Iso-Seq ccs params

### ISSUE THREAD

**Issue by kenneditodd** [PacificBiosciences/pbbioconda#599]
Hello,

I have a question regarding input for lima with the IsoSeq workflow. There are two different sets of recommendations when running ccs. Is there a preference towards one or does it depend on what question the user is trying to answer? I could see the SMRT Tools recommendation being less strict and leading to the identification of rare/long transcripts with lower accuracy whereas the Iso-Seq CLI workflow recommendation focuses on accuracy.

[SMRT Tools v12.0](https://www.pacb.com/wp-content/uploads/SMRT_Tools_Reference_Guide_v12.0.pdf) on pg 35 recommends the following settings as input for ccs for specifically Iso-Seq.
```
ccs --min-passes 1 --min-rq 0.9 --skip-polish subreads.bam ccs.bam
```

However, the [Iso-Seq CLI workflow](https://isoseq.how/clustering/cli-workflow.html) recommends using hifi reads.
```
ccs subreads.bam ccs.bam
extracthifi ccs.bam hifi.bam
```

**Comment by armintoepfer** [comment]
Please follow the latter.

**Comment by kenneditodd** [comment]
@armintoepfer thanks!
