### ISSUE TITLE
isoseq3 collapsed output seems suspicious compare to aligned isoforms.

### ISSUE THREAD

**Issue by unique379r** [PacificBiosciences/pbbioconda#600]
Hi

I ran pbmm2 and isoseq3 on multiple barcoded samples to map and collapse transcripts. However, the number of collapsed transcripts is significantly lower than the number of mapped transcripts. I am not sure why this is happening. Is it a bug in the software? Also, Isoseq3 does not generate a list of transcripts that were ignored for collapsing, so I am unable to troubleshoot the issue myself. Any guidance or clues would be greatly appreciated.

**See output for few samples.**

<img width="2120" alt="Screenshot 2023-07-24 at 3 56 14 PM" src="https://github.com/PacificBiosciences/pbbioconda/assets/41694905/37ff7776-eefd-4d60-9f59-41f7e970fc3c">

**Commands i used:**
**Step 1:** lima multiplexed --> lima --isoseq --> isoseq3 refinement --> isoseq3 cluster

**Step2: Mapping of hq.bam using pbmm2_v1.10.0**

```
pbmm2 align --num-threads 24 --log-level TRACE --log-file pbmm2_mapped_log --preset ISOSEQ --sort genome_fa input.hq.bam output.pbmm2_sort.bam
```
**Step3: Collapsing the bam using  isoseq3_v3.8.2**

```
isoseq3 collapse --log-level TRACE --log-file collapse_log --do-not-collapse-extra-5exons input.mapped_bam output.collapse.gff
```

**Comment by jmattick** [comment]
Hi @unique379r. The number of collapsed isoforms is expected to be less than the the number of mapped transcripts. If you want to compare the FLNC counts, we have that information in our `collapse` output files. We don't generate a list of ignored FLNCs but we do generate a list of included FLNCs that map to their collapsed pbid in the `read_stat.txt` file.  
https://isoseq.how/classification/isoseq-collapse.html#output 

If those numbers do not look as expected please re-open this issue.
