### ISSUE TITLE
Barcodes not the same as in 10X sequencing

### ISSUE THREAD

**Issue by Tianran1** [PacificBiosciences/pbbioconda#601]
**Operating system**
Which operating system and version are you using?
Linux

**Package name**
ISO-seq pipeline

**Describe the bug**
I am analyzing one sample from both single-cell MAS-seq and 10x sequencing. I want to check their barcodes overlapping for the count matrix, but I found no intersection, which is weird. I am wondering if the barcodes were revered or modified after the ISO-seq pipeline.

**Comment by armintoepfer** [comment]
Pinging @Magdoll

**Comment by jmattick** [comment]
Hi @Tianran1. That's correct. Our barcode lists are reverse complemented.
