### ISSUE TITLE
groupdedup error when using heteroduplex split fwd/rev reads

### ISSUE THREAD

**Issue by alexb-wang** [PacificBiosciences/pbbioconda#602]
**Operating system**
Linux

**Package name**
isoseq 4.0.0

**Describe the bug**
isoseq groupdedup terminate with "ERROR: movie name must not be empty" when using .bam with reads split using heteroduplex finder into single-strand /fwd and /rev reads. Groupdedup works fine if these single-strand reads are removed, leading me to believe it's just having an issue with the /fwd or /rev annotation in the qname.

**Comment by armintoepfer** [comment]
It's likely an edge-case that we haven't tried before. We will look into this when time allows.
