### ISSUE TITLE
Pacbio ID  and genome coordinate

### ISSUE THREAD

**Issue by gengbaobao** [PacificBiosciences/pbbioconda#603]
Hello developers,

After running "isoseq3 collapse", I get the collapse.gff file containing transcript_id like "PB.X.X". Is there any correspondence bwtween PacBio ID (PB.X.X) and the genome coordinate? Or just generated randomly.

Best,
Baobao

**Comment by jmattick** [comment]
Hi @gengbaobao,
The PacBio ID does not correlate to genome coordinates. `collapse` is generating the "PB.X.Y" id based on the order that the windows are being processed. 
Best,
Jessica
