### ISSUE TITLE
collapse error - im tag missing

### ISSUE THREAD

**Issue by Ollipolli1909** [PacificBiosciences/pbbioconda#604]
Hi, issues was already reported before - suggested solution was update to Isoseq 3.8 - I am running 4.0.0 but still get this error:

>|> 20230823 05:56:18.093 -|- WARN -|- BamRecordIsGood -|- 0x7f42fa455d40|| -|- Read transcript/563 does not have tag im or is. Reads without im or is will be assumed to be a single molecule.

1. ran cluster on service provider supplied hifi bam
2. mapped to genome using minimap2
3. ran cluster, getting above error message

**Comment by armintoepfer** [comment]
You need to use `pbmm2` to align reads. We do not recommend pure `minimap2`, as it won't forward custom BAM tag.
