### ISSUE TITLE
Bug in actc --chunk

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#605]
Hi,
I'm running actc version:
```
actc 0.4.0

Using:
  actc     : 0.4.0 (commit 0.4.0)
  pbbam    : 2.4.99 (commit v2.4.0-23-g59248fe)
  pbcopper : 2.3.99 (commit v2.3.0-9-g4eb7ac8)
  boost    : 1.81
  htslib   : 1.17
  zlib     : 1.2.13
```

This command:
```
sbatch -a 1-20 -t 360 --mem=48G --wrap "actc -j 4 --chunk \$SLURM_ARRAY_TASK_ID/20 subreads.bam aligned.ccs.bam aligned.ccs.actc.\$SLURM_ARRAY_TASK_ID.bam"
```

For some reason it is consistently outputting empty fasta (and therefore empty BAM) for most of the chunks, and the same chunks every time are empty. Other chunks are running fine. It must be a bug in the chunk feature of actc

**Comment by armintoepfer** [comment]
Are your ccs reads sorted by ZMW id? If not, sort the file using samtools sort -t zm, or wait another week as I just implemented chunking for unsorted input

**Comment by armintoepfer** [comment]
Try this, it's a work in progress https://github.com/PacificBiosciences/actc/commit/9157141ef29f2b2c46348e63beddd1aaac109376

**Comment by gevro** [comment]
No, the ccs reads are sorted by chromosome position because they are post-pbmm2 alignment + sort.

Thanks for the quick update. I will try it.

**Comment by armintoepfer** [comment]
Aligned reads are not supported.
