### ISSUE TITLE
Multiplex workflow starting with hifi.bam ...

### ISSUE THREAD

**Issue by drkoryjohns** [PacificBiosciences/pbbioconda#607]
The documentation provided here:

https://isoseq.how/clustering/examples.html#multiplexed-samples

... includes paths to toy data to use for the multiplexed example workflow that do NOT exist?

Can you update your documentation please updated paths to data that can be used to run the workflow?

When I attempt to run the workflow on my actual multiplexed data, NA is reported for every isoform in place of sample identifier(s) in the abundance file that is returned.  

Would like to use the toy data to ensure workflow is working as intended.

Thank you,

Kory Johnson

**Comment by armintoepfer** [comment]
Thank you, we will investigate internally.

**Comment by armintoepfer** [comment]
Closing as a duplicate, please keep your eyes on https://github.com/PacificBiosciences/pbbioconda/issues/615 for further information
