### ISSUE TITLE
lima after ccs: handling of kinetics tags

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/pbbioconda#610]
If ccs v6.4.0 is run before lima v2.6.0, does lima know how to correctly clip the kinetics tags (ip,pw,fi,fp,ri,rp) that correspond to the barcodes?

Are there other tags that lima knows how to clip correctly, or can specific tags be specified for this barcode-related clipping?

Thanks

**Comment by armintoepfer** [comment]
`lima` knows how to properly demultiplex unaligned PacBio reads processed by PacBio tools. That includes kinetics and methylation tags.
