### ISSUE TITLE
how to construct the barcode_primer.fa file

### ISSUE THREAD

**Issue by TripleEmma** [PacificBiosciences/pbbioconda#613]
I have a general question regarding the BARCODES.fa file provided to lima for iso-seq data analysis. This file contains primer and barcode sequences, and I'm unsure about how to properly combine these sequences. I understand that the primer barcode IDs should end with '5p' and '3p' to indicate their direction, but I couldn't find specific information about the sequence arrangement.

For example, the barcode is"ACACACAGACTGTGAG", the forward primer is "GCAATGAAGTCGCAGGGTTG", and the reverse primer is "AAGCAGTGGTATCAACGCAGAGT". How should I combine these sequences? I've tried two different combinations based on my reading, and both yield a similar number of sequences as output. I'm uncertain which one is correct.
**combination 1:**
>sample_5p 
**ACACACAGACTGTGAG** GCAATGAAGTCGCAGGGTTG (barcode in bold, plus forward primer)
>sample_3p
AAGCAGTGGTATCAACGCAGAGT (reverse primer)

**combination 2:**
>sample_5p
**ACACACAGACTGTGAG** GCAATGAAGTCGCAGGGTTG (barcode in bold, plus forward primer)
>sample_3p
ACTCTGCGTTGATACCACTGCTT **CTCACAGTCTGTGTGT** (reverse complementary of reverse primer and barcode)

I would appreciate your insight on this question. Thank you!

**Comment by armintoepfer** [comment]
The best is if you reach out to PacBio's customer support, as this question is not really a technical one about our binaries distributed by bioconda. They will help you! https://www.pacb.com/support/technical-support/
