### ISSUE TITLE
https://downloads.pacbcloud.com/public/dataset/ not publicly available?

### ISSUE THREAD

**Issue by bfoquet** [PacificBiosciences/pbbioconda#615]
**Operating system**
Windows - MobaXterm v23.2

**Package name**
N/A

**Conda environment**
N/A

**Describe the bug**
I'm unable to access the example data needed to test the isoseq package (e.g. https://downloads.pacbcloud.com/public/dataset/IsoSeq_sandbox/2020_Alzheimer8M_subset/alz.1perc.ccs.bam ). I am also unable to access https://downloads.pacbcloud.com/public/dataset/ on my webbrowser (google chrome, see error pasted below), but I can access https://downloads.pacbcloud.com/public/ and several of its subdirectories. 

**Error message**
Error message in terminal:
![image](https://github.com/PacificBiosciences/pbbioconda/assets/28549041/b4efa748-7f85-4e8e-b056-4adae4945763)
Error message in web browser: 
![image](https://github.com/PacificBiosciences/pbbioconda/assets/28549041/113903d2-b311-4960-9bb5-b160db312e1f)

**To Reproduce**
wget https://downloads.pacbcloud.com/public/dataset/IsoSeq_sandbox/2020_Alzheimer8M_subset/alz.1perc.ccs.bam

**Expected behavior**
I expected to download the example data set to try the Isoseq package

**Comment by armintoepfer** [comment]
We've fixed the example
