### ISSUE TITLE
IPA error command 

### ISSUE THREAD

**Issue by wez078** [PacificBiosciences/pbbioconda#619]
Dears,
I am running the IPA assembler for my hifi reads under the Ubuntu Linux system and always got error  as below 

"ValueError in file /storage/proj/Pea_root_rot/Miniconda3/envs/ipa/etc/ipa.snakefile, line 57:
Invalid format specifier ' 02d ' for object of type 'int'
  File "/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/etc/ipa.snakefile", line 59, in <module>
  File "/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/etc/ipa.snakefile", line 57, in prenum
ERROR: Command '/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/python3 -m snakemake --dryrun -j 2 -d RUN -p -s /storage/proj/Pea_root_rot/Miniconda3/envs/ipa/etc/ipa.snakefile --configfile RUN/config.yaml --reason' returned non-zero exit status 1.
Exiting."

and also details running was below, I try reads in fasta and and fastq format, all reported same error, and my reads are hifi css read 

Many thanks for your help on this 
cheers
wentao

(ipa) wentao@rind1:/storage/proj/Pea_root_rot/pathogenome_assembly/ipa_test$ ipa local --nthreads 5 --njobs 2 --tmp-dir ./  --dry-run -i /storage/proj/Pea_root_rot/Pea_Pacbio_Pathogen/AE5.fasta.gz
INFO: /storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/ipa local --nthreads 5 --njobs 2 --tmp-dir ./ --dry-run -i /storage/proj/Pea_root_rot/Pea_Pacbio_Pathogen/AE5.fasta.gz
INFO: ipa.py ipa (wrapper) version=1.8.0 ... Checking dependencies ...
INFO: Dependencies
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/python3
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/ipa2-task
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/falconc
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/minimap2
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/nighthawk
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/pancake
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/pblayout
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/racon
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/samtools
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/ipa_purge_dups
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/ipa_purge_dups_split_fa
snakemake version=7.32.4
ipa2-task 1.8.0 (commit 89f9124a7aa07d170db0eb490c12a5aeb36bcf64)
 Machine name: 'Linux'
Copyright (C) 2004-2021     Pacific Biosciences of California, Inc.
This program comes with ABSOLUTELY NO WARRANTY; it is intended for
Research Use Only and not for use in diagnostic procedures.

falconc version=1.15.0+git., nim-version=1.2.0
minimap2 version=2.26-r1175
Nighthawk 1.0.0 (commit SL-release-10.2.0-11-g332ccaa)
pancake 1.6.0 (commit SL-release-10.2.0-175-gb750c42)
pblayout 1.4.0 (commit SL-release-10.2.0-64-gd59326a)
racon version=1.5.0
samtools 1.18
Using htslib 1.18
ipa_purge_dups Version: 1.2.5

To run this yourself:
/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/python3 -m snakemake --dryrun -j 2 -d RUN -p -s /storage/proj/Pea_root_rot/Miniconda3/envs/ipa/etc/ipa.snakefile --configfile RUN/config.yaml --reason

Starting snakemake --dryrun ...
 CWD: /storage/proj/Pea_root_rot/pathogenome_assembly/ipa_test/RUN
 NPROC: 5
 NPROC_SERIAL: 5
 config: {'advanced_options': '', 'coverage': 0, 'genome_size': 0, 'm4filt_high_copy_sample_rate': 1.0, 'max_nchunks': 40, 'nproc': 5, 'phase_run': 1, 'polish_run': 1, 'purge_dups_calcuts': '', 'purge_dups_run': 1, 'reads_fn': 'RUN/input.fofn', 'tmp_dir': './'}
ValueError in file /storage/proj/Pea_root_rot/Miniconda3/envs/ipa/etc/ipa.snakefile, line 57:
Invalid format specifier ' 02d ' for object of type 'int'
  File "/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/etc/ipa.snakefile", line 59, in <module>
  File "/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/etc/ipa.snakefile", line 57, in prenum
ERROR: Command '/storage/proj/Pea_root_rot/Miniconda3/envs/ipa/bin/python3 -m snakemake --dryrun -j 2 -d RUN -p -s /storage/proj/Pea_root_rot/Miniconda3/envs/ipa/etc/ipa.snakefile --configfile RUN/config.yaml --reason' returned non-zero exit status 1.
Exiting.
(ipa) wentao@rind1:/storage/proj/Pea_root_rot/pathogenome_assembly/ipa_test$

**Comment by wez078** [comment]
Dears,
I finally figured this out, now the IPA assembler worked for me 
Thanks
wt

**Comment by tpshea2** [comment]
Hello-
I know this issue was recently closed but I get the exact same error even after trying a number of modifications to the config.yaml file in the RUN directory.  Any suggestions on what to try to get ipa to run?  Thank you.

/path/to/pbipa/bin/python3 -m snakemake -j 6 -d RUN -p -s /path/to/pbipa/etc/ipa.snakefile --configfile RUN/config.yaml  --reason
Invalid format specifier ' 02d ' for object of type 'int'
  File "/cil/shed/apps/external/pbipa/etc/ipa.snakefile", line 59, in <module>
  File "/cil/shed/apps/external/pbipa/etc/ipa.snakefile", line 57, in prenum

**Comment by armintoepfer** [comment]
Would be great if @wez078 shares his solution.

**Comment by wez078** [comment]
Hello looked like same issues as mines, I figured this it, by:
change line 57 of snake file to specify the: return f'{RULE_COUNT:02d}-'" to the other format: 
return '{:02d}-'.format(RULE_COUNT)

and all worked well now for the IPA

cheers
wt

**Comment by tpshea2** [comment]
Thank you very much for sharing.  My job got further along with this edit
to the snake file.
