### ISSUE TITLE
Question: does pbmm2 modify MM and ML tags for supplementary alignments with hard clippings?

### ISSUE THREAD

**Issue by lh3** [PacificBiosciences/pbbioconda#621]
@armintoepfer, here is a pbmm2 question for you. PacBio now outputs MM/ML tags for methylation. When pbmm2 outputs a supplementary alignment with hard clippings, does it modify the original MM/ML, copy them over to the output SAM line, or discard MM/ML on hard clipped SAM line? For the context, see samtools/hts-specs#646, but you don't have to read the thread.

**Comment by armintoepfer** [comment]
Hey @lh3, `pbmm2` never hard clips. All of our alignments are either primary or supplementary with soft clippings.

**Comment by lh3** [comment]
Got it. Thanks!
