### ISSUE TITLE
Isoseq cluster2 failed when running with  more than 30M consensus reads.

### ISSUE THREAD

**Issue by 7kylin** [PacificBiosciences/pbbioconda#628]
hi，all：
My problems are as follows:
**Operating system**
CentOS Linux release 7.4.1708 (Core)

**Package name**
isoseq 4.0.0 (commit v4.0.0)

Using:
  pbbam     : 2.4.99 (commit v2.4.0-16-g5cc6e4b)
  pbcopper  : 2.3.99 (commit v2.3.0-14-g5ac5693)
  pbmm2     : 1.11.99 (commit v1.11.0-1-g1b5a417)
  minimap2  : 2.15
  parasail  : 2.1.3
  boost     : 1.77
  htslib    : 1.17
  zlib      : 1.2.13

**Describe the bug**
terminate called without an active exception
/opt/gridengine/default/spool/tjcompute133/job_scripts/336846: 行 2: 34707  (core dumped)  isoseq cluster2 flnc100.bam transcripts.bam

**To Reproduce**
I qsub this step with vf=500G,p=50 ,but it still exited with this error.

**Expected behavior**
How can I run cluster with 30M consensus reads?

Thanks for your reply.

**Comment by armintoepfer** [comment]
We can't help you given the information you've provided. Have you tried clustering fewer reads? When does it start breaking? We've run it with up to 500M HiFi reads.

**Comment by 7kylin** [comment]
> We can't help you given the information you've provided. Have you tried clustering fewer reads? When does it start breaking? We've run it with up to 500M HiFi reads.

Yes, The program running normally with less than 20M reads.
Can you tell me how much memory and cpu you use? I will try it later.
Or what is  needed for this program is GPU?
Thanks a lot.

**Comment by armintoepfer** [comment]
We run with `-j 128` for those benchmarks

| #HiFi | Wall time | CPU time | Peak RSS |
| ----- | --------- | -------- | -------- |
| 500M  | 1d 15h    | 38d 20h  | 954 GB   |
| 250M  | 11h 14m   | 28d 5h   | 317 GB   |
| 125M  | 6h 23m    | 10d 4h   | 127 GB   |
| 63M   | 2h 5m     | 4d 11h   | 69 GB    |
| 31M   | 58m 44s   | 2d 1h    | 50 GB    |

**Comment by 7kylin** [comment]
> We run with `-j 128` for those benchmarks
> 
> #HiFi	Wall time	CPU time	Peak RSS
> 500M	1d 15h	38d 20h	954 GB
> 250M	11h 14m	28d 5h	317 GB
> 125M	6h 23m	10d 4h	127 GB
> 63M	2h 5m	4d 11h	69 GB
> 31M	58m 44s	2d 1h	50 GB

I have got it  and thank you very much.
