### ISSUE TITLE
how can I merge the single-cell matrix of two samples?

### ISSUE THREAD

**Issue by gygys** [PacificBiosciences/pbbioconda#630]
Hello:
I have sc-Iso-seq data for two samples. I generated two "isoform-count matrix" files using "pigeon make-seurat", but their pbid are not equal, how can I merge the single-cell matrix of these two samples?
Or how to analyze multiple samples with iso-seq and merge them at the end?

Any answer would be appreciated!

**Comment by armintoepfer** [comment]
The best is if you reach out to PacBio's customer support, as this question is not really a technical one about our binaries distributed by bioconda. They will help you! https://www.pacb.com/support/technical-support/
