### ISSUE TITLE
Identification of structural variants in simulated genome by pbsv

### ISSUE THREAD

**Issue by priyambial123** [PacificBiosciences/pbbioconda#632]
Hello,

To understand the steps in background of identification of structural variants by pbsv tool, I performed the following steps:

1. Simulated the deletions in the reference GRCh38 genome in R (using RVSim package)
2. Simulated genome was aligned (using pbmm2 tool)
3.  Sorted the simulated genome (samtools)
4. Discovered structural variants (pbsv tool)

No structural variants was there in the simulated genome after running pbsv analysis. Is something I have to run or have missed here. It would be helpful to know how the structural variants are identified

```
##First step
library(RSVSim)
genome = "/scicore/home/cichon/GROUP/temp_pacbio/reference/human_GRCh38_no_alt_analysis_set.fasta"
sim = simulateSV(output=NA, genome=genome, dels=3, sizeDels=10, bpSeqSize=6, seed=456, verbose=FALSE)


##Second step - Simulated genome from above step was aligned (using pbmm2 tool)
pbmm2 align reference.fasta simulated_genome.fasta aligned.bam

## Third step - Aligned bam was sorted (by samtools)
samtools sort aligned.bam -o aligned_sorted.bam

##Fourth step - Structural variants were identified by pbsv tool
pbsv discover aligned_sorted.bam discovery-aligned.svsig.gz
pbsv call reference.fasta aligned.svsig.gz sample_var.vcf

```

Thank you

**Comment by armintoepfer** [comment]
Since this is a not an issue with our tools distributed through bioconda, please follow up with support@pacb.com
