### ISSUE TITLE
Jasmine ERROR

### ISSUE THREAD

**Issue by Duyh814** [PacificBiosciences/pbbioconda#634]
I'm a fresh man in bioinformatics, i dont know how to solve Error in java , Is there any way to solve my ERROR information.
I install by bioconda jasmine ,but I meet the follow problem
I use ```jasmine ccs.bam test1.bam -j 1 --log-level INFO```

''' ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
21:05:44.957 [main] ERROR  - error parsing parameters::
org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: -j
Exception in thread "main" java.lang.NullPointerException
        at uio.amg.zhong.jasmine.JASMINE.findXMLfile(JASMINE.java:494)
        at uio.amg.zhong.jasmine.JASMINE.main(JASMINE.java:40)'''

**Comment by armintoepfer** [comment]
You are using the wrong jasmine. Not sure what program you calling. Get the binary from bioconda or https://github.com/PacificBiosciences/jasmine/releases/tag/v2.0.0
