### ISSUE TITLE
mistake in isoseq refine documentation for single cell

### ISSUE THREAD

**Issue by MengjunWu** [PacificBiosciences/pbbioconda#637]
Hi,

I am following the single cell CLI Workflow for analyzing iso-seq data. 

In Step 4 - Refine:  the input files for isoseq refine are specified as: 
<movie>.flt.bam or <movie>.flt.transcriptset.xml

the actual command in the documentation is:
isoseq refine <movie>.fl.5p--3p.bam primers.fasta <movie>.fltnc.bam --require-polya

I understood "<movie>.fl.5p--3p.bam" should be the input for isoseq tag step while  isoseq refine took output from isoseq tag? Just want to confirm if this is a mistake in the documentation and whether the correct input should be <movie>.flt.bam instead of <movie>.fl.5p--3p.bam?

Many thanks,
Mengjun

**Comment by jmattick** [comment]
Hi @MengjunWu, Thank you for opening this issue. You are correct. We run `isoseq tag` before `isoseq refine`. We will update the documentation to reflect this.

**Comment by MengjunWu** [comment]
Many thanks for the reply. 

There is another problem with isoseq tag, When I run the command,  it does not return the flt.transcriptset.xml file. I think it suppose to generate both bam and xml file?
