### ISSUE TITLE
PBSV to detect heterogeneity?

### ISSUE THREAD

**Issue by TristanJang** [PacificBiosciences/pbbioconda#639]
Greetings, 
I am writing because I am using multiple SV calling tools to detect both consensus and heterogeneity in structural variants in Mycobacterium tuberculosis. Is there a setting or a flag allowing me to change variant allele frequency, allowing me to detect heterogenous structural variants after mapping the reads to its own consensus de novo assembly? 

Thanks,
Tristan

**Comment by armintoepfer** [comment]
I don't think so. Pinging @ctsa who is developing the next HiFi SV caller.
