### ISSUE TITLE
Pigeon report script fails

### ISSUE THREAD

**Issue by dsampath31** [PacificBiosciences/pbbioconda#642]
**Operating system**
MAC

**Package name**
https://github.com/ConesaLab/SQANTI3/blob/master/utilities/report_pigeon/pigeon_report.R
Rscript used to provide reports from pigeon, (pigeon 1.1.0)

**Conda environment**
Using Mac's Rstudio server

**Describe the bug**
There is a bug in line 15 in **pigeon_report.R** script as the number of arguments is 5 not 6.
class.file <- args[1]
junc.file <- args[2]
**utilities.path <- args[4]**
saturation.curves <- args[5]
report.format <- args[6]

**if (length(args) < 6) {
  stop("Incorrect number of arguments! Script usage is: [classification file] [junction file] [utilities directory path] [True/False for saturation curves] [pdf|html|both]. Abort!")
}**

**Error message**
I correct the arguments number and run the script
 `Rscript ~/Documents/isoseq/SQANTI3/utilities/report_pigeon/pigeon_report.R *lite_classification.txt *lite_junctions.txt ~/Documents/isoseq/SQANTI3/utilities/report_pigeon/ False both
`
```
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
`summarise()` has grouped output by 'lenCat'. You can override using the `.groups` argument.
Warning message:
`guides(<scale> = FALSE)` is deprecated. Please use `guides(<scale> = "none")` instead.
Error in `[.data.frame`(t3.a.SJ, , c(1, 5, 6)) :
  undefined columns selected
Calls: rbind ... standardGeneric -> eval -> eval -> eval -> [ -> [.data.frame
Execution halted
```

**Comment by dsampath31** [comment]
I edited the script to reflect correct number of arguments and applied `sed "s/within_cage_peak/within_CAGE_peak/g` then the script ran fine producing PDF and HTML. 

The main script still requires change in the number of arguments and reflect the latest release with uppercase "CAGE"

**Comment by armintoepfer** [comment]
Please report to the appropriate repository. We don't maintain SQANTI3
