### ISSUE TITLE
isoseq groupdedup std::get: wrong index for variant

### ISSUE THREAD

**Issue by MT2901** [PacificBiosciences/pbbioconda#643]
**Operating system**
5.14.0-162.6.1.el9_1.x86_64 GNU/Linux

**Package name**
isoseq  4.0.0

**Conda environment**
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bamtools                  2.5.2                hdcf5f25_2    bioconda
bedtools                  2.31.1               hf5e1c6e_0    bioconda
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.23.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
certifi                   2019.11.28       py27h8c360ce_1    conda-forge
htslib                    1.17                 h6bc39ce_1    bioconda
isoseq                    4.0.0                h9ee0642_0    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libcurl                   7.87.0               h6312ad2_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libnghttp2                1.51.0               hdcd2b5c_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lima                      2.9.0                h9ee0642_1    bioconda
ncurses                   6.4                  h59595ed_2    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
pbccs                     6.4.0                h9ee0642_0    bioconda
pbmm2                     1.13.1               h9ee0642_0    bioconda
pbpigeon                  1.2.0                h4ac6f70_0    bioconda
pbskera                   1.2.0                hdfd78af_0    bioconda
pbtk                      3.1.1                h9ee0642_0    bioconda
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pyfaidx                   0.5.3                    py27_0    bioconda
pysam                     0.8.4                    py27_0    bioconda
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
readline                  8.2                  h8228510_1    conda-forge
samtools                  1.18                 hd87286a_0    bioconda
setuptools                44.0.0                   py27_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.44.2               h2c6b66d_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge

**Describe the bug**
Hi, I am trying to process some single cells isoseq data, which the ccs reads were in fastq.gz. I managed to covert the fastq.gz to unaligned bam file. I have followed the the standard single cells isoseq pipeline (https://isoseq.how/umi/examples.html) till the isoseq groupdedup step, which I encounter the following error:

isoseq groupdedup --keep-non-real-cells sample.bam sample_dedup.bam

| 20240130 23:48:34.431 | FATAL | Exception thrown in worker: std::get: wrong index for variant
terminate called without an active exception
Aborted (core dumped)

The sample.bam was sorted and contained the  “CB”  “XC” tag,  would you please suggest the issue? I also uploaded a short example bam.

[sample.bam.gz](https://github.com/PacificBiosciences/pbbioconda/files/14105602/sample.bam.gz)

**Comment by armintoepfer** [comment]
You can't use fastq to ubam converted data as input. Please try to get the
original unaligned BAM file.

MisoT2901 ***@***.***> schrieb am Mi., 31. Jan. 2024, 01:03:
