### ISSUE TITLE
isoseq3 installation on macOS

### ISSUE THREAD

**Issue by a11is0nshi** [PacificBiosciences/pbbioconda#644]
**Operating system**
macOS, version 13.2.1

**Package name**
isoseq3 / lima. I have updated the complete env by running 'conda update --all'. My channel priorities are set up according to the bioconda recommendations. 

**Conda environment**
```
# packages in environment at /Users/allisonshi/anaconda3/envs/myenv:
#
# Name                    Version                   Build  Channel
```

**Describe the bug**
I am unable to download the isoseq3 package through the command "conda install isoseq3" because I am informed that I also need to install the "lima" package. However, it appears that the "lima" package as per https://anaconda.org/ is only compatible with linux-64. Does this mean I am unable to install isoseq3 because I have a mac? Is there a solution to installing isoseq3 and lima on my computer?

**To Reproduce**
Results of the command 'conda install isoseq3'

Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides lima needed by isoseq3-3.2.0-0

Could not solve for environment specs
The following package could not be installed
└─ isoseq3 is not installable because it requires
   └─ lima, which does not exist (perhaps a missing channel).

Results of the command 'conda install lima'

Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - lima

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/bioconda
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Expected behavior**
I hope to be able to download the isoseq3 package on my macOS.

**Comment by armintoepfer** [comment]
Please have a look at the compatibility matrix. It's not supported.

https://github.com/PacificBiosciences/pbbioconda?tab=readme-ov-file#packages
