### ISSUE TITLE
How to extract INS.DUP type REF and ALT sequence 

### ISSUE THREAD

**Issue by lixuenan** [PacificBiosciences/pbbioconda#646]
**Operating system**
linux
I call SV with PBSV call ,and I get some INS.DUP,BND,Now I want to get ALT  DUP sequences ,but it does not appear in vcf file,
How  can I get this sequences?
chr1    339052  pbsv.INS.DUP.19 C       <DUP>   .       PASS    SVTYPE=DUP;END=339380;SVLEN=328 GT:AD:DP        0/1:6,5:11
chr1    339337  pbsv.INS.DUP.20 T       <DUP>   .       PASS    SVTYPE=DUP;END=339450;SVLEN=113 GT:AD:DP        0/1:5,5:10

**Comment by armintoepfer** [comment]
This is not supported. Pinging @ctsa who is developing our `pbsv2` successor
