### ISSUE TITLE
pigeon make-seurat error: could not open plain text file

### ISSUE THREAD

**Issue by JiangyanYu** [PacificBiosciences/pbbioconda#647]
I am using smrttools v13. At the last step of pigeon make-seurat, I receive this error:

pigeon make-seurat --dedup /home/852-2/corrected/852-2.dedup.fasta --group /home/852-2/mapped/852-2.collapsed.group.txt -d /home/852-2/seurat /home/852-2/mapped/852-2_classification.filtered_lite_classification.txt --log-level DEBUG --log-file /home/852-2/seurat/log.txt

20240205 11:19:44.058 | FATAL | pigeon make-seurat ERROR: [pbbam] text file writer ERROR: could not open plain text file:
  file: /home/852-2/seurat//home/852-2/mapped/852-2.annotated.info.csv
  reason: No such file or directory

It seems that the xxx.annotated.info.csv file is in the same location as the xxx.classification.filtered_lite_classification.txt. Therefore I copy the xx.classification.filtered_lite_classification.txt to current working directory. This solved the problem:

pigeon make-seurat --dedup /home/852-2/corrected/852-2.dedup.fasta --group /home/852-2/mapped/852-2.collapsed.group.txt -d /home/852-2/seurat 852-2_classification.filtered_lite_classification.txt --log-level DEBUG --log-file /home/852-2/seurat/log.txt

Is this the correct way to bypass the error? Or is this a bug in this version? Thanks!

**Comment by armintoepfer** [comment]
Please reach out to support@pacb.com, thank you!

**Comment by omarelgarwany** [comment]
I solved this issue by using the `--output-prefix` flag:
`  -o,--out-prefix         STR   Prefix for all, non-matrix files. If not specified, the primary input classification
                                file will be used to determine the prefix. Example:
                                'my_isoforms_classification.filtered_lite_classification.txt' or
                                'my_isoforms_classification.txt' input will yield output prefix 'my_isoforms'.`
