### ISSUE TITLE
isoseq collapse error: Could not find length of CCS read

### ISSUE THREAD

**Issue by Hyeyeonggg** [PacificBiosciences/pbbioconda#648]
**Operating system**

> CentOS Linux 8

**Package name**

> isoseq 4.0.0
> conda 23.11.0
> `conda update --all` results `# All requested packages already installed.`
> 

**Conda environment**
What is the result of `conda list`? 

```
# packages in environment at /genomics/tools/longread/miniconda3/envs/isoseq:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.19.1               h5eee18b_0
ca-certificates           2023.12.12           h06a4308_0
htslib                    1.13                 h9093b5e_0    bioconda
isoseq                    4.0.0                h9ee0642_0    bioconda
krb5                      1.20.1               h568e23c_1
libcurl                   7.88.1               h91b91d3_2
libdeflate                1.17                 h5eee18b_1
libedit                   3.1.20230828         h5eee18b_0
libev                     4.33                 h7f8727e_1
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libnghttp2                1.52.0               ha637b67_1
libssh2                   1.10.0               h37d81fd_2
libstdcxx-ng              11.2.0               h1234567_1
lima                      2.9.0                h9ee0642_1    bioconda
ncurses                   6.4                  h6a678d5_0
openssl                   1.1.1w               h7f8727e_0
pbbam                     1.7.0                h058f120_1    bioconda
pbmm2                     1.13.1               h9ee0642_0    bioconda
pbpigeon                  1.0.0                hdfd78af_0    bioconda
xz                        5.2.10               h5eee18b_1
zlib                      1.2.13               h5eee18b_0
```

**Describe the bug**

> My data is `segmented.bam` file from the MAS-Seq bulk Iso-Seq & Revio platform. (HiFi reads that have segmented using skera)
> 
> I processed this data as follows:
```
lima segmented.bam IsoSeq_v2_primers_12.fasta fl.bam --isoseq --peek-guess --overwrite-biosample-names
isoseq refine fl.IsoSeqX_${barcode}_5p--IsoSeqX_3p.bam IsoSeq_v2_primers_12.fasta flnc.bam --require-polya
isoseq cluster2 flnc.bam clustered.bam
pbmm2 align --preset ISOSEQ --sort clustered.bam hg38.mmi mapped.bam
isoseq collapse --do-not-collpase-extra-5exons mapped.bam clustered.bam collpase.gff --log-file collapse.log
```
> Error from this command
> `isoseq collapse --do-not-collapse-extra-5exons mapped.bam clustered.bam collapse.gff --log-file collapse.log` 
> 
> I've processed other standard Iso-seq data & single-cell MAS-ISOseq data that didn't have any error in the collpase step.
> I have no idea what part in the bam file has length of CCS read information. 

**Error message**

>|> 20240206 23:16:19.973 -|- FATAL -|- operator() -|- 0x7f12a26dcd40|| -|- Could not find length of CCS read m84172_240116_125246_s3/63967683/ccs/9075_13738
>|> 20240206 23:16:20.451 -|- FATAL -|- Run -|- 0x7f12a26dcd40|| -|- isoseq collapse ERROR: std::exception

**Comment by Hyeyeonggg** [comment]
I omitted `flnc.bam` which is the optional input in `isoseq collapse` command.
This made the command complete. 
But I want to know the resolution of the above issue with `flnc.bam` file !

Thank you.

**Comment by Hyeyeonggg** [comment]
I should use `flnc.bam` from `isoseq refine` instead of `clustered.bam` from `isoseq cluster2`.

**Comment by bio-tombow** [comment]
hi, I have two questions. 1: How to determine the barcode file? I currently choose the following: 
>NEB_5p
GCAATGAAGTCGCAGGGTTGGG
>Clontech_5p
AAGCAGTGGTATCAACGCAGAGTACATGGGG
>NEB_Clontech_3p
GTACTCTGCGTTGATACCACTGCTT
Then I run this command to remove the barcode, lima segmented.bam primer.fasta fl.bam --isoseq --peek-guess, the bam file size. The size of the bam file has been reduced from 130Mb (ccs.bam) to 22Mb (Clontech_5p--NEB_Clontech_3p.bam). Does this mean that barcodes are the majority? Is this normal? In addition, after I refine (isoseq refine Clontech_5p--NEB_Clontech_3p.bam primers.fasta alz.flnc.bam) and cluster (isoseq cluster alz.flnc.bam clustered.bam --verbose --use-qvs), my file only has 2600 sequences (only ~2Mb). Is this normal? I am working on a plant genome, which has 30,000 genes.

**Comment by armintoepfer** [comment]
This is a closed issue and your issue is not a technical problem with our binaries on bioconda. Please reach out to PacBio's official support.
