### ISSUE TITLE
Lima execution seems unexpectedly slow on MASseq run

### ISSUE THREAD

**Issue by cyrilcros** [PacificBiosciences/pbbioconda#649]
**Operating system**
Nextflow 23.10.11.5893 on a SLURM cluster, `${task.cpus}`=128 cpu / 128GB RAM resource request which lands on nodes with a single Epyc9754.

**Package name** / **Conda environment**
Lima 2.9.0 - I use `conda ='bioconda::lima=2.9.0'` in  my `nextflow.config` so the environment will really just have that.

**Describe the bug**
Lima with the `--isoseq` mode looks like it processes 40,000 reads /min
The [reported speed](https://lima.how/faq/Speed.html) in the lima documentation is much faster, and I am using a high core count / good CPU.
`htop`  shows many suspended threads and a single one really running. I also feel this was not the case in previous versions? I am
exceeding the wall time limit when my previous runs on the same data in December were finishing faster.

`    lima hifi_reads_skera.bam primers.fasta hifi_reads.fl.bam --isoseq --log-level INFO --num-threads ${task.cpus}
`

**Error message**
No error message

**To Reproduce**
See https://isoseq.how/umi/tertiary-analysis.html, demo data is present at  https://downloads.pacbcloud.com/public/dataset/MAS-Seq/

**Expected behavior**
Lima properly uses all the cores it has.

**Comment by armintoepfer** [comment]
Maybe you are limited by IO?

You can also try to set this `export PB_BAMREADER_THREADS=12`

**Comment by cyrilcros** [comment]
Hi, I think you are absolutely right. We added some new nodes to our cluster in December where my jobs are mostly landing. I am also seeing a slow down when checking out the workflow version I used back then.
