### ISSUE TITLE
Question on Quantification & Differential Expression Workflow

### ISSUE THREAD

**Issue by MGordon09** [PacificBiosciences/pbbioconda#650]
**Operating system**
```
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

**Package name**
`isoseq collapse2`

**Conda environment**
```
  Name    Version  Build       Channel 
─────────────────────────────────────────
  isoseq  4.0.0    h9ee0642_0  bioconda
```

**Describe the bug**
I have a general question on IsoSeq workflow. I have virus-infected cells with 3 viral variants (and  reps for each condition) I want to look at differential expression of viral transcripts in addition to host transcript isoform analysis. My question is should I skip the `isoseq3 cluster` for viral DEA and align `flnc.bam` directly to reference?

**Error message**
NA

**To Reproduce**
```
lima
isoseq 
isoseq3 refinement
isoseq3 cluster (??)
pbmm2
```
**Expected behavior**
Bam file with aligned transcripts for `stringTie2` input

**Comment by armintoepfer** [comment]
Please reach out to support@pacb.com, as we can only help you with technical issues. Thank you.
