### ISSUE TITLE
pigeon make-seurat : cell count is different from the result from isoseq correct

### ISSUE THREAD

**Issue by Hyeyeonggg** [PacificBiosciences/pbbioconda#652]
My data is from single cell MAS-IsoSeq.

After cell calling with default knee method, the count of real cell was 1600.
So I used the percentile method with 99 and got 3200 cells.
But after `pigeon make-seurat` and making SeuratObject, I found the cell count 10700.

With the knee method, SeuratObject also has 1600 cells.
With the percentile 98, SeuratObject has 11000 cells same with the output of `isoseq correct`.

I did the same command on above all examples.

I want to know why this discrepancy came from only in 99 percentile method.

Thank you.

**Comment by Hyeyeonggg** [comment]
For this issue, i tried to find where the difference generated.

I believe that `isoseq groupdedup` execution uses `rc` tag in BAM files from `isoseq correct` step. 

I checked the cells having `rc:i:1` which means predicted real cells in `corrected.bam` file generating from `isoseq correct`. 
--> 10747
But bcstats.tsv from `isoseq bcstats` with input file as `corrected.bam` showed the real cell --> 3225

The other sample: 8497 vs 8686

Does bcstats.tsv filter more when deciding the real cells?

**Comment by armintoepfer** [comment]
Please reach out to support@pacb.com, as we can only help you with technical issues. Thank you.
