### ISSUE TITLE
Where can I find pbsv source code?

### ISSUE THREAD

**Issue by tillea** [PacificBiosciences/pbbioconda#653]
**Operating system**
Debian GNU Linux

**Package name**
I do not have any problem with conda but would like to package pbsv for Debian from source.  While the LICENSE is specified as [BSD-3-Clause](https://github.com/PacificBiosciences/pbsv/blob/master/LICENSE) the repository does not contain the source code.

**Describe the bug**
Please provide the source code for `pbsv`

Thanks a lot, Andreas.

**Comment by armintoepfer** [comment]
We are not planning on releasing the source code for `pbsv`.

**Comment by tillea** [comment]
So the license statement applies only to the data you provide for `pbsv`?  That's a shame since in Debian we would like to provide a decent Free Software base for Bioinformatics research.  Usually researchers are keen on looking at the source code to see what is happening with data.  Moreover we are building for different hardware architectures and specifically arm64 might become relevant for recent hardware from Apple.
