### ISSUE TITLE
pbfusion::bam_scanner unknown data type in input

### ISSUE THREAD

**Issue by shizhuoxing** [PacificBiosciences/pbbioconda#655]
Dear developers,

I've been using pbfusion for fusion gene detection, and I encountered an issue with version v0.4.0. The error message is:
[2024-02-18T09:44:19.827Z ERROR pbfusion::bam_scanner] Unknown data type in input ["s1.hifi.Transcript.fastq.bam"]

Here are the commands I used:
pbmm2 align genome.fa s1.hifi.Transcript.fastq.gz s1.hifi.Transcript.fastq.bam --preset ISOSEQ --sort -j 40 -J 40
pbfusion discover --gtf refdata-gex-GRCh38-2020-A.gtf.bin --output-prefix s1.hifi --threads 40 -b s1.hifi.Transcript.fastq.bam

Thank you and look foward to your reply.

- ShiZ

**Comment by velociroger-pb** [comment]
Can you post the output of `samtools view -H s1.hifi.Transcript.fastq.bam` please?

**Comment by shizhuoxing** [comment]
The simplifyed output of samtools view -H s1.hifi.Transcript.fastq.bam was list at below:

![image](https://github.com/PacificBiosciences/pbbioconda/assets/17041305/6999281f-0a29-4122-b506-987e2c90bf3b)
![image](https://github.com/PacificBiosciences/pbbioconda/assets/17041305/54e1393f-8024-4e5a-9e54-984b82c61497)

**Comment by velociroger-pb** [comment]
Can you post a couple of reads for us to check?

**Comment by shizhuoxing** [comment]
Sure, i have upload a test file on here.
[test.sam.gz](https://github.com/PacificBiosciences/pbbioconda/files/14479367/test.sam.gz)

**Comment by velociroger-pb** [comment]
To me it looks like the read type is incorrect and that your bam file is malformatted. You can read about our bam spec [here](https://pacbiofileformats.readthedocs.io/en/13.0/BAM.html)
