### ISSUE TITLE
pbfusion error

### ISSUE THREAD

**Issue by DongTang91** [PacificBiosciences/pbbioconda#657]
Hi :
    when  i run  pbfusion ,i got a  error ：
`thread 'main' panicked at 'Error: cowardly refusing to overwrite binary output file.', src/bin/pbfusion.rs:84:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

software version
`conda install pbfusion=v0.4.0`

command ：
`/pbfusion gff-cache --gtf GRCm39.gtf -b GRCm39.gtf.bin`
 
How can I solve this problem。

**Comment by velociroger-pb** [comment]
If you've previously made your cached gtf, you'll need to delete it before re-making it
