### ISSUE TITLE
Include polyA peaks as an input for pigeon classify

### ISSUE THREAD

**Issue by MengjunWu** [PacificBiosciences/pbbioconda#659]
Hi,

I was wondering if you could include polyA peaks as an input for pigeon classify, currently there is only --poly-a option which only takes polyA motifs. The Squanti3 only has the option to include polyA peaks by '--polyA_peak".  In addition, is it possible to have flexible options which are compatible with Squanti3 input options such as "--phyloP_bed ", given the output from pigeon classify actually has the phylop column.

Many thanks,
Mengjun

**Comment by armintoepfer** [comment]
Thank you for posting. We might take this into consideration, but the feature list for this year is already quite full. I've put it into our backlog.
