### ISSUE TITLE
unable to run on mac

### ISSUE THREAD

**Issue by proukakis** [PacificBiosciences/pbbioconda#661]
**Operating system**
Mac 12.6

**Package name**
pbmm2 latest version via conda

**Conda environment**
pbmm2                     1.7.0                h9d1909e_1    bioconda
python                    3.8.3                h26836e1_1  
(does it need 2.7? have also tried it in this, same results)

**Describe the bug**
$ pbmm2 align ref.mmi reads.bam aligned.bam

(from Revio)

**Error message**
>|> 20240313 22:42:54.640 -|- FATAL -|- CheckPositionalArgs -|- 0x2045c9600|| -|- pbmm2 align ERROR: Could not determine read input type(s). Please do not mix data types, such as BAM+FASTQ. File of files may only contain BAMs or datasets.

thanks

**Comment by tanyasarkjain** [comment]
Having the same issue

**Comment by armintoepfer** [comment]
This list will tell you MacOS compatibility https://github.com/PacificBiosciences/pbbioconda?tab=readme-ov-file#packages
