### ISSUE TITLE
Help for " FATAL | ccs ERROR: map::at" using ccs

### ISSUE THREAD

**Issue by yuan102379** [PacificBiosciences/pbbioconda#663]
Hi，

Thanks for your outstanding software for Hifi data analysis. However, I meet with a problem when generating Hifi reads (ccs reads) from subreads using ccs software.

**command**: 
ccs m84178_231122_121702_s4.hifi_reads.bc1015.bam m84178_231122_121702_s4.hifi_reads.bc1015.hifi.bam
| 20240319 13:08:26.744 | FATAL | ccs ERROR: map::at

The version of ccs software is 6.4.0, and the index of bam file has been constructed by pbindex tool.

**samtools view -H m84178_231122_121702_s4.hifi_reads.bc1015.bam**
@HD     VN:1.6  SO:unknown      pb:5.0.0
@RG     ID:a3226f14/105--105    PL:PACBIO       DS:READTYPE=CCS;Ipd:Frames=ip;PulseWidth:Frames=pw;BINDINGKIT=102-739-100;SEQUENCINGKIT=102-118-800;BASECALLERVERSION=5.0;FRAMERATEHZ=100.000000;BarcodeFile=metadata/m84178_231122_121702_s4.barcodes.fasta;BarcodeHash=e7c4279103df8c8de7036efdbdca9008;BarcodeCount=113;BarcodeMode=Symmetric;BarcodeQuality=Score LB:ZYR-JMH-PBM20230165  PU:m84178_231122_121702_s4     SM:20231122_PBL2301349  PM:REVIO        BC:AGAGAGATCGCATGACACGTGTGTT    CM:R/P1-C1/5.0-25M
@PG     ID:ccs  PN:ccs  VN:7.0.0 (commit v7.0.0)        DS:Generate circular consensus sequences (ccs) from subreads.   CL:/opt/pacbio/tag-ccs-current/bin/ccs --streamed --log-level INFO --stderr-json-log --kestrel-files-layout --movie-name m84178_231122_121702_s4 --log-file metadata/m84178_231122_121702_s4.ccs.log --min-rq 0.9 --non-hifi-prefix fail --knrt-ada --pbdc-model /opt/pacbio/tag-ccs-current/bin/../models/revio_v1.onnx --alarms metadata/m84178_231122_121702_s4.ccs.alarms.json
@PG     ID:lima VN:2.7.1 (commit v2.7.1-1-gf067520)     CL:/opt/pacbio/tag-lima-current/bin/lima --movie-name m84178_231122_121702_s4 --kestrel-files-layout --quality hifi --output-missing-pairs --shared-prefix --hifi-preset SYMMETRIC-ADAPTERS --store-unbarcoded --split-named --reuse-source-uuid --reuse-biosample-uuids --stderr-json-log --alarms metadata/m84178_231122_121702_s4.hifi_reads.lima.alarms.json --log-file metadata/m84178_231122_121702_s4.hifi_reads.lima.log pb_formats/m84178_231122_121702_s4.hifi_reads.consensusreadset.primrose.xml metadata/m84178_231122_121702_s4.barcodes.fasta hifi_reads/m84178_231122_121702_s4.hifi_reads.demux.bam
@PG     ID:primrose     VN:1.4.0 (commit v1.4.0)        CL:/opt/pacbio/tag-primrose-current/bin/primrose --movie-name m84178_231122_121702_s4 --kestrel-files-layout --quality hifi --reuse-source-uuid --stderr-json-log --log-file metadata/m84178_231122_121702_s4.hifi_reads.primrose.log --alarms metadata/m84178_231122_121702_s4.hifi_reads.primrose.alarms.json --keep-kinetics

Could give me some suggestions, please?

Yours, 

Yuan Tian

**Comment by armintoepfer** [comment]
Your reads are already HiFi. Enjoy.

**Comment by yuan102379** [comment]
Thanks for your response. So how can I know wether the reads is Hifi or not?

**Comment by armintoepfer** [comment]
Look at the file name. It's called hifi_reads

**Comment by yuan102379** [comment]
So, if the bam file is consisted of hifi reads, there will be a problem of "RROR: map::at" in ccs software?

**Comment by armintoepfer** [comment]
CCS generates hifi. You already have hifi.
