### ISSUE TITLE
Isoseq collapse filtering out criteria

### ISSUE THREAD

**Issue by MengjunWu** [PacificBiosciences/pbbioconda#664]
Hi,
I have some problems with isoseq collapse. While most of my reads (90%) are mapped, almost half of them are filtered out after isoseq collpase. I was wondering how do you calculate coverage and identify? I am using the mg tag to get the identity, and calculating coverage per read as number of matches and mismatches in the cigar string divided by the read length, but I get much less reads filtered out than by isoseq collapse with the same thresholds. Are either coverage or identity calculated differently?

Many thanks
Mengjun

**Comment by armintoepfer** [comment]
Assigning to @jmattick

**Comment by jmattick** [comment]
Hi @MengjunWu, 
`collapse` filters based on the following:
1. Read is mapped 
2. Read is a primary alignment
3. Read meets the minimum coverage (aligned end - aligned start) / (read length)
5. Read meets the minimum identity (matches / (matches + mis-matches + inserted bases + deleted bases)
6. Optional: If using single-cell workflow, read must be marked as coming from a real cell using the `rc` tag. 

These minimum values can be changed using the following options. 
```
Alignment Filter Options:
  --min-aln-coverage              FLOAT  Ignore alignments with less than minimum query read coverage. [0.99]
  --min-aln-identity              FLOAT  Ignore alignments with less than minimum alignment identity. [0.95]
```
