### ISSUE TITLE
pbfusion

### ISSUE THREAD

**Issue by tky199996** [PacificBiosciences/pbbioconda#665]
Hello, when I run pbfusion's sample file, pbfusion gff-cache --gtf gencode.v38.annotation.gtf, it works fine. But when I want to run the Gal6a version of the gtf file, the following error occurs:
thread 'main' panicked at 'Missing feature annotation 'gene_name'', src/annotation.rs:468:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
What went wrong and how do I fix it?

**Comment by tky199996** [comment]
> 您好，当我运行 pbfusion 的示例文件 pbfusion gff-cache --gtf gencode.v38.annotation.gtf 时，它工作正常。但是当我想运行 gtf 文件的 Gal6a 版本时，会出现以下错误： thread 'main'paniced at 'Missing feature comment 'gene_name'', src/annotation.rs:468:28 note: run `RUST_BACKTRACE=1`withenvironment variable to显示回溯 出了什么问题以及如何修复它？
My gtf file is a comment file about the gal6a version of Red Jungle Fowl

**Comment by zeeev** [comment]
Hi @tky199996 ,

Check if the GTF contains features that are lacking a gene_name field. Pbfusion requires that each feature contain a gene name. You can remove those entries and it should work.

**Comment by tky199996** [comment]
> 你好@tky199996,
> 
> 检查 GTF 是否包含缺少gene_name 字段的功能。Pbfusion 要求每个特征都包含一个基因名称。您可以删除这些条目，它应该可以工作。

Thank you for your quick reply, in fact I don't understand how to check, my gtf file is the reference genome of red jungle fowl downloaded from ensembl without any modifications, can you tell me what should I do? Thank you again

**Comment by tky199996** [comment]
> 你好@tky199996,
> 
> 检查 GTF 是否包含缺少gene_name 字段的功能。Pbfusion 要求每个特征都包含一个基因名称。您可以删除这些条目，它应该可以工作。
Thanks, I got it, I will try and do it again, thank you very much

**Comment by tky199996** [comment]
> > 你好@tky199996,
> > 检查 GTF 是否包含缺少gene_name 字段的功能。Pbfusion 要求每个特征都包含一个基因名称。您可以删除这些条目，它应该可以工作。
> 
> Thank you for your quick reply. I downloaded the visual py script in your repository locally. When running the script using python3, the following error occurred. What went wrong?

**Comment by zeeev** [comment]
Can you send a few hundred lines of the GTF file so I can take a look. The error is telling me that there's a missing field called "gene_name", you can probably just add that entry, by coping ID or some other unique identifier.

**Comment by tky199996** [comment]
> Can you send a few hundred lines of the GTF file so I can take a look? The error is telling me that there's a missing field called "gene_name", you can probably just add that entry, by coping ID or some other unique identifier.

![1](https://github.com/PacificBiosciences/pbbioconda/assets/120616828/1ecba2d4-0d3b-459f-b7a6-e42fc0a93051)
![2](https://github.com/PacificBiosciences/pbbioconda/assets/120616828/3ed99988-5694-4a6b-a499-9bcbab36d40e)
Hello, I deleted the gtf file that lacked 'gene name' according to the method you mentioned before. I can run pbfusion gff-cache normally, but an error occurred when using the script for visualization.
Traceback (most recent call last):
  File "/home/tianky/full-length-transcript/FL_denovo20230616/33.rna_classification/33.heart/funsion/visualize_fusion.py", line 231, in <module>
    main(args)
  File "/home/tianky/full-length-transcript/FL_denovo20230616/33.rna_classification/33.heart/funsion/visualize_fusion.py", line 227, in main
    plot_fusion(ref_genes, alignments, breakpoints, args.output)
  File "/home/tianky/full-length-transcript/FL_denovo20230616/33.rna_classification/33.heart/funsion/visualize_fusion.py", line 128, in plot_fusion
    gene1_start = min([x[0][1][0][0] for x in list(alignments.values()) if x[0][0] == breakpoints[0][0]])
ValueError: min() arg is an empty sequence

**Comment by tky199996** [comment]
> Can you send a few hundred lines of the GTF file so I can take a look? The error is telling me that there's a missing field called "gene_name", you can probably just add that entry, by coping ID or some other unique identifier.
Hello, this is my bam file after alignment using pbmm2. Do I need to delete the first few lines?
![新](https://github.com/PacificBiosciences/pbbioconda/assets/120616828/5510aa6b-6e94-422e-b819-3ed083540b03)

**Comment by zeeev** [comment]
Hi @tky199996,

I'm going to close out this issue. I see you were able to run pbufsion successfully. There is a ticket open for the other issue you described: https://github.com/PacificBiosciences/pbbioconda/issues/660

Did you find any biologically meaningful fusion genes?

**Comment by tky199996** [comment]
> 你好@tky199996,
> 
> 我要结束这个问题了。我看到您能够成功运行 pbufsion。您描述的其他问题有一张票：#660
> 
> 您是否发现了任何具有生物学意义的融合基因？
Hello, I have found the fusion gene and just want to visualize it. I wonder if you have fixed the visualization problem? If you release a new version, I hope to try to visualize the fusion gene. Thank you for your help. At least I have found the fusion gene. Your software has helped me a lot. Thank you again.

**Comment by zeeev** [comment]
Can you please post your comments to this thread, where we're addressing the issue: https://github.com/PacificBiosciences/pbbioconda/issues/660
