### ISSUE TITLE
Convert FASTQ in unaligned BAM

### ISSUE THREAD

**Issue by meryyr** [PacificBiosciences/pbbioconda#668]
Hi,
I'm trying to extract HiFi reads from ccs data. The problem I have is that these ccs data were uploaded in fasta and fastq format on the SRA, and not as BAM files (unaligned BAM). Therefore, the extracthifi command does not work for the extraction of HiFi from ccs.
I saw that there is a bam2fastx converter provided by PacBio, so I was wondering if there is a tool or if there is something I can do to convert the fastq files that I have in BAM files. 

Just to be clear, the fastq file that I have now looks something like this: 
@read_name length=... 
CAATGAAGTCGCAGGGTTGGGGTGGCATTGGAACCCAGTTCTGCCCAGCCCCCAGGAGCCCTTGACATAGCAACATGCTTCCCTAAAGGAGAAAAAAAAATG
+read_name length=....
~~~~~~~~~~~~~~~~|~}~~~~~~~~~~~~~~~~~~~~~~~~]~~~~T~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~z~~~~~~v~~~N~~~


Thank you for your help!

**Comment by armintoepfer** [comment]
We don't support that use case, sorry.
