### ISSUE TITLE
hifihla call-reads: thread 'main' panicked at src/cli/callreads_cli.rs:320:14:

### ISSUE THREAD

**Issue by hhuili** [PacificBiosciences/pbbioconda#669]
**Operating system**
LSB Version: :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description: CentOS Linux release 7.9.2009 (Core)
Release: 7.9.2009
Codename: Core

**Package name**
hifihla v0.3.0

**Conda environment**
Name	Version	BuildChannel
_libgcc_mutex	0.1	conda_forge	https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
_openmp_mutex	4.5	2_gnu	https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
hifihla	0.3.0	hdfd78af_0	bioconda
libgcc-ng	13.2.0	h807b86a_5	https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libgomp	13.2.0	h807b86a_5	https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libstdcxx-ng	13.2.0	h7e041cc_5	https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib	1.2.13	hd590300_5	https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
meryl	1.4.1	h4ac6f70_0	https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
pbtk	3.1.1	h9ee0642_0	bioconda
winnowmap	2.03	h43eeafb_2	bioconda

**Describe the bug**
I used `hifihla call-reads` to call HLA loci from an aligned BAM of HiFi reads. My data were shorter (~5kb) Target Enrichment HiFi Reads. HiFi reads were aligned to `GRCh38/T2T` using `minimap2` and `Winnowmap`, but encountered the same error (see `Error message`).

**Error message**
nohup: ignoring input
thread 'main' panicked at src/cli/callreads_cli.rs:320:14:
bad fetch: Fetch
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
   3: hifihla::cli::callreads_cli::hifihla_call_reads_main
   4: hifihla::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
./02.run_hifihla.sh: line 12: 156288 Aborted                 (core dumped) $hifihla_dir/hifihla call-reads -j 8 -a $bam_dir/$sample.sort.bam --outdir ./02.hifihla
Done!

**To Reproduce**
We can send our data for testing via priviate email if it is needed.

**Comment by jrharting** [comment]
Hi!  This looks like a fetch error in htslib -- are you able to view the bam files in igv and view the data at HLA-a/b/c?  I would def be interested in checking these data out if you can share.  My email is jharting@pacb.com.  Thank you!

**Comment by jrharting** [comment]
make sure to use the grch38_notalts ref.  here is a link:
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

**Comment by jrharting** [comment]
incorrect reference
