### ISSUE TITLE
dedup

### ISSUE THREAD

**Issue by GelatinousGiant** [PacificBiosciences/pbbioconda#670]
Hi,

I am just wondering what is the approximate run time for the dedup algorithim?

I am running on 20 cores each with 50GB of ram and trying to deduplicate a bam file thats ~50GB in size but its been running for >8 hours and only outputted a file ~2GB in size so far. 

Is there way to check logs of progress on this step?

Thanks!

**Comment by armintoepfer** [comment]
You can try `--log-level INFO` or `DEBUG`, but no guarantees that it will give you an ETA
