### ISSUE TITLE
questions about pbsv

### ISSUE THREAD

**Issue by rabbitdsy** [PacificBiosciences/pbbioconda#671]
I have 180 samples, and I used “Parallel processing per chromosome” pipeline, and obtained ".svsig.gz" file for each sample.
I have tried to joint call all samples together (CHM2.0 as ref) using "pbsv call -j 40 T2T.fa T2T.sample1.*.svsig.gz T2T.sample1.vcf", but it took too long (40 cores 128 GB).
I wonder can I call SV for each sample separately, and get one-sample vcf, and then merge all vcf together?
If can, what is the differences between "separately calling and merge" vs "joint calling"?

Waiting for your suggestions, Thanks

**Comment by armintoepfer** [comment]
Hi. You can do the either. Yes it will take very long to jointly call 180 samples. It's a philosophical question about your approach that only you can answer.
