### ISSUE TITLE
Isoseq3 cluster fatal run

### ISSUE THREAD

**Issue by EglantineMB** [PacificBiosciences/pbbioconda#672]
**Package name**
isoseq3 

**Conda environment**
isoseq3

**Describe the bug**
isoseq3 cluster stops with fatal error

**Error message**
20240405 08:10:23.800 -|- FATAL -|- Run -|- 0x2b27eb67d980|| -|- isoseq cluster ERROR: map::at

**To Reproduce**
from flnc file provided by sequencing center:

isoseq3 cluster flnc-1.bam test.bam 

**Expected behavior**
I would have expected to obtain a set of clustered isoforms called test.bam

**Comment by armintoepfer** [comment]
Can you please provide an example to reproduce
