### ISSUE TITLE
Demultiplexing using lima

### ISSUE THREAD

**Issue by Nitin123-4** [PacificBiosciences/pbbioconda#674]
Hi team I have:  Kinnex run bam, these are the segmented reads in bam file.

For demultiplexing, the barcoded cDNA amplification primers we used are:

SAMP102-001:
>IsoSeqX_bc01_5p
CTACACGACGCTCTTCCGATCTACTACACGCAATGAAGTCGCAGGGTTGGG
>IsoSeqX_3p
AAGCAGTGGTATCAACGCAGAGTAC

SAMP102-002:
>IsoSeqX_bc02_5p
CTACACGACGCTCTTCCGATCTACTAGTAGCAATGAAGTCGCAGGGTTGGG
>IsoSeqX_3p
AAGCAGTGGTATCAACGCAGAGTAC

For demultiplexing can I use:

lima --isoseq --dump-clips --peek-guess -j 24 FILE-segmentedreads.bam SAMP102-001.cDNA_amplification_primers.fasta SAMP102-001.demult.bam
lima --isoseq --dump-clips --peek-guess -j 24 FILE-segmentedreads.bam SAMP102-002.cDNA_amplification_primers.fasta SAMP102-002.demult.bam

OR I need to create one _primers.fasta where I can give info as:

>SAMP102-001_5p
CTACACGACGCTCTTCCGATCTACTACACGCAATGAAGTCGCAGGGTTGGG
>SAMP102-002_5p
CTACACGACGCTCTTCCGATCTACTAGTAGCAATGAAGTCGCAGGGTTGGG
>primer_3p
AAGCAGTGGTATCAACGCAGAGTAC

and then run:

lima --isoseq --dump-clips --peek-guess -j 24 FILE-segmentedreads.bam primers.demux.fasta 

Please suggest.

**Comment by armintoepfer** [comment]
You combine them and run demux once

**Comment by Nitin123-4** [comment]
When I combine them and run I can see reads are distributed for both of them, but when I am doing it one at at time looks like almost all the reads are going in both the samples.

Thanks.
