### ISSUE TITLE
The *.flnc_count.txt output from isoseq collapse does not generate columns for multiple samples

### ISSUE THREAD

**Issue by YanqingHuang01** [PacificBiosciences/pbbioconda#676]
I followed the steps in this page: 
https://isoseq.how/clustering/examples.html for multiplexed samples. 

Demux and primer removal
$ lima --isoseq --peek-guess *.hifi_reads.bam IsoSeq_v2_primers_12.fasta output.bam

Combine inputs
$ ls output.IsoSeqX*bam > all.fofn

 Remove poly(A) tails and concatemer
$ isoseq refine all.fofn IsoSeq_v2_primers_12.fasta flnc.bam --require-polya

Cluster2
$ isoseq cluster2 flnc.bam clustered.bam

Mapping
$pbmm2 align --preset ISOSEQ --sort <clustered.bam> <ref.fa> <mapped.bam>

Collapse
$isoseq collapse --do-not-collapse-extra-5exons <mapped.bam> <flnc.bam> <collapsed.gff>

However, the output file *.flnc_count.txt doesn't contain columns for multiple samples. It only generates a column labeled 'BioSample_1' instead of the expected layout:

  id	BioSample1	BioSample2
  PB.1.1	2	2
  PB.2.1	1	2
  PB.3.1	1	1

**Comment by jmattick** [comment]
Hi @YanqingHuang01. Thanks for catching an issue with our docs. The example is missing the `--overwrite-biosample-names` option on the cDNA demux step. 

https://isoseq.how/clustering/cli-workflow.html#step-2---primer-removal-and-demultiplexing

**Comment by aindap** [comment]
Hi @jmattick  -

I have a similar question. The CRO I work with returned me individual flnc bam files. I write them a file of filenames:

```
ls flnc.*.bam > flnc_fofn.txt
```

Then I run cluster2:

```
isoseq cluster2 $fofn clustered.bam
```

Then pbmm2 align:

```
pbmm2 align \\
        --sort \\
        -j $threads \\
        -J $sort_threads \\
        --preset ISOSEQ \\
       
        --log-level INFO \\
        --unmapped \\
        --bam-index BAI \\
        $reference \\
        $clustered_bam \\
      mapped.bam
```

But then how to provide the flnc.bam to collapse if the upstream steps of cluster2 and pbmm2 used fofn file listing multiple flnc bam?

**Comment by XiaoyuZhan520** [comment]
Same question as @aindap
