### ISSUE TITLE
Error while running Falcon

### ISSUE THREAD

**Issue by ptamamang24** [PacificBiosciences/pbbioconda#678]
I am using WSL2  in Windows 11. I running Falcon assembler for pacbio long-reads (CLR). I have attached my config and error log file. Can you please help to sort out this issue? TIA.

[fc_run_fungal.txt](https://github.com/PacificBiosciences/pbbioconda/files/15029817/fc_run_fungal.txt)

[log file.txt](https://github.com/PacificBiosciences/pbbioconda/files/15029800/log.file.txt)

**Comment by gconcepcion** [comment]
Falcon is no longer supported, and I can ensure that you will have a difficult time running in Windows 11  WSL2. Not impossible, but it's never been tested internally and I'm reasonably sure you will hit some snags at some point.

But for your first question - you might want to start with this thread:
[Exception: Some tasks are recently_done but not satisfied: {Node(0-rawreads/tan-split)}
](https://github.com/PacificBiosciences/FALCON/issues/674)
