### ISSUE TITLE
Cannot download Iso-Seq example data

### ISSUE THREAD

**Issue by ianyfchang** [PacificBiosciences/pbbioconda#679]
**Error message**
Cannot download example files listed in https://isoseq.how/umi/examples.html

The requested URL /public/dataset/IsoSeq_sandbox/2022_pbmc_singlecell_mini/ccs.bam.pbi was not found on this server.

Thank your

**Comment by zeeev** [comment]
cc @Magdoll

**Comment by Magdoll** [comment]
Hi @ianyfchang  sorry the dataset has been moved to 
https://downloads.pacbcloud.com/public/dataset/Kinnex-single-cell-RNA/TUTORIAL-DATA-PBMC-single-cell-mini/
please download from here!
