### ISSUE TITLE
unexpected keyword argument 'radius'

### ISSUE THREAD

**Issue by hermeseduardo** [PacificBiosciences/pbbioconda#68]
**Operating system**
UNIX cluster

**Package name**
```
**Conda environment**
# packages in environment at /apps/miniconda3/4.3.24:
#
asn1crypto                0.22.0                   py35_0
biopython                 1.70                np112py35_1    bioconda
bzip2                     1.0.6                         3
cairo                     1.14.8                        0
cairocffi                 0.7.2                    py35_1    conda-forge
cairosvg                  2.0.0rc6                 py35_0    conda-forge
certifi                   2016.2.28                py35_0
cffi                      1.10.0                   py35_0
conda                     4.3.25                   py35_0
conda-env                 2.6.0                         0
cryptography              1.8.1                    py35_0
cssselect                 1.0.1                    py35_0
fontconfig                2.12.1                        3
freetype                  2.5.5                         2
gatk                      3.8                      py35_0    bioconda
gitdb2                    2.0.0                    py35_0
gitpython                 2.1.3                    py35_0
idna                      2.6                      py35_0
jbig                      2.1                           0
jpeg                      9b                            0
libffi                    3.2.1                         1
libiconv                  1.14                          0
libpng                    1.6.30                        1
libtiff                   4.0.6                         3
libxml2                   2.9.4                         0
libxslt                   1.1.29                        0
lxml                      3.8.0                    py35_0
mkl                       2017.0.3                      0
mmtf-python               1.0.2                    py35_0    bioconda
msgpack-python            0.4.8                    py35_0
numpy                     1.12.1                   py35_0
olefile                   0.44                     py35_0
openjdk                   8.0.121                       1
openssl                   1.0.2l                        0
packaging                 16.8                     py35_0
pandas                    0.20.3                   py35_0
pillow                    4.2.1                    py35_0
pip                       9.0.1                    py35_1
pixman                    0.34.0                        0
pycosat                   0.6.2                    py35_0
pycparser                 2.18                     py35_0
pyopenssl                 17.0.0                   py35_0
pyparsing                 2.2.0                    py35_0
python                    3.5.4                         0
python-dateutil           2.3                      py35_0    bioconda
pytz                      2017.2                   py35_0
pyvcf                     0.6.8                    py35_0    bioconda
readline                  6.2                           2
regex                     2016.06.24               py35_1    bioconda
reportlab                 3.4.0                    py35_0
requests                  2.14.2                   py35_0
ruamel_yaml               0.11.14                  py35_1
setuptools                36.4.0                   py35_0
six                       1.10.0                   py35_0
smmap2                    2.0.1                    py35_0
sqlite                    3.13.0                        0
tinycss                   0.4                      py35_0    conda-forge
tk                        8.5.18                        0
wheel                     0.29.0                   py35_0
xlrd                      1.1.0                    py35_0
xlsxwriter                0.9.8                    py35_0
xvfbwrapper               0.2.9                    py35_0    conda-forge
xz                        5.2.2                         1
yaml                      0.1.6                         0
zlib                      1.2.8                         3
`````

**Describe the bug**

**Error message**
```py
Traceback (most recent call last):
  File "/apps/miniconda3/4.3.24/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/apps/miniconda3/4.3.24/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1600, in <module>
    main(sys.argv)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1596, in main
    ovlp_to_graph(args)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1418, in ovlp_to_graph
    ug2 = identify_spurs(ug, u_edge_data, 50000)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1171, in identify_spurs
    n_ego_graph = nx.ego_graph(ug2, n, radius=10)
TypeError: ego_graph() got an unexpected keyword argument 'radius'
```

**Comment by hermeseduardo** [comment]
Any suggestion regarding this issue?

**Comment by isovic** [comment]
Hi @hermeseduardo ,
Looking at the list of packages in your Conda environment, I can't find the `networkx` package.
Can you verify that you have it installed?
Also, which version?
At first I thought there might have been an API change between different versions, but I just looked at the docs of NetworkX and I don't think that's the case. Would be good to have the version info in any case.
Best regards,
Ivan.

**Comment by pb-cdunn** [comment]
Your conda-env is also missing `pb-falcon` and `pb-assembly`. Try reinstalling miniconda, then `conda install pb-assembly; condate update --all`.

(But use a different conda environment if you start over. Conda currently has a big problem with `openssl` that you might run into, and we can't do much about that.)

**Comment by hermeseduardo** [comment]
Thanks you, we tried to reinstall miniconda but got the following:

> conda install pb-assembly
Fetching package metadata .................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - pb-assembly -> genomicconsensus -> pbcommand >=1.1.1 -> python >=2.7,<2.8.0a0
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by hermeseduardo** [comment]
We were able to install re-instl and update but still get: TypeError: ego_graph() got an unexpected keyword argument 'radius

This is a list of applications and version numbers provided when we run a conda update –all:

asn1crypto                0.24.0                   py27_0
avro-python2              1.8.2                      py_1    bioconda
bcftools                  1.9                  h47928c2_1    bioconda
bedtools                  2.27.1               he860b03_3    bioconda
blas                      1.0                         mkl
blasr                     5.3.2                hac9d22c_4    bioconda
blasr_libcpp              5.3.1                hac9d22c_3    bioconda
bwa                       0.7.17               h84994c4_4    bioconda
bzip2                     1.0.6                h14c3975_5
ca-certificates           2019.1.23                     0
certifi                   2018.11.29               py27_0
cffi                      1.11.5           py27he75722e_1
chardet                   3.0.4                    py27_1
cryptography              2.5              py27h1ba5d50_0
curl                      7.63.0            hbc83047_1000
cython                    0.29.4           py27he6710b0_0
decorator                 4.3.2                    py27_0
enum34                    1.1.6                    py27_1
future                    0.17.1                   py27_0
genomicconsensus          2.3.2                    py27_3    bioconda
h5py                      2.8.0            py27h989c5e5_3
hdf5                      1.10.2               hba1933b_1
htslib                    1.9                  h47928c2_5    bioconda
idna                      2.8                      py27_0
intel-openmp              2019.1                      144
ipaddress                 1.0.22                   py27_0
iso8601                   0.1.12                   py27_1
krb5                      1.16.1               h173b8e3_7
libcurl                   7.63.0            h20c2e04_1000
libdeflate                1.0                  h14c3975_1    bioconda
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran-ng            7.3.0                hdf63c60_0
libssh2                   1.8.0                h1ba5d50_4
libstdcxx-ng              8.2.0                hdf63c60_1
linecache2                1.0.0                    py27_0
minimap2                  2.15                 h84994c4_1    bioconda
mkl                       2019.1                      144
mkl_fft                   1.0.10           py27ha843d7b_0
mkl_random                1.0.2            py27hd81dba3_0
mummer4                   4.0.0beta2      pl526hfc679d8_3    bioconda
ncurses                   6.1                  he6710b0_1
networkx                  2.2                      py27_1
nim-falcon                0.0.0                         0    bioconda
numpy                     1.15.4           py27h7e9f1db_0
numpy-base                1.15.4           py27hde5b4d6_0
openssl                   1.1.1a               h7b6447c_0
pb-assembly               0.0.4                    py27_3    bioconda
pb-dazzler                0.0.0                h470a237_0    bioconda
pb-falcon                 0.2.5            py27hc0aa232_3    bioconda
pbalign                   0.3.2                    py27_0    bioconda
pbbam                     0.19.0               h6678c95_1    bioconda
pbcommand                 1.1.1                    py27_2    bioconda
pbcopper                  0.4.2                h02d93b8_0    bioconda
pbcore                    1.6.5                    py27_0    bioconda
pbmm2                     0.12.0               ha87ae23_0    bioconda
perl                      5.26.2               h14c3975_0
pip                       19.0.1                   py27_0
pycparser                 2.19                     py27_0
pyopenssl                 19.0.0                   py27_0
pysam                     0.15.2           py27h1671916_1    bioconda
pysocks                   1.6.8                    py27_0
python                    2.7.15               h9bab390_6
python-consensuscore      1.1.1            py27h02d93b8_2    bioconda
python-consensuscore2     3.1.0                    py27_2    bioconda
python-edlib              1.2.3.post1      py27h470a237_0    bioconda
python-intervaltree       3.0.2                      py_0    bioconda
python-msgpack            0.5.6            py27h470a237_0    bioconda
python-sortedcontainers   2.1.0                      py_0    bioconda
pytz                      2018.9                   py27_0
readline                  7.0                  h7b6447c_5
requests                  2.21.0                   py27_0
samtools                  1.9                  h91753b0_5    bioconda
setuptools                40.7.3                   py27_0
six                       1.12.0                   py27_0
sqlite                    3.26.0               h7b6447c_0
tk                        8.6.8                hbc83047_0
traceback2                1.4.0                    py27_0
unittest2                 1.1.0                    py27_0
urllib3                   1.24.1                   py27_0
wheel                     0.32.3                   py27_0
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               h7b6447c_3

**Comment by hermeseduardo** [comment]
We ran it from the scratch but still got the same issue:

# Given preads.ovl,
# write sg_edges_list, c_path, utg_data, ctg_paths.
time python -m falcon_kit.mains.ovlp_to_graph  --min-len 500 --overlap-file preads.ovl >| fc_ovlp_to_graph.log
+ python -m falcon_kit.mains.ovlp_to_graph --min-len 500 --overlap-file preads.ovl
falcon-kit 1.2.5
Traceback (most recent call last):
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1600, in <module>
    main(sys.argv)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1596, in main
    ovlp_to_graph(args)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1418, in ovlp_to_graph
    ug2 = identify_spurs(ug, u_edge_data, 50000)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/falcon_kit/mains/ovlp_to_graph.py", line 1171, in identify_spurs
    n_ego_graph = nx.ego_graph(ug2, n, radius=10)
TypeError: ego_graph() got an unexpected keyword argument 'radius'
2019-02-15 05:26:16,249 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-02-15 05:26:16,249 - root - WARNING - CD: '/flush3/esc003/Cynegetis_impunctata/2-asm-falcon' -> '/flush3/esc003/Cynegetis_impunctata/2-asm-falcon'
2019-02-15 05:26:16,250 - root - WARNING - CD: '/flush3/esc003/Cynegetis_impunctata/2-asm-falcon' -> '/flush3/esc003/Cynegetis_impunctata/2-asm-falcon'
2019-02-15 05:26:16,251 - root - CRITICAL - Error in /apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/flush3/esc003/Cynegetis_impunctata/2-asm-falcon/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/apps/miniconda3/4.3.24/envs/denovo_asm3/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
pwd
+++ pwd
++ echo 'FAILURE. Running top in /flush3/esc003/Cynegetis_impunctata/2-asm-falcon (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	3m57.593s
user	12m1.853s
sys	0m26.377s
+ finish
+ echo 'finish code: 1'

**Comment by pb-cdunn** [comment]
I don't know. We use the same networkx that you have, `networkx 2.2 py27_1`

You need to go into the directory `/flush3/esc003/Cynegetis_impunctata/2-asm-falcon` and run `bash -vex user_script.sh` yourself. From there, you should be able to copy/paste the specific command that fails, `time python -m falcon_kit.mains.ovlp_to_graph ...`

If you reproduce that, then you can debug from there. Somehow, you are using an old version of **networkx**, and you will have to track that down yourself. E.g. you might not be using the `python` that you think (try `which python`), or you might pull **networkx** from elsewhere by accident. `radius` is *definitely* legal with **networkx--2.2**.

Your earlier problem related to the use of python2 and python3 in the same environment. We do not currently support that for **pb-assembly** (for a variety of reasons, which is why we currently restrict `python` rather than `python2`). You might need to use one environment for Falcon and a different one for your other work.

**Comment by pb-cdunn** [comment]
https://github.com/PacificBiosciences/pbbioconda/pull/94/files

> Python packages require version 2.7; Python 3 is currently not supported! You cannot install PacBio packages alongside python 3-only packages in the same environment!** In order to use python 3-only packages, create a separate conda env.

**Comment by hermeseduardo** [comment]
you were right, the problem was the wrong local version of networkx. All good now!
