### ISSUE TITLE
Isoseq3 cluster2 exits without error message

### ISSUE THREAD

**Issue by sagnikbanerjee15** [PacificBiosciences/pbbioconda#685]
**Operating system**
Linux

**Package name**

isoseq 4.0.0 (commit v4.0.0)

Using:
  pbbam     : 2.4.99 (commit v2.4.0-16-g5cc6e4b)
  pbcopper  : 2.3.99 (commit v2.3.0-14-g5ac5693)
  pbmm2     : 1.11.99 (commit v1.11.0-1-g1b5a417)
  minimap2  : 2.15
  parasail  : 2.1.3
  boost     : 1.77
  htslib    : 1.17
  zlib      : 1.2.13

**Describe the bug**
Executing -->
nohup isoseq3 cluster2 --log-level TRACE --log-file $PWD/isoseq3_cluster.log --num-threads 64 $PWD/flnc_first2.fofn $PWD/first2.clustered.bam 1> $PWD/first2.clusterd.output 2> $PWD/first2.clustered.error &

Program exits without any error message but does not produce the intended results

**Error message**
No error message

**To Reproduce**
Works on small dataset. Exists without error on large datasets.

**Expected behavior**
Produce clustered transcript file

**Comment by armintoepfer** [comment]
Were you able to succeed? What are your system specs? Where in the log is it stopping?

**Comment by armintoepfer** [comment]
I'll reopen once you provide a reproducible example
