### ISSUE TITLE
Generate HiFi reads

### ISSUE THREAD

**Issue by meryyr** [PacificBiosciences/pbbioconda#687]
Hi!
What are the parameters to get HiFi reads? The minimum passes need to be at least 3 and the rq value of 0.99 ? 
Something like the code below should give me HiFi reads, is this correct ? 
`
$ccs7 --reportFile --minPasses=3 --minPredictedAccuracy=0.99 --logFile mylog.txt subreads.bam ccs.bam`

P.S.: I'm using version  7.0 of SMRT Link tools, and version 3.4.1 of ccs (the samples I'm working with use an old chemistry, so I can't use the last version of ccs)

Thank you for the help!!

**Comment by armintoepfer** [comment]
HiFi means >=Q20. In your case, the configuration is correct.
