### ISSUE TITLE
isoseq for scRNA: UMI with homopolymers are not removed

### ISSUE THREAD

**Issue by JiangyanYu** [PacificBiosciences/pbbioconda#692]
**Operating system**
Linux

**Package name**
smrtlinks v13

**Conda environment**
not used in installation

**Describe the bug**
UMI AAAAAAAAAAAA are found in the annotated.info.csv. 

**Error message**
not a program error.

**To Reproduce**
grep AAAAAAAAAAAA in annotated.info.csv

**Expected behavior**
In the 10x cellranger pipeline, molecules with homopolymers UMI are removed, might be due to low quality. Can you please explain further why these molecules are included in the isoseq pipeline? Thanks very much!

**Comment by armintoepfer** [comment]
You need to remove them on their own.
