### ISSUE TITLE
What can I do only with .fastq reads?

### ISSUE THREAD

**Issue by dudududu12138** [PacificBiosciences/pbbioconda#693]
Hi, I want to use your isoseq toolkit to detect novel isoforms from pacbio long read RNA-seq data. But I download the data from SRA dataset. And they only offer the raw reads in fastq format. There are no raw.bam. So most of your tools won't work. And there are many datasets like this. Some of them are just fastq files while some are raw bam without primers.fasta. 
My questions are:
1. So what can I do with such kind of data? 
2. Does it make sense that I transfer the reads from raw.fastq to raw.bam and then I use <isoseq cluster>? 
3. And dose the <lima> necessary if I don't have <primers.fasta> file? 
4. Is the primer generic? If the primer is not provided with the raw data, where can I get the primer from?

My aim is to detect novel isoforms from pacbio data. Thanks!

**Comment by armintoepfer** [comment]
Our software only consumes unaligned BAM input files, as each read contains important annotations through BAM tags.
