### ISSUE TITLE
isoseq groupdedup for variant analysis

### ISSUE THREAD

**Issue by gneedle1** [PacificBiosciences/pbbioconda#694]
I want to do variant calling on .bam files from Hifi data, using deepvariant. When I put .bam files that have followed the isoseq workflow to the refine step (.corrected.bam) deepvariant works, but the .bam made by groupdedup seems to remove the quality scores and wont run through deepvariant. Is groupdedup only used for isoform detection?

**Comment by armintoepfer** [comment]
Yes

**Comment by Jiayi-Wang-Joey** [comment]
Hi! I have the same problem. I am wondering if you managed to restore the quality scores for running DeepVariant? Thanks in advance!

**Comment by armintoepfer** [comment]
The tool output was not meant to be piped into DeepVariant.
