### ISSUE TITLE
What's the difference of = and X cigar of pbmm2?

### ISSUE THREAD

**Issue by leon945945** [PacificBiosciences/pbbioconda#696]
Hi, I saw that pbmm2 substitute the M cigar of minimap2 with `=` or `X` #217, and I saw that `=` and `X` present together in CIGAR field like this:
>133=1X145=1D72=1X

My question is that, `=` and `X` both represent match, what's the difference of `=` and `X`?

**Comment by leon945945** [comment]
And it seems that usually a `1` before `X`? What is that mean.

**Comment by zeeev** [comment]
Hi @leon945945,

This is addressed in the sam/bam specification: https://samtools.github.io/hts-specs/SAMv1.pdf

X's represent mismatches, whereas `=` are a match or mismatch.

**Comment by leon945945** [comment]
Thanks, it's clear.
