### ISSUE TITLE
PBSV system requirements

### ISSUE THREAD

**Issue by MKaandemir** [PacificBiosciences/pbbioconda#697]
Hello, I'm interested in optimizing CPU usage for PBSV. What would you recommend for 30X WGS HiFi data in terms of RAM and CPU resources?

**Comment by MKaandemir** [comment]
I used 8 cpu and 48 gb ram for just chromosome 1 but it took like 4 hour. Is it normal?

**Comment by armintoepfer** [comment]
Sounds about right. Modern laptops already have 8 CPU cores. Please use a reasonable sized HPC node when processing a whole human genome.

**Comment by MKaandemir** [comment]
Could you define what constitutes a reasonably sized HPC node? Despite allocating extra CPUs, the processing time hasn't decreased. I plan to use this for numerous samples, so it needs to be optimized for cost and performance. It runs on AWS Batch, so I prefer not to use machines with more than 8 CPUs for this tool.
