### ISSUE TITLE
CRAM support for more tools

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/pbbioconda#699]
Hi All,

I was pleasantly surprised to find that there is CRAM support for hiphase, and I was wondering if there is any intention to extend this support to other PacBio tools?

I personally would get a lot of benefits out of CRAM support in pbmm2 (input and output), as well as pbsv and trgt.

Cheers,
Mitchell

**Comment by zeeev** [comment]
Hi @mrvollger,

Thanks for the feedback. To answer you question, not at the moment.
