### ISSUE TITLE
Example Kinnex data set error 404

### ISSUE THREAD

**Issue by FabianJetzinger** [PacificBiosciences/pbbioconda#701]
On the site https://isoseq.how/clustering/examples.html, the toy S-reads dataset produces a 404 not found error.
Link: https://downloads.pacbcloud.com/public/dataset/IsoSeq_sandbox/human_80k_Sreads.segmented.bam

**Comment by zeeev** [comment]
cc @Magdoll

**Comment by armintoepfer** [comment]
I've just pinged @Magdoll again.
