### ISSUE TITLE
How do I control 

### ISSUE THREAD

**Issue by SethMagnusJarvis** [PacificBiosciences/pbbioconda#703]
**Operating system**
Linux running on an HPC

**Package name**
isoseq 4.0.0 (commit v4.0.0)

Using:
  pbbam     : 2.4.99 (commit v2.4.0-16-g5cc6e4b)
  pbcopper  : 2.3.99 (commit v2.3.0-14-g5ac5693)
  pbmm2     : 1.11.99 (commit v1.11.0-1-g1b5a417)
  minimap2  : 2.15
  parasail  : 2.1.3
  boost     : 1.77
  htslib    : 1.17

**Conda environment**
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_sysroot_linux-64_curr_repodata_hack 3                   h69a702a_14    conda-forge
alsa-lib                  1.2.11               hd590300_1    conda-forge
bedtools                  2.31.1               hf5e1c6e_1    bioconda
blast                     2.15.0          pl5321h6f7f691_1    bioconda
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
bwa                       0.7.18               he4a0461_0    bioconda
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.28.1               hd590300_0    conda-forge
ca-certificates           2024.7.4             hbcca054_0    conda-forge
cairo                     1.18.0               h3faef2a_0    conda-forge
certifi                   2024.6.2           pyhd8ed1ab_0    conda-forge
circos                    0.69.9               hdfd78af_0    bioconda
contourpy                 1.1.1            py38h7f3f72f_1    conda-forge
curl                      8.8.0                he654da7_0    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
edlib                     1.2.3                h2d50403_1    bioconda
entrez-direct             22.1                 he881be0_0    bioconda
expat                     2.6.2                h59595ed_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.53.0           py38hfb59056_0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
gettext                   0.22.5               h59595ed_2    conda-forge
gettext-tools             0.22.5               h59595ed_2    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
glimmerhmm                3.0.4           pl5321hdbdd923_8    bioconda
graphite2                 1.3.13            h59595ed_1003    conda-forge
harfbuzz                  8.5.0                hfac3d4d_0    conda-forge
htslib                    1.20                 h5efdd21_1    bioconda
icu                       73.2                 h59595ed_0    conda-forge
importlib-resources       6.4.0              pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
isoseq                    4.0.0                h9ee0642_0    bioconda
joblib                    1.4.2              pyhd8ed1ab_0    conda-forge
k8                        1.2                  h6618dc6_1    bioconda
kernel-headers_linux-64   3.10.0              h4a8ded7_14    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py38h7f3f72f_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libasprintf               0.22.5               h661eb56_2    conda-forge
libasprintf-devel         0.22.5               h661eb56_2    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.8.0                hca28451_0    conda-forge
libdeflate                1.20                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.2                h59595ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0              h77fa898_11    conda-forge
libgd                     2.3.3                h119a65a_9    conda-forge
libgettextpo              0.22.5               h59595ed_2    conda-forge
libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
libgfortran-ng            13.2.0              h69a702a_13    conda-forge
libgfortran5              13.2.0              h3d2ce59_13    conda-forge
libglib                   2.80.2               hf974151_0    conda-forge
libgomp                   13.2.0              h77fa898_11    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0              hc0a3c3a_11    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.4.0                h2c329e2_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
lima                      2.9.0                h9ee0642_1    bioconda
matplotlib-base           3.7.3            py38h58ed7fa_0    conda-forge
minimap2                  2.28                 he4a0461_1    bioconda
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
ncbi-vdb                  3.1.1                h4ac6f70_0    bioconda
ncurses                   6.5                  h59595ed_0    conda-forge
numpy                     1.24.4           py38h59b608b_0    conda-forge
openjdk                   22.0.1               hb622114_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.1                h4ab18f5_1    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.43                hcad00b1_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-b-cow                0.007           pl5321hd590300_0    conda-forge
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-clone                0.46            pl5321h166bdaf_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h166bdaf_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h166bdaf_0    conda-forge
perl-config-general       2.65            pl5321hdfd78af_0    bioconda
perl-digest-perl-md5      1.9             pl5321hdfd78af_2    bioconda
perl-encode               3.21            pl5321hd590300_0    conda-forge
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-config      0.008           pl5321ha770c72_0    conda-forge
perl-extutils-helpers     0.026           pl5321ha770c72_0    conda-forge
perl-extutils-installpaths 0.012           pl5321ha770c72_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-extutils-pl2bat      0.005           pl5321ha770c72_0    conda-forge
perl-font-ttf             1.06            pl5321hdfd78af_1    bioconda
perl-gd                   2.76            pl5321h5b5514e_1    bioconda
perl-inc-latest           0.500           pl5321ha770c72_0    conda-forge
perl-io-compress          2.201           pl5321hdbdd923_2    bioconda
perl-io-string            1.08            pl5321hdfd78af_4    bioconda
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h4ac6f70_6    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321h031d066_2    bioconda
perl-math-bezier          0.01            pl5321hdfd78af_2    bioconda
perl-math-round           0.07            pl5321ha770c72_0    conda-forge
perl-math-vecstat         0.08            pl5321hdfd78af_2    bioconda
perl-module-build         0.4234          pl5321ha770c72_0    conda-forge
perl-module-build-tiny    0.039           pl5321h166bdaf_0    conda-forge
perl-module-implementation 0.09            pl5321ha770c72_0    conda-forge
perl-module-runtime       0.016           pl5321hdfd78af_2    bioconda
perl-number-format        1.76            pl5321hd8ed1ab_0    conda-forge
perl-params-validate      1.31            pl5321h031d066_2    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h166bdaf_0    conda-forge
perl-readonly             2.05            pl5321ha770c72_0    conda-forge
perl-regexp-common        2017060201      pl5321hd8ed1ab_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h166bdaf_0    conda-forge
perl-set-intspan          1.19            pl5321hdfd78af_2    bioconda
perl-statistics-basic     1.6611          pl5321hdfd78af_3    bioconda
perl-storable             3.15            pl5321h166bdaf_0    conda-forge
perl-svg                  2.87            pl5321hd8ed1ab_0    conda-forge
perl-test-fatal           0.016           pl5321ha770c72_0    conda-forge
perl-text-format          0.62            pl5321hdfd78af_0    bioconda
perl-time-hires           1.9764          pl5321h031d066_4    bioconda
perl-try-tiny             0.31            pl5321ha770c72_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
perl-xml-parser           2.44_01         pl5321hc3e0081_1003    conda-forge
pillow                    10.3.0           py38h9e66945_0    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
python                    3.8.19          hd12c33a_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      4_cp38    conda-forge
quast                     5.2.0           py38pl5321h40d3509_4    bioconda
readline                  8.2                  h8228510_1    conda-forge
samtools                  1.20                 h50ea8bc_0    bioconda
setuptools                70.1.1             pyhd8ed1ab_0    conda-forge
simplejson                3.19.2           py38h01eb140_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sysroot_linux-64          2.17                h4a8ded7_14    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
unicodedata2              15.1.0           py38h01eb140_0    conda-forge
wget                      1.21.4               hda4d442_0    conda-forge
wheel                     0.43.0             pyhd8ed1ab_1    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

**Describe the bug**
I'm trying to run isoseq cluster2. 

I have 2 errors, one is that it keeps trying to use too many cores. How to I tell it how many cores it can use?

The other, when it doesn't run into that error is that I get an error from an underlying c-library and I don't know why or how

Terminate called without an active exception is the error I have a much bigger issue with because it means nothing, but it would also be good to be able to say how many cores can be used so it doesn't keep killing itself.

**Error message**

Error 1: =>> PBS: job killed: ncpus 50.38 exceeded limit 24 (sum)

Error 2: terminate called without an active exception

**To Reproduce**
Error 1 is using your example data. I've also seen error 2 once or twice with it but it's much more common with my data. I think it may base how many cores it has off how much ram it has, but that might just be how our cluster kills jobs. 

**Expected behavior**
I expected it to run as it says in the tutorial

**Comment by zeeev** [comment]
Hello,

It looks like you're not allocating enough resources on your cluster to run isoSeq Cluster. The clue is here:
``` Error 1: =>> PBS: job killed: ncpus 50.38 exceeded limit 24 (sum)

Try requesting more resources for your job.

**Comment by SethMagnusJarvis** [comment]
I've tried allocating all sorts (I've gone as high as as high as 72cores) and it tried using 80+, I don't know what it needs. Is there a way to set how much it can use so I'm not on some kind of infinite treadmill of giving it an increasing amount of resources? 

And do you know anything about the 2nd error which is the one I've been having more trouble with.

**Comment by zeeev** [comment]
Try the following:

```isoseq cluster2 --all-help```

You'll want:

```  -j,--num-threads                INT   Number of threads to use, 0 means autodetection. [0]```

I'm pretty sure the second and first error are the same. No exception thrown and the code terminates. That sounds like the cluster terminating the job because of the first error.

**Comment by SethMagnusJarvis** [comment]
I only get the 2nd error when I don't get the first but you might bbe right. I'll try this. Thank you!
