### ISSUE TITLE
Certain reads with missing methylation modification tags

### ISSUE THREAD

**Issue by tobybaker** [PacificBiosciences/pbbioconda#704]
I am looking at CpG methylation probabilities from the jasmine-processed example data _HG002.GRCh38.haplotagged.bam_ (downloaded from [here](https://downloads.pacbcloud.com/public/revio/2022Q4/WGS-variant-pipeline-analysis/alignments/)).

When looking at the reads that overlap a given CpG site, I see that a minority of reads have no methylation ML/MM tag information for any CpGs on the read. 

It appears that pb-CpG-tools treats these reads as corresponding to a set of unmethylated CpGs when using the `count` pileup method, but I am unsure how to treat these without the associated probabilities. 

What is the cause of these reads and how should they be handled?

**Comment by armintoepfer** [comment]
```
  Empty MM/ML tag            No methylation sites.
  Missing MM/ML tag, np = 0  No kinetic input.
  Missing MM/ML tag, np > 0  Insufficient passes.
  ```

That means, we couldn't process the read.

**Comment by tobybaker** [comment]
Thank you for the clarification. 

Could you please also clarify why the reads with a low number of passes and missing ML/MM tags appear to be added to the unmethylated counts when using pb-CpG-tools with `count` mode?
