### ISSUE TITLE
Is HGAP4 output compatible with pb-assembly?

### ISSUE THREAD

**Issue by gbdias** [PacificBiosciences/pbbioconda#71]
Hi,

- Based on the documentation from older Falcon versions, one could use the pbsmrtpipe hdftosubread bam read files and the HGAP4 fasta reads as inputs to Falcon.
https://pb-falcon.readthedocs.io/en/latest/hgap4_adapt.html
- Is this still supported in current versions of pb-assembly?

**Comment by gbdias** [comment]
- I was using the HGAP4-generated fasta and bam files as inputs for Falcon Unzip (pb-assembly).
- Although this [page](https://pb-falcon.readthedocs.io/en/latest/hgap4_adapt.html) (earlier Falcon version) says that it is ok to use HGAP4 output as input for Falcon there is no information if pb-assembly also supports this process.
- Indeed, I was encountering errors when trying to do this https://github.com/PacificBiosciences/pbbioconda/issues/69. I has the same problem with versions 0.0.1 and 0.0.2 of pb-assembly
- Then I decided to re-generate the .bam and .fasta files using the standalone PacBio tools [bax2bam](
https://github.com/pacificbiosciences/bax2bam/) and [bam2fastx](
https://github.com/pacificbiosciences/bam2fastx/) and use those as input for pb-assembly (v 0.0.1). The problem was solved.
- It would be nice having someone from pb-bioconda confirm if pb-assembly is compatible with HGAP4 output files. In any case, these experiments seem to suggest it is not.

**Comment by pb-cdunn** [comment]
> Is `hgap4_adapt.py` still supported in current versions of pb-assembly?

Yes, but version consistency is important. You can copy some settings from `fc_run.generated.json`. However, you must have run HGAP4 with `falcon_ns.task_options.save_las_for_unzip = true`.
