### ISSUE TITLE
Unable to rename biosamples with lima

### ISSUE THREAD

**Issue by linley-sherin** [PacificBiosciences/pbbioconda#716]
**Operating system**
Linux, running on a cluster

**Package name**
` lima      : 2.9.0 (commit v2.9.0) `

**Conda environment**
```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
isoseq                    4.0.0                h9ee0642_0    bioconda
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
lima                      2.9.0                h9ee0642_1    bioconda
pbmm2                     1.14.99              h9ee0642_0    bioconda
pbpigeon                  1.2.0                h4ac6f70_0    bioconda
pbskera                   1.2.0                hdfd78af_0    bioconda
pbtk                      3.1.1                h9ee0642_0    bioconda
```

**Describe the bug**
I want to assign biosample names to each barcode pair so that they match my experimental sample_ids. When I use --biosample-csv input.csv as documented in the [official lima documentation](https://lima.how/faq/biosample.html), I get a fatal error. I want to do this at this step because we ran multiple SMRT cells with 24 samples total, so each kinnex/MAS-seq barcode was used twice and if I use the default 'Biosample' labels then more than one sample is given the same id.

**Error message**
`| FATAL | Could not find requested barcode from XML from BioSample 3FGP with name 3FGP_5p in barcode file!`

**To Reproduce**
I am using the following command, with input_file (segemented_file) in BAM format, barcode_file in fasta format and output_file in BAM format.
```
 lima "$segmented_file" \
         "$barcode_file" \
         "$output_file" \
         --isoseq \
         --peek-guess \
         --biosample-csv biosample_ids.csv    
```

The biosample_ids.csv looks like this:
```
Barcodes,Bio Sample
3FGP_5p--IsoSeqX_3p,3FGP
4MTP_5p--IsoSeqX_3p,4MTP
5MGP_5p--IsoSeqX_3p,5MGP
1FTP_5p--IsoSeqX_3p,1FTP
6FGP_5p--IsoSeqX_3p,6FGP
4MGP_5p--IsoSeqX_3p,4MGP
5FTP_5p--IsoSeqX_3p,5FTP
4FGP_5p--IsoSeqX_3p,4FGP
1MTP_5p--IsoSeqX_3p,1MTP
```

I am not sure why the ERROR message is referencing an XML file.

**Comment by armintoepfer** [comment]
Maybe it's an implementation detail that it mentions XML. Have you tried withoput `--peek-guess`?

**Comment by JAGalarza** [comment]
I get the same error. Im working on HiFi.bam reads.
