### ISSUE TITLE
skera adapeter.fasta for kinnex single-cell sequencing: where to download?

### ISSUE THREAD

**Issue by WeiCSong** [PacificBiosciences/pbbioconda#719]
Hi,
 Please could you tell me where to obtain the fasta sequence of kinnex single-cell analysis? I could only find the MAS-seq adapter at https://downloads.pacbcloud.com/public/dataset/Kinnex-single-cell-RNA/

**Comment by armintoepfer** [comment]
Please reach out to PacBio tech support as this is not related to PacBio distributed software via bioconda.
