### ISSUE TITLE
pbsv call somatic SV for tumor/normal samples

### ISSUE THREAD

**Issue by DayTimeMouse** [PacificBiosciences/pbbioconda#720]
Hi,

I'd like to call somatic structural variants (SVs) using paired tumor and normal samples. 

However, after obtaining tumor_normal.vcf file via pbsv(2.9.0), how to select the SVs that are only included in the tumor sample(means somatic SVs).

Best regards.

**Comment by armintoepfer** [comment]
There is no such feature. You can do join calling and then look which sample contributes to each variant. Otherwise, try to give our newest SV caller https://github.com/PacificBiosciences/sawfish a spin
