### ISSUE TITLE
pigeon sort error: GFF/GTF file error for some but NOT all files

### ISSUE THREAD

**Issue by AnnikaMueller05** [PacificBiosciences/pbbioconda#721]
**Operating system**
I am working on a Windows laptop, but accessing our university's high-performance computing system via the MobaXterm linux environment.
The commend uname -r output ends in 5.x86_64

**Package name**
The issue is with the pigeon sort command. 
conda list
packages in environment at /home/mueannik/.conda/envs/AnnikaIsoSeq:
Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
isoseq                    4.0.0                h9ee0642_0    bioconda
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
lima                      2.9.0                h9ee0642_1    bioconda
pbmm2                     1.14.99              h9ee0642_0    bioconda
pbpigeon                  1.2.0                h4ac6f70_0    bioconda

pbpigeon                  1.2.0                h4ac6f70_0    bioconda
I ran conda update --all to update everything. 
Since we thought there may be an issue with this anyway, we reinstalled pigeon using micromamba, but the error remains.

**Describe the bug**
It appears that the GFF file is not found. The GFF is there and i have all permissions for said file. Now here's where it gets weird:
The error only appears for 6 out of 9 files. 3 files can be processed just fine. 
The ones without issues are the three smallest files; different testing conditions, so unlikely to be related to the conditions. Might a memory-related, you may say? That's what I thought, but we still have 5TB left. Also, I deleted the output from all files and only ran it for specimen1 and I still get the same error. 
It does not matter whether I run it via a script or directly from the command line. 
The GFF is not corrupted, no hidden characters, etc. I also repeated all the steps before to make sure the error does not lie upstream, but the log files all appear okay. 
Interestingly, I do not have these issues when copying the first 1,000 lines of said GFF for example, so the issue really doesn't seem to be related to the GFF or format issues. I also tried the same with the last 1,000 entries to double-check whether the file maybe ends prematurely, but also here everything works just fine. This brings me back to whether this may be file size-related, but I really don't see how 5TB can be too little for the IsoSeq analysis of just one specimen. Furthermore, see below:
Interestingly, the command runs for a while before the error occurs. In the output directory, over a thousand new files are being created, one Specimen1.alignedIsoseq.collapsed.sorted.gff and the rest called /path/Specimen1.alignedIsoseq.collapsed.sorted.gff. followed by scaffold or chromosome names. I extracted the scaffold names from the GFF (to be sorted) for which no file was created to check whether there's an issue here. No issue visible and also, when extracting the respective lines and running pigeon sort, this runs smoothly! Next, I wanted to check whether one of the lines causes the crash during processing. I extracted the names of the scaffolds for which a file was created, i assume these are temporary files that are being created during processing, but which are not present in the final sorted.gff. I extracted the respective lines to a test file test.gff and ran pigeon sort test.gff. Again, no problems here. So the issue does not seem to be caused by the lines themselves. It also does not seem to be space-related to me, because then the space issue should persist when repeating it for the lines which have not been added to the sorted.gff file. Also, 5TB should be plenty.
I am running out of ideas, please help me!

**Error message**
| 20241005 08:57:19.381 | FATAL | pigeon sort ERROR: GFF/GTF file error
  reason : No such file or directory
See format documentation at https://isoseq.how

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!
The problem is that the problem does not occur when only using parts of the GFF file, so I cannot really provide a small dataset without providing the entire dataset. I am attaching my troubleshooting script of today. I am not attaching everything I tried the days before, but it was pretty standard sanity checks, i.e. checking that the GFF is not corrupted. Furthermore, I am attaching information about the file sizes of the collapsed GFFs.
[20240913_CCS.pdf](https://github.com/user-attachments/files/17265881/20240913_CCS.pdf)
[test.txt](https://github.com/user-attachments/files/17265885/test.txt)

**Expected behavior**
A sorted GFF output

**Comment by armintoepfer** [comment]
Please reach out to PacBio's tech support, as this isn't a problem with the bioconda binaries, but a generic workflow question.
