### ISSUE TITLE
Running ont data with pbsv produced an error

### ISSUE THREAD

**Issue by coopsor** [PacificBiosciences/pbbioconda#722]
**Package name**
pbsv --2.9.0
**Describe the bug**
When I was using pbsv to call data from the HG002 sample with ONT data, I encountered an error: "20241021 07:45:20.291 -|- FATAL -|- Run -|- 0x7fc28fcaa780|| -|- pbsv discover ERROR: [pbbam] read group ERROR: unknown platform model 'PromethION'". It appears that pbsv does not support ONT sequencing data. 
**Error message**
Paste the error message / stack.
>|> 20241021 07:45:20.291 -|- FATAL -|- Run -|- 0x7fc28fcaa780|| -|- pbsv discover ERROR: [pbbam] read group ERROR: unknown platform model 'PromethION'
**To Reproduce**
pbsv discover  HG002_GRCh37_ONT-UL_UCSC_20200508.phased.bam tools/pbsv/ont.svsig.gz --tandem-repeats HG002_PacBio_CCS_15kb/ref/hs37d5.trf.bed
the bam data come from: https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/UCSC_Ultralong_OxfordNanopore_Promethion/HG002_GRCh37_ONT-UL_UCSC_20200508.phased.bam
**Expected behavior**
I would like to know how to resolve this issue, as it seems that other tools have successfully used pbsv with ONT data(sniffles2,svdss).

**Comment by armintoepfer** [comment]
pbsv is tested on PacBio data. All other platforms, run at your own risk.
