### ISSUE TITLE
FATAL ccs ERROR could not open for reading

### ISSUE THREAD

**Issue by Arraiano-Castilho** [PacificBiosciences/pbbioconda#723]
Hello, 

I am trying to run ccs to generate HiFi reads. My input .bam file (11Gb) results from pbsim3 simulations and is sorted and converted from sam to bam with samtools v1.17. 

When running ccs I get the following error in the DEBUG log mode, with program crashing and no HiFi reads generated:

(...)
| 20241022 23:36:16.849 | WARN | BAM merge: Cannot open file /work/FAC/FBM/DEE/isanders/micro_myco-nccr/ctorres/RAC_transfer_bay/test/pbsim/v2/Lopma1/tmp/thread.3_296.Lopma1_merged.sorted.ccs.bam! Will retry in 1 seconds.
| 20241022 23:36:18.345 | VERBOSE | Closing pool fafPoolGpuDraft_
| 20241022 23:36:18.345 | VERBOSE | Closing pool fafPoolGpuPolish_
| 20241022 23:36:18.347 | FATAL | ccs ERROR: [pbbam] BAM reader ERROR: could not open for reading:
  file: /work/FAC/FBM/DEE/isanders/micro_myco-nccr/ctorres/RAC_transfer_bay/test/pbsim/v2/Lopma1/tmp/thread.3_296.Lopma1_merged.sorted.ccs.bam

I am running ccs with the following command line:
ccs ${sample}_merged.sorted.bam ${sample}_merged.sorted.ccs.bam -j ${cores} --report-file ${sample}_report_file.txt --log-level DEBUG --log-file ${sample}_css_test.log

Error is consistent with other bam files, but possible to run when using smaller ones that don't require multi-threading. 

At some point I suspected that for some reason and because I am running this in the cluster of my university, that the issue could be related to permissions accessing the tmp bam files generated during ccs run at specific computing nodes, so I did force them to be written in a different folder that I have 100% sure that I have full permissions by exporting the $TMPDIR before running ccs.

export TMPDIR=$(echo $output_dir/tmp)

It did write the files to the specified folder but the issue persists. 

I am using ccs installed via conda (see env contents) in linux machine (cluster) with slurm job scheduler and I have tried with up to 200Gb memory. 

conda env. content:
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.2               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
htslib                    1.21                 h5efdd21_0    bioconda
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libdeflate                1.21                 h4bc722e_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
pbbam                     2.4.0                hdcf5f25_1    bioconda
pbccs                     6.4.0                h9ee0642_0    bioconda
pbcopper                  2.3.0                h4ac6f70_3    bioconda
pbsim3                    3.0.4                h4ac6f70_0    bioconda
pbtk                      3.1.1                h9ee0642_0    bioconda
xz                        5.2.6                h166bdaf_0    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge

Any help with this would be much appreciated. 

Thank you very much for your time.
Ricardo

**Comment by armintoepfer** [comment]
We only support official PacBio files.
