### ISSUE TITLE
Multi-threading option doesn't work in pbsv call

### ISSUE THREAD

**Issue by mas-agis** [PacificBiosciences/pbbioconda#724]
**Operating system**
Linux Red Hat - with slurm job scheduler

**Package name**
pbsv 2.6.2 (commit SL-release-10.1.0-175-g866ef3c)

**Conda environment**
```
# packages in environment at /home/mnaji/.conda/envs/pbsv:
#
# Name                    Version                   Build  Channel
pbsv                      2.6.2                h9ee0642_0    bioconda

```

**Describe the bug**
I submit the `pbsv call` to join call two individuals using slurm scheduler with 5 cores assigned and specify the -j option in the command. Yet, the program used only one core while running. 
My bash script is as follows 
```
#!/bin/bash -l
#
#SBATCH -t 24:00:00
#SBATCH --ntasks=1
#SBATCH -c 5
#SBATCH --mem-per-cpu=20G

#load modules
module load devel/Miniconda/Miniconda3

#getting the variables
PATH1="/some_path"

#change dir
cd $PATH1

#activate conda
conda activate pbsv

pbsv call -j 5 --min-sv-length 50 --max-ins-length 100000 REF/ARS-UCD1.2_Btau5.0.1Y.fa 40533_OLDBOY-pbmm2.svsig.gz 40534_OASISP-pbmm2.svsig.gz test_output.vcf
```
I cancel the job because its using only one core instead of 5. The report of cancelled-slurm job as follows
```
State: CANCELLED (exit code 0)
Nodes: 1
Cores per node: 5
CPU Utilized: 00:00:15
CPU Efficiency: 13.04% of 00:01:55 core-walltime
Job Wall-clock time: 00:00:23
Memory Utilized: 18.82 MB
Memory Efficiency: 0.02% of 100.00 GB
```

*Expected behavior**
I would expect the multi-threading option of -j works smoothly using all cores assigned in by the job-scheduler. I tried also to update the conda package of pbsv to the version 2.9. But, it still using only a single core.
Can you check on this?

**Comment by armintoepfer** [comment]
We haven't touched pbsv in a long time and it not all steps are parallelized. There's nothing fundamentally wrong here.
