### ISSUE TITLE
Pigeon make-seurat produces empty output

### ISSUE THREAD

**Issue by TheCatalyticMicroChip** [PacificBiosciences/pbbioconda#727]
**Operating system**
I am using Linux 3.10.0-1160.88.1.el7.x86_64

**Package name**
I am using loading StdEnv/2023 smrtlink-sequel2/13.1.0.221970 ... pigeon 1.2.0

**Conda environment**
Working on an HPC

**Describe the bug**
I am following the isoseq workflow as described here: https://isoseq.how/classification/workflow.html, but I believe the last command fails: `pigeon make-seurat --dedup B_dedup.fasta --group B.collapsed.group.txt -d make-seurat B_classification.filtered_lite_classification.txt`

**Error message**
I am not getting an error message, I am getting empty files in the last step of the workflow. info.csv has the expected information, however, annotated.info.csv and annotated-prefilter.info.csv are empty. See below the first two lines of input files:
![Question](https://github.com/user-attachments/assets/4046f0ab-1ace-43e7-a2f1-cad540ad73b5)
`

**Comment by beeesal** [comment]
I'm experiencing the same issue, were you able to resolve this?
