### ISSUE TITLE
pbmm2 crashes with std::out_of_range error on large-memory nodes but works on low-memory nodes

### ISSUE THREAD

**Issue by SarahBailey1998** [PacificBiosciences/pbbioconda#731]
**Operating system**
RHEL 9

**Package name**
pbmm2, specifically versions 1.16.0 and 1.14.99.

We tested a few of the pbmm2 apptainer images:
- https://depot.galaxyproject.org/singularity/pbmm2:1.16.0--h9ee0642_0
- https://depot.galaxyproject.org/singularity/pbmm2:1.14.99--h9ee0642_0
- quay.io: biocontainers/pbmm2:1.16.0--h9ee0642_0

We tested 1.16.0 with conda as well.

**Describe the bug**
pbmm2 works correctly on low-memory nodes but consistently fails on large-memory/CPU nodes.

**Error message**
On large nodes, pbmm2 fails with the following error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  stoi
Aborted
```

On large nodes, additional errors appear just before failure, referencing futex locking and memory mapping as seen in the left tab of the attached screenshot. The right tab shows the same command when run on a low memory node.
![error](https://github.com/user-attachments/assets/d0f88384-d830-4020-8c1c-d83f3761781b)

**Expected behavior**
The software should behave consistently across nodes regardless of memory and CPU configuration.

**Comment by armintoepfer** [comment]
This has been fixed internally very recently and we will release it in a reasonable time. Thank you for letting us know.

**Comment by SarahBailey1998** [comment]
Awesome thank you! 😊
