### ISSUE TITLE
Proper use of Isoseq3 cluster for species with subgenomes / homoeologs  genes

### ISSUE THREAD

**Issue by JBerthelier** [PacificBiosciences/pbbioconda#733]
Dear Isoseq authors, 

I am mannipulation isoseq data for a polyploid plant species (composed of 4 subgenomes ) and composed of homoeologs genes, 
I noticed that using the default "isoseq3 cluster" step cause to clustering flnc reads that belong to different homoeologs genes together, causing mistake and bad collapsing step.

Would you have a suggestion to avoid that issue?

Best regards,

Jérémy

**Comment by armintoepfer** [comment]
We cluster based on exon-intron structure, not SNV differences. You could try `cluster2`, but you might need SNV phasing, which we currently don't offer.

**Comment by JBerthelier** [comment]
ok! I will try that. Thanks for the quick reply
