### ISSUE TITLE
isoseq instructions

### ISSUE THREAD

**Issue by jeramiahsmith** [PacificBiosciences/pbbioconda#734]
in your isoseq usage documentation it looks like the example command in out of order (ref and input swapped). You have:

pbmm2 align --preset ISOSEQ --sort <input.bam> <ref.fa> <mapped.bam>

but it should be:

pbmm2 align --preset ISOSEQ --sort <ref.fa> <input.bam> <mapped.bam> 

Usage:
  pbmm2 align [options] <ref.fa|xml|mmi> <in.bam|xml|fa|fq|gz|fofn> [out.aligned.bam|xml]

**Comment by armintoepfer** [comment]
Technically you are correct. In practice, pbmm2 allows the swapped order if the input types are different
