### ISSUE TITLE
Release notes transpose FALCON version and pb-assembly version

### ISSUE THREAD

**Issue by mp15** [PacificBiosciences/pbbioconda#75]
The release notes at https://github.com/PacificBiosciences/pbbioconda/wiki/Release-notes transpose FALCON version and pb-assembly version. pb-assembly should be 0.0.3 and pb-falcon should be 0.2.5 at https://github.com/PacificBiosciences/pbbioconda/wiki/Release-notes#pb-assembly-025.
Also https://github.com/PacificBiosciences/pbbioconda/wiki/Release-notes#pb-falcon-003 is labelled as pb-falcon, it should probably be pb-assembly?

**Comment by skingan** [comment]
Thank you for catching this, Martin. The release notes have been corrected.
