### ISSUE TITLE
ERROR: CLI::Interface - unknown option name: sorttouch quiver_done.exit

### ISSUE THREAD

**Issue by rob123king** [PacificBiosciences/pbbioconda#76]
**Package name**
Using latest bioconda installation with intervaltree prior version to fix an issue 

**Describe the bug**
in the 4-polish folder and quiver-run folder the error is 
ERROR: CLI::Interface - unknown option name: sorttouch quiver_done.exit

**Error message**
ERROR: CLI::Interface - unknown option name: sorttouch quiver_done.exit

Any idea what is causing this error? almost got it to complete but failing at the quiver stage.

**Comment by armintoepfer** [comment]
Try updating all packages in conda. I suspect you don't have the latest pbmm2 version

**Comment by rob123king** [comment]
I did conda pb-assembly update and the version is still quite old. I am using bioconda installation of pb-assembly
pbmm2 --version
pbmm2 0.8.1 (commit 0.8.1)

How do I update just this?

**Comment by armintoepfer** [comment]
`conda update --all`

**Comment by biolittleboy** [comment]
> `conda update --all`

hello, sir
The same error happened after i update all. 
### My conda channels
default
### Try to solve
`conda update --all` & `conda update -c bioconda --all`

Can you show me your conda channels and `conda list` or give me another advice to solve this problem.
Thank you so much!

**Comment by mp15** [comment]
If just upgrading the packages does not work then after you upgrade you might want to wind back your unzip pipeline one step by removing the 4-phase/quiver-* directories and their contents.

Fixing this requires at least two package updates to make falcon work. ```pbmm2``` but also ```pbcore``` to then parse the resulting output (maybe ```pbcommand``` and ```pbalign``` too?). Given that it is just a matter of pinning the minimum correct versions in the recipe, could PacBio (@pb-cdunn?) just fix the min version in the recipe and update to build 3 just like they did with build 2 please?
