### ISSUE TITLE
Genomic consensis IMPORT FRROR

### ISSUE THREAD

**Issue by yuyang3** [PacificBiosciences/pbbioconda#77]
**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`?

conda install -c bioconda genomicconsensus 
latest version

**Describe the bug**

the installation shows is done 
but when you run quiver it cann't run 

**Error message**
Paste the error message / stack.

File "miniconda2/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /bin/miniconda2/lib/libhts.so.2: undefined symbol: BZ2_bzBuffToBuffCompress

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

conda -c install bioconda genomeconsensus
also updata to the latest pysam 
**Expected behavior**

how to run the quiver

**Comment by biolittleboy** [comment]
# d 
- dd

**Comment by pb-cdunn** [comment]
Have you solved this yet? If you use a consistent conda environment, that should work. This looks like a configuration problem. What is the result of `conda list`?

Also, it is possible that you have overridden your conda environment somehow. For example, sometimes users set `$PYTHONPATH` or `$LD_LIBRARY_PATH` without realizing it.

Most likely, you need to force everything to be consistent in your environment, via `conda update --all`

(Essentially, this is your problem: https://github.com/samtools/htslib/issues/493 , which could happen if your htslib was built to use libbz2 but libbz2 is not available in your environment.)

**Comment by pb-dseifert** [comment]
this is definitely a bioconda-related issue, as the failure is in pysam, and not any PB packages.
