### ISSUE TITLE
xml documentation for pbmm2

### ISSUE THREAD

**Issue by mchaisso** [PacificBiosciences/pbbioconda#78]
The readme references xml files, but does not give their format/required content.

**Comment by ylipacbio** [comment]
PacBio DataSet XML definition: https://pacbiofileformats.readthedocs.io/en/5.1/DataSet.html
Tools to create/modify DataSet XML: http://pacificbiosciences.github.io/pbcoretools/pbcoretools.html

**Comment by armintoepfer** [comment]
We'll add links to the pbmm2 readme. Will close as soon as it's done.

**Comment by armintoepfer** [comment]
Added and will be synced to GitHub soon.
