### ISSUE TITLE
Inverted performance scaling problem with arrow/variantcaller

### ISSUE THREAD

**Issue by HenrivdGeest** [PacificBiosciences/pbbioconda#79]
**Operating system**
	Scientific Linux release 7.4 
        56x  Intel(R) Xeon(R) CPU E7-4830 v4 @ 2.00GHz

**Package name**
arrow (or genomicConsensus) module from this github page, version 2.3.2

**Conda environment**
na
**Describe the bug**
The performance of arrow is the best using a single thread. The more threads its given, the slower it gets.

**Error message**
```
For example, i run the tool with a single contig, around 100kb in size, with sequel chemistry 3 (latest since oct 2018)
/usr/bin/time -v  variantCaller --referenceFilename referenceset.xml --outputFilename ./chunk1.alignmentset.xml.consensus.fasta   --algorithm arrow ./chunk1.alignmentset.xml -j #76 
-j1:
	User time (seconds): 11.04
	System time (seconds): 0.77
	Percent of CPU this job got: 130%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:09.07

-j4:
	User time (seconds): 23.01
	System time (seconds): 1.55
	Percent of CPU this job got: 262%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:09.34
-j56:
	User time (seconds): 253.38
	System time (seconds): 1971.71
	Percent of CPU this job got: 3734%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:59.57

```
**To Reproduce**
na

**Expected behavior**
I expect the tool being faster or of equal speed compared to 1 thread. In my case it behaves the opposite.

**Comment by armintoepfer** [comment]
The overhead to manage those python threads seems too high for a 11 second run. I guess it gets better once you have sufficient data to fire those threads.
We'll soon release a C++ implementation of GenomicConsensus that should fix said issue.
