### ISSUE TITLE
isoseq3 package not found at bioconda

### ISSUE THREAD

**Issue by danieleyumi** [PacificBiosciences/pbbioconda#8]
**Operating system**
Which operating system and version are you using?
MacOS Sierra 10.13.4

**Package name**
Which package / tool is causing the problem? Which version are you using, use `tool --version`. Have you updated to the latest version `conda update package`?
isoseq3 was not found at bioconda
The Anaconda3 was installed using graphical installer
conda was updated
All the installation steps available at https://github.com/PacificBiosciences/IsoSeq_SA3nUP/wiki/Tutorial:-Installing-and-Running-Iso-Seq-3-using-Conda was successfully done but the instalaltion of isoseq3.

**Describe the bug**
isoseq3 package was not found at bioconda channel

**Error message**
Paste the error message / stack.
(anaCogent5.2) MBP-de-Daniele:~ daniyumi$ conda install -n anaCogent5.2 -c bioconda isoseq3
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - isoseq3

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/osx-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page

**To Reproduce**
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Expected behavior**
All the optional packages below were successfully installed 
conda install -n anaCogent5.2 -c bioconda pbcoretools # for manipulating PacBio datasets
conda install -n anaCogent5.2 -c bioconda bamtools    # for converting BAM to fasta
conda install -n anaCogent5.2 -c bioconda pysam       # for making CSV reports

Thank you,
Daniele

**Comment by armintoepfer** [comment]
IsoSeq3 is not available for MacOS, as you see in this table https://github.com/PacificBiosciences/pbbioconda#packages

**Comment by danieleyumi** [comment]
Thank you for the prompt reply but unfortunately I still do not see isoseq3 available at:
https://conda.anaconda.org/bioconda/osx-64
as I can see pysam, bamtools, etc.
Thanks,

**Comment by pb-dseifert** [comment]
https://anaconda.org/bioconda/isoseq3
There is only a `linux-64` artifact available, not an `osx-64`. There are no `osx-64` isoseq3 artifacts because isoseq3 is not supported on macOS. It's that simple.

**Comment by danieleyumi** [comment]
Thank you for the prompt reply. Is there a plan to put isoseq3 available for macOS? Thank you again.

**Comment by armintoepfer** [comment]
Thank you for the hint. We'll add a note on said wiki. Please see the FAQ regarding OS support.
