### ISSUE TITLE
pbsv SIGSEGV/SIBABRT on very long reads

### ISSUE THREAD

**Issue by wdecoster** [PacificBiosciences/pbbioconda#84]
**Operating system**
CentOS7

**Package name**
pbsv 2.1.1 (commit v2.1.1)

**Conda environment**
```
# packages in environment at /home/wdecoster/anaconda3/envs/pbsv:
#
# Name                    Version                   Build  Channel
pbsv                      2.1.1                         0    bioconda
```

**Describe the bug**
I am using simulated pacbio reads (40x coverage, human genome, simulated by simlord), all with exactly the same length per dataset. Reads were aligned using minimap2 with pbsv-preferred settings. `pbsv discover` works fine for all lengths. When using `pbsv call` everything works fine for reads up to 75kb, but at the next length (100kb and longer) I start encountering a SIGSEGV or SIGABRT (see below). Attempting to replicate the issue caused the SIGABRT, next time again the SIGSEGV. The vcf output contains the header, but no variants. The program also seems to use an excessive amount of memory (swapping on a server with 500GB RAM). The error was not reproduced on a bam file with only 100kb reads mapping to chr21.

**Error message**
```
>|> 20190131 09:17:24.664 -|- WARN       -|- ParseInputFiles at ../src/tools/mike/MikeWorkflow.cpp:170 -|- 0x7fd73f9cc740|| -|- Overriding output file simlord-100000-RG.vcf
>|> 20190131 09:48:31.108 -|- FATAL      -|- operator() at ../subprojects/pbcopper/src/logging/Logging.cpp:100 -|- 0x7fd733ff7700|| -|- caught SIGSEGV
```

or

```
>|> 20190131 09:00:12.509 -|- WARN       -|- ParseInputFiles at ../src/tools/mike/MikeWorkflow.cpp:170 -|- 0x7fd8471b2740|| -|- Overriding output file simlord-100000-RG.vcf
>|> 20190131 09:09:24.131 -|- FATAL      -|- operator() at ../subprojects/pbcopper/src/logging/Logging.cpp:71 -|- 0x7fd8377ee700|| -|- caught exception: "std::bad_alloc"
>|> 20190131 09:09:24.133 -|- FATAL      -|- operator() at ../subprojects/pbcopper/src/logging/Logging.cpp:84 -|- 0x7fd8377ee700|| -|- caught SIGABRT
```

**To Reproduce**
If helpful I could share a bam file which causes this issue.

**Expected behavior**
I'm not sure if there is an explicit upper limit to read lengths :-)

**Comment by armintoepfer** [comment]
Please share the offending BAM so I can try to reproduce it. Thank you

**Comment by wdecoster** [comment]
You can get the bam file from this link (54GB/ md5sum: 2269816c3d2337b2529454165dcb5f0b): https://data.bioinf.be/public/simlord-100000-RG.bam
(If you let me know when you downloaded the file then we can clean up on our end).

I don't sequence anything on PacBio, but pbsv also works decently for data from "the other long read sequencing company" ;-) 
It was just easier to find a simulator for PacBio data for my application. SVs were not _explicitly_ simulated as this simulation is based on the HG00733 assembly.

**Comment by armintoepfer** [comment]
Can you please post the exact commands that you used and link the reference.fasta that you used?

**Comment by wdecoster** [comment]
Sure:

```
pbsv discover simlord-100000-RG.bam variants-simlord-100000-RG.svsig.gz
pbsv call GRCh38.fa variants-simlord-100000-RG.svsig.gz simlord-100000-RG.vcf
```
(using gnu-parallel to process multiple files, but I filled in the names now in the commands)

with GRCh38.fa = ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

**Comment by armintoepfer** [comment]
This will be addressed in the upcoming version.

**Comment by wdecoster** [comment]
Thanks!

**Comment by caspargross** [comment]
I am encountering this exact same bug in pbsv 2.2.2 (installed via conda).
To reduce the memory requirements, I tried to run pbsv on single chromosomes. While this works fine for some chromosomes, others repeatedly break with SIGSEV or SIGABRT errors

Here is one `.svsig` file created where pbsv repeatedly crashes (Ref: GRCH38):
https://cloud.imgag.de/index.php/s/PS7kADgYJtZ587q

**Comment by armintoepfer** [comment]
What read lengths do you have?

**Comment by caspargross** [comment]
Very long. I am using the published HG002 ONT dataset from GIAB

ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/Ultralong_OxfordNanopore/guppy-V3.2.4_2020-01-22/

Longest reads are >2Mb, attached is a file with read lengths (2nd colum) and frequency (1st column)
[read_lengths.txt](https://github.com/PacificBiosciences/pbbioconda/files/4281752/read_lengths.txt)

**Comment by armintoepfer** [comment]
Ok, understood. Thanks for reporting. Might take a look later, but keep in mind, the PB in pbsv does not stand for ONT :)
