### ISSUE TITLE
pbmm2 to report MD tag

### ISSUE THREAD

**Issue by gbdias** [PacificBiosciences/pbbioconda#88]
Hi,

- Do you plan to enable additional minimap2 options in pbmm2?
- Specifically, I am trying to output alignments with the --MD tag. This is required for SV calling using Sniffles. It is feasible with minimap2 but currently this option does not seem to be present in pbmm2.

Thanks,
Guilherme

**Comment by armintoepfer** [comment]
No plan on adding MD. Please use samtools calmd as postprocessing.
