### ISSUE TITLE
falcon_kit.mains.fasta_filter is crashing

### ISSUE THREAD

**Issue by roblehmann** [PacificBiosciences/pbbioconda#9]
**Operating system**
CentOS Linux release 7.3.1611

**Package name**
pb-assembly installed today via anaconda

**Describe the bug**
crashing command: python -m falcon_kit.mains.fasta_filter median -

Falcon crashes because falcon_kit.mains.fasta_filter does not accept file name input from the standard input, but expects a file path.
Following test call works: python -m falcon_kit.mains.fasta_filter median <path-to-fasta-file>

Is falcon_kit 1.2.2 outdated?

**Error message**
```
#fc_fasta2fasta < my.input.fofn >| fc.fofn
while read fn; do  cat  ${fn} | python -m falcon_kit.mains.fasta_filter median - | fasta2DB -v raw_reads -i${fn##*/}; done < my.input.fofn
+ read fn
+ fasta2DB -v raw_reads -im170528_174820_42276_c101191972550000001823283109291706_s1_p0.1.subreads.fasta
+ python -m falcon_kit.mains.fasta_filter median -
+ cat /home/lehmanr/dataStore/melPacbio/r000112_42276_170525/DAM4_0245/A07_1/Analysis_Results/m170528_174820_42276_c101191972550000001823283109291706_s1_p0.1.subreads.fasta
falcon-kit 1.2.2
pypeflow 2.0.4
Traceback (most recent call last):
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/lehmanr/.conda/envs/denovo_asm/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lehmanr/anaconda_lib/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 234, in <module>
    main(sys.argv)          # pragma: no cover
  File "/home/lehmanr/anaconda_lib/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 231, in main
    args.func(args)
  File "/home/lehmanr/anaconda_lib/.conda/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/mains/fasta_filter.py", line 164, in cmd_run_median_filter
    with open(args.input_path, 'r') as fp_in:
IOError: [Errno 2] No such file or directory: '-'
cat: write error: Broken pipe
Standard input is empty, terminating!

```

**Comment by gconcepcion** [comment]
Did the test case work successfully? 

It's always better to test the install on the test case rather than your own dataset first

**Comment by gconcepcion** [comment]
FYI: I am able to replicate this bug - however. In your fc_run.cfg you should use 
`pa_fasta_filter_option=streamed-median` 
instead of
`pa_fasta_filter_option=median`

**Comment by roblehmann** [comment]
The test case works. I am trying to isolate the problem by using the same fc_run.cfg from the example for my data. However, I get the same error. Strange...
I'll try the pa_fasta_filter_option

**Comment by roblehmann** [comment]
The error does not occur when I use the greg200k-sv2 example fc_run.cfg with my data, but it does occur when I use the human genome example [fc_run.cfg](https://github.com/PacificBiosciences/pb-assembly/blob/master/cfgs/fc_run_human.cfg). I will have to go through the different options and see who the culprit is.

**Comment by roblehmann** [comment]
I can confirm, the correct `pa_fasta_filter_option` fixed the issue. 
Thanks for the quick help Greg!

**Comment by gconcepcion** [comment]
Great! Glad it works! 
Hope you assemble some great genomes :)

**Comment by roblehmann** [comment]
Thanks, in fact I did already - the Nemo genome came out quite good! I’m glad you guys are working to improve Falcon further.
