### ISSUE TITLE
Falcon unzip fetch_reads.py read_set hash table

### ISSUE THREAD

**Issue by EdHarry** [PacificBiosciences/pbbioconda#91]
**Operating system**
Linux 3.2.0-105-generic 146-Ubuntu

**Package name**
Falcon Unzip 1.1.5

**Describe the bug**
In falcon unzip / mains / fetch_reads.py when reading 'pread_to_contigs' and updating the read_set hash table, shouldn't the line be "if hit_ctg not in read_set.values()..." rather than "if hit_ctg not in read_set..." (line 84 in version 1.1.5 from bioconda)

**Comment by pb-cdunn** [comment]
Thanks. We'll address this soon.

(Internally: TAG-3653 )
