### ISSUE TITLE
Bax2bam without scraps 

### ISSUE THREAD

**Issue by mvollger** [PacificBiosciences/pbbioconda#98]
**Package name**
bax2bam

This is a feature request and not a bug. 

I would like there to be a flag to prevent scrap bams form being generated when converting bax.h5 to bam. 

When converting TBs of data it is a huge IO strain to write all these files when ultimately in most situations these files will immediately be deleted. 

Thanks!
Mitchell

**Comment by armintoepfer** [comment]
Hey Mitchell!

bax2bam is one of those tools that has one purpose and won't be changed afterwards; it reached its stable EOL version when released. If you are open to edit the source code and compile your own version, I can give you some hints where to look at.

Armin

**Comment by pb-dseifert** [comment]
...and yes, we do accept PRs, even to products in EOL/deep-maintenance mode

**Comment by armintoepfer** [comment]
https://github.com/PacificBiosciences/bax2bam

**Comment by mvollger** [comment]
Fair enough. I doubt I will have the time to make this change, but I will check out the src just in case, thanks for sharing!  I am going to close, and if I do end up working on it I will make a PR.
