### ISSUE TITLE
add pbbamify to pbmm2

### ISSUE THREAD

**Issue by Arkarachai** [PacificBiosciences/pbbioconda#99]
The quay.io/biocontainers/pbmm2:0.12.0--ha87ae23_0 pbmm2 don't have md5 for contig, so I have to use pbbamify to add it and sort BAM as well. I think it would be good if you bake-in pbbamify inside pbmm2 using and exposing an option to use it, so we don't have to do bamify and sort later.

**Comment by armintoepfer** [comment]
1) You can use `--sort` in pbmm2
2) Why do you need md5? It's simply not computable when using an `.mmi` as input.

**Comment by Arkarachai** [comment]
This is related to issue #96 which I tried to mix and match software from conda with official releases. We found that using pbbamify to add md5 would make the tool work, so we just want to recommend this change in case it is useful for other people.
I have a reference genome, so I can still compute md5.

**Comment by armintoepfer** [comment]
Why are you trying so hard to game the system? You are spending a lot of IO and compute time just for the sake trying to fit two pieces that are not supposed to work.

Either use `conda install genomicconsensus` or wait for the next official PacBio release that contains the latest `pbmm2` and `genomicconsensus`.

**Comment by armintoepfer** [comment]
Oh and one last comment, `pbmm2` is open source for a reason. Feel free to modify it yourself and send patch!
